### ISSUE TITLE
vertebral labelling disappear with registration

### ISSUE THREAD

**Issue by SaraDupont** [spinalcordtoolbox/spinalcordtoolbox#1141]
On data with axial and sagittal T2, to have vertebral labels on the t2_ax, they need to be created on the t2_sag and registered on the t2_ax, but the label file is empty after registration (due to the nearest neighbour interpolation). 

data in `folder_shared/sct_issues/20170131_issue11xx`
command line : `sct_register_multimodal -i labels_sag.nii.gz -d t2_ax.nii.gz -identity 1 -x nn`

**Comment by jcohenadad** [comment]
are labels simple points? if so, then the trick is to dilate before registration

**Comment by SaraDupont** [comment]
Yes they are. Is there a function to keep only a single point from a "dot" to apply after registration ? (instead of eroding which could erase the label)

**Comment by jcohenadad** [comment]
in sct_label_vertebrae there is some code that dilates, register, get center of mass, then recreate label.
look at get_z_and_disc_values_from_label

**Comment by SaraDupont** [comment]
Ok, thanks !

**Comment by SaraDupont** [comment]
We can create a function to facilitate this procedure in case users need it. Functions should : 
- separate labels in different files 
- warp each label file with a tri-linear interpolation
- take the center of mass of the warped label
- add label files back together

**Comment by joshuacwnewton** [comment]
Given that `sct_apply_transfo` presently has an `islabel` option for dilating + taking the center of mass for warped label images, I'm pretty certain we can consider this issue resolved?

I'm closing this issue for now, but if I've misunderstood, I'm happy to reopen.
