### ISSUE TITLE
sct_compute_snr error too many indices for array

### ISSUE THREAD

**Issue by alexfoias** [spinalcordtoolbox/spinalcordtoolbox#1190]
used the command: `sct_compute_snr -i sag_small_1_ALI_concat.nii.gz -m mask_sag_small_1_ALI_concat.nii.gz -method diff`
data : `/folder_shared/sct_issues/20170302_issue1190`

**Comment by slevyrosetti** [comment]
Due to the use of `set_orientation` instead of `orientation` (from `sct_image`) --> 4D data were cropped to 3D data.

**Comment by slevyrosetti** [comment]
Fixed in PR1197 (branh `sl_issue1190_compute_snr`).

**Comment by joshuacwnewton** [comment]
It seems like this issue was fixed in #1197, but never linked to the issue. So, closing now.
