### ISSUE TITLE
input image should be converted to float using im.changeType to prevent overflow

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1259]

**Comment by joshuacwnewton** [comment]
This issue is precisely the same issue described in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3959 (i.e. integer images overflowing after subtraction), and @mguaypaq described exactly the same solution:

> Convert inputs to float64 when doing any arithmetic (for example, most or all operations in sct_maths), and store the results as float64.

Closing as duplicate.
