### ISSUE TITLE
Have the sct and slicer work together

### ISSUE THREAD

**Issue by poquirion** [spinalcordtoolbox/spinalcordtoolbox#1482]
Start from the jca_issue1452 branch (see #1453 )

Try to make the following script work:

```
cd t1
# segment spinal cord
sct_propseg -i t1.nii.gz -c t1
# label vertebrae
sct_label_vertebrae -i t1.nii.gz -s t1_seg.nii.gz -c t1
# get two label points
sct_label_utils -i t1_seg_labeled.nii.gz -vert-body 2,6
# register t1 to PAM50
sct_register_to_template -i t1.nii.gz -s t1_seg.nii.gz -l labels.nii.gz -c t1
# warp PAM50 to t1
# Note: no need for WM atlas at this point (-a 0)
sct_warp_template -d t1.nii.gz -w warp_template2anat.nii.gz

# dmri
# ----------
cd ../dmri
# separate b=0 and DWI and average each group
sct_dmri_separate_b0_and_dwi -i dmri.nii.gz -bvec bvecs.txt -a 1
# segment cord
sct_propseg -i dwi_mean.nii.gz -c dwi
# register dmri template to dmri
sct_register_multimodal -i dwi_mean.nii.gz -d $SCT_DIR/data/PAM50/template/PAM50_t1.nii.gz -iseg dwi_mean_seg.nii.gz -dseg $SCT_DIR/data/PAM50/template/PAM50_cord.nii.gz -initwarp ../t1/warp_anat2template.nii.gz -param step=1,type=seg,algo=slicereg,poly=5,smooth=5
# rename warping field
mv warp_dwi_mean2PAM50_t1.nii.gz warp_dmri2template.nii.gz
# concat transforms
sct_concat_transfo -d ../t1/t1.nii.gz -w warp_dmri2template.nii.gz,../t1/warp_template2anat.nii.gz -o warp_dmri2anat.nii.gz

```

To write more test with the new framework would be a good think too .

**Comment by poquirion** [comment]
One of the most important things is to replace sys.exit() by a raise where sys.exit() it is not absolutely necessary.

**Comment by poquirion** [comment]
I need to separate the mpi module from the rest to make it work out of the box.
They had problems with psutil and mpi4py

**Comment by joshuacwnewton** [comment]
Maybe there's something I'm missing, but I'm not sure there's anything here that's applicable to modern-day SCT. 

The pipeline looks remarkably similar to what we currently do in `batch_processing.sh`, and the side-comments (write new tests, raise exceptions) are already on our radar as general recommendations/goals.

So, I think this issue can be closed?

**Comment by jcohenadad** [comment]
Somewhat a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3430. The topic is still relevant

**Comment by joshuacwnewton** [comment]
Ahhhh, it was referring to _that_ slicer. My apologies! I didn't see any sort of slicer-related commands in the script list above, so I assumed they were unrelated.
