### ISSUE TITLE
Data directories (eg. PAM50) location is hard-coded within $SCT_DIR

### ISSUE THREAD

**Issue by zougloub** [spinalcordtoolbox/spinalcordtoolbox#1536]
Someshing should be done so these can be located elsewhere:
- Typically such data ends up in `/usr/share` on UNIX.
- Assuming the lib gets to work with Python 2 & 3, it would typically be split into a python2 package, a python3 package, and a data package. It would be sad to duplicate the data.

**Comment by jcohenadad** [comment]
one benefits of having the data/models inside `$SCT_DIR` is that these can change across versions, and some researchers like to have multiple versions of SCT installed (e.g., v2.0 for a study that was started long time ago, and v3.0 for a more recent study). So it makes it clear for them what data pertains to which version. Open to discussion.

**Comment by joshuacwnewton** [comment]
> Typically such data ends up in `/usr/share` on UNIX.

As far as I understand, this is only relevant for UNIX programs/packages. But, SCT is (effectively) a Python package (given our hopes to be pip-installable), and our use of `data/` is pretty insular. If our data files needed to be accessible by other programs or packages, then I think moving the data files outside of the package would make sense. But, for now I think I agree with @jcohenadad that it makes more sense to keep the data files inside `$SCT_DIR`.

**Comment by joshuacwnewton** [comment]
Hardcoding data directories was reinforced as an intentional design decision as per https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3312.

Given that this (older) issue is in conflict of as more recent design decision, I think it's safe to close this issue.
