### ISSUE TITLE
Docker integration for distros testing in Travis CI

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1677]
### Description
Since Travis supports Docker (https://docs.travis-ci.com/user/docker/), it might be a good idea for us to use it in order to test SCT on different distros. We always have this problem of SCT working on some distros and sometimes after a commit, it stops working and we'll discover that only when a user sends a message or reports a bug. What we can do is to decide which distros we actually officially support (Ubuntu, CentOS > 7, etc.) and then create tests to check SCT on these distros using Docker.

**Comment by zougloub** [comment]
I feel like even today, Travis builds are quite long. I'm thinking that maybe we should only run an exhaustive test procedure on certain branches (eg. `master`, branches whose name contains `travis`, or commits mentioning an issue/pr number `#n`?) to avoid hampering the development.

There is distro testing code pretty close to what you're talking about in https://github.com/zougloub/sct_docker/tree/cJ-offline-and-testing, and creating a piece of code to perform the testing, eg.
```sh
/path/to/sct_docker/distro-test.py [--distros DISTRO_LIST] [--revision NAME] [--command ADDITIONAL_TEST] [--jobs PARALLEL_JOBS]
```
would perform testing of the current or a specific revision.

It would be easy to run locally.

Maybe these docker scripts/recipes should land in the SCT repo? Not sure.

**Comment by zougloub** [comment]
There's an https://github.com/neuropoly/sct_docker repo, so for now I submitted a PR there.
If we want that Sphinx documentation here, perhaps the files should be moved here.

Take a look at https://github.com/neuropoly/sct_docker/pull/2.
The embryonic  `sct_docker_testing.py` script generates and runs Docker images containing testing commands:

```
usage: sct_docker_testing.py test [-h] [--distros DISTROS [DISTROS ...]] [--version VERSION] [--commands COMMANDS [COMMANDS ...]]

optional arguments:
  -h, --help            show this help message and exit
  --distros DISTROS [DISTROS ...]
                        Distributions to test (docker image names)
  --version VERSION
  --commands COMMANDS [COMMANDS ...]
```

Note: when testing many distros, the testing loop doesn't yet abort on failure, stores failure status, or runs the configs in parallel, collecting their output cleanly. It just runs everything sequentially for now.

**Comment by jcohenadad** [comment]
to follow-up on this issue, what strategy do we want for Travis to run all those distros-test? e.g. would be good to do it before each release.

**Comment by zougloub** [comment]
I tried to run Travis on https://github.com/neuropoly/sct_docker but I was busting the time limit easily, we need to create different jobs if we want to not run over it. If we have badass servers and we are running these tests on-demand I'm not sure Travis is really helpful. But it can still be setup. BTW, did you end up getting familiar with that sct_docker?

**Comment by jcohenadad** [comment]
agreed about running those tests locally on-demand. I didn't have a chance to play with sct_docker yet.

**Comment by kousu** [comment]
I want to pick this up since it would be helpful for #2642 . I also think it is time to expand the MacOS list to include 10.15.

**Comment by kousu** [comment]
I think it's worth testing a full cross-platform build on every PR. The tests run in parallel so they don't take longer than 20 minutes to finish. My impression from watching a few is that the slowest part seems to be waiting for OS X VMs to become available.

If we think Travis is slow, we might consider migrating to Github Actions; they seem to have a faster cluster; or maybe just a less-taxed cluster.

**Comment by joshuacwnewton** [comment]
@kousu Just checking in on this, from what I can tell quite a lot of OSs/distros have been added to our CI (albeit on cron jobs rather than on PRs). It looks like https://github.com/neuropoly/spinalcordtoolbox/issues/2692 covers adding 10.15 CI, too.  Can this issue be closed, then?

**Comment by joshuacwnewton** [comment]
This issue came up while I was searching for other issues -- looks like this can be closed now, as we use GitHub Actions, and test across many different distro types.
