### ISSUE TITLE
Error writing output if folder does not exist

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1696]
### Prerequisites

* [x] Did you check past issues for similar issue(s) ?
* [x] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [x] If you are using a development environment, is your environment updated ?

### Description

Error writing output if folder does not exist. The proposed solution is to create path if necessary.

### Steps to Reproduce

~~~
cd sct_testing_data/mt
sct_extract_metric -i mt1.nii.gz -l 51 -o ~/path_that_does_not_exist/output.xls
~~~

Error:
~~~
Error of writing permissions on file: /Users/julien/path_that_does_not_exist/output.xls
~~~

### State of spinalcordtoolbox

Spinal Cord Toolbox (master/caf11f46d92fe8765490a53325acbf0e2b36b8f1)

**Comment by zougloub** [comment]
Creating the path if necessary is not a standard practice and I don't think it's a good idea, so the proposed solution is to indicate that the parent folder doesn't exist.
