### ISSUE TITLE
Running `-v 2` for registration scripts no longer outputs intermediate `matplotlib` plots

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1741]
### Description

When using `-v 2` [these intermediate QC files](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9b1aeac9634f706e6673e3b1384099745816325a/scripts/msct_register_landmarks.py#L345-L383) are no more output. 

This issue has probably been introduced in a recent PR (no time to investigate more at this point). An acceptable workaround would probably be to output those qc files locally (instead of looking if path_qc exists), and generate them if verbose=2.

### Steps to Reproduce

data: `sct_testing_data/t2`
~~~
sct_register_to_template -i t2.nii.gz -s t2_seg.nii.gz -l labels.nii.gz -v 2
~~~

### State of spinalcordtoolbox

9b1aeac9634f706e6673e3b1384099745816325a

**Comment by joshuacwnewton** [comment]
In modern-day SCT, `msct_register_landmarks` now exists in `landmarks.py`. The relevant function that produces these plots is:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/spinalcordtoolbox/registration/landmarks.py#L204-L295

The plots are saved to the current working directory, which in this case, is the `sct_register_to_template` temp folder:

![image](https://user-images.githubusercontent.com/16181459/212503447-4990dbc8-9f56-48e1-a90d-d8cb865cf63e.png)

So, it looks like the "acceptable workaround" was applied at some point during the refactoring of `msct_register_landmarks`.
