### ISSUE TITLE
Allow better filtering for including folders like t2_sag, t2_ax

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1763]
### Description

Currently, in order to launch `sct_pipeline` we have to specify the exact input and ground truth file names. This becomes problematic as some folders are called t2_sag, t2_ax, etc., so we are currently missing them in the large testing. One solution would be to use a database and filter on contrasts as opposed to file names. This issue is related to the parallel efforts in setting up a [local testing database](https://github.com/neuropoly/sct_testing_management) at NeuroPoly Lab. 

To move forward, one solution would be to output a file that contains all fields from the database (e.g. could be json, as already possible via the web-based interface), and parse this file in `sct_pipeline` for field-base subject selection. There is already some [legacy code](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_pipeline.py#L180) in `sct_pipeline` to do that, so we would just need to adapt to the new format of the database.

Another approach would be to directly communicate with the DB using an API (@fperdigon is working on it), but one limitation is that it would require access to the DB, which is not always possible (e.g. when launching jobs on Compute Canada).

**Comment by charleygros** [comment]
I think we could go with the first option (ie using a file provided by the database), as it seems already working and to provide the information we need.

But maybe I am missing something (& sorry for this question): what would be the interest to directly communicate with the database using an API?

**Comment by jcohenadad** [comment]
@charleygros excellent question: the benefit of the API is to update the DB with batch of subjects. For example, if you want to update the coverage information in 100 subjects, you can send a request via an API vs. doing it manually via the web interface for each subject. A list of feature is available [here](https://github.com/neuropoly/sct_testing_management/issues/31).

**Comment by jcohenadad** [comment]
Update: @perone is working on an [API](https://github.com/neuropoly/bids_neuropoly) that takes BIDS dataset as input, and output a Python structure which could be interpreted by `sct_pipeline`. So the refactoring of `sct_pipeline` should take into consideration these ongoing developments.

**Comment by joshuacwnewton** [comment]
`sct_pipeline` is no longer used, and `sct_run_batch` was designed to be compatible with BIDS-formatted datasets. 

Closing as completed.
