### ISSUE TITLE
Give more information about the number of subjects used for `deepseg_gm_models/large_model.onnx`

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1767]

**Comment by charleygros** [comment]
I think we already have this info under `data/deepseg_*_models/READ_ME.txt`

**Comment by perone** [comment]
This information is already inside the zip file of the model, do you want me to add it somewhere else also ?

**Comment by jcohenadad** [comment]
when the user does `sct_deepseg_gm -h`, it should be made explicit how to get more info from the model (it is the case for the model "challenge" where there is a link to it).

**Comment by perone** [comment]
Ah ok ! I think we should start adding this information on sphinx and then put a link to the help pointing to the correct sphinx doc. What do you think ? Otherwise, we'll have information spread in too many places.

**Comment by perone** [comment]
I'll wait for the PR #1683 merge before doing that because all the sphinx docs are there.

**Comment by joshuacwnewton** [comment]
Currently, this information is not uploaded to our Sphinx documentation. To make things a little easier, the current contents of `deepseg_gm_models/README.txt` are:

```
sct_deepseg_gm models
===============================================================================

This folder contains the sct_deepseg_gm models:

- challenge_model
	This model was trained in the Gray Matter Segmentation Challenge dataset.
	http://cmictig.cs.ucl.ac.uk/spinal-cord-grey-matter-segmentation-challenge
	This public dataset includes 40 subjects, rated by 4 different raters,
	providing a total amount of 1762 axial slices. This dataset contains
	only healthy controls.
	This dataset was created on 26 Nov 2017.

- large
	This model was trained on private dataset, which includes 232 subjects
	and a total amount of 3963 axial slices.
	This dataset, besides the healthy controls, also contained the following
	pathologies: multiple sclerosis, cervical spondylotic myelopathy, spinal cord
	injury, syringomyelia.
	This dataset was created on 26 Nov 2017.

Changelog
===============================================================================

2018-02-05:
	- Added readme with dataset descriptions

2017-11-26:
	- Models creation
```

**Comment by joshuacwnewton** [comment]
Closing this issue in favor of #4046.
