### ISSUE TITLE
Implement integrity test for sct_flatten_sagittal

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1799]
to address this: https://github.com/neuropoly/spinalcordtoolbox/issues/1790

the integrity could check if the output image is empty.

**Comment by joshuacwnewton** [comment]
I believe the current `sct_flatten_sagittal` test would have caught #1790:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/testing/cli/test_cli_sct_flatten_sagittal.py#L9-L14

Checking the results of the test falls under https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3764, so I'm closing this as a duplicate.
