### ISSUE TITLE
Output verbose for syntax should show relative path instead of absolute

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1806]
Most people run commands locally and expect to get the output in the local folder. Hence, there is no point in displaying full path when calling `sct.display_viewer_syntax()`.

e.g. instead of 
~~~
fsleyes t2s.nii.gz -cm greyscale /Users/julien/sct_course-paris18/single_subject/data/t2s/t2s_seg.nii.gz -cm red -a 70.0 &
~~~

show:
~~~
fsleyes t2s.nii.gz -cm greyscale t2s_seg.nii.gz -cm red -a 70.0 &
~~~

**Comment by jcohenadad** [comment]
This should be dealt with the refactoring of argparse

**Comment by joshuacwnewton** [comment]
Hmm. Personally, I like the absolute path. To me, it makes the command a little more foolproof. 

> Most people run commands locally and expect to get the output in the local folder. 

This may be true, but even if just a few people don't run it locally, then copying and pasting could cause us trouble. 

Embarrassingly, I was one of those people! I had typed in subfolders (e.g. `-i t2/t2.nii.gz`) and I thought something had gone wrong when the command didn't work (#2929). :sweat_smile: 

If all of the filepaths were absolute, then this wouldn't happen, which could save us time answering questions on the forum, etc.

**Comment by jcohenadad** [comment]
fair enough

**Comment by joshuacwnewton** [comment]
Thinking about this, there might actually be a middle ground we can do here:

- Check to see if the file is present in the working directory:
    - If it is, use the relative path
    - If it isn't, use the absolute path

That way, we get the best of both worlds -- the command will always function, but we'll get a short, easy-to-read output 95% of the time.
