### ISSUE TITLE
New function to make a movie out of axial slices

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1861]
### Description

The function would take 3D volume (and possibly an overlaid segmentation and display it in red) and output a 2D movie that scrolls along the 3rd dimension. Frame rate could be an argument.

I think @perone already has something.

would be useful for presentations

**Comment by joshuacwnewton** [comment]
Given that there are existing utilities to perform this function (e.g. [`gif_your_nifti`](https://github.com/miykael/gif_your_nifti)), is this still needed?

**Comment by jcohenadad** [comment]
nope! and nice find about the gif_your_nifti! i didn't know about it
