### ISSUE TITLE
Consider using optional ensembling during inference time

### ISSUE THREAD

**Issue by perone** [spinalcordtoolbox/spinalcordtoolbox#1893]
_(I'm just adding this idea for the future, just to not forget about it, since it involves almost all machine learning models we use.)_

There are some things that can be done to improve Machine Learning/Deep Learning results by trading performance (resources usage), and ensembling is one of them. I think we should consider adding an option for using ensembling during inference time as an optional parameter, so if users don't have a performance requirement (which is common, for instance, when you want to segment just a few volumes), they can get better results by waiting a little more for the inference. Now, this requires training more models and shipping these models as well, so it will by effect increase download time of models during installation.

**Comment by joshuacwnewton** [comment]
Migrated to https://github.com/neuropoly/idea-projects/issues/13.
