### ISSUE TITLE
List supported distros in documentation

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1907]
### Description

Since we now have a [Docker image for several distros](https://github.com/neuropoly/sct_docker#generation-and-distribution), that we use for testing, maybe we should list those in the documentation?  We would also describe the extra-steps required for specific distro.

**Comment by joshuacwnewton** [comment]
Currently, we test many linux distros in our CI, without even having to use an SCT Docker image. 

As well, we list our supported distros in the [Installation for Linux](https://spinalcordtoolbox.com/user_section/installation/linux.html#supported-operating-systems).

So, I think this issue has been addressed.
