### ISSUE TITLE
Display message inside FSLeyes when running SCT pipelines

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1930]
### Description

When providing typical SCT batch pipelines to users, we usually include `fsleyes` syntax that opens the viewer. In the Terminal, we explain to check if the segmentation is OK (and modify it if necessary), but of course the user misses the message (because FSLeyes hides the Terminal). Example [here](https://github.com/spine-generic/spine-generic/blob/9245caf1d99de5a4c67c0731baa2b507b076d672/process_data.sh#L25):

```bash
  echo "Segment spinal cord"
  sct_propseg -i t1.nii.gz -c t1
  file_seg="t1_seg.nii.gz"
  # Check segmentation results and do manual corrections if necessary
  echo "Check segmentation and do manual correction if necessary, then save segmentation as t1_seg_manual.nii.gz"
  fsleyes t1.nii.gz -cm greyscale t1_seg.nii.gz -cm red -a 70.0 &
```

Instead, it would be much nicer to have this message displayed inside FSLeyes. 

@perone do you think the FSLeyes Python plugin makes this feature possible?

**Comment by perone** [comment]
When I was developing the other plugins, I tried to find a way to call the `fsleyes` specifying the script to load but I wasn't able to find a native way to do that, you can only load them after loading `fsleyes`. 
One alternative to solve the mentioned issue is to show the message in the terminal and wait for user pressing any key before opening fsleyes.

**Comment by joshuacwnewton** [comment]
> One alternative to solve the mentioned issue is to show the message in the terminal and wait for user pressing any key before opening fsleyes.

Given FSLeyes' limitation here, I think that this is the best available option. It can be done using something like [this](https://unix.stackexchange.com/a/293941):

```bash
read -n 1 -s -r -p "Press any key to check segmentation (and do manual correction if necessary)"
```

Given that we have an answer, and given that this is more of an issue with bash script design, rather than SCT itself, I'm closing this issue as resolved.
