### ISSUE TITLE
Flattened image is zero for slices below a certain `z` value

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#1933]
### Description

segmentation is fine, however the image appears dark-- probably something wrong with center of mass calculation. See here:
![screen shot 2018-07-16 at 14 08 07](https://user-images.githubusercontent.com/2482071/42775224-de5d3704-8901-11e8-8a35-7d02152c1024.png)

data:
https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/6e48508a/?limit=25#52be

**Comment by joshuacwnewton** [comment]
The user's data has been deleted on Dropbox. I'm not sure how else we'll be able to debug/reproduce this issue. :sweat:

**Comment by jcohenadad** [comment]
oopsi! let's close in this case
