### ISSUE TITLE
Issues with type output and compression

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2176]
When using `sct_image -type` to change from one type to another (or to the same), the output image is usually larger than the input, suggesting issues in handling data quantization. 

Example:
~~~
sct_download_data -d sct_testing_data
cd sct_testing_data/t2
sct_image -i t2_seg.nii.gz -type uint8 -o t2_seg_uint8.nii.gz
~~~
compare image sizes
~~~
ll t2_seg*
--> -rw-r--r--  1 julien  staff   695 27 Feb 10:16 t2_seg.nii.gz
--> -rw-r--r--  1 julien  staff  1797 27 Feb 10:19 t2_seg_uint8.nii.gz
~~~
Look at data type:
~~~
fslhd t2_seg.nii.gz | grep data_type
--> data_type      UINT8
fslhd t2_seg_uint8.nii.gz | grep data_type
--> data_type      UINT8
~~~

**Comment by jcohenadad** [comment]
Ideally, I would like to replace our [current implementation](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/image.py#L965), which is heavy and poorly-validated, with something more standard (e.g. nibabel, nipy) if it already exists.

**Comment by jcohenadad** [comment]
Another problem: sometimes, the command does **not** work. Example on sct_testing_data/t2:
~~~
sct_image -i t2.nii.gz -type float32 -o t2f.nii.gz
~~~

the output is int16 (not float32)

**Comment by joshuacwnewton** [comment]
I can't reproduce 100%, because `sct_testing_data` no longer has a single `t2_seg.nii.gz` file -- it has several now. Additionally, the segmentation files are already in `uint8`, so there is no file size change anyway.

However, testing using `t2.nii.gz`:

```console
(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2/type_check$ sct_image -i t2.nii.gz -type uint8 -o t2_uint8.nii.gz
(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2/type_check$ sct_image -i t2.nii.gz -type float32 -o t2_float32.nii.gz
(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2/type_check$ ls -lah
total 652K
drwxr-xr-x 2 joshua joshua 4.0K Jan 17 15:37 .
drwxr-xr-x 3 joshua joshua 4.0K Jan 17 15:33 ..
-rw-r--r-- 1 joshua joshua 299K Jan 17 15:34 t2_float32.nii.gz
-rw-r--r-- 1 joshua joshua 223K Jan 17 15:34 t2.nii.gz
-rw-r--r-- 1 joshua joshua 120K Jan 17 15:37 t2_uint8.nii.gz
```

We can see that the `uint8` copy shrinks in size, and the `float32` copy is correctly created as float:

```console
(master) joshua@tadpole:~/repos/spinalcordtoolbox/data/sct_testing_data/t2/type_check$ fslhd t2_float32.nii.gz 
filename        t2_float32.nii.gz

sizeof_hdr      348
data_type       FLOAT32
```
