### ISSUE TITLE
generate labeled SC with sct_process_segmentation

### ISSUE THREAD

**Issue by renelabounek** [spinalcordtoolbox/spinalcordtoolbox#2275]
How to generate labeled SC image from a discfile? After SCT update, following command is not working:

`sct_label_utils -i t1.nii.gz -create-viewer 1,2,3,4,5,6,7,8,9,10,11,12 -o t1_labels_disc.nii.gz`
`sct_process_segmentation -i t1_seg.nii.gz -p label-vert -discfile t1_labels_disc.nii.gz`

I am getting output:

`Command-line usage error: argument -p does not exist. Did you mean: -o, -r, -v, -i, -z, -h?
Aborted...`

Before SCT update it worked. Command's help did not help me.

Thanks,
Rene

**Comment by jcohenadad** [comment]
@renelabounek as of 4.0.0 it would be this command:
~~~
sct_label_vertebrae -i t1.nii.gz -s t1_seg.nii.gz -discfile t1_labels_disc.nii.gz
~~~

(could you please post issues on the SCT forum because other users might have the same question and could benefit from the answers-- thanks!)

**Comment by renelabounek** [comment]
@jcohenadad, yes I will post it there. Thanks, Rene

**Comment by joshuacwnewton** [comment]
Closing, as this is a usage question (not an bug/issue).
