### ISSUE TITLE
Calling WarpTemplate fails

### ISSUE THREAD

**Issue by benjamindeleener** [spinalcordtoolbox/spinalcordtoolbox#2320]
Hello, I was trying to use the class `WarpTemplate` (from `sct_warp_template`), but I couldn't call it directly in my python environment. Here is the output I get:

```
Traceback (most recent call last):
  File "sct_crop_template.py", line 137, in <module>
    folder_out=folder_out, path_template=path_template, verbose=cropper.verbose)
  File "/cerebro/cerebro1/dataset/bmpd/derivatives/sc_preproc/code/sct/scripts/sct_warp_template.py", line 53, in __init__
    self.folder_template = param.folder_template
NameError: name 'param' is not defined
```

The reason is that the variable "param" is defined at the end of the script, in the scope of `if __name__ == "__main__":`, which is not run when calling `WarpTemplate` directly.

There might be other scripts that have the same issue.

**Comment by joshuacwnewton** [comment]
Closing this issue, as the script init steps were standardized in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3091. Now, we no longer store script logic in `if __name__ == "__main__"`.

Before:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9499780bfd8631cd43d688251eb79fd340bb0401/scripts/sct_warp_template.py#L250-L253

After:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/spinalcordtoolbox/scripts/sct_warp_template.py#L290-L292
