### ISSUE TITLE
Folder removal should be based on folder name, not dataset name

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2390]
After downloading a dataset, the function checks if the folder already exists. See code [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/scripts/sct_download_data.py#L138). If it does, it removes it before unzipping. The problem is that the existence check is based on the dataset name (from input `-d`), not on the actual folder name. Typically, those two names are the same, however in some cased it is not, making folder removal failing.

Possible solutions:
- Check if Python's unzip module allows to verify if a folder with the same name already exists, and if it does, if the module allows for removal before unzipping.
- During checking, instead of using the dataset name (`data_name`), use the enclosed folder name to be unzipped.

**Comment by joshuacwnewton** [comment]
This has been fixed at some point. The existence check now relies on the actual dataset path, and not the dataset name:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1b5c49c3904dffe63546adbadc47759a53fbc8ca/spinalcordtoolbox/download.py#L287-L289

![image](https://user-images.githubusercontent.com/16181459/212490652-617972ab-921c-46ec-acaf-77a84eea6e5f.png)
