### ISSUE TITLE
Generate SCT citation function

### ISSUE THREAD

**Issue by alexfoias** [spinalcordtoolbox/spinalcordtoolbox#2412]
Create a function *sct_citation* to output the bibtex citation in the terminal.
https://github.com/neuropoly/spinalcordtoolbox#citing-spinalcordtoolbox

**Comment by RignonNoel** [comment]
Just an update to refresh the link that is out-dated in the issue description: 

http://localhost:63342/spinalcordtoolbox/documentation/build/html/user_section/citing_sct.html#main-reference

---

And here is a link for introduction to BibText: http://www.bibtex.org/

**Comment by RignonNoel** [comment]
I close this PR based on PR discussion: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3670#issuecomment-1023601524

---

 - adding another CLI adds 'noise' for our users (ie: there is already a lot of CLI functions that they need to learn about, so it could be overwhelming to see a list of many CLIs)
 - not having this function 'forces' them to go on https://spinalcordtoolbox.com/, where the citation is listed, alongside other citations (to sct_deepseg_sc, PAM50, etc.), so it gives them the opportunity to not only cite SCT main paper, but also other papers from our group
 - going in the website, they will be exposed to other useful stuff (tutorials, etc.)
