### ISSUE TITLE
Use CDN for downloading data, binaries and miniconda

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2415]
Currently, data and binaries are hosted on OSF + neuropoly website (as a mirror where OSF is not accessible for some countries). 

This approach is suboptimal as:
- it requires more maintenance (two URLs to manage)
- download could be faster if server is closer to user

A suggestion would be to use a CDN for data, binaries and miniconda.

Related to #2403

**Comment by kousu** [comment]
The advantage to the current approach is that we have some redundancy.

We could also make a Github project for each binary/data package we need and use Github Releases as our CDN. Github is less blocked around the world than what we're using now.

I think we can probably eventually package everything -- the data, the binaries -- as python packages, and then we can trust in PyPI's CDN and there's minimal maintenance on our end -- all we need is to run `twine` somewhere, and as we saw this week in https://github.com/neuropoly/ivado-medical-imaging/pull/217 we can fully automate that.

**Comment by jcohenadad** [comment]
i'm not sure i understand where physically the data/binary would be, and how we would maintain them.

**Comment by kousu** [comment]
https://pypi.org/sponsors/
> PyPI uses Fastly's CDN to quickly serve content to end-users, allowing us to minimize our hosting infrastructure and obscure possible downtime.

So, files get uploaded to PyPI's core mirrors and are stored there -- probably in the US? When a request comes in for a user via Fastly it hits Fastly's servers, which are [scattered around the world](https://www.fastly.com/network-map), and if those servers have that file cached they return it, if not they go talk to PyPI's core mirror first, download it, then relay it to the user.

(if we're worried about slow/blocked downloads in certain countries then it's important to note that Fastly only has one mirror in China and two in Africa and none in Russia/north Asia.)

Other CDNs work the same way. They're basically just automated mirrors, doing what we're currently doing by hand but on-demand, and usually they're paired with high bandwidth datacenters.

**Comment by kousu** [comment]
I just did some experiments and found that Github has a CDN too. Here in Canada, Github serves from `lb-*-iad.github.com` (eg `lb-140-82-114-4-iad.github.com`); from Germany, it serves from `lb-*-ams.github`.com` (eg `lb-140-82-118-4-ams.github.com`). "iad" is somewhere in the US according to [MaxMind](https://www.maxmind.com/en/geoip-demo), and "ams" is short for Amsterdam -- Amsterdam has become something of a big data hub lately.

So, they use the same idea: a bunch of automated mirrors.

**Comment by zougloub** [comment]
Putting it on github on the other hand, I don't see a problem with that. If anything it's improving traceability at the same time.

**Comment by kousu** [comment]
> I'm not a huge fan of storing arbitrary data on PyPI, it's not very nice.

Why not? What have you run into with it?

---

And it's not arbitrary data, it's key software components of the project. Even the neural network models are just compiled binaries for an unusual processor architecture by another name.

**Comment by joshuacwnewton** [comment]
I think we can close this issue. We now have our data and binaries stored on GitHub, and https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2669 covers the possibility of using PyPI to host dependencies.
