### ISSUE TITLE
shrink-factor superior to one should be enabled

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2422]
When specifying shrink-factor>1, the registration routine set this parameter back to one, due to a supposedly wrong generation of warping field. We should fix that, because in some instances, higher shrink factor is important.

**Comment by joshuacwnewton** [comment]
This issue is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1210. Closing.
