### ISSUE TITLE
Send email once sct_run_batch is done

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2475]
Useful feature.

**Comment by jcohenadad** [comment]
@cfhammill i think you've implemented that feature, right?

**Comment by joshuacwnewton** [comment]
> @cfhammill i think you've implemented that feature, right?

This feature was indeed implemented in:

*  https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2732

However, it's usage isn't exactly clear? If you enter an email in `-email-to`, it will then prompt you for your password. 

When I try using an account without 2FA, I get:

```
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n
5.7.8  https://support.google.com/mail/?p=BadCredentials w26-20020a05620a0e9a00b006fa22f0494bsm3648209qkm.117 - gsmtp')
```

When I try using an account _with_ 2FA, I get:

```
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n
5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor x21-20020a05620a0b5500b0070688f60025sm5341042qkg.76 - gsmtp')
```

If I try setting up an application-specific password, it works!

![image](https://user-images.githubusercontent.com/16181459/213333136-78e6cf8d-6ff3-4071-ae6a-9e9856cba03a.png)

![image](https://user-images.githubusercontent.com/16181459/213333173-b9014baa-fc34-4790-80a3-aa836ff6075c.png)

I've got no idea how this works for other email providers, though. :sweat:
