### ISSUE TITLE
Vertebral labelling-DL: Retrieve spine generic centerline coordinates 

### ISSUE THREAD

**Issue by lrouhier** [spinalcordtoolbox/spinalcordtoolbox#2483]
Using python tools (nibabel, numpy) extract the coordinates of the centerline at the disc level (previously obtained).
The centerline is represented by non zero pixels for each subjects in XXX_centerline.nii.gz files.

part of #2438

**Comment by joshuacwnewton** [comment]
Closing, as this issue was marked as "Done" in the Vertebral Labeling project board: https://github.com/spinalcordtoolbox/spinalcordtoolbox/projects/10
