### ISSUE TITLE
Integration of whole cord pediatric spinal cord maps

### ISSUE THREAD

**Issue by BennettLandman** [spinalcordtoolbox/spinalcordtoolbox#2530]
**Feature justification: Is your feature request related to a problem? Please describe.**

We have created mFFE, AD, FA, RD, MD, Jacobian, and age-specific whole cord pediatric maps and are interested in integrating the maps into SCT. Pediatric imaging on 308 patients was conducted at the Monroe Carrel Jr. Children’s Hospital between October 2016-Novemeber 2018. Out of those 308 patients, we selected 160 high resolution multi-echo gradient echo (mFFE) scans (mean: 9.05 years, range: 0.5-18 years) for their scanning region between Brain-T12. We then processed the mFFE scans and registered them to the template space by using a customized semi-automatic processing pipeline involving Spinal Cord Toolbox (SCT). The registered mFFEs were non-zero averaged with iterative-reweighting and a Brain-T12 pediatric cord was generated. Out of 160 registered mFFE volumes, we eventually selected 150 diffusion MRI scans (mean: 8.98 years, range: 0.5-18 years) based on diffusion pre-processing and registration accuracy. DTI indices (FA, RD, MD, and AD) were computed for each dMRI scan and registered to the template space. FA, RD, MD, and AD whole cords maps were similarly generated using iterative-reweighting. We further extracted Jacobian values from the displacement fields and constructed whole cord Jacobian maps for both controls and abnormals. Age-specific maps in relation to the Jacobian have been generated as well. All cord maps are in the same space as SCT’s T2*-weighted template, have a crop radius of 70mm, and span from Brain-T12. 

**Describe the solution you'd like**
We would like to provide these for community use with the SCT. 

**Describe alternatives you've considered**
Direct posting of the volumes outside of SCT would not provide the integrated functionalities that are realized with the synergies within SCT.  

**Additional context**
Thank you.

**Comment by jcohenadad** [comment]
Hi @BennettLandman, this is super exciting! Thank you for considering integrating your template inside SCT.

To have your template 100% compatible with SCT, meaning that people could use your template interchangeably with the PAM50 (or other template, like the "old" MNI-Poly-AMU template), the procedure would be the following:

- Generate a binary mask of the cord, as well a labels along each intervertebral disc and mid-vertebral bodies. These mask and labels will be used by `sct_register_to_template`. 
- Generate a WM/GM atlas to enable `sct_extract_metric` functionalities. Without the atlas, it would still be possible to use `sct_extract_metric`, but only within the masks provided by your existing template (e.g., whole WM or GM, if you already have those). So ideally, your template would come with an atlas as well. There is already [code available](https://github.com/neuropoly/spinalcordtoolbox/tree/master/dev/atlas) to warp the Gray's Anatomy spinal WM atlas onto the PAM50 template, as described in [Levy et al. Neuroimage 2015](https://paperpile.com/app/p/61cc5c0c-df97-0118-9d1b-f6ca62272ce4). The procedure lacks documentation, but we are more than happy to guide you through the process (and in the meantime improve the documentation!). 
- Once all the necessary files are generated, organize them into specific folders:
~~~
PediatricTemplate/
├── README.txt  --> Describes how the template was generated, add license, contributors, reference, etc.
├── CHANGES.txt --> Describe changes across versions of the template
├── atlas/
│   ├── info_label.txt --> file used by SCT to identify files and their specific use. I suggest you copy the PAM50's info_label.txt and adapt it to your specific template. More details on [SCT course p94](https://osf.io/arfv7/?version=5)
│   ├── PediatricTemplate_atlas_00.nii.gz
│   ├── PediatricTemplate_atlas_01.nii.gz
│   ├── ...
│   └── PediatricTemplate_atlas_XX.nii.gz
|
└── template/
    ├── info_label.txt
    ├── PediatricTemplate_cord.nii.gz
    ├── PediatricTemplate_label_disc.nii.gz
    ├── PediatricTemplate_label_levels.nii.gz
    ├── PediatricTemplate_label_t2s.nii.gz
    ├── PediatricTemplate_label_dti-fa.nii.gz
    ├── PediatricTemplate_label_dti-md.nii.gz
    ├── PediatricTemplate_label_dti-rd.nii.gz
    └──PediatricTemplate_label_dti-ad.nii.gz

- Zip your folder (remove all the crap if generated from an OSX station, more details [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/Package-data-&-binaries#data-models-and-course-material)), upload it on our 2 mirrors (OSF + neuropoly website, I will help with that), and update `scripts/sct_download_data.py` with the URL. 
- Update `sct_register_to_template` usage to let users know there is now this new template that they can use, and update SCT's course material.

I might forget things. Once the procedure is settled, I will create an entry into our wiki to make the procedure seamless for everyone who would like to contribute with additional templates. Please feel free to bug me with questions.

**Comment by jcohenadad** [comment]
@BennettLandman do you have any update on this?  Looks like your template would be useful to other users, see e.g. [this post](http://forum.spinalcordmri.org/t/pam50-atlas-and-pediatric-atlas/261/2)

**Comment by BennettLandman** [comment]
@ashwinkumargb Can you work with the team to start getting the prototypes exchanged?

**Comment by ashwinkumargb** [comment]
@jcohenadad @BennettLandman I will work on making the template compatible with SCT. I will keep you updated and let you know of any questions.

**Comment by jcohenadad** [comment]
@ashwinkumargb any update on this?

**Comment by joshuacwnewton** [comment]
For repository maintenance purposes, we have been cleaning up old issues. Because this issue hasn't had much activity in the past ~3 years, it will be temporarily closed for now.

That said, our team is still very interested in the work you have done with pediatric spinal cord maps. In fact, recently the lab has renewed efforts towards pediatric template creation and registration:

- https://github.com/sct-pipeline/pediatric-template
- https://github.com/neuropoly/pediatric-DL-registration

So, we would very much like to continue conversations about your work in this area! :slightly_smiling_face:
