### ISSUE TITLE
Implement CSA normalization

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2543]
### Rationale

When using images that are not corrected for gradient non-linearities, the edge of the FOV is '"compressed". When computing CSA on typical T1w brain images, the cord at the bottom is compressed and the CSA is under-estimated.

Possible solutions, investigated in [REF PAPINUTTO] are:
- to normalize the CSA with a measure taken from another close-by anatomical location, e.g. the C2 vertebrae (e.g. width and height). Problem: not reproducible.
- registration to template, and use Jacobian in axial plane to estimate the shrinkage done between the template and the subject's image.

**Comment by charleygros** [comment]
GNL correction paper: [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6175276/).

Recent paper found by @lrouhier: [here](https://onlinelibrary.wiley.com/doi/abs/10.1111/jon.12666).
Which recommend the use of the spinal canal diameters (---> another motivation for [CSF segmentation](https://onlinelibrary.wiley.com/doi/abs/10.1111/jon.12666)).

**Comment by jcohenadad** [comment]
Alternatively, we could also undistort images a posteriori using e.g. https://surfer.nmr.mgh.harvard.edu/fswiki/GradUnwarp

**Comment by charleygros** [comment]
> Alternatively, we could also undistort images a posteriori using e.g. https://surfer.nmr.mgh.harvard.edu/fswiki/GradUnwarp

The documentation mentions:

> Obtain from your local Siemens or GE vendor the spherical harmonics expansion that represents the gradient coils used in the MRI system you want to correct. This is a text file with proprietory information.

Is that something that is easily available?

Also, my understanding is that there are two effects we want to take into account: (i) gradient nonlinearity distorsions, ie imaging effect (ii) atrophy, ie biological / disease consequence. These effect can also be combined.

**Comment by jcohenadad** [comment]
This paper from Yiannakas et al. J Neuroimaging 2019 looks at lumber cord normalization, we could easily implement this normalization factor:
https://www.ncbi.nlm.nih.gov/pubmed/30582252

**Comment by joshuacwnewton** [comment]
CSA Normalization was implemented by @sandrinebedard in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3515, so I'm closing this issue for now.

However, I'm not sure if we have explored all of the methods listed in this issue. So, if we still want to keep an issue open, I can create a new issue in `neuropoly/idea-projects` that summarizes the ideas from this issue.

**Comment by jcohenadad** [comment]
> However, I'm not sure if we have explored all of the methods listed in this issue. So, if we still want to keep an issue open, I can create a new issue in neuropoly/idea-projects that summarizes the ideas from this issue. (LMK!)

no need, I think we are good! Thank you though
