### ISSUE TITLE
wxPython elements are not displayed properly on OSX Catalina

### ISSUE THREAD

**Issue by lrouhier** [spinalcordtoolbox/spinalcordtoolbox#2595]
When loading the FSLeyes plugin from SCT and then changing the card, images are not properly displayed:
![Screen Shot 2020-02-03 at 5 20 19 PM](https://user-images.githubusercontent.com/22171999/73696207-c793f000-46a9-11ea-9e7d-7231a9e993ae.png)

Commit: 8cdf9a0ff676abac01ac201a140d137642a6cf8c

Note: This issue is likely specific to OSX Catalina, although this must be further confirmed.

**Comment by joshuacwnewton** [comment]
The FSLeyes plugin has been rewritten a couple of times since this issue. And, I believe that the elements are now displayed properly on newer versions of macOS. (See, e.g. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3988#issuecomment-1366050617.)
