### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found libGL error: failed to load driver: swrast

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2623]
A user reported the following problem while checking PyQt:
~~~
OS: linux (Linux-4.15.0-88-generic-x86_64-with-debian-buster-sid)
...
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[OK]
~~~

Another (related) problem is that the test outputted "OK" even though errors were encountered.

More info at:
http://forum.spinalcordmri.org/t/installation-failed-during-installation-of-keras/349/5#

**Comment by alexfoias** [comment]
I couldn’t reproduce the error : https://gist.github.com/alexfoias/7cda180196be97457e40c5dd8de4627f#file-output-install-sct

I tested also with vnc: https://gist.github.com/alexfoias/7cda180196be97457e40c5dd8de4627f#file-output-sct-check-dependencies-from-teamviewer

**Comment by jcohenadad** [comment]
Closing for now, we will reopen if the error is reproduced
