### ISSUE TITLE
sct_download_data removes execute permissions on some binaries

### ISSUE THREAD

**Issue by cfhammill** [spinalcordtoolbox/spinalcordtoolbox#2645]
Happens with `sct_download_data -d applywarp` in (adab63cc; this may move as that PR gets reorganized).

 ```
sct_download_data -d applywarp
ls -l applywarp-bin/applywarp
```

Shows `rw-` where 

```
wget https://osf.io/ge65h/download -O applywarp.zip
unzip applywarp.zip
ls -l applywarp-bin/applywarp
```
Shows `rwx` as expected.

**Comment by cfhammill** [comment]
I think this may be due to python zipfile extracting: https://stackoverflow.com/questions/39296101/python-zipfile-removes-execute-permissions-from-binaries

**Comment by kousu** [comment]
This is definitely because of using zipfiles. We should use .tar.gz's instead. That's what `binaries_debian` and `binaries_osx` do :)

**Comment by mguaypaq** [comment]
It looks like [we abandoned the idea of distributing binaries for applywarp](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2529#issuecomment-605680038), so this issue is obsolete
