### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#2674]
Locally, a complete test suite run is about 10 minutes. Doing this on Travis is much, much slower.

[![2020-04-24-152034_980x621_scrot](https://user-images.githubusercontent.com/987487/80249077-b4693e80-8660-11ea-9927-e8273afd0430.png)](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/builds)

Ideas:

1. It seems that running the Ubuntu builds are fast, generally running in parallel and taking about 12 minutes each (so about 12 minutes total), but the OS X builds are slow, taking about 20 minutes each, and running serially since they have to queue for an available OS X VM, including the extra time they spend blocked.
2. Since we're [using rebasing](https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#commit-sequences), consider disabling ["Build pushed pull requests"](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/settings), because it causes [doubled building](https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests):
  
  ![2020-04-24-151835_693x270_scrot](https://user-images.githubusercontent.com/987487/80249197-eed2db80-8660-11ea-9c5a-35d684432dd5.png)
  
  The difference between "travis-ci/push" and "travis-ci/pr" is that the latter makes a merge commit with master -- but if we're always rebasing we shouldn't have merges so building the PR's branch is always enough to test that it's properly integrated with `master`. This might not speed up the overall build time since Travis runs the two as isolated build jobs, but I am hoping it will make the VMs more available to us, particularly the OS X VMs.

**Comment by kousu** [comment]
I turned off `travis-ci/pr` and builds have been faster since then.

**Comment by Drulex** [comment]
Hey I noticed that CI still runs on push and PR (example https://github.com/neuropoly/spinalcordtoolbox/pull/2781). Is this desired?

**Comment by kousu** [comment]
@drulex thanks for noticing! I turned that back on to try to get https://github.com/neuropoly/spinalcordtoolbox/pull/2751 merged because it turned out that disabling "PR" means that no branches from forks can get merged. I don't see how to balance these needs. I hope there's something I've missed or misunderstood.

What would happen if we turned off `travis-ci/push` and turned on `travis-ci/pr`? Then forks would get tested and be mergeable, branches in this repo would get tested and be mergeable so long as they had an associated PR? But `master` would not get tested on changes. It would get tested by the `cron` job though.

The 

```
      if: branch = release or type = cron
```

lines that limit testing to only the main platforms would effectively just be

```
      if: type = cron
```

but I was already thinking that would make more sense anyway, since I would rather focus on catching regressions daily by cron than release-ly when they'll show up as a pile of errors to fix the last day before a release.

**Comment by Drulex** [comment]
Took a quick look at the travis docs and it seems that we can use the `push` hook with a safelist specifying `master` as a branch only (https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches). This combined with the `pr` hook should do it, what do you think?

In any case your idea of having a frequent cron job on `master` is good and may make the `push` to `master` hook redundant (but if we get it to work without breaking other stuff it doesn't hurt to have).

Anyways I just find the double builds annoying, especially when they each take up to an hour.

**Comment by kousu** [comment]
> Took a quick look at the travis docs and it seems that we can use the `push` hook with a safelist specifying `master` as a branch only (https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches). This combined with the `pr` hook should do it, what do you think?

That sounds good. We should safelist `release` too since the [release process](https://github.com/neuropoly/spinalcordtoolbox/wiki/versioning) uses it to add some extra files (namely the CHANGELOG and version.txt) and run a final test run.

The docs are a little unclear to me. If we add

```
# safelist
branches:
  only:
  - master
  - stable
```

to .travis.yml will that break PR builds? Probably not, but I guess there's no good way to tell without actually merging something to `master` and making a bunch of PRs to try it out.
 
> Anyways I just find the double builds annoying, especially when they each take up to an hour.

I am 100% in agreement.

I've changed it in https://travis-ci.com/github/shimming-toolbox/shimming-toolbox-py/settings to be

![Screenshot from 2020-07-16 15-16-26](https://user-images.githubusercontent.com/987487/87712894-5b003f80-c777-11ea-9fee-7191c7afc853.png)

the opposite of what it was. So now `master` isn't going to get built on merges, it will only get built daily by `cron`, and the release process is broken.

**Comment by Drulex** [comment]
I was proposing to keep `Build pushed branches`, but adding a safelist (or a blocklist now that I think of it).

One of the two settings below should work:

```
# safelist
branches:
  only:
  - master
  - release
```

or

```
# blocklist
branches:
  except:
  - master
  - release
```

This way master and release keep getting tested on pushes (on top of cron jobs)

**Comment by kousu** [comment]
Well, here goes nothing.

**Comment by kousu** [comment]
I'll leave `Build pushed branches` off for now to save our time; but when #2798 gets merged lets one of us remember to turn it back on. Do you have the rights to turn it back on if you need to?

**Comment by kousu** [comment]
I turned `Build pushed branches` back on and committed @Drulex's suggestion! Now I'm going to make a bunch of PRs to see how Travis reacts.

**Comment by kousu** [comment]
So now we have:

- only one check needs to be run for each PR #2798 
- only four platforms are tested regularly #2690

Tactics to try next:

- turn [caching](https://docs.travis-ci.com/user/caching/) back on
- split the linter from the tests, and [split the tests themselves](https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines) into unit and integration steps; this might increase the runtime by repeating some of the installation steps, but should shorten each step from ~15minutes to ~5minutes, which will hopefully be overall faster.

By the way, the time Travis reports that a build took is the *sum* of all the steps; it doesn't account for parallelization. Right now, our tests are taking "1 hour" (4 builds x 15minutes) it's actually more like 25 minutes because they are done somewhat in parallel.

**Comment by kousu** [comment]
Title changed in light of #3125. Most of these techniques are applicable to Actions; but some are Travis-specific.

**Comment by kousu** [comment]
Travis continues to be soooo slow:

![2020-12-28-143641_872x560_scrot](https://user-images.githubusercontent.com/987487/103238922-272a6800-491a-11eb-963e-4db11adb1a5d.png)

The problem is mainly that the macOS and Windows VMs didn't even boot for us until about half an hour after the job was submitted.

**Comment by kousu** [comment]
https://docs.travis-ci.com/user/speeding-up-the-build/ suggests adding a subcommand to our test script to select a sub-piece to run:

> Then you change your script command to use the new environment variable to determine the script to run.
> ```
> script: "bundle exec rake test:$TEST_SUITE"
> ```

We could split `.ci.sh` into `.ci.sh unit_tests`, `.ci.sh integration_tests`, `.ci.sh lint`, and maybe `.ci.sh batch_tests`.

**Comment by joshuacwnewton** [comment]
Just to follow-up on this issue:

- We've switched from Travis to GitHub Actions, meaning much of this discussion is now no longer applicable.
- The current bottleneck is now our `batch_processing.sh` test, rather than `pytest`, meaning that splitting up CLI/API tests (as mentioned above) wouldn't provide much benefit.

That said, it seems like the speed issues that originally prompted this issue were somewhat inherent to Travis:

> The problem is mainly that the macOS and Windows VMs didn't even boot for us until about half an hour after the job was submitted.

By comparison, even at their longest times, I feel as though the current GitHub Action times are manageable enough to not prompt SCT developers to try and speed them up. (I personally don't feel hampered by CI times?)

Furthermore, waiting will be minimized even more once https://github.com/github/roadmap/issues/370 is made available to the public.)

**Comment by mguaypaq** [comment]
> Furthermore, waiting will be minimized even more once [github/roadmap#370](https://github.com/github/roadmap/issues/370) is made available to the public, since it prevents the "wait for tests -> merge -> update with master -> wait for tests -> merge" process that stems from concurrently-approved PRs.

Oooh! That'll be a very nice feature.
