### ISSUE TITLE
Output lesion statistics per slice

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2677]
> **Note**: This issue is part of a set of issues focused on the overlap in scope between `sct_process_segmentation` and `sct_analyze_lesion`.  Both of these scripts compute statistics on binary segments, but both scripts have certain features that the other lacks.
>
> - https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2677
> - https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3378
> - https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2707
> - https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2682

As currently implemented, `sct_analyse_lesion` can only provide level-wise statistics (with flag `-f`). It would be nice to have "ROI Occupied by lesion" and "Lesion distribution" calculated per-slice.

We could maybe consider using the same code that is used by `sct_process_segmentation` for dealing with aggregation between slices and/or vertebral levels. 

Related to [Forum post](http://forum.spinalcordmri.org/t/lesion-analysis-outputs/390)

**Comment by Nilser3** [comment]
Hi Julien,
I have tried to solve the problem by introducing **-perslice** function from _sct_process_segmentation_ in _sct_analyze_lesion_ command:
![sct_analyze_lesion](https://user-images.githubusercontent.com/77469192/204771439-293ffb55-054f-4fcd-8ed6-dc10a57532ff.png)

In this way we would be obtaining the area of the lesions for each slice, so I have a problem. What would happen if I have two or more lesions in a slice?
![t2s_7t_ms](https://user-images.githubusercontent.com/77469192/204770898-ea06979e-93be-4b50-89f5-9576797b8016.png)

Maybe we could calculate the area of each lesion per label and per slice.
[it's a work in progress]

**Comment by jcohenadad** [comment]
Good question. Given that the code already creates one label per lesion, I _think_ the approach would be to run the statistics per label, and for each label, have the option to do it per slice or per vertebral level. However, I would be careful with the implementation, because there are current discussions to try to leverage the existing APIs instead of duplicating them. See notably:
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3378
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2682

**Comment by Nilser3** [comment]
@jcohenadad  Do you have the issue where this command line was built? that would help me (the codes have not been simple to understand). It will take me longer than expected, but I'm working on it.

**Comment by jcohenadad** [comment]
> @jcohenadad Do you have the issue where this command line was built?

I'm not sure I understand your question. What do you mean by "this command line"? Are you referring to a user forum post?

**Comment by joshuacwnewton** [comment]
We have received a new user request for this feature here: https://forum.spinalcordmri.org/t/how-to-add-custom-tracts-when-using-sct-analyze-lesion/1290/2
