### ISSUE TITLE
DISPLAY variable is set....................[FAIL]

### ISSUE THREAD

**Issue by alexfoias** [spinalcordtoolbox/spinalcordtoolbox#2693]
I installed the most recent version on osx 10.15.4 (19E287).
I get an error message when running `sct_check_dependencies`.

```
Spinal Cord Toolbox (git-master-36238247360b0ccd76d9cd679eaebc4e2c754cc1)

SCT info:
- version: git-master-36238247360b0ccd76d9cd679eaebc4e2c754cc1
- path: /Users/alfoi/code/spinalcordtoolbox
OS: osx (Darwin-19.4.0-x86_64-i386-64bit)
CPU cores: Available: 8, Used by SCT: 8
RAM: Primary memory available: 16.00 gigabytes
Check Python executable.............................[OK]
  Using bundled python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] at /Users/alfoi/code/spinalcordtoolbox/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.18.4)
Check if cryptography is installed..................[OK] (2.9.2)
Check if dipy is installed..........................[OK] (1.1.1)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras (2.1.5) is installed.................[OK]
Check if matplotlib is installed....................[OK] (3.2.1)
Check if nibabel is installed.......................[OK] (3.1.0)
Check if pandas is installed........................[OK] (1.0.3)
Check if psutil is installed........................[OK] (5.7.0)
Check if pyqt5 (5.11.3) is installed................[OK]
Check if pytest is installed........................[OK] (5.4.1)
Check if pytest-cov is installed....................[OK] (2.8.1)
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.23.0)
Check if scipy is installed.........................[OK] (1.4.1)
Check if scikit-image is installed..................[OK] (0.16.2)
Check if scikit-learn is installed..................[OK] (0.22.2.post1)
Check if tensorflow (1.5.0) is installed............[OK]
Check if xlrd is installed..........................[OK] (1.2.0)
Check if xlutils is installed.......................[OK]
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.46.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3[secure] is installed...............[OK] (1.25.9)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[FAIL]
```

**Comment by alexfoias** [comment]
Doing `echo 'export DISPLAY=127.0.0.1:0.0' >> .zshrc` similar to suggested [here](https://github.com/neuropoly/spinalcordtoolbox/wiki/SCT-on-Windows-10:-Installation-instruction-for-SCT-on-Windows-subsytem-for-linux#environment-preparation) seems to fix the problem.

**Comment by alexfoias** [comment]
Maybe we could include the line :

`echo "export DISPLAY=127.0.0.1:0.0" >>$RC_FILE_PATH`

after this line:
https://github.com/neuropoly/spinalcordtoolbox/blob/ca79993a6bbb6c221a3054bf197658af9e258005/install_sct#L254

and this line:
https://github.com/neuropoly/spinalcordtoolbox/blob/ca79993a6bbb6c221a3054bf197658af9e258005/install_sct#L257

@jcohenadad what do you think ?

**Comment by jcohenadad** [comment]
i wouldn't enforce this global variable on the user's home env. 

what happens if you try to run (without making the change you suggested, make sure to restart a new terminal to clean up your env variables):
```
sct_get_centerline -i T1_contrast.nii -method viewer
```
Do you see a PyQt window that pops up?

**Comment by alexfoias** [comment]
I did the changes and cleaned up the env vars

The PyQt window pops up correctly.

**Comment by jcohenadad** [comment]
ok, so it's only a problem with the DISPLAY variable which is somehow not defined on the zsh 10.15 OSX. @kousu @saulo-p @cfhammill @bcdarwin any idea how we could check if users can open a figure? Some background about the "DISPLAY variable check" here: https://github.com/neuropoly/spinalcordtoolbox/pull/2522

**Comment by kousu** [comment]
`$DISPLAY` is a Linux-specific thing. OS X doesn't use X Windows (unless you go far out of your way) so it doesn't have this defined.

But looking through some CI logs, I see that OS X generally [has this defined](https://api.travis-ci.org/v3/job/685530762/log.txt)

```
Check if DISPLAY variable is set....................[[92mOK[0m]
```

while [Linux does not](https://api.travis-ci.org/v3/job/685530759/log.txt)

```
Check if DISPLAY variable is set....................[[91mFAIL[0m]
```

It *shouldn't* be defined in CI, because CI has no graphical display to use. Maybe older OS Xes were trying to try Unix programs into getting along by always defining $DISPLAY?

**Comment by alexfoias** [comment]
maybe it will help, I'm running **osx 10.15.4 (19E287)** with **zsh 5.7.1 (x86_64-apple-darwin19.0)**.

**Comment by kousu** [comment]
Great. I have a copy of that available too so I will be able to look at this closer. It's lower down on my priorities right now though.

**Comment by jcohenadad** [comment]
Another report from a user: https://forum.spinalcordmri.org/t/check-if-display-variable-is-set-fail-in-sct-check-dependencies/488/5

**Comment by Drulex** [comment]
Like @kousu mentioned `DISPLAY` is a `X11` specific environment variable so it doesn't make sense to rely on it on platforms that don't run X (even if it is sometimes set in other environments). It is not a good indicator and may confuse users.

Why check this in the first place? I think that if someone tries to use a GUI application/functionality in an environment that doesn't have a graphical interface of some sort it is reasonable to crash (with a nice error message).

**Comment by jcohenadad** [comment]
> Why check this in the first place? I think that if someone tries to use a GUI application/functionality in an environment that doesn't have a graphical interface of some sort it is reasonable to crash

In the past, I would have users contacting me saying e.g.  "sct_label_utils -i blabla -create-viewer doesn't work".  It would take 5 back-and-forth messaging for me to understand what "doesn't work" means. To avoid that back-and-forth, the check was introduced so the dev team can ask users to run `sct_check_dependencies` and figure out immediately what the problem is.
