### ISSUE TITLE
Update multi-subject processing documentation

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2697]
After https://github.com/neuropoly/spinalcordtoolbox/pull/2658, we should update the SCT course material and example dataset.

**Comment by alexfoias** [comment]
I can take care of this.

**Comment by cfhammill** [comment]
Thanks @alexfoias, let me know if you have any questions about the new script.

**Comment by joshuacwnewton** [comment]
This has been completed as part of the SCT course/SCT tutorial overhaul in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3493.
