### ISSUE TITLE
Disable `download()` progress bar in CI

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#2719]
Like, #2709, [`download()`](https://github.com/neuropoly/spinalcordtoolbox/blob/fcf2c9d29277ed85c70f9a9f7941922e104d997b/install_sct#L255) is noisy. This is good for interactive use but in CI it's a nuisance and uses up our 4MB logfile quota. We should figure out how to turn it off, but only for CI.

curl and wget don't seem to have any handy environment variables we can lean on here. Maybe set an `alias`? Or invent our own environment variable?

**Comment by cfhammill** [comment]
Why are we using `wget` or `curl`? Could we `spinalcordtoolbox/download.py` which uses `sct_progress_bar` that can be disabled with an environment variable?

**Comment by joshuacwnewton** [comment]
> Why are we using wget or curl? Could we spinalcordtoolbox/download.py which uses sct_progress_bar that can be disabled with an environment variable?

@cfhammill From what I can tell, we do use `sct_download_data` in most instances, I think! 

Ctrl+F'ing for 'download', the only usage of the `download()` function that I can see is grabbing the Miniconda install script. 

https://github.com/neuropoly/spinalcordtoolbox/blob/fcf2c9d29277ed85c70f9a9f7941922e104d997b/install_sct#L512-L519

I imagine we need to install Miniconda before we can do anything internal to SCT (even regardless of pip or no pip?). But, you've rightfully pointed this out. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
@kousu AFAIK `curl` and `wget` [provide `--silent` and `--quiet`](https://www.mattcutts.com/blog/how-to-fetch-a-url-with-curl-or-wget-silently/) flags respectively. This might be a dumb question on my part, but what would the environment variables you mention be used for?

**Comment by cfhammill** [comment]
@joshuacwnewton good point. I think @kousu just wanted a way to activate those just on travis. Which should be easy enough with one of the travis specific environment variables. Not much point in having them user configurable, the user probably almost always wants the progress bar.

**Comment by kousu** [comment]
Yep. To control them on Travis we need to use an environment var because that's how Travis let's us do things. But this could be as simple as rewriting all our calls to curl as

curl $CURL_SILENT

(note: *don't* quote this one; you want it to evaluate to nothing instead of the empty string)
and then setting CURL_SILENT=--silent in .travis.yml.

You can imagine more stable iterations of that idea.

On August 16, 2020 8:45:23 PM EDT, Chris Hammill <notifications@github.com> wrote:
>@joshuacwnewton good point. I think @kousu just wanted a way to
>activate those just on travis. Which should be easy enough with one of
>the travis specific environment variables. Not much point in having
>them user configurable, the user probably almost always wants the
>progress bar.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/neuropoly/spinalcordtoolbox/issues/2719#issuecomment-674602859

-- 
kousu

**Comment by kousu** [comment]
On August 16, 2020 4:57:21 PM EDT, Chris Hammill <notifications@github.com> wrote:
>Why are we using `wget` or `curl`? Could we
>`spinalcordtoolbox/download.py` which uses `sct_progress_bar` that can
>be disabled with an environment variable?

curl and wget are pretty standard tools. I consider them part of the baseline shell vocabulary.

And we need them for bootstrapping. download.py doesn't exist when install_sct starts.

consider brew or npm's standard install instructions which go `curl | bash`. Not that that's a good habit to encourage but until we're packaged #1516 in a real package manager this is the state of the art.

**Comment by joshuacwnewton** [comment]
Oh! I didn't even realize there was an issue for this. I fixed this in #3423.
