### ISSUE TITLE
Gather detection function under a single CLI

### ISSUE THREAD

**Issue by lrouhier** [spinalcordtoolbox/spinalcordtoolbox#2737]
The sct_label_vertebrae PR adds object detection models and a CLI to call the model. The idea would be to use a single CLI that load the model and perform the inference the same way sct_deepseg works now. 
sct_detect_pmj could be integrated into this new CLI.

**Comment by lrouhier** [comment]
This sct_detect CLI could also call a 'detect' script from ivadomed (which would need to be implemented) so that we keep the repartition made with sct_deepseg. 
It could benefits from a folder in `__sct_data_dir__` (something like detect_model).

**Comment by joshuacwnewton** [comment]
Closing this PR as the DL-based `sct_label_vertebrae` effort has stalled.

Any further ideas can be discussed when a future student picks up https://github.com/neuropoly/idea-projects/issues/6.
