### ISSUE TITLE
Binary output segmentation have INT64

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2758]
SCT version: 97c98986d39ddc6e448fa2db79c46f3d3fadafac

Output seg (with thresholding) has type INT64, where UINT8 could probably suffice.

**Comment by joshuacwnewton** [comment]
Closed in favor of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3959.
