### ISSUE TITLE
MSE threshold is too flexible in centerline tests

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2773]
The current integrity test has too much "flexibility" in the output:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c470421e32ee25f2b73de843fe5b11d05e316cf1/testing/test_sct_get_centerline.py#L53

Instead, we should:
- compare with a centerline obtained with the latest version of SCT
- do it on t1, t2s, t2 and dwi contrasts
- accept no error (e.g. we could compute the Dice between output centerlines and GT centerlines)

**Comment by joshuacwnewton** [comment]
This issue was fixed by #2774 (the test was refactored and moved to `pytest`), but the issue was never linked:

> Screenshot:
> ![image](https://user-images.githubusercontent.com/16181459/213883842-91405453-bb09-494c-b975-116e2e54a784.png)
