### ISSUE TITLE
Update documentation and examples using sct_download_data

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2778]
With https://github.com/neuropoly/spinalcordtoolbox/pull/2733, the default behaviour for downloading dataset has changed, see example below:

~~~
julien-macbook:~/temp/test $ sct_download_data -d sct_testing_data

--
Spinal Cord Toolbox (git-jca/2769-cross-platform-compatibility-9c768f0c2b55e5df559c8cc9bd2f973fdd996edc)

Trying URL: https://github.com/sct-data/sct_testing_data/releases/download/r20200504-11-g30ffe88/sct_testing_data-r20200504-11-g30ffe88.zip
Downloading: sct_testing_data-r20200504-11-g30ffe88.zip
Status: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 6.80M/6.80M [00:04<00:00, 1.60MB/s]
Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20200707114526.187413-ha46pk9q)
Unzip data to: /var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20200707114526.187413-ha46pk9q
Destination folder: /Users/julien/temp/test
Checking if folder already exists...
Removing temporary folders...
Done!

julien-macbook:~/temp/test $ ll
total 0
drwxr-xr-x   3 julien  staff   96  7 Jul 11:45 .
drwxr-xr-x@ 26 julien  staff  832  7 Jul 11:45 ..
drwxr-xr-x  13 julien  staff  416  7 Jul 11:45 sct-data-sct_testing_data-30ffe88
~~~

Namely, instead of created the expected `sct_testing_data` folder, it creates `sct-data-sct_testing_data-30ffe88`. In order to output `sct_testing_data`, one has to specify the output flag `-o sct_testing_data`.

The SCT course and various documentation should be updated accordingly.

**Comment by joshuacwnewton** [comment]
> Namely, instead of created the expected `sct_testing_data` folder, it creates `sct-data-sct_testing_data-30ffe88`. In order to output `sct_testing_data`, one has to specify the output flag `-o sct_testing_data`.

This behavior no longer exists in `sct_download_data.
