### ISSUE TITLE
Output json sidecars a la BIDS from various functions

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2807]
We should start outputting the provenance (software version) along with SCT outputs, to become closer to a proper [BIDS App](https://bids-apps.neuroimaging.io/about/). 

We could start outputting a json sidecar after running:
- `sct_deepseg_sc` (cord segmentation)
- `sct_deepseg_gm` (gm segmentation)
- `sct_label_vertebrae` (vertebral labeling)

Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2788

**Comment by joshuacwnewton** [comment]
Closing as duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3394.
