### ISSUE TITLE
Some functions are not working or became obsolete

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#2828]
While working on the documentation https://github.com/neuropoly/spinalcordtoolbox/pull/2814, I noticed a few functions that are not functioning. Some are stale and probably obsolete. The purpose of this issue is to decide what to do with them (keep or get rid of):
- isct_check_detection
- isct_convert_binary_to_trilinear.py --> usage works but outputs status=2
- isct_get_fractional_volume
- isct_minc2volume-viewer --> this one works (at least the usage works), but it's unclear what it does and if it is still relevant.
- isct_test_ants --> usage works but outputs status=2
- isct_warpmovie_generator also see https://github.com/neuropoly/spinalcordtoolbox/issues/2818

Related to https://github.com/neuropoly/spinalcordtoolbox/pull/2819, https://github.com/neuropoly/spinalcordtoolbox/issues/1548

**Comment by jcohenadad** [comment]
@joshuacwnewton @Drulex i think you've looked into related issues recently-- what is the status of this issue, can we close it?

**Comment by joshuacwnewton** [comment]
I've only looked at `isct_warpmovie_generator`, and that was just to move it to `dev/` temporarily. It still needs work to fix, but I'm not sure of the extent yet. I'm also unsure of the other scripts. So, this should stay open.

**Comment by joshuacwnewton** [comment]
This has been completed. 

We went over the obsolete scripts in the [2022-10-06](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.whzl7b1wl29g) dev meeting, then moved the scripts to `dev/` in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3908.
