### ISSUE TITLE
Remove pip install numpy from install_sct

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#2847]
https://github.com/neuropoly/spinalcordtoolbox/blob/49cb4a16ade7c91533e669c8d1d2a777f5bbfe66/install_sct#L532-L536

is a workaround for https://github.com/scikit-image/scikit-image/issues/4919. We should keep an eye on that issue and, if a solution is found, remove this line from our codebase.

See also https://github.com/neuropoly/spinalcordtoolbox/issues/2841#issuecomment-674435824_

**Comment by joshuacwnewton** [comment]
Closing as this was fixed by #2946 but never linked.
