### ISSUE TITLE
Update docs for spinalcordtoolbox.registration module

### ISSUE THREAD

**Issue by Drulex** [spinalcordtoolbox/spinalcordtoolbox#2872]
Once module is refactored, update the docs.

**Comment by RignonNoel** [comment]
Hi @Drulex ! Would it be possible for you to give me a little bit more information on which refactor we were waiting at the time you created this issue ?

I would like to clarify the issue content and status to make sure that it doesn't fall between two cracks.

**Comment by Drulex** [comment]
Probably this one: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2873 (sorry the description isn't very detailed).

The refactoring effort is (was?) tracked here: https://github.com/spinalcordtoolbox/spinalcordtoolbox/projects/7

**Comment by joshuacwnewton** [comment]
We no longer expose API documentation (due to the lack of availability for downstream users), so I'm closing this issue.

Any inline documentation (e.g. docstrings) can be updated as part of the refactoring issue itself.
