### ISSUE TITLE
Add extra indentation for continuations of list line wrapping in argparse help

### ISSUE THREAD

**Issue by cfhammill** [spinalcordtoolbox/spinalcordtoolbox#2889]
https://github.com/neuropoly/spinalcordtoolbox/pull/2842/files/73abe6a7dca60f4537d3743a3338ccc09f07990f#r485212011

For now the automatic line wrapping computes the indentation to match the first non whitespace character. This looks bad in a list e.g.

```
  - An item with a particularly long 
  explanation wraps like this
```

when we would want it to wrap like

```
  - An item with a particularly long 
    explanation wraps like this
```

Would need to add a special case in `SmartFormatter`

**Comment by joshuacwnewton** [comment]
Also worth noting that lists can come in different flavors, e.g. `-`, `*`, and numbered lists (`1. 2. 3.`) etc. which might make this trickier.

Depending on how complex this gets, we might want to expand the [Dash for flags dev Wiki page](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Dash-for-flags) into an "Argparse" page that talks in more detail about how to write descriptions for our `R|` formatting.

**Comment by joshuacwnewton** [comment]
We no longer use `R|` formatting; instead, we rely on a combination of built-in argparse formatters.

That said, this is still an issue. For example, using `sct_register_multimodal -h`:

![image](https://user-images.githubusercontent.com/16181459/212484330-06443015-a5e6-413f-ae32-44d63c16a31e.png)

Ideally, `type` would instead display:

```
                          - type: {im, seg, imseg, label} type of data used for registration. Use
                            type=label only at step=0.
```
