### ISSUE TITLE
Improvements to CI build

### ISSUE THREAD

**Issue by Drulex** [spinalcordtoolbox/spinalcordtoolbox#2923]
Context here: https://github.com/neuropoly/spinalcordtoolbox/pull/2910/files#r495432222

Purpose:
- Decouple CI tests from CI environment
- Speed up CI build using some kind of parallelization
- Run certain builds/suites only in certain conditions (e.g `batch_processing` on `master` or `cron`, linting on one platform only, etc)

**Comment by joshuacwnewton** [comment]
I'm also curious about optimizations for individual build jobs. e.g.
* [Caching dependencies](https://docs.travis-ci.com/user/speeding-up-the-build/#caching-the-dependencies)
* One-off tricks like the `git clone` settings mentioned in [this article](https://medium.com/pinterest-engineering/how-a-one-line-change-decreased-our-build-times-by-99-b98453265370) (see also the related [Hacker News](https://news.ycombinator.com/item?id=24877034) discussion). That would depend on what's currently taking up time in our `.travis.sh` script, of course.

Annoyingly, though, the build time is given as one long duration in the build logs. e.g. for [this CentOS 8 build](https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/739653682) it's displayed as `765.92s`. This makes it tricky to profile how long each of the individual steps take. 

![Screenshot from 2020-10-28 18-06-23](https://user-images.githubusercontent.com/16181459/97501839-605d5080-1948-11eb-9a6e-413c0b8660a0.png)

I did come across a ["Code folding and timing in Travis CI"](https://garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/) article that could be of use, though, so I'm mentioning it here for posterity. I'm going to try and replicate what that person did in their [deploy.sh](https://github.com/garbetjie/travis-folding-and-timing/blob/master/deploy.sh) script to see if I can find low-hanging fruit for optimization.

**Comment by joshuacwnewton** [comment]
After running into this:

![travis_bottleneck](https://user-images.githubusercontent.com/16181459/97517808-29406c80-1953-11eb-879b-16ebb77cb355.PNG)

I feel _sliiiiightly_ motivated to make this my next priority. :P

**Comment by Drulex** [comment]
I also looked at this issue briefly when exploring pip packaging and realized that the major bottleneck is the install step. It is very long due to the fact that `install_sct` is downloading and installing `miniconda` (also the same job does testing + linting). Even if we want to split the CI in multiple jobs, the install step would still be necessary in each job.

In my `pip` packaging experiment I simplified the installation to `pip install -e .` and was then able to split the CI build (using Github Actions) in different jobs (see https://github.com/Drulex/spinalcordtoolbox/actions and https://github.com/Drulex/spinalcordtoolbox/actions/runs/311130106/workflow). 

This brings a decent improvement, but the dependencies installation step is still long given the amount of dependencies. What is nice about Actions is that we can host our own actions runners and run the CI on our infrastructure (which is what I did), therefore we can control the environment. We could setup the environment with the required dependencies and effectively cut the installation time to a few seconds instead of a few minutes. Another advantage of a self-hosted actions runner is that we can run the tests on machines with more cores vs hosted Travis and Actions virtual machines that are typically 1-2 VCPU.

Anyways this is all experimental, but I am fairly confident that unless we transition to a more "lightweight" installation there isn't much we can improve on unless we use pre-configured environments.

**Comment by Drulex** [comment]
> After running into the queue getting backed up, I feel _sliiiiightly_ motivated to make this my next priority. :P

@joshuacwnewton https://github.com/neuropoly/spinalcordtoolbox/issues/2979

**Comment by joshuacwnewton** [comment]
Closing this issue, as the main problem have either been fixed or discussed elsewhere:

* `.ci.sh` no longer checks the branch we're on (so it is decoupled)
* The issue of parallelization is better covered by #2674
* For splitting up `.ci.sh` into different types of runs:
  * Linting and batch_processing.sh have now been handled by separate GH Actions workflows
  * For coverage, we have #2702
