### ISSUE TITLE
Document available tasks/models in deepseg

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3013]
As we add more models/tasks into deepseg, we need to document what these models could be used for. Beyond the short description which appears in `-list-tasks`, it would be great to show a representative image and segmentation output produced by this image.

Suggestion:
- In each model repository's README, display a figure
- In SCT's RTD, present each model by including the figure from each repos.

**Comment by joshuacwnewton** [comment]
Duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3767.
