### ISSUE TITLE
Order of flag has an impact on the use of -list-labels

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3014]
Based on this comment https://github.com/neuropoly/spinalcordtoolbox/pull/3012#pullrequestreview-525550375, we should find a solution for the order-sensitive use of `-list-labels`

**Comment by joshuacwnewton** [comment]
> ```shell
> sct_extract_metric -f test -list-labels 
> ```

The issue described in the review was fixed. Now the behavior is the same regardless of order:

```console
