### ISSUE TITLE
Problem detecting gcc installation on macOs Big Sur

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3049]
Context: https://forum.spinalcordmri.org/t/installation-validation-failed-installation-failed/570/6?u=jcohenadad

I am wondering if this line does not produce status=0, even with gcc being installed?
https://github.com/neuropoly/spinalcordtoolbox/blob/fc1879ea9aa2862c7c888d2454ae62bccde861d2/install_sct#L162

While addressing this issue, I suggest we move the [check_requirement](https://github.com/neuropoly/spinalcordtoolbox/blob/fc1879ea9aa2862c7c888d2454ae62bccde861d2/install_sct#L311) _after_ displaying the local specs, because this is relevant information for the dev team to help debugging:
~~~
SCT version ......... dev
Installation type ... in-place
Operating system .... osx (0.)
Shell config ........ /Users/alex/.zshrc
~~~

**Comment by joshuacwnewton** [comment]
Aha!

```
ANES-AKB46MBP:spinalcordtoolbox-5.0.1 akb46$ gcc --version

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

It looks like this might be a potential solution, but the recent replies are mixed: https://gist.github.com/gaquino/87bdf0e6e852e445c0489379d3e9732a

**Comment by jcohenadad** [comment]
hum... it might be that brew's install of gcc needs to be updated. I'd rather avoid relying on Apple's `xcode-select` command if we can.

**Comment by jcohenadad** [comment]
@alexfoias what do you get with `gcc --version` on your Big Sur?

**Comment by joshuacwnewton** [comment]
This link seems to cover it: https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

> The problem is that Xcode Command-line Tools needs to be updated

> With any major or semi-major update you'll need to update the command line tools in order to get them functioning properly again. Check Xcode with any update. This goes beyond Mojave...

**Comment by joshuacwnewton** [comment]
> hum... it might be that brew's install of gcc needs to be updated. I'd rather avoid relying on Apple's xcode-select command if we can.

Ah, apologies. I've just seen what you've mentioned. Good point.

**Comment by joshuacwnewton** [comment]
It looks like all is well on the user's end after updating command line tools. :)

https://forum.spinalcordmri.org/t/installation-validation-failed-installation-failed/570/10

**Comment by alexfoias** [comment]
> @alexfoias what do you get with `gcc --version` on your Big Sur?

```
[16/11/20 3:01:51] (base) alex@NeuroPoly-MacBook-Pro ~ % gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by jcohenadad** [comment]
> It looks like all is well on the user's end after updating command line tools. :)

right, but now we need to find a fix for the 99% of our macOs users who will experience a bug and are afraid to seek for help on the forum 😞 

@alexfoias: did you manually update our xcode tools after upgrading? i'm wondering why you did not have that issue.

**Comment by joshuacwnewton** [comment]
> right, but now we need to find a fix for the 99% of our macOs users who will experience a bug and are afraid to seek for help on the forum disappointed

A simple solution could be to parse for `xcrun: error: invalid active developer path` and ask the user to update their command-line tools. 

At the very least, I think we could update this to be a little more informative:

https://github.com/neuropoly/spinalcordtoolbox/blob/fc1879ea9aa2862c7c888d2454ae62bccde861d2/install_sct#L163-L164

As `gcc --version` returning a nonzero exit code won't always mean `gcc` isn't installed.

**Comment by jcohenadad** [comment]
A simple solution could be to parse for xcrun: error: invalid active developer path and instruct the user to update their command-line tools from the install script. But, hmm... I wonder about homebrew, as you've mentioned.

We should investigate more the homebrew solution...

> At the very least, I think we could update this to be a little more informative:

Agreed-- we should simply output the result of `gcc --version`.

**Comment by alexfoias** [comment]
Yes, xcode was one of the first apps that needed to update after the OS upgrade. I did it before running the install.

**Comment by Drulex** [comment]
Perhaps checking that `gcc` exists in the path is good enough. Instead of `gcc --version` we could check the return of `which gcc`.

**Comment by joshuacwnewton** [comment]
> Perhaps checking that `gcc` exists in the path is good enough. Instead of `gcc --version` we could check the return of `which gcc`.

Just to make sure we're on the same page here, from what I understand, the trouble is not so much detecting gcc, but our approach to updating gcc. We use homebrew to install gcc if `gcc --version` fails:

https://github.com/neuropoly/spinalcordtoolbox/blob/fc1879ea9aa2862c7c888d2454ae62bccde861d2/install_sct#L167-L174

But `brew install gcc` didn't actually fix things in this case. For this user, they got:

```
Do you want to install it now? (accepting to install "gcc" will also install "brew" in case it is not installed already)? [y]es/[n]o: y
Warning: gcc 10.2.0 is already installed and up-to-date
To reinstall 10.2.0, run `brew reinstall gcc`
```

So, `brew` thinks gcc is up to date, but Xcode command-line tools still needed to be updated.

**Comment by kousu** [comment]
We talked about this at the weekly meeting, but to summarize my perspective: gcc is only needed in case dependencies, or dependencies-of-dependencies, need to be compiled. We're talking about extension modules like skimage or numpy here. It's a code path that isn't hit very often, though it's important when it is hit.

python's packaging system only half-integrates with other languages. If it needs to build an extension module it will look for gcc (or the equivalent for whatever OS it's on) but it can't version pin the version of the compiler wants, or what optimizations to turn on or off. In order to achieve those things properly we need to use a different package manager.

The stop-gap that's most common in pythonland these days is to rely on .whl's. All python extension modules are (unofficially?) expected to have wheels pre-compiled and uploaded to PyPI.

Instead of relying on pip, it would be more reliable to use a more system-wide package manager. We can write custom `brew` and `conda` recipes for sct, maybe get ourselves packages in `apt` via neurodebian.

In the meantime, let's just take gcc out of the install script entirely. It's a "build-dep", not a "run-dep", so it's not even necessary most of the time. We can replace it with a note in the docs that if you're installing from source or on an unofficial platform you should make sure to have a compiler installed, "for example, `apt-get install build-essential` or `brew install gcc`".

**Comment by zougloub** [comment]
I think that a reasonable way is that unless we are using GCC directly, we should not check for it, and it would be reasonable when issues arise, to open bugs on the dependencies that are hit by build-from-source problems. Either that, or we make an SCT distribution.
We could also perform some checks in the installer, but instead of checking for GCC directly, we try to install a setuptools package which requires compiling C code. But it is possible that in some cases, GCC is not needed, because the user happens to have access to suitable wheels.

**Comment by Drulex** [comment]
Observation: I was messing with some minimal cloud images that don't have `gcc` installed (https://cloud-images.ubuntu.com/bionic/). I disabled the `gcc` check locally and was surprised to see that at least one library (`psutil`) tried to compile from source .

```
  Building wheels for collected packages: colored, psutil, pytest-console-scripts, requirements-parser, transforms3d, future, docopt, pyyaml, html5lib
  Building wheel for colored (setup.py) ... done
  Created wheel for colored: filename=colored-1.4.2-py3-none-any.whl size=14001 sha256=00adf2b42df213277e48024eab469f790ffaff3c90da6cf9316b431d5a547a8a
  Stored in directory: /home/cloud/.cache/pip/wheels/b7/be/ae/a98f7701429c3cfcebf4d2b537e48a1571549a4d8b55463a01
  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/spinalcordtoolbox/python/envs/venv_sct/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j9800sw8/psutil_b0aaf259aec3480e8c57c13ac3dcea9e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j9800sw8/psutil_b0aaf259aec3480e8c57c13ac3dc
ea9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6uvzxweb
       cwd: /tmp/pip-install-j9800sw8/psutil_b0aaf259aec3480e8c57c13ac3dcea9e/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
  creating build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_memleaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_testutils.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/psutil
  gcc -pthread -B /tmp/spinalcordtoolbox/python/envs/venv_sct/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=573 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/tmp
/spinalcordtoolbox/python/envs/venv_sct/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
  unable to execute 'gcc': No such file or directory
  C compiler or Python headers are not installed on this system. Try to run:
  sudo apt-get install gcc python3-dev
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil                                                    
```

I haven't tried messing around with `--only-binary` and other options, but I will at some point soon.

**Comment by jcohenadad** [comment]
Thank you for looking into this @Drulex !

**Comment by jcohenadad** [comment]
Error not being encountered for a while, closing for now.
