### ISSUE TITLE
Measure CSA based on distance from spinal cord landmark such as the pontomedullary junction (PMJ)

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3063]
## Context

Currently, CSA is measured and aggregated using vertebral levels. This is inaccurate, as people's positioning on the scanner (eg head tilting) impacts the location of the spinal level wrt. vertebral level.

We use the vertebral levels because they are easy to "see" and label, and also because this is what people have been doing so far. 

But some groups (eg UCSF, Queens U.) are now using the distance between a spinal (vs. vertebral) landmark in order to report CSA value.

## Proposed solution

Implement a way to compute CSA as a function of the distance to the PMJ. 

Some details:
- The PMJ can be detected with `sct_detect_pmj`. We should check the precision of the detection is sufficient.
- The computed distance should be along the spinal cord centerline (ie: not a "straight line" distance).

The input would be:
- the distance to the PMJ
- the extent of the mask in mm in the S-I direction

The output would be a binary mask with value 1. 

Illustration of the proposed approach (source: [Google Drawing](https://docs.google.com/drawings/d/1X3IIxPnRtuf2wE9ZVqqNUUvFyKhle-KRSAiWMLwJ4wE/edit)):

![CSA_length_PMJ](https://user-images.githubusercontent.com/2482071/122075905-6b2a0000-cdc8-11eb-8353-4ba117547fb2.png)

**Comment by sandrinebedard** [comment]
With the proposed approach, length from PMJ: cord curvature between PMJ and point where CSA is measured varies across individual → that adds variance 

**Solution**:
Take the projection of the PMJ on the extrapolated and spline-regularized SC centerline and compute the distance along the centerline:

![image](https://user-images.githubusercontent.com/71230552/122279364-f503c700-ceb5-11eb-8035-850dcb3db456.png)
