### ISSUE TITLE
Using SCT to straighten 3D T1 images

### ISSUE THREAD

**Issue by cepa995** [spinalcordtoolbox/spinalcordtoolbox#3074]
Hi, is there a way to use SCT in order to straighten specific part of the spine? For example in 3D T1 images as the one below: 

![image](https://user-images.githubusercontent.com/67524891/101043426-9a8cc400-357e-11eb-9642-899cf910385d.png)
I've looked at documentation and this seems like a likely solution: 
```
  -ldisc-input <file>   Labels located at the posterior edge of the
                        intervertebral discs, for the input image (-i). All disc
                        covering the region of interest should be provided.
                        Exmaple: if you are interested in levels C2 to C7, then
                        you should provide disc labels 2,3,4,5,6,7). More
                        details about label creation at http://sourceforge.net/p
                        /spinalcordtoolbox/wiki/create_labels/. This option must
                        be used with the -ldisc_dest parameter.
```

Am I on the right track, or is there other way to do it (i.e. specific feature in SCT) without manual labor?

**Comment by jcohenadad** [comment]
Hi,

the way to do it would be:
~~~
sct_deepseg_sc -i IMAGE -c t1
sct_straighten_spinalcord -i IMAGE -s IMAGE_seg
~~~

**Comment by jcohenadad** [comment]
fixed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3074#issuecomment-738068070
