### ISSUE TITLE
Add module for automatic contrast/modality detection

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3078]
>  **Note**: This issue has been created to document a WIP pull request that had become stale. No issue had been opened for that PR, so this issue is to discuss how best to continue that work.

PR #2328 aims to add automatic contrast/modality detection to various SCT scripts by creating a `spinalcordtoolbox/modality_detection` module. 

The old working branch (`bs/modality_detection`) is not in a usable state because of how greatly it has diverged from `master`. I've left it alone, but I also switched PR #2328 to a temporary base branch (instead of `master`) so that GitHub's UI would [display only the new commits](https://github.com/neuropoly/spinalcordtoolbox/pull/2328/commits). This is only for show, so that people in the future can more easily refer to the past work. 

Related work is contained in the https://github.com/bsauty/sc_mri_modality_detection repository.

**Comment by jcohenadad** [comment]
> Should this work be continued?

yup 😊 
--> https://github.com/neuropoly/spinalcordtoolbox/pull/2328#issuecomment-739040271

**Comment by jcohenadad** [comment]
Closing (for now), until it becomes a relevant issue again at some point
