### ISSUE TITLE
Split "Command-line Tools" RTD page into 1 page per CLI script

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3095]
Previously, in our old [SourceForge](https://sourceforge.net/p/spinalcordtoolbox/wiki/) documentation, we had a dedicated [Tools](https://sourceforge.net/p/spinalcordtoolbox/wiki/tools/) page containing subpages for each SCT script.

By comparison, on ReadTheDocs, we have a single ([Command-Line Tools](https://spinalcordtoolbox.com/en/stable/user_section/command-line.html)) page that contains *all* of the CLI scripts. I think it could be better to split this page up once more and have 1 page per script, for the following reasons:

* The existing page is very lengthy, so it is hard to skim through.
* Our argparse help descriptions are getting very long for some scripts. If we had dedicated RTD pages for each script, we could move some of this information to the script's webpage instead, making `-h` more readable.
    * Lengthy `-h` example: [`sct_register_multimodal`](https://spinalcordtoolbox.com/en/stable/user_section/command-line.html#sct-register-multimodal)
* We have existing "Advanced Usage Tips" pages for some commands. These pages are currently in the "Tutorials" section, but we could move these tips and tricks to each script's dedicated page. That way, the usage information for script is centralized in 1 location.
    * [`sct_propseg`](https://spinalcordtoolbox.com/en/stable/user_section/tutorials/correcting_sct_propseg.html)
    * [`sct_register_to_template`](https://spinalcordtoolbox--3094.org.readthedocs.build/en/3094/user_section/tutorials/customizing_registration.html)

**Comment by jcohenadad** [comment]
@joshuacwnewton this is a brilliant idea. Agreed with all the points you raised. 

Regarding the readability of some usages, eg [sct_register_multimodal](https://spinalcordtoolbox.com/en/stable/user_section/command-line.html#sct-register-multimodal), I am wondering if we could maybe come up with a flag, that would set the number of chars we want to display for the usage, and we would use that flag when generating the content on RTD (currently it's set for 80chars (i think), and we should definitely increase it).

**Comment by joshuacwnewton** [comment]
When you say "number of chars", you're referring to the width/length of each line, right? 

This is a bit tricky, because argparse line length is set when the argparse text formatter is first initialized:

```python
    parser = argparse.ArgumentParser(
        formatter_class=HelpFormatter(width=80)  # Set to value >80
    )
```

In our case, we have our custom `SmartFormater` that we would adapt. But, the point being, width has to be set before the arguments themselves are parsed. :sweat_smile: 

I do have an alternate idea, though. There is a Sphinx extension called [`sphinx-argparse`](https://sphinx-argparse.readthedocs.io/en/stable/) which renders argparse help descriptions as proper html (tables, headers, etc.). This could be more readable than using the plaintext output of `-h`, and this would solve the line length problem at the same time. :slightly_smiling_face:

**Comment by jcohenadad** [comment]
> When you say "number of chars", you're referring to the width/length of each line, right?

yup!

> In our case, we have our custom SmartFormatter that we would adapt. But, the point being, width has to be set before the arguments themselves are parsed. 😅
I do have an alternate idea, though. There is a Sphinx extension called sphinx-argparse which renders argparse help descriptions as proper html (tables, headers, etc.). This could be more readable than using the plaintext output of -h, and this would solve the line length problem at the same time. 🙂

brilliant!!!

**Comment by joshuacwnewton** [comment]
I'm realizing now that this wasn't addressed by #3355 like I thought. It might have been in a previous iteration of that PR. Oops, my bad for linking the PR to this issue. :sweat_smile:

**Comment by joshuacwnewton** [comment]
One other benefit of this is that we can link between the tutorials and the command line tools pages.

For example, take the ["Shape Metric Computation"](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/shape-metric-computation.html) page:

> This section demonstrates how to compute shape metrics of the spinal cord using the `sct_process_segmentation` command. Of primary interest is the cross-sectional area (CSA) of the spinal cord, but this command will also calculate other shape metrics, such as diameter, orientation, and symmetry of the cord.

Instead, I'm envisioning using the [`:any:`](https://stackoverflow.com/questions/45741961/sphinx-add-code-formatting-to-ref?rq=1) role to get the following effect:

> This section demonstrates how to compute shape metrics of the spinal cord using the [`sct_process_segmentation`](https://spinalcordtoolbox.com/user_section/command-line.html#sct-process-segmentation) command. Of primary interest is the cross-sectional area (CSA) of the spinal cord, but this command will also calculate other shape metrics, such as diameter, orientation, and symmetry of the cord.

Except in this case, the link will automatically point to a dedicated page for the CLI script, one that looks something like [this](https://spinalcordtoolbox--3340.org.readthedocs.build/user_section/command-line.html#sct-analyze-lesion).

Then, we could also link back from the CLI script page to the tutorial pages (e.g., `"This script is featured in the following tutorials..."`) so it will be easy to jump back and forth.

**Comment by joshuacwnewton** [comment]
Note to self: In the most recent SCT Course (2023), we rewrote the segmentation section to de-emphasize `sct_propseg`. However, `sct_propseg` had a very detailed page dedicated to tweaking its parameters.

When we split the command line page into individual pages, we should re-add this information back to the `sct_propseg` page.

**Comment by joshuacwnewton** [comment]
I'd like to try returning to this issue as per the motivation from `sct_deepseg` (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3767#issuecomment-2340850327).

Specifically, my "pie in the sky" pipe dream is to implement `sphinx-argparse` formatting for all of our scripts. For more context, see my previous experiment here: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3340#issuecomment-1128955919

On reflection, I'm hoping it will be possible to automate the necessary reformatting. Mainly, the need for `\n` to be at the start of the next string, rather than the end of the previous string. If I can do that, then the effort required to reformat the docs will be drastically decreased. 

I think this is also a good opportunity to see how `sphinx-argparse` has evolved. Perhaps the reformatting isn't even necessary? :thinking:
