### ISSUE TITLE
Migration to new organization

### ISSUE THREAD

**Issue by alexfoias** [spinalcordtoolbox/spinalcordtoolbox#3096]
The current repository is under neuropoly. The plan is to move it to https://github.com/spinalcordtoolbox

**Comment by alexfoias** [comment]
One thing to keep in mind is the sponsor feature. Currently is activated for the neuropoly organization, not sure if additional paperwork would be necessary if we change the organization.

**Comment by jcohenadad** [comment]
> One thing to keep in mind is the sponsor feature. Currently is activated for the neuropoly organization, not sure if additional paperwork would be necessary if we change the organization.

Excellent point indeed, but no: no additional paperwork needed. As you can see in the sponsor page, other projects not part of neuropoly are listed (qMRLab, etc.)

**Comment by joshuacwnewton** [comment]
Just to be thorough, I took a quick look at [GitHub's Guide to Organizations](https://resources.github.com/downloads/github-guide-to-organizations.pdf) to get a sense of the pros/cons of different organization structures. This part specifically stood out to me:

> **Option 2: A SINGLE ORGANIZATION WITH MULTIPLE TEAMS TO MANAGE REPOSITORY ACCESS**
>
> This can potentially create a substantial work load for administrators in larger companies with many teams [...]. This method should be avoided by large companies where no single owner should have access to all repositories.

This sounds like it describes the administation workload neuropoly has been facing. So, I think it makes a lot of sense to split SCT off into its own org, rather than keeping SCT under the neuropoly umbrella. 

I would be happy to take care of administrative tasks for the spinalcordtoolbox org (teams, repository moving, etc.). :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
Question: Isa second SCT org for ["sct-data"](https://github.com/sct-data) necessary? I'm looking at [ivadomed's](https://github.com/ivadomed) structure, and they group all of their repos under a single org.

cc: @kousu who has been working on the sct-data repos recently.

**Comment by jcohenadad** [comment]
> Question: Is it necessary to have multiple SCT orgs (for "sct-data" and "sct-pipeline")? I'm wondering if this is overly complicated, making adminsitration/collaboration/discoverability a little tougher. These are all related projects, so having them be linked under a single org makes a bit more sense to me.

great question-- i've been asking myself this question for the past 5 years without definite answer. The main motivation for keeping a specific org for sct-pipeline is that sometimes we use the URL to the organization in papers/grants/conferences, e.g.  "_SCT also has a few compatible pipelines (https://github.com/sct-pipeline) which are really really cool! 🤓_ "

and the sct-data repos, well... i guess this one could indeed go under "spinalcordtoolbox" org 😊 . I don't see any good reason against it.

**Comment by kousu** [comment]
A reminder to us: please update https://docs.google.com/document/d/128gydw06Wzvb6VlgE_bCzsOdHnqv4_PrcdvC5RD63uk/edit#heading=h.594n4g8ijcio 's Github section once this is done.

**Comment by joshuacwnewton** [comment]
As a small update: This has mostly been completed! 

There is one last thing I would like to ask about: The `neuropoly` org contains a number of SCT-affiliated side projects. You can find a full list here: https://github.com/orgs/neuropoly/teams/spinal-cord-toolbox/repositories

@jcohenadad @charleygros Would you be able to touch on the current status of these repos (active or stale?), and whether they should be moved?

**Comment by jcohenadad** [comment]
> @jcohenadad @charleygros Would you be able to touch on the current status of these repos (active or stale?), and whether they should be moved?

absolutely! i think they are all more or less stale. In order of staleness (less stale to more stale), i would put:
- neuropoly/distriploy  (we've recently used it, but it is not sct-specific)
- neuropoly/docker (i don't think we are using that anymore, maybe it will be useful in the future, but here again i don't think it is sct-specific)
the other ones are either completely stale (no need to move) or not sct-specific

**Comment by joshuacwnewton** [comment]
Thank you for the clarification! In that case, we should maybe consider archiving the most stale repositories (which is a [reversible read-only status](https://github.blog/2017-11-08-archiving-repositories/) to indicate when projects are no longer receiving contributions).
