### ISSUE TITLE
Function `zeros_like()` performs an unnecessary, noisy rescaling operation

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3110]
See also https://github.com/neuropoly/spinalcordtoolbox/pull/3104#issuecomment-747763574.

`spinalcordtoolbox/image.py` has a function called `zeros_like`. It creates a copy of the image (to preserve headers, etc.) using the `change_type` function, then sets the data values to 0.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/11249f7b9eab4791cd1834c537cfafd1379bac02/spinalcordtoolbox/image.py#L1227-L1229

`change_type` has some additional rescaling logic to handle quantization errors that also warns the user. Normally this is useful for non-zero images, but since we're just going to be setting data to 0 anyway, it's unnecessary.

So, I think it might be better to do this instead, which should also prevent the warning from firing.

```
dst = img.copy()
dst.data[:] = 0 
dst = dst.change_type(dtype)
return dst 
```

**Comment by zougloub** [comment]
I think it's more elegant if you can make a copy of headers but use `new.data = numpy.zeros_like(ref.data)`
