### ISSUE TITLE
Display vertebral level when using -perslice 1 option

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3113]
When running `sct_process_segmentation` (or `sct_extract_metric`) with option `perslice 1`, each row corresponds to a slice. However, when doing so, the column "VertLevel" is empty:

Filename | Slice (I->S) | VertLevel | MEAN(area)
-- | -- | -- | --
/Users/julien/temp/20201217_inspired/results6/data_processed/HC02/bl/cord/processing_sct/t2_tra_seg.nii.gz | 0 |   | 70.41316501066880
/Users/julien/temp/20201217_inspired/results6/data_processed/HC02/bl/cord/processing_sct/t2_tra_seg.nii.gz | 1 |   | 76.68867922117070
/Users/julien/temp/20201217_inspired/results6/data_processed/HC02/bl/cord/processing_sct/t2_tra_seg.nii.gz | 2 |   | 76.84621033344560
/Users/julien/temp/20201217_inspired/results6/data_processed/HC02/bl/cord/processing_sct/t2_tra_seg.nii.gz | 3 |   | 81.27146085321930
/Users/julien/temp/20201217_inspired/results6/data_processed/HC02/bl/cord/processing_sct/t2_tra_seg.nii.gz | 4 |   | 82.83952355053640

It shouldn't be empty, because we _know_ the information about vertebral level, if user input vertebral labeling file, as was done here, with the flag `-vertfile`. 

So as a feature, we should fill this column "VertLevel" when the vertebral level for each slice is known.

**Comment by joshuacwnewton** [comment]
I very much agree with this suggestion. The blank space stood out to me too while writing #3094.

We already have the capacity to get the level values, e.g. when we do `-perslice 1 -vert`:

https://github.com/neuropoly/spinalcordtoolbox/blob/997c82ebaa2aa3c0502b9fc3d8f753d0efbc08a7/spinalcordtoolbox/aggregate_slicewise.py#L260

But, for `-perslice 1 -z` we don't bother getting the level values for some reason.

https://github.com/neuropoly/spinalcordtoolbox/blob/997c82ebaa2aa3c0502b9fc3d8f753d0efbc08a7/spinalcordtoolbox/aggregate_slicewise.py#L269

So, I think a small tweak to this line in  `aggregate_per_slice_or_level()` is all we need.
