### ISSUE TITLE
Create CLI for self2patch denoising for DWI data

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3115]
Details of the method: https://shreyasfadnavis.medium.com/patch2self-self-supervised-denoising-via-statistical-independence-4601fda38c20

**Comment by joshuacwnewton** [comment]
Duplicate of #3234.

**Comment by joshuacwnewton** [comment]
Re-opening just to test this GitHub feature: https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate

**Comment by joshuacwnewton** [comment]
Duplicate of #3234

**Comment by joshuacwnewton** [comment]
Aha! So you have to make sure to not add a period at the end for some reason... :facepalm:
