### ISSUE TITLE
Redundant 'change_orientation' for vertebral labeling file

### ISSUE THREAD

**Issue by yanchunCoBIUS** [spinalcordtoolbox/spinalcordtoolbox#3134]
The **vertebral labeling file** has been changed orientation(`Image().change_orientation('RPI')`) twice, which is redundant, the details trace of the code in the following:

File: `sct_extract_metric.py`:
- [Line 360](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_extract_metric.py#L360), in main:
    -  `im_vertebral_labeling = Image(fname_vertebral_labeling).change_orientation("RPI")`
- [Line 381-383](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_extract_metric.py#L381-L383), in main:
    - `agg_metric = extract_metric(data, labels=labels, slices=slices, levels=levels, perslice=perslice,
                                    perlevel=perlevel, vert_level=im_vertebral_labeling, method=method,
                                    label_struc=label_struc, id_label=id_label, indiv_labels_ids=indiv_labels_ids)`

File: `aggregate_slicewise.py`:
- [Line 426-428](https://github.com/neuropoly/spinalcordtoolbox/blob/08498bffb297dabccd43a3ab8967cdeea3ff1bd7/spinalcordtoolbox/aggregate_slicewise.py#L426-L428), in extract_metric:
    - `return aggregate_per_slice_or_level(data, mask=mask, slices=slices, levels=levels, perslice=perslice,
                                        perlevel=perlevel, vert_level=vert_level, group_funcs=group_funcs,
                                        map_clusters=map_clusters)` 
- [Line 250](https://github.com/neuropoly/spinalcordtoolbox/blob/08498bffb297dabccd43a3ab8967cdeea3ff1bd7/spinalcordtoolbox/aggregate_slicewise.py#L250), in aggregate_per_slice_or_level:
    - `im_vert_level = Image(vert_level).change_orientation('RPI')`

**Comment by jcohenadad** [comment]
i wouldn't use the label "bug" thought, but rather "enhancement"

**Comment by joshuacwnewton** [comment]
This issue was fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/49ed68e029886661ad93546f5c0cd981839a6541 (see: commit https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3120/commits/6cc12ca04ba79e830eee0575cba355fdeb66d9b2), but the issue was never linked.
