### ISSUE TITLE
Centralize SCT's test data code (dummy fixtures, 'sct_testing_data/')

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3136]
Currently, SCT tests use test data from a few different locations:

* `sct_testing_data/`: Contains real anatomical images
* `spinalcordtoolbox/testing/create_test_data.py`: Contains a few `dummy_<imagetype>` functions
* `unit_testing/test_aggregate_slicewise.py` (and many others): Per-test-module `pytest.fixtures` for dummy image data. There are lots of these scattered about.

I have few questions... My hope is to write some clearer recommendations in the [Tests](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Tests) developer Wiki page.

* When should we be using real anatomical data vs. dummy data? (I imagine it's context-dependent, but are there any broad recommendations we can give to make writing tests easier for contributors? This would be useful in cases like https://github.com/neuropoly/spinalcordtoolbox/pull/3120#discussion_r549472092)
* Are we even using all of the dummy data functions? 
* Can we centralize the dummy data functions? (It seems a bit scattered to have dummy data in both in the `spinalcordtoolbox` module _and_ in each individual test file. I'm wondering if we could move the fixtures to a centralized file containing test data fixtures, so they're available to all tests. That way, we're more likely to reuse existing dummy data, rather than creating data each time we write a new test.)

**Comment by joshuacwnewton** [comment]
In https://github.com/neuropoly/spinalcordtoolbox/pull/3152#discussion_r553622125, I proposed that some module-scoped dummy test images should instead be prepared in `conftest.py`. This would allow us to use `pytest.mark.parametrize` without having to rely on fixture functions.

**Comment by joshuacwnewton** [comment]
> Can we centralize the dummy data functions? (It seems a bit scattered to have dummy data in both in the `spinalcordtoolbox` module _and_ in each individual test file. I'm wondering if we could move the fixtures to a centralized file containing test data fixtures, so they're available to all tests. That way, we're more likely to reuse existing dummy data, rather than creating data each time we write a new test.)

I've come across the [`pytest-cases`](https://smarie.github.io/python-pytest-cases/#why-pytest-cases) plugin. It provides a really nice way of organizing test data (test cases). It's also well-documented and well-maintained.

It also solves a related problem. Right now, Pytest doesn't allow us to use our data fixtures with parameterization. We've bumped into this a few times (https://github.com/neuropoly/spinalcordtoolbox/pull/3116#discussion_r548999135, https://github.com/neuropoly/spinalcordtoolbox/pull/3152, etc.), so using this plugin could be a "two birds with one stone" kind of solution.

**Comment by kousu** [comment]
Judging from people confused in these pytest threads (and even one entire subpackage!):

* https://github.com/pytest-dev/pytest/issues/349#issuecomment-251174481
* https://smarie.github.io/python-pytest-cases/#why-pytest-cases
* https://stackoverflow.com/questions/42228895/how-to-parametrize-a-pytest-fixture/56871701#56871701

I would suggest our problem here stems from pytest having a blind-spot in that

>     requires a few lines of code to be generated. For example artificial data creation using numpy and/or pandas

case, which is something we do a lot of. Everything we call "dummy data" falls under this case. I think the pattern we've been using so far is:

```
def dummy1():
   return ...

def dummy2():
   return ...

@pytest.mark.parameterize('image', [dummy1(), dummy2()])
def test_something(image):
    assert image.something ...
```

That's not great because:

1. it generates all the dummy data when the test modules are first loaded; this means it generates all that data even if their tests aren't run
    - this [seems to be](https://stackoverflow.com/questions/42228895/how-to-parametrize-a-pytest-fixture/56871701#56871701) the pytest devs' primary anxiety
2. this doesn't fit in with the rest of the fixtures system, which led to the glitches I'm currently trying to fix by using fixtures the way pytest wants in #3152

**Comment by joshuacwnewton** [comment]
> I would suggest our problem here stems from pytest having a blind-spot

Exactly. Pytest doesn't allow us to use our data fixtures with parameterization (https://github.com/pytest-dev/pytest/issues/349). We've bumped into this a few times (https://github.com/neuropoly/spinalcordtoolbox/pull/3116#discussion_r548999135, https://github.com/neuropoly/spinalcordtoolbox/pull/3152, etc.), because it's natural for us to want use data fixtures (our input data often requires some setup, given the complexity of medical imaging data). And, it's natural for us to want to parametrize, too. 

The [`pytest-cases`](https://smarie.github.io/python-pytest-cases/#why-pytest-cases) plugin was designed to solve exactly this problem, and is well-documented/well-maintained. It also provides a really nice way of organizing test data (test cases), which would address the "Can we centralize the dummy data functions?" question, too. So, I think using this plugin could be a "two birds with one stone" kind of solution.

**Comment by kousu** [comment]
Solutions:

1. Write scripts to generate dummy data, but then *save them to a file* and include them in `sct_testing_data/`
    - I guess then we have to keep the scripts around in https://github.com/neuropoly/spinalcordtoolbox/tree/master/testing ?
2. The `request.getfixturevalue()` workaround: https://stackoverflow.com/questions/42014484/pytest-using-fixtures-as-arguments-in-parametrize/42599627#42599627 (this only works for for us because our dummy data is not itself parameterized)
3. Use `pytest-cases`

**Comment by joshuacwnewton** [comment]
I've just noticed https://github.com/pytest-dev/pytest/issues/349#issuecomment-664373270

I feel even more comfortable going with 3) knowing that a pytest dev likes `pytest_cases` enough to want to integrate the plugin into core functionality.

**Comment by joshuacwnewton** [comment]
I've written a [**Test data**](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming:-Test-data) dev Wiki page providing recommendations and an overview of how we currently do things. Please give it a read if you have time, and let me know if you have any thoughts about how it could be improved.

My main suggestion moving forward would be to turn the functions in `spinalcordtoolbox/testing/create_test_data.py` into proper test fixtures. I'm thinking that we would have a file dedicated to data fixtures where people can look first before creating new fixtures.

**Comment by kousu** [comment]
It's okay to make fixtures that are local to each test suite/file/folder. In fact, pytest is designed for that: you can do `@fixture(scope="module")` or as a method inside a class full of `test_` functions: https://docs.pytest.org/en/stable/fixture.html#autouse-fixtures-xunit-setup-on-steroids.

If we have common fixtures, then yes, I agree, For example:

https://github.com/neuropoly/spinalcordtoolbox/blob/3dfd4f81f9e4364dab4d94894ea687a625dbdea5/unit_testing/test_image.py#L137-L146

is used

https://github.com/neuropoly/spinalcordtoolbox/blob/3dfd4f81f9e4364dab4d94894ea687a625dbdea5/unit_testing/test_labels.py#L44

and ditto here

https://github.com/neuropoly/spinalcordtoolbox/blob/3dfd4f81f9e4364dab4d94894ea687a625dbdea5/unit_testing/test_labels.py#L31

I made it into a fixture on this branch.  It's probably okay to stay there for now but I'd be into splitting these fixtures out into differently themed fixture-only files. I haven't read enough of the tests to know how to arrange that though.

**Comment by joshuacwnewton** [comment]
Given the discussion here, as well as the creation of the "Test data" page, I think the only thing remaining is:

> - `spinalcordtoolbox/testing/create_test_data.py`: Contains a few `dummy_<imagetype>` functions

We should get these dummy data fixtures out of the `spinalcordtoolbox` package and into `testing` (assuming they're even used at all).
