### ISSUE TITLE
Lint shell in CI

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3143]
Once we do #3142, it would be good to also add [`shellcheck`](https://github.com/koalaman/shellcheck/) to our CI runs. We don't have a lot of shell scripts but the ones we do have are critical glue. I've fixed up all the shell issues it could find in #3102, so the next step would be to keep them clean with the help of shellcheck.

**Comment by joshuacwnewton** [comment]
Since changes to our shell scripts are (relatively) infrequent, would it be easier to only run `shellcheck` when needed? 

I've added a [Shell scripts](https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming:-Shell-scripts-(install_sct,-.ci.sh,-.travis.sh)) page in the dev Wiki for now.
