### ISSUE TITLE
Replace argv=None with type hinting in script main functions

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3176]
In https://github.com/neuropoly/spinalcordtoolbox/issues/3085#issuecomment-740083842, we decided on `None` as a default value for `argv` in all of our scripts.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/37f0bde2ca521424598ba9665853b2c99944996b/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L509

But, on second thought, why does main need a default value? We expect that `argv` should always be passed, and `None` can cause issues like: https://github.com/neuropoly/spinalcordtoolbox/pull/3156#issuecomment-759593822. To fix #3156, I rewrote the `main()` declaration as follows:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/51511fc387113c853c290b0a5d81c85a02fd9f93/spinalcordtoolbox/scripts/sct_label_utils.py#L234-L239

(We also expect `argv` to be a list of strings (i.e. unparsed CLI arguments), so I added type hinting for this. An empty list `[]` will pass the type-hinting check, too. This is good, as calling `main(argv=[])` fulfills scripts where calling no args is valid, too.) 

I think it could be good to add this to the remaining scripts, too.

**Comment by kousu** [comment]
I like this idea.
