### ISSUE TITLE
Change "installation" GH label from category to context

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3192]
SCT uses labels to organize issues/PRs:

* **Category** labels (1 per PR) that say what kind of change it is (e.g. bugfix, refactoring, feature, etc.)
* **Context** labels (1+ per PR) that say what areas of the codebase the change affects (e.g. sct_deepseg, API: image.py, etc.)

Right now, "installation" is a category label. But, installation is more like an area of the codebase (`install_sct`), and often we want to combine "installation" with "bugfix" or "refactoring" and etc. So, I think it should be a context label instead.

(I was fixing up the labels for the 5.1.0 release when I thought of this... lots of installation + bug PRs, and installation + refactoring PRs.)

**Comment by jcohenadad** [comment]
I don't have a strong opinion on this. I'll join the majority.

**Comment by joshuacwnewton** [comment]
It's quite a nitpicky thing, anyway... I believe it only truly affects how PRs are grouped in our changelog. :sweat_smile:

**Comment by joshuacwnewton** [comment]
I'm going to close this, as I realize now that `installation` is used for more than just `install_sct`/`setup.py` issues, but also packaging/distribution, so I think it makes sense to keep it as a category label.
