### ISSUE TITLE
Estimate cord atrophy using SoftSeg

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3207]
### Context

Estimating subtle cord atrophy is important in MS.
Recent work [LINK TO PAUL REPOS] introduced a pipeline to quantify the sensitivity of "hard" segmentation to detect small atrophies. The pipeline is based on a global resizing of the image.
With the recent introduction of SoftSeg [REF], which produces soft segmentations, we would like to investigate whether CSA measured from soft segmentation is more sensitive to detect subtle atrophy.

### Methodology

- Adapt Paul's pipeline for SoftSeg
- Compare conventional vs. SoftSeg approach

### Bibliography

- Gros et al
- Paul article
- other MS cord atrophy related articles

**Comment by joshuacwnewton** [comment]
Migrated to https://github.com/neuropoly/idea-projects/issues/8.

**Comment by jcohenadad** [comment]
Duplicate of https://github.com/sct-pipeline/csa-atrophy/issues/24
