### ISSUE TITLE
Provide clear, up-to-date recommendations for manual vertebral labeling in RTD

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3265]
A [user on the forum](https://forum.spinalcordmri.org/t/best-practices-for-manually-defining-vertebral-levels/645) has asked for clarification about best practices for performing manual vertebral labelling, prior to running `sct_register_to_template`. Some points of confusion:

* When should manual labelling be used? (vs. automatic labelling)
* How many vertebrae should be labelled? (1 vs. 2 vs. 2+)
* Where should the labels be placed? (Body vs. disc)

@jcohenadad has provided [an in-depth comment](https://forum.spinalcordmri.org/t/best-practices-for-manually-defining-vertebral-levels/645/2?u=joshuacwnewton) addressing these points. It would be good to translate this into a page on RTD.

_(**Note:** There is currently [an open PR](https://github.com/neuropoly/spinalcordtoolbox/pull/3094) to add material for `sct_register_to_template` to RTD (from the existing SCT Course). But, the existing material only briefly mentions manual labelling, see https://github.com/neuropoly/spinalcordtoolbox/pull/3094#discussion_r588916789. So, perhaps manual labelling advice should go into its own separate page, as to not overload the SCT Course.)_

**Comment by jcohenadad** [comment]
> perhaps manual labelling advice should go into its own separate page, as to not overload the SCT Course.

I _think_ that having everything about vertebral labeling centralized into one location would be easier than to have to look at different places. If we do a good job in presenting it in a hierarchical way (eg: not a flat collection of paragraphs, but some sub-headings, with "basic principle', "additional tips", "for experts", etc. it will be easy to navigate and not too overwhelming)
