### ISSUE TITLE
sct_deepseg output data with suffix "-manual" which is confusing (and wrong)

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3278]
### Description

Running this:
```console
Spinal Cord Toolbox (git-HEAD-79b2046831b02c5fb3ab742978777ba81e00ad49)

sct_deepseg -i dwi_1500_orient_dwi_mean.nii.gz -task seg_mice_gm-wm_dwi
--


WARNING: fname_roi has not been specified, then the entire volume is processed.

Loaded 512 axial slices.
^[[B
Done! To view results, type:
fsleyes dwi_1500_orient_dwi_mean.nii.gz -cm greyscale dwi_1500_orient_dwi_mean_gmseg_manual.nii.gz -cm red -a 70.0 &
```

As can be seen, the output segmentation is called with added suffix `_gmseg_manual`. Why the "manual", given this is an automatic segmentation? @charleygros maybe you have a clue?

**Comment by charleygros** [comment]
> As can be seen, the output segmentation is called with added suffix `_gmseg_manual`. Why the "manual", given this is an automatic segmentation? @charleygros maybe you have a clue?

When "-o" is [not specified](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_deepseg.py#L226) in the command line, we pull the [target suffix that is used during training](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/inference.py#L307) (often "XX-manual"...).
This needs to be changed. I will take care of it in coming PR. Plus, this is not in line with the [parser documentation](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_deepseg.py#L54).

**Comment by charleygros** [comment]
I corrected the config file of this [specific model](https://github.com/ivadomed/model_seg_mice_gm-wm_dwi_unet2d-multichannel-softseg/commit/387bd16d29af589586e6af0104a6f2beb11abd9a).

The parser documentation will be corrected in a coming SCT PR also including new release of this model (renamed and possibly retrained, see [issue](https://github.com/neuropoly/spinalcordtoolbox/issues/3279)). Coming soon.

**Comment by charleygros** [comment]
Updates:
- PR initiated here: PR #3321 
- Still working on the new model, see [issue](https://github.com/neuropoly/spinalcordtoolbox/issues/3279) --> Expected tomorrow (Australia time)
- Once the model is retrained --> new release of it --> update release ID in the `sct_deepseg` code --> PR ready for review when done

**Comment by joshuacwnewton** [comment]
I'm reopening this issue because the same issue exists for the `seg_lumbar_sc_t2w` model, which is very relevant for the following tutorial:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4180

I'll look into a fix for this ASAP.

**Comment by joshuacwnewton** [comment]
I've double-checked all of the existing deepseg models, and 1 other model uses the `_seg-manual` suffix (`t2star_sc`). The rest of the models use appropriate suffixes.

I'll update both releases and submit a PR.
