### ISSUE TITLE
Force location of data downloading for some datasets

### ISSUE THREAD

**Issue by charleygros** [spinalcordtoolbox/spinalcordtoolbox#3312]
**Feature justification: Is your feature request related to a problem? Please describe.**

When using `sct_download_data`, some data (e.g. `exvivo_template` or deepseg models) should be installed under specific folders, eg `$SCT_DIR/data/`. Here is a full list of our current uses of `sct_download_data` (from https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3310#issuecomment-805972981):

> 1. Binaries -> `bin/`
> 2. Models -> `data/`
> 3. Templates -> `data/`
> 4. Testing/example data -> `./`
> 5. Course data -> `./`

More context [here](https://github.com/neuropoly/spinalcordtoolbox/issues/3280#issuecomment-805395427).

**Describe the solution you'd like**
If `-o` is not specified by the user, we can use the default location for each dataset, that could be integrated in a dictionary, similarly than [here ](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_download_data.py#L24) with the URL.

**Comment by joshuacwnewton** [comment]
This is especially relevant for our test suite, as downloading the test data to the working directory results in many duplicated copies of `sct_testing_data` if you run `pytest` in different locations.

This cropped up in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3436#discussion_r660865597, so there's motivation to fix this before releasing https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3373.
