### ISSUE TITLE
Output XXX_seg_labeled.nii.gz is FLOAT64

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3318]
outputs:
- t1_seg_labeled.nii.gz
- t1_seg_labeled_discs.nii.gz

are in FLOAT64.

This is a waste of space and prone to error. Output should be UINT8.

to reproduce: try with sct_example_data

**Comment by joshuacwnewton** [comment]
Closed in favor of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3959.
