### ISSUE TITLE
Calling an SCT script using `.main()` changes the global logging level

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3341]
At the start of each CLI script, we set the global logging level using the parsed verbose argument. For example:

https://github.com/neuropoly/spinalcordtoolbox/blob/916ab591ca2e35cab9f5f27ec2439ce8fdb0b9d2/spinalcordtoolbox/scripts/sct_apply_transfo.py#L341-L344

This works as intended when calling scripts via the command line. However, when calling a script in code via `.main()`, changing the global logging level like this feels more like an unexpected side effect. 

For example, take this call in `moco.py`:

https://github.com/neuropoly/spinalcordtoolbox/blob/916ab591ca2e35cab9f5f27ec2439ce8fdb0b9d2/spinalcordtoolbox/moco.py#L768-L773

`-v 0` is set for `sct_apply_transfo`, but because it gets set globally, `-v 0` leaks outside of this call to the rest of moco, undoing whatever was initially set for `param.verbose` in moco.

**Comment by joshuacwnewton** [comment]
If we can figure out how the script is called (maybe by looking `sys.argv`), then we could do something like:

* Called via CLI: Set local and global log level
* Called via code: Set local log level only

Relevant code:

https://github.com/neuropoly/spinalcordtoolbox/blob/916ab591ca2e35cab9f5f27ec2439ce8fdb0b9d2/spinalcordtoolbox/utils/sys.py#L60-L61

**Comment by kousu** [comment]
This is why `logging` lets you make sub-loggers that you can control the levels of individually. We use these all over the place:

https://github.com/neuropoly/spinalcordtoolbox/search?q=getLogger

Maybe `sct_apply_transinfo` is just some legacy code that needs patching?

**Comment by joshuacwnewton** [comment]
> Maybe `sct_apply_transinfo` is just some legacy code that needs patching?

It's not just `sct_apply_transfo`, though; this is the behavior across all of our SCT scripts. They're currently all setting the `root` logger via [`set_global_loglevel`](https://github.com/neuropoly/spinalcordtoolbox/blob/916ab591ca2e35cab9f5f27ec2439ce8fdb0b9d2/spinalcordtoolbox/utils/sys.py#L41-L61), with the justification being:

https://github.com/neuropoly/spinalcordtoolbox/blob/916ab591ca2e35cab9f5f27ec2439ce8fdb0b9d2/spinalcordtoolbox/utils/sys.py#L59
