### ISSUE TITLE
Turn "manual correction" scripts from sister projects into native SCT functionality

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3353]
SCT's sister projects have created manual correction CLI scripts:

* `ukbiobank`: [`/cli/manual_correction.py`](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/blob/master/pipeline_ukbiobank/cli/manual_correction.py)
* `spine-generic`: [`/spinegeneric/cli/manual_correction.py`](https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/manual_correction.py)
* https://github.com/spinalcordtoolbox/sct_tutorial_data/blob/master/multi_subject/manual_correction.py
* https://github.com/ivadomed/canproco/pull/16

These files are basically "SCT extensions": functionality wise, they're coupled deeply with existing SCT scripts. Because of how closely linked those scripts are to SCT, this led to a situation where development in SCT was tied to this external code from the other projects, which was a little complicated to coordinate. (See https://github.com/neuropoly/spinalcordtoolbox/pull/3253#issuecomment-824339914.)

An alternative could be if everything was under "SCT's domain" (e.g. `sct_manual_correction`), so that we could handle everything over here, and simply provide an interface that the sister projects could use. This might make development a littler easier (not having to make changes in multiple repos at once, while also allowing sister projects to reuse code more easily).

**Comment by sandrinebedard** [comment]
Maybe one thing less useful about including this script in SCT, the manual correction of segmentations is performed using ITK-SNAP (for UKbiobank, I think it was a change I made comparing to spine-generic) and is not SCT dependent. So this was useful for external people performing the manual corrections, it had simpler installation procedure this way and more windows-compatible 🙂 (see [this discussion](https://github.com/sct-pipeline/ukbiobank-spinalcord-csa/issues/33) for context)

(I still think it would be great to intergrate this in SCT 😊)

One other thought for manual disc labeling, the labels we want to create may differ between projects, it could be a parameter for the function!

**Comment by alexfoias** [comment]
@joshuacwnewton can I pass you this issue ? thanks.

**Comment by jcohenadad** [comment]
Let's list all the features we need for this manual correction pipeline

- Not necessarily dependent on SCT. Unless we do disc labeling, SCT-specific QC reports (that output YAML files).
- sct_qc could be run on the corrected files to assess correctness of corrections
- Package a sub-dataset. Ex: If correction is done by another rater who _only_ needs access to the data to correct, it would be convenient to _only_ share the data to correct, and package them into a single ZIP file.
- Date/time and name of rater to be added to an automatically created JSON (sidecar to the label)
  - If label already exists, append name
- If manual labels has already been corrected, the script asks user to re-modify it
- Requires BIDS-compliance?
  - Manual labels are stored under `derivatives/xxx` folder
  - Suffixes should be parametrizable
- What to correct?
  - Segmentation (SC, GM)
  - Disc label: Label values should be parametrizable (eg: "2, 3, 4", or "-1" for all visible discs, default), add link to SCT website tutorial with def of labels in the usage help.
  - Lesions (MS, tumours, etc.)
  - Compression site

**Comment by mguaypaq** [comment]
New repository created: [manual-correction](https://github.com/spinalcordtoolbox/manual-correction).
To do:
* Collect the different versions of the script in various repositories, and put each one, as-is, in a separate branch of this repository
* Start developing a generalization of them all on the main branch and/or in PRs.

**Comment by joshuacwnewton** [comment]
Given the interim stance that a centralized manual correction script should exist outside of SCT for now (with the potential for it to be added into SCT later on), I'm going to unassign myself from this issue.

But, in the future, should we decide to integrate this functionality into SCT, I'll be happy to help. :)

**Comment by valosekj** [comment]
> New repository created: [manual-correction](https://github.com/spinalcordtoolbox/manual-correction). To do:
> 
> * Collect the different versions of the script in various repositories, and put each one, as-is, in a separate branch of this repository

Collected in https://github.com/spinalcordtoolbox/manual-correction/issues/1
(I used an issue with crossrefs instead of separate branches to reduce code duplications)


> * Start developing a generalization of them all on the main branch and/or in PRs.

I'm going to start to work on that.

**Comment by valosekj** [comment]
Closing since we have introduced [spinalcordtoolbox/manual-correction](https://github.com/spinalcordtoolbox/manual-correction) repository including [manual_correction.py](https://github.com/spinalcordtoolbox/manual-correction/blob/main/manual_correction.py).

**Comment by joshuacwnewton** [comment]
Switching the "closed" type from "completed" to "not planned".
