### ISSUE TITLE
`sct_qc` displays the wrong arguments/command

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3356]
When using `sct_qc`, it will take the script name from the `-p` argument, then incorrectly combine it with the other arguments from `sct_qc`. Example:

```bash
# Input command 
sct_qc -i dmri_crop.nii.gz -d dmri_crop_moco.nii.gz -s dmri_crop_moco_dwi_mean_seg.nii.gz -p sct_dmri_moco -qc "$SCT_BP_QC_FOLDER"

# What it actually displays (these are not valid arguments for 'sct_dmri_moco`)
sct_dmri_moco -i dmri_crop.nii.gz -d dmri_crop_moco.nii.gz -s dmri_crop_moco_dwi_mean_seg.nii.gz
```

![Screenshot from 2021-04-21 17-27-17](https://user-images.githubusercontent.com/16181459/115966576-474eea00-a4fc-11eb-91e6-4aacc9c90339.png)

I imagine that this is not specific to `sct_dmri_moco`, but I have not checked yet.

**Comment by jcohenadad** [comment]
> I imagine that this is not specific to sct_dmri_moco, but I have not checked yet.

indeed-- i've always wanted to open an issue on this-- i'm glad you did

**Comment by joshuacwnewton** [comment]
I don't think it's feasible (nor wise) to try to recreate whatever the corresponding `sct_dmri_moco` command would have been (since for most scripts, there are a lot of configuration parameters that can't be inferred from the end results only).

Instead, I think the best thing to do is be transparent about the args that were passed to `sct_qc`.

----

Now, to get the displayed command to start with `sct_qc`, we currently would have to change the `process` variable, since this is what's used to determine the first bit of the command that gets displayed:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1734574255b1a98e640d82a15bcf51ff016a1c8e/spinalcordtoolbox/reports/qc.py#L708

(`process` gets passed to the `command` argument of `Params()`.)

Unfortunately, the `generate_qc()` function _also_ uses the `process` argument to determine which type of QC report to generate. So, unfortunately, this _must_ stay `'sct_dmri_moco'`.

----

Despite this, I think there's a sneaky little trick we can do: Keep `process` as the original script, but change the displayed args to include brackets and `sct_qc`. This would be done via the `args_disp` variable in `sct_qc`, which gets manually crafted anyway:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1734574255b1a98e640d82a15bcf51ff016a1c8e/spinalcordtoolbox/scripts/sct_qc.py#L84-L89

Result:

![image](https://user-images.githubusercontent.com/16181459/215299433-3f7f0539-0949-4e7b-9d0d-19b7284cc4bd.png)
