### ISSUE TITLE
Improve listing of references

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3357]
The ["application" references](https://spinalcordtoolbox.com/en/latest/overview/references.html#applications) is a wall of text with the same formatting-- it is hard to read.

A suggestion would be to add _some_ formatting to it, eg:

- Kong _et al_. [Intrinsically organized resting state networks in the human spinal cord](http://www.pnas.org/content/111/50/18067.abstract). **PNAS** 2014
- Duval _et al_. [In vivo mapping of human spinal cord microstructure at 300mT/m](https://www.ncbi.nlm.nih.gov/pubmed/26095093). **Neuroimage** 2015

Alternative:

- Kong et al. _Intrinsically organized resting state networks in the human spinal cord_. **PNAS** 2014. [LINK](http://www.pnas.org/content/111/50/18067.abstract)

**Comment by ahill187** [comment]
Oh yah, this is a good idea, it makes it a lot more readable. I think I like the first one best!

**Comment by copperwiring** [comment]
@jcohenadad  I know this is an old issue but[ "application" references](https://spinalcordtoolbox.com/en/latest/overview/references.html#applications) link doesn't work anymore. Can you please give the updated link if this issue still needs work?

![image](https://user-images.githubusercontent.com/23316280/124038611-43d15680-d9b6-11eb-8554-56fe38cfd67c.png)

**Comment by jcohenadad** [comment]
> @jcohenadad I know this is an old issue but[ "application" references](https://spinalcordtoolbox.com/en/latest/overview/references.html#applications) link doesn't work anymore. Can you please give the updated link if this issue still needs work?
> 
> ![image](https://user-images.githubusercontent.com/23316280/124038611-43d15680-d9b6-11eb-8554-56fe38cfd67c.png)

good catch! here it is: https://spinalcordtoolbox.com/en/latest/overview/studies.html

**Comment by copperwiring** [comment]
Thank you @jcohenadad . If no one is working on this, I can assign this to myself. Seems a low hanging fruit

**Comment by copperwiring** [comment]
Oh, wait. I can't assign myself this issue. Do I need any other permissions for it? @joshuacwnewton

**Comment by joshuacwnewton** [comment]
Sorry about that! We're still in a bit of limbo as @kousu and I work through the checklist in https://github.com/neuropoly/onboarding/issues/2. 

I've sent you an invite to @spinalcordtoolbox. :slightly_smiling_face:

**Comment by copperwiring** [comment]
Oh, no problem. Just wanted to keep you in loop :)
