### ISSUE TITLE
Add support for Python 3.9 by 2024-10-14

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3367]
> **Note**: This issue used to cover the tasks of supporting both Python 3.8 and Python 3.9. However, Python 3.8 support was added in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3916, which was accomplished by removing our dependency on `tensorflow`. So, I've edited this issue to hide any mentions of `tensorflow`/Python 3.8, so that we can focus purely on Python 3.9.

Current blockers for Python 3.9:

- [ ] PyQt5 (`v5.14.2`): Unable to install wheel on Windows, and the srcbuild process requires `qmake`. ([#3367 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3367#issuecomment-1531670177))
    - Potential fix 1: Renaming the Python 3.8 `.whl` file to trick `pip`. ([#3367 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3367#issuecomment-1531718166))
    - Potential fix 2: Updating PyQt5 to a version with Python 3.9 wheels. ([#3367 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3367#issuecomment-1531769467))
    - Potential fix 3: _Downgrading_ PyQt5 to a version with Python 3.9 wheels (???). ([#3367 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3367#issuecomment-1533181462))

<details>
<summary> Past blockers for Python 3.9 (Completed) </summary>

- [x] `tensorflow==1.15.0`
    * This would be pinned due to #3361, however [wheels are not provided for Py3.9](https://pypi.org/simple/tensorflow/). 
    * The first Py3.9-supporting version is `tensorflow==2.5.0`. We've used 2.0.1 before (see #2592) but it's unclear if 2.5.0 is viable. More testing is needed.
    * Alternatively, #3046 will drop the dependency on tensorflow altogether.
- [x] `onnxruntime==1.4.0`
    * EDIT: Good news! This will be fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3433.
    * ~~We pin this due to #3037, however [wheels are not provided](https://pypi.org/simple/onnxruntime/) for Py3.9.~~
    * ~~The recommended fix is to `brew install libomp`, which was tested successfully in #2932. However, this requires us to add a external dependency to SCT, which means we'll have to ask every user to `brew install libomp`.~~

</details>

<details>
<summary> Past blockers for Python 3.8 (Completed) </summary>

- [x] `tensorflow==1.15.0`
    * This would be pinned due to #3361, however [wheels are not provided for Py3.8](https://pypi.org/simple/tensorflow/). 
    * The first Py3.8-supporting version is `tensorflow==2.2.0`. We've used 2.0.1 before (see #2592) but it's unclear if 2.2.0 is viable. More testing is needed.
    * Alternatively, #3046 will drop the dependency on tensorflow altogether.

</details>

**Comment by abelfodil** [comment]
@joshuacwnewton can we migrate to TF2 using this script https://www.tensorflow.org/guide/migrate for the time being?

Basically since there is a [compatibility layer](https://www.tensorflow.org/api_docs/python/tf/compat/v1) in TF2 that keeps v1 behavior, it seems to be a low effort migration but I didn't fiddle with the tool yet.

**Comment by joshuacwnewton** [comment]
We've gotten a report in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3912#issuecomment-1278124169 that Python 3.7 is incompatible with certain Windows environments.

> Hrm, some dependencies want Python at least 3.8, and others (ivadomed specifically) want Python strictly less than 3.9, so we're trying again with Python 3.8.10 (the latest 3.8.* which has a windows installer).

I'm not quire sure of what "certain Windows environments" means at this point, but given that Python 3.8 works, we may want to prioritize switching SCT's primary Python version to 3.8, which would also preempt the upcoming deadline.

**Comment by joshuacwnewton** [comment]
Reopening this issue, since was intended to cover Python 3.9 as well, 

(Thankfully, Python 3.8's EOL is 14 Oct 2024, so we have some time.)

**Comment by joshuacwnewton** [comment]
I've begun looking into Python 3.9 support once more in [`jn/3367-support-python-3.9`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/jn/3367-support-python-3.9). 

Installation seems to work fine on all platforms except Windows. The problem here is `PyQt5==5.14.2`:

- Currently, we're pinning to `5.14.2` because of an issue with Ubuntu dependencies: [#3925](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3925)
- However, version `5.14.2` only provides wheels for [Python 3.5-3.8](https://pypi.org/project/PyQt5/5.14.2/#files).
- Oddly, though, on Unix platforms, [the wheel is used anyway](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/4862056487/jobs/8667907539#step:4:351), even though the environment [is Python 3.9](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/4862056487/jobs/8667907539#step:5:35).
- For Windows, however, building from source [seems to be necessary](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/4862056487/jobs/8667907727#step:3:195).
    - `PyQT5`'s build process is somewhat non-standard. It depends on a separate package `PyQt-builder`.
    - `PyQt-builder` depends on a build tool called [`qmake`](https://en.wikipedia.org/wiki/Qmake) being present on the system:
        ```python
            # Check we have a qmake.
            if self.qmake is None:
                self.qmake = self._find_exe('qmake')
                if self.qmake is None:
                    raise PyProjectOptionException('qmake',
                            "specify a working qmake or add it to PATH")
        ```    
   - But, from what I can tell, you need to [install the entire Qt framework](https://stackoverflow.com/questions/68771530/qmake-on-windows#comment121578369_68771530) in order to use `qmake` on Windows.

So, building PyQt5 on Windows seems to be out of the question here, and we'll need to find another way forward:

1. Rename the `5.14.2` wheel to sidestep version restrictions on Windows (seeing as the `5.14.2` wheels were able to install just fine on Unix platforms, despite not officially supporting Python 3.9). 
    - NB: I've seen this workaround recommended for PyQt5 elsewhere, too: [altendky/pyqt-tools#98 (comment)](https://github.com/altendky/pyqt-tools/issues/98#issuecomment-968296553).
2. Unpin `5.14.2` and install a more recent version of PyQt5 that has Python 3.9 wheels available.
   - Necessarily, this would require us to find an alternate solution for [#3925](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3925).

I'm leaning towards unpinning PyQt5, though I'm not sure how I'd go about fixing #3925 yet.... :thinking:

**Comment by joshuacwnewton** [comment]
> 1. Rename the `5.14.2` wheel to sidestep version restrictions on Windows

I was skeptical about this, but I did a quick, hacked-together test in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/0d7ef81500f22e138d50cf03a14c7692d6ed46b9, and it seems to just... work?

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50.4M  100 50.4M    0     0  28.1M      0  0:00:01  0:00:01 --:--:-- 28.1M
Processing c:\users\joshu\appdata\local\temp\tmp-75974867\pyqt5-5.14.2-py3-none-win_amd64.whl
Collecting PyQt5-sip<13,>=12.7 (from PyQt5==5.14.2)
  Using cached PyQt5_sip-12.12.1-cp39-cp39-win_amd64.whl (78 kB)
Installing collected packages: PyQt5-sip, PyQt5
Successfully installed PyQt5-5.14.2 PyQt5-sip-12.12.1
```

I also made a point to see if a Qt-based SCT script like `sct_label_utils -create-viewer` would fail. But, it absolutely works:

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/16181459/235718515-124b3354-eb0e-4f9b-82f2-8921e5104ae5.png)

</details>

This is a good start, but I still want to explore unpinning `PyQt5`, because it would be a much better long-term solution (for e.g. Python 3.10 and beyond).

**Comment by joshuacwnewton** [comment]
> 2. Unpin `5.14.2` and install a more recent version of PyQt5 that has Python 3.9 wheels available.
>     * Necessarily, this would require us to find an alternate solution for [#3925](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3925).

I've tried this out in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/d36e89d2650462383c6adfaeb1d75657871a75a0. 

((Going for lunch now! I'll edit this comment once I explore the results a bit more.))

**Comment by joshuacwnewton** [comment]
A third potential solution: In Slack, Raj noticed that, oddly, `PyQt5==5.13.x` wheels install correctly on Windows, even though `PyQt5==5.14.x` forces a build of the source distribution. (Weird!) 

Given that our current range of acceptable versions is `pyqt5>=5.12.0,<5.15.0`, I tried instead limiting this range to `<5.14.0` in commit 6c461fc9b3ae92bcd2b077fa651431e7a6e4873d. Oddly, however, this resulted in the [`PyQt5-5.12.3-5.12.10-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/4873156280/jobs/8692327016#step:3:207) wheel being installed instead of the expected 5.13.x wheel. And, all of the tests pass without issue.

> (Wait. So, the PyQT 5.14.x doesn't include `cp39` in its wheel name, but PyQT _5.12.x_ does?)

Nonetheless, I think this might be the most straightforward way to transition to Python 3.9 in the short term, since it doesn't require hacky workarounds or installing new dependencies like the other two solutions do.
