### ISSUE TITLE
Argparse help string for `sct_dmri_moco -bvals` is misleading

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3374]
https://github.com/neuropoly/spinalcordtoolbox/blob/67170203934274498b90bc65f6a084f724b6ec19/spinalcordtoolbox/scripts/sct_dmri_moco.py#L78

`bvals` should not be an image file (`.nii.gz`). See [`read_bvals_bvecs`](https://github.com/dipy/dipy/blob/c846bf5a23b7e95343a9cf231df2653473602456/dipy/io/gradients.py#L44-L45) for the expected extensions.

**Comment by jcohenadad** [comment]
ahhhhh! good catch 😊
