### ISSUE TITLE
Scrollbar includes hole page in html QC report

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3384]
### Description
With the new interactive QC report in SCT v5.3.0, the scrollbar now includes the hole html page, whenever I try to get to the next image using the down arrow, the page goes down too, it's a problem for large QC reports :

https://user-images.githubusercontent.com/71230552/117716922-26e38880-b1a8-11eb-9bd6-76b1f993ce21.mp4

Here is the QC report with an older version of SCT (v5.0.1), the scrollbar only included the list of images on the left:
![image](https://user-images.githubusercontent.com/71230552/117716260-6067c400-b1a7-11eb-9f72-3b1921e5658a.png)

**Comment by joshuacwnewton** [comment]
Interesting... I can't seem to reproduce the full-page scroll bar.

<details>
<summary> Chrome, Ubuntu 20.04 </summary>

![Screenshot from 2021-05-10 17-31-12](https://user-images.githubusercontent.com/16181459/117727102-93b14f80-b1b5-11eb-99b0-d37167bb83d2.png)

</details>

<details>
<summary> Firefox, Ubuntu 20.04 </summary>

![Screenshot from 2021-05-10 17-31-24](https://user-images.githubusercontent.com/16181459/117727134-a166d500-b1b5-11eb-8d1b-433e04f1ae32.png)

</details>

On my end, when I inspect the table on my page, I see the scrollbar is attached to `<div class="fixed-table-body">`, which is governed by [`bootstrap-table.min.css`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/reports/assets/_assets/css/bootstrap-table.min.css). In the non-minified version, the relevant bit looks to be [these lines](https://github.com/wenzhixin/bootstrap-table/blob/c1aa2efb383f63c9450c8cb7ad00ea34bee5d719/src/bootstrap-table.css#L58-L62). 

<details>
<summary> Inspect element window </summary>

![Screenshot from 2021-05-10 17-52-45](https://user-images.githubusercontent.com/16181459/117729285-9eb9af00-b1b8-11eb-9700-e3e6bb79851d.png)

</details>

So, everything looks to be rendering as intended for me. Could you share a .zip of your QC folder, @sandrinebedard? (Or, if it's too large, maybe just the `index.html` file itself?)

**Comment by joshuacwnewton** [comment]
(As an aside, I can still reproduce the issue that @jcohenadad describes, though.)

**Comment by sandrinebedard** [comment]
> Just to be sure, could you share a .zip of your QC folder, @sandrinebedard?

@joshuacwnewton the file is too big (it's a QC report with 1000 subjects 😂), so here is a dropbox link: https://www.dropbox.com/s/e0suanmtx7g8y7q/qc.zip?dl=0

On my end, I can also  reproduce on firefox...

**Comment by joshuacwnewton** [comment]
Thanks for sharing the QC folder! I can reproduce as well using that folder. So, that would seem to confirm that this only occurs for a very large amount of subjects.

I remember from the last PR that we had recently noticed some visual issues that were dependent on loading times (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3253#discussion_r616713718). And, when there are a large amount of subjects, I notice that the page sort of hangs/pauses for a second or two while loading the table... so, maybe certain elements load out of order, and the browser somehow catches the vertical overflow before the... CSS table does? (This is just amateruish speculation, though, as this sort of issue exceeds my limited knowledge of webdev. :sweat_smile:)
