### ISSUE TITLE
`sct_dmri_display_bvecs` fails in v5.3.0

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#3386]
### Description

`sct_dmri_display_bvecs` fails in v5.3.0

### Steps to Reproduce

0. I installed the newest stable [release 5.3.0](https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases/tag/5.3.0) from zipped source code. 

1. Then I run `sct_dmri_display_bvecs`:
 
```
sct_dmri_display_bvecs -bvec sub-01_run-01_dwi.bvec
```

**Expected behavior:** Display scatter plot of gradient directions from bvecs file.

**Actual behavior:** The script failed on:

```
--
Spinal Cord Toolbox (5.3.0)

sct_dmri_display_bvecs -bvec sub-01_run-01_dwi.bvec
--

Traceback (most recent call last):
  File "/usr/local/lib/sct_v5.3.0/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py", line 133, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/sct_v5.3.0/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py", line 65, in main
    verbose = arguments.v
AttributeError: 'Namespace' object has no attribute 'v'   
```

**Comment by joshuacwnewton** [comment]
Thanks for reporting this! I will fix this ASAP. 

(Aside: We're not currently testing `sct_dmri_display_bvecs` at all. So, I'll try to add a test as well.)

**Comment by jcohenadad** [comment]
thank you for reporting this bug @valosekj 🙏
