### ISSUE TITLE
Using `matplotlib.pyplot.show()` causes MacOS 10.15 runners to hang

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3388]
If a pytest test calls a CLI script that uses `pyplot.show()`, the macOS runner will hang indefinitely. I experienced this in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3387#issuecomment-839915047 and one other test (see linked comment). To confirm the cause, I temporarily commented out `pyplot.show()` in 3b5aefe and the runner no longer stalled out.

When doing a project-wide search for `plt.show()`, I notice there are 9 instances where the command is commented out, however there are still 5 other instances, hence this issue.

There's an existing [internal Wiki entry](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-Moving-away-from-pyplot) about `pyplot` which recommends to refactor to matplotlib's OO interface (I didn't write this -- renaming a page changes the author on GitHub Wikis). My question is, is a complete refactor necessary? If it's just `plt.show()` that's the problem, could we get away with leaving the existing `pyplot` code and simply removing `plt.show()` (assuming we're also saving the plot as an image)?

**Comment by valosekj** [comment]
I have checked also another scripts which use plt.show() and do not have that commented out. 

For example `sct_compute_ernst_angle`:

```
sct_compute_ernst_angle -tr 2000 -v 2
```

Figure is displayed in case of this script, but the script changes backend manually:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/67170203934274498b90bc65f6a084f724b6ec19/spinalcordtoolbox/scripts/sct_compute_ernst_angle.py#L48-L49

**Comment by joshuacwnewton** [comment]
My current idea for handling this is to check the backend, then only run `plt.show()` if the backend supports GUIs.

```python
INTERACTIVE_BACKENDS = ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt5Agg', 'Qt5Cairo', 
                        'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo']
NONINTERACTIVE_BACKENDS = ['agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

def matplotlib_backend_supports_gui():
    backend = get_backend()
    if backend in INTERACTIVE_BACKENDS:
        return True
    elif backend in NONINTERACTIVE_BACKENDS:
        return False
    else:  # An attempt to handle user-supplied backends which are unknown to matplotlib
        return None

# Usage in code
if matplotlib_backend_supports_gui():
    plt.show()
```

I have also submitted an upstream feature request, which would make it easier to check the backend: https://github.com/matplotlib/matplotlib/issues/20281

**Comment by tacaswell** [comment]
Without digging into this, my knee-jerk guess is that when you are on OSX and the osx backend gets selected, then `plt.show()` (by design!) blocks forever showing the GUI window to your runner!  My guess is if you run the tests locally on a mac, a window will pop up and the tests will hang until you close the window.  

You can see the lengths we go to in mpl to test the interactive backends in a safe way: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_backends_interactive.py

**Comment by joshuacwnewton** [comment]
Thanks for taking the time to comment! :slightly_smiling_face: 

> when you are on OSX and the osx backend gets selected, then plt.show() (by design!) blocks forever showing the GUI window to your runner!

Currently, we try to detect headless systems by checking whether `$DISPLAY` is set, then we manually set the backend to a non-interactive backend. 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/spinalcordtoolbox/compat/launcher.py#L20-L22

(Whether or not we should even be doing this is another question, hehe.)


But, this means for our macOS runners, I think that it wouldn't be on the `osx` backend. So, my understanding was that we should instead run into the "non-GUI" exception (rather than having it hang), but that's not the case.

**Comment by tacaswell** [comment]
Unless you explicitly want to test the GUI aspect of something, I suggest unconditionally setting the backend to Agg (that is what we do in the Matplotlib tests).  It avoids a whole class of pain points (related to making sure you have the event loop running enough, etc) and will make your tests run faster!

I would also check your that on the osx test runner `$DISPLAY` is really not set.

**Comment by jcohenadad** [comment]
> Currently, we try to detect headless systems by checking whether `$DISPLAY` is set, then we manually set the backend to a non-interactive backend.

@joshuacwnewton is there a redundancy with this modification of the shell profile?
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/install_sct#L268

If we could minimize surgery on user's shell profile it would be great

**Comment by joshuacwnewton** [comment]
> @joshuacwnewton is there a redundancy with this modification of the shell profile?

:+1:

This was added before my time, but I've been suspicious of it ever since looking into this issue.

**Comment by tacaswell** [comment]
I'm now very unsure as to how y'all are using Matplotlib.  I would be happy to jump on a call to understand that and then (hopefully) point you in a direction that will be less painful.

**Comment by joshuacwnewton** [comment]
> I'm now very unsure as to how y'all are using Matplotlib.

It's a bit of a long story... `spinalcordtoolbox` is essentially a Python package, but it's not currently `pip` installable, so we've used a shell script to perform pre- and post-installation steps that can't be done via `setuptools`. 

Because of the existence of the shell script, there's been a temptation to solve some problems in non-Python ways _(e.g. modifying the user's RC file during installation to set `MPLBACKEND`, even though that could have been handled using e.g. `matplotlib.use()`)_. 

So, there's been an ongoing process to reel things back in to keep everything purely Python. (#1526)

**Comment by joshuacwnewton** [comment]
> I would also check your that on the osx test runner `$DISPLAY` is really not set.

I wrote a test to verify this assumption, and also assumptions about whether `Agg` is properly set. The test passes on all of our runners [except MacOS 10.15](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/2646119475?check_suite_focus=true#step:3:2369). 

The curious thing is that `DISPLAY` does indeed get set, and `MPLBACKEND` does is set to `Agg`. However, `matplotlib.get_backend()` still evaluates to `macosx`. So, that certainly looks like the cause of the hanging CI runs. 

The question now is: why is the `MPLBACKEND=Agg` not reflected in the actual backend for our MacOS runner?

**Comment by joshuacwnewton** [comment]
> The question now: Why is `MPLBACKEND=Agg` not reflected in the actual backend for our MacOS runner?

My theory for this is that `matplotlib` gets imported somewhere in the test suite _outside_ of the CLI launcher. Because we're only setting `MPLBACKEND` in the CLI launcher, `MPLBACKEND` isn't set prior to `matplotlib`'s first import. 

Just to test, if we instead set `MPLBACKEND` in the package-level `__init__.py`, then the [test passes](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/2646317083?check_suite_focus=true#step:3:2288). Doing it this way is has the same effect as setting it in the launcher (because the launcher imports SCT), but this method also affects non-CLI usage of the `spinalcordtoolbox` package, which means `MPLBACKEND` is set early enough.

**Comment by kousu** [comment]
> Unless you explicitly want to test the GUI aspect of something, I suggest unconditionally setting the backend to Agg (that is what we do in the Matplotlib tests). It avoids a whole class of pain points (related to making sure you have the event loop running enough, etc) and will make your tests run faster!

I agree with this. We should be setting `MPLBACKEND: Agg` *in our CI scripts*.

But also, our scripts should not be calling `plt.show()` at all. It is interactive by design, so it should only be done in interactive programs, IMO. I always thought it was meant for data exploring in your own scripts. We can replace any uses of it with `plt.savefig()` to make our scripts non-interactive -- because they should be noninteractive.
