### ISSUE TITLE
`matplotlib` defaults to non-interactive backend, causing `UserWarning` for `plt.show()`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3392]
The easiest way to demonstrate is using `sct_dmri_display_bvecs`:

```
--
Spinal Cord Toolbox (git-master-a62fb672c602b9863a8c03521eb272bfd7bad9e1)

sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt
--

Saving figure: bvecs.png

/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py:137: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
```

This warning occurs and no figure is shown.

We explicitly set the backend type using the `MPLBACKEND` environment variable. (Option 2. in [this list](https://matplotlib.org/2.0.2/faq/usage_faq.html#what-is-a-backend).)

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a62fb672c602b9863a8c03521eb272bfd7bad9e1/install_sct#L266-L272

We started using the `Agg` backend in #2157 (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2238/commits/cd521dbdce9fb74332528a6a0d3b253012dfd492) to avoid crashes on headless systems (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2138). 

Moving forward, I can think of two options, depending on whether we need interactive `matplotlib` windows in SCT.

* If we want interactive windows, we should figure out how to set `MPLBACKEND=Agg` (a non-interactive backend) for headless systems only. 
* If we don't care about interactive windows, and instead only want to generate images to disk, then we should remove any instances of `plt.show()`.

**Comment by jcohenadad** [comment]
Thank you for opening this @joshuacwnewton 

In the case of `sct_dmri_display_bvecs` I we _can_ go without interactive figure, and having it work would be like the cherry on the cake. Maybe we can check if user is on headless system, and if that's the case interactive mode is turned off?

**Comment by joshuacwnewton** [comment]
> Maybe we can check if user is on headless system, and if that's the case interactive mode is turned off?

The interesting thing is, I think we already do check if the user is on a headless system... but in the launcher:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a62fb672c602b9863a8c03521eb272bfd7bad9e1/spinalcordtoolbox/compat/launcher.py#L20-L22

So we're doing the same thing twice: once in the launcher, and once in the installer. It's possible that this is redundant, and that just the check in the launcher will be sufficient (as you've said).

**Comment by valosekj** [comment]
> 
> We explicitly set the backend type using the `MPLBACKEND` environment variable. (Option 2. in [this list](https://matplotlib.org/2.0.2/faq/usage_faq.html#what-is-a-backend).)
> 
> https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a62fb672c602b9863a8c03521eb272bfd7bad9e1/install_sct#L266-L272
> 

Interesting, there is missing `elif` statement for `zsh`. Is that intention?

**Comment by joshuacwnewton** [comment]
> BTW.
> I thought that `export MPLBACKEND=TkAgg` run in my `zsh` CLI could solve the issue with `plt.show()`, so I tried:
> 
> ```
> git checkout master
> export MPLBACKEND=TkAgg
> sct_dmri_display_bvecs -bvec ~/sub-001/dwi/sub-001_dwi.bvec
> ```
> 
> But it didn't and I still get the same warning:
> 
> `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure. plt.show()`

Interesting. I tried this just now, and your steps work for me:

```console
> echo $MPLBACKEND
Agg
> sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt

--
Spinal Cord Toolbox (git-master-9a4b45715240d6c08b8d71587ffbe99a41326cc6*)

sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt
--

Saving figure: bvecs.png

/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py:137: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
> export MPLBACKEND=TkAgg
> echo $MPLBACKEND
TkAgg
> sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt

--
Spinal Cord Toolbox (git-master-9a4b45715240d6c08b8d71587ffbe99a41326cc6)

sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt
--

Saving figure: bvecs.png
```

**Comment by valosekj** [comment]
> Interesting. I tried this just now, and your steps work for me:

Hm, I have just replicated your steps and still get backend warning, although backend looks changed to `TkAgg` in my CLI:

```console
$ git checkout master
$ echo $MPLBACKEND
Agg
$ sct_dmri_display_bvecs -bvec ~/sub-01/dwi/sub-01_dwi.bvec

--
Spinal Cord Toolbox (git-master-a62fb672c602b9863a8c03521eb272bfd7bad9e1)

sct_dmri_display_bvecs -bvec ~/sub-01/dwi/sub-01_dwi.bvec
--

Saving figure: bvecs.png

/usr/local/sct/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py:137: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()


$ export MPLBACKEND=TkAgg 
$ echo $MPLBACKEND
TkAgg
$ sct_dmri_display_bvecs -bvec ~/sub-01/dwi/sub-01_dwi.bvec

--
Spinal Cord Toolbox (git-master-a62fb672c602b9863a8c03521eb272bfd7bad9e1)

sct_dmri_display_bvecs -bvec ~/sub-01/dwi/sub-01_dwi.bvec
--

Saving figure: bvecs.png

/usr/local/sct/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py:137: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()                 
```

I tried this in my Terminal using zsh with oh-my-zsh extension on MacOS Catalina (10.15.7).

**Comment by valosekj** [comment]
Another interesting thing -- I tried to add following two lines into master `sct_dmri_display_bvecs.py`:

```
import matplotlib
print(f'Backend in python: {matplotlib.get_backend()}')
```
And I have found out that even if I run in my Terminal `export MPLBACKEND=TkAgg`, the backend in python is still `agg`:

```console
$ export MPLBACKEND=TkAgg                                                                                                                                              /0,2s
$ echo $MPLBACKEND       
TkAgg                                                                                                                                                                                                  /0,1s
$ sct_dmri_display_bvecs -bvec ~/sub-01/dwi/sub-01_dwi.bvec

--
Spinal Cord Toolbox (git-master-a62fb672c602b9863a8c03521eb272bfd7bad9e1*)

sct_dmri_display_bvecs -bvec ~/sub-01/dwi/sub-01_dwi.bvec
--

Saving figure: bvecs.png

Backend in python: agg
/usr/local/sct/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py:139: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()                                                                                                                                                                                           
```

**Comment by joshuacwnewton** [comment]
That's very interesting! Trying what you suggest, I still see it working for me.

<details>
<summary> Output of <code>print(f'Backend in python: {matplotlib.get_backend()}')</code></summary>

```console
> echo $MPLBACKEND
Agg
> sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt

--
Spinal Cord Toolbox (git-master-77d4b7ddc716e69b1dc223536a7c026ff12abad8*)

sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt
--

Saving figure: bvecs.png

Backend in python: agg
/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py:139: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
> export MPLBACKEND=TkAgg
> echo $MPLBACKEND
TkAgg
> sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt

--
Spinal Cord Toolbox (git-master-77d4b7ddc716e69b1dc223536a7c026ff12abad8*)

sct_dmri_display_bvecs -bvec sct_example_data/dmri/bvecs.txt
--

Saving figure: bvecs.png

Backend in python: TkAgg
```

</details>

Could you run `sct_check_dependencies`? For me, you can see that `DISPLAY` is set.


<details>
<summary> Output of <code>sct_check_dependencies</code></summary>

```console
❯ sct_check_dependencies

--
Spinal Cord Toolbox (git-master-77d4b7ddc716e69b1dc223536a7c026ff12abad8*)

sct_check_dependencies 
--

SCT info:
- version: git-master-77d4b7ddc716e69b1dc223536a7c026ff12abad8*
- path: /home/joshua/repos/spinalcordtoolbox
OS: linux (Linux-5.8.0-53-generic-x86_64-with-debian-bullseye-sid)
CPU cores: Available: 8, Used by ITK functions: 8
RAM: Total: 15863MB, Used: 4336MB, Available: 10626MB
Check Python executable.............................[OK]
  Using bundled python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04) 
[GCC 7.3.0] at /home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.4.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if ivadomed is installed......................[OK] (2.7.4)
Check if matplotlib is installed....................[OK] (3.3.4)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.19.5)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.1.5)
Check if psutil is installed........................[OK] (5.8.0)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.2.3)
Check if pytest-cov is installed....................[OK] (__version__ = '2.11.1')
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.25.1)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.24.1)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0+cpu) is installed.............[WARNING] (1.5.0 != 1.5.0+cpu mandated version))
Check if torchvision (0.6.0+cpu) is installed.......[WARNING] (0.6.0 != 0.6.0+cpu mandated version))
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.60.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.4)
Check if pytest_console_scripts is installed........[OK]
Check if wquantiles is installed....................[OK] (0.4)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............[OK]
```

</details>


But, if `DISPLAY` is possibly not set, then perhaps the following setting in the launcher is triggering on your machine:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/77d4b7ddc716e69b1dc223536a7c026ff12abad8/spinalcordtoolbox/compat/launcher.py#L20-L22

**Comment by valosekj** [comment]
> Could you run sct_check_dependencies to double-check? On my machine, DISPLAY is set:

Sure, below is the output of `sct_check_dependencies`. `DISPLAY` variable is not set on my machine:

<details>
<summary>Output of `sct_check_dependencies`</summary>

```console
$ sct_check_dependencies

--
Spinal Cord Toolbox (git-master-a62fb672c602b9863a8c03521eb272bfd7bad9e1*)

sct_check_dependencies 
--

SCT info:
- version: git-master-a62fb672c602b9863a8c03521eb272bfd7bad9e1*
- path: /usr/local/sct
OS: osx (Darwin-19.6.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by ITK functions: 4
RAM: Total: 8192MB, Used: 5039MB, Available: 2630MB
Check Python executable.............................[OK]
  Using bundled python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ] at /usr/local/sct/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.2.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if ivadomed is installed......................[OK] (2.0.2)
Check if matplotlib is installed....................[OK] (3.3.0)
Check if nibabel is installed.......................[OK] (3.1.1)
Check if numpy is installed.........................[OK] (1.19.1)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.0.5)
Check if psutil is installed........................[OK] (5.7.2)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.1.0)
Check if pytest-cov is installed....................[OK] (__version__ = '2.10.1')
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.24.0)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.1)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.23.1)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0) is installed.................[OK] (1.5.0)
Check if torchvision (0.6.0) is installed...........[OK] (0.6.0)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.48.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.25.10)
Check if pytest_console_scripts is installed........[FAIL]
No module named 'pytest_console_scripts'
Check if wquantiles is installed....................[FAIL]
No module named 'wquantiles'
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[FAIL]
```

</details>

**Comment by joshuacwnewton** [comment]
> And then I run again following code and figure was finally displayed for me!

Hoorah! At least we know that `MPLBACKEND` does what we hope for, then. :blush: 

> `DISPLAY` variable is not set on my machine:

That's odd. Assuming you are using X Window System (i.e. a UNIX-based system with a display), then `DISPLAY` should be [set automatically when you log in](https://docstore.mik.ua/orelly/unix3/upt/ch35_08.htm).

Is there anything unique about your environment? (e.g. Remote/SSH session) If so, [this SE post](https://unix.stackexchange.com/questions/138936/why-wont-x11-display-work-through-ssh-login) might be relevant to you.

**Comment by valosekj** [comment]
> Hrm, that's a bit odd. Assuming you are using X Window System (i.e. a UNIX-based system with a display), then DISPLAY should be set automatically when you log in.
> Is there anything unique about your environment (e.g. Remote/SSH session)? If so, this SE post might be relevant to you.

I have pretty standard MacBook Pro and I use local terminal (no ssh/remote sessions). Problem can be that [MacOS doesn't run X11 by default](https://stackoverflow.com/a/31622440/12605960) and X11 is available using [XQuartz](https://support.apple.com/en-gb/HT201341).

**Comment by joshuacwnewton** [comment]
> Problem can be that [MacOS doesn't run X11 by default](https://stackoverflow.com/a/31622440/12605960) and X11 is available using [XQuartz](https://support.apple.com/en-gb/HT201341).

Ah, I see. That makes detecting headless macOS machines much more difficult. 

We could show all interactive plots on macOS by default, but then SCT may appear to hang if no display is available.
