### ISSUE TITLE
Improve `sct_label_vertebrae` by skipping straightening (using orthogonal planes)

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3395]
### Context

Currently, in `sct_label_vertebrae` there is a necessary step which involves straightening the spinal cord (ie: bringing it from the natural curved space to a "straight" spinal cord). This step is required by:
- the current template-based disc detection and;
- the option `sct_label_vertebrae -discfile`, which uses a disc label and produces a labeled segmentation.

The problem is that the straightening is **very** long, and is also prone to errors and inaccuracies (notably related to a parameter defining the smoothness of the centerline).

### Suggestion

Implement a function that computes the plane orthogonal to the spinal cord centerline and that passes through a label. That way, straightening can be avoided.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/39456460/226650261-12e19e62-146b-4d94-b9f3-8ed7cc66c6b3.png">

Note that this approach will also become useful once the [new deep learning-based disc detection method](https://github.com/ivadomed/ivadomed/pull/787) is available in SCT.

**Comment by joshuacwnewton** [comment]
Migrated to https://github.com/neuropoly/idea-projects/issues/7.

**Comment by jcohenadad** [comment]
@NadiaBlostein Could you please point us to your Venus-SCT code that does compute the plane orthogonal to the spinal cord centerline? This will be useful for @valosekj who will work on this issue. 

An alternative approach, instead of computing the orthogonal plane to the centerline, would be to compute the shortest distance between each disc label and a point on the centerline. Maybe this could be implemented by iterating across all points on the centerline, computing the distance, and keeping the shortest distance as the candidate. @sandrinebedard @benjamindeleener do you have any other suggestions?

**Comment by NadiaBlostein** [comment]
[Here](https://github.com/sct-pipeline/venus-integration) it is!

**Comment by valosekj** [comment]
I discovered that the functionality performing labeling from discs (without applying the straightening) is available within the [labels.labelize_from_discs](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/47ab308361c6e9d98f4a6c1d58e98d03363f5814/spinalcordtoolbox/labels.py#L219-L241) function.

It can be run by:

```
sct_label_utils.py -i sub-001_seg.nii.gz -disc labels.nii.gz -o sub-001_seg_labeled.nii.gz
```

However, the current implementation does not deal with the level above the top disc and the level below the bottom disc. In other words, the levels above and below the first and the last discs are not labelled:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/39456460/226699806-63f0727f-f4d2-4c8f-9c54-99dc22141349.png">

I proposed a solution in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4072

**Comment by valosekj** [comment]
It is important to note that the solution proposed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4072 does not compute orthogonal projection or shortest distance. It just takes the closest slice to the disc coordinate. This is probably fine for axially acquired images with thick slices (like 3 mm slice thickness) as shown [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4072#issue-1634465041).

However, @NathanMolinier pointed out a relevant comment that for images with thin slices (like 1mm slice thickness), slight discrepancy might occur, leading to different labeling:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/39456460/226712688-d41d986a-d514-4898-b440-6f967bcb1926.png">

**Comment by NathanMolinier** [comment]
Just to add a quick comment about the difference between the two following methods:
- doing an orthogonal projection
- finding the closest point 

In a continuous world, doing an orthogonal projection of a point or finding the closest point on a line should converge to the same point however this is not our case, because images are made of discrete pixels.

Therefore:

Doing an orthogonal projection will lead to the real closest coordinate which will be a `float` coordinate, whereas finding the closest point on a discrete line will lead to an `integer` coordinate.

Our choice will depend on how precise we want our method to be. This point is also relevant if we want to compare the performances of several methods (like [here](https://github.com/spinalcordtoolbox/disc-labeling-hourglass/issues/2))

Note: Our precision also depends on how precisely are gathered ground truth labels.
