### ISSUE TITLE
Remove dependency on PyTorch by relying only on `onnxruntime` and ONNX models

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3396]
Currently, SCT depends on at least some version of PyTorch (CPU or GPU, either is OK) so that we can run inference on `.pt` models trained using `ivadomed`. But, some of ivadomed's models are already available in the ONNX representation, so theoretically we could run inference without having to rely on `torch` at all.

#### Motivation

 * `torch` is _heavy_: 600MB for the CPU version, and 1.3GB for the GPU version. Removing this dependency makes SCT much lighter.
 * Not depending on `torch` makes a `pip` install much more viable for https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526. We wouldn't have to expose any CPU/GPU installation workarounds to the user, making for a more seamless installation procedure.

#### Blockers

- [ ] Some, but not all models are in the ONNX format. See, for example, this issue: https://github.com/ivadomed/ivadomed/issues/749
- [ ] `spinalcordtoolbox` currently lists `ivadomed` as a requirement, which in turn depends on `torch`. So, even if SCT removes `torch` from its requirements, we'll still be tied to it via `ivadomed`. Notably, though, we only use `ivadomed` in a single place for a single purpose: inference in `sct_deepseg`.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9a4b45715240d6c08b8d71587ffbe99a41326cc6/spinalcordtoolbox/scripts/sct_deepseg.py#L18

**Comment by jcohenadad** [comment]
> theoretically we could run inference without having to rely on torch at all.

That would be amazing. But, what library would be used then, if not pytorch?

**Comment by joshuacwnewton** [comment]
> That would be amazing. But, what library would be used then, if not pytorch?

Just to clarify, PyTorch would still be used within `ivadomed` to train/evaluate the models. But, using the ONNX representations, we would simply use `onnxruntime` to perform inference.

This is already done within `ivadomed` -- we would basically just extract the ONNX inference function from ivadomed, and leave the rest of the project out of SCT.

**Comment by kousu** [comment]
pytorch or tensorflow, especially when used in GPU mode, are like *compilers*. Listing them in our dependencies is like packaging your entire build toolchain along with your software: you can do it, but 99% of the time it's a lot of dead weight.

I'm going to [quote myself](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526#issuecomment-844089393) here:

> We could make it so `pip install spinalcordtoolbox[dev]` installs torch, `pip install spinalcordtoolbox` installs just `onnx`, and make sure all our models are packaged in .onnx format.
> 
> Cutting through the jargon and hype, we can view:
> 
>     * trained models as binary programs
> 
>     * inference is running those programs
> 
>     * model training as compilation or build, and
> 
>     * pytorch code defining a neural network and and training data as source code.
> 
> 
> The thing that's different from other kinds of programming is we can't distribute training data or do the build on end-user hardware or even on CI hardware. Even if we were training on open data sets (which we're not) they are so large and take so long to train on anything but specialized GPU clusters that it's pointless.
> 
> Plus, with tensorflow and pytorch, you need to distribute the network source code in order for the trained weights to make sense, which is probably the biggest reason everyone conflated training/testing/using in deep learning.
> 
> But `onnx` picked up on this insight, and saves the structure of the network alongside the trained weights, so there's no need to distribute the "source code" at all.
> 
> In that light, torch's GPU parts are just another _build_ dependency for us. I am not nearly as worried about making build dependencies difficult (though I still think we should make that easier too when we can).

Another analog is the difference between `javac` (aka the JDK) and `java` (the JRE): the former compiles code that runs on the latter. Or the SDKs for video game consoles vs the consoles themselves; or . My understanding is pytorch and tensorflow make it impossible (except maybe for the GPU code) to separate the development from the runtime environment; but onnx does.

**Comment by joshuacwnewton** [comment]
> We could make it so pip install spinalcordtoolbox[dev] installs torch

We don't even have to do that much. Doing a quick project-wide search, I don't think SCT actually uses `torch` at all in its own codebase. I think we only install `torch+cpu` as a way to counteract the upstream dependency that `ivadomed` imposes on us.

**Comment by kousu** [comment]
Here's another question we should look into: *does* onnx support GPUs? GPUs are most important for compiling (aka training) simply because that takes many many iterations, but they can still be beneficial just to accelerate runtime as well.

Answering my own question: it seems so, via `onnxruntime-gpu`: https://pypi.org/project/onnxruntime-gpu/.

And like torch and tensorflow, the GPU version is much larger, but it's a difference of 4MB to 30MB, not 600MB to 1300MB.

**Comment by jcohenadad** [comment]
> An extension of this idea is: Instead of importing imed_inference, we could handle this ONNX inference functionality inside SCT. This has the (huge) added benefit of letting us exclude ivadomed as a dependency, which would decouple SCT from ivadomed and make SCT immune to any upstream changes.

this is a very interesting idea. The potential limitation that comes to mind is that some of the pre/post-processing is currently handled by ivadomed (bias field correction, resampling, cropping, etc.). @charleygros @andreanne-lemay can correct me if I'm wrong. In any case, we should consider this as I understand the potential benefits.

**Comment by joshuacwnewton** [comment]
> this is a very interesting idea. The potential limitation that comes to mind is that some of the pre/post-processing is currently handled by ivadomed (bias field correction, resampling, cropping, etc.).

Ah. Thank you for chiming in. If any of the pre/post-processing is done using `torch`, this could make things a bit harder.

**Comment by kousu** [comment]
> some of the pre/post-processing is currently handled by ivadomed (bias field correction, resampling, cropping, etc.).

Oh that's a very good point. That doesn't fit into my compiler taxonomy.

I doubt the pre/post-processing is done with *torch*, it's probably done by reshaping/averaging `numpy` arrays. But that means python code that needs to be distributed with the model. In my taxonomy above, I disregarded all the python code, saying it could get compiled into the .onnx files, but I forgot that there's non neural-network steps involved.

We can still make it work. We could split make `pip install ivadomed[build]` install `torch` and the training script construct a .onnx file, and conversely have `pip install ivadomed` run normally, checking if there's a .onnx file available and failing otherwise.

It would be easier to package if ivadomed wasn't a monolith; if it was, say, a `ivadomed-core` with utilities and base classes, and then a series of `ivadomed-model-x`, `ivadomed-model-y` packages. But that's a lot more work than I want to drag everyone through right now.

**Comment by joshuacwnewton** [comment]
> I doubt the pre/post-processing is done with torch, it's probably done by reshaping/averaging numpy arrays.

We use the [`segment_volume`](https://github.com/ivadomed/ivadomed/blob/c00ef65e6e2080f71f20b1fb2c0d1f7925a13f64/ivadomed/inference.py#L253-L369) function from `ivadomed.inference`. Looking over that function, the pre/postprocessing operations are taken from `torchvision` and applied using `torch.Dataset`, which means that inference is much more coupled to `torch` than I initially thought.

I may have gotten ahead of myself with this idea, and I apologize for that. :sweat:

**Comment by jcohenadad** [comment]
> If any of the pre/post-processing is done using torch, this could make things a bit harder, so this is good to be aware of.

it is not

**Comment by joshuacwnewton** [comment]
Given the previous investigation in this issue, I'd like to close this as a `wontfix` because of the following intractible blockers:

1. All `sct_deepseg` models must have ONNX versions. 
    - There are significant blockers for this on ivadomed's side of things, e.g. [ivadomed/#749](https://github.com/ivadomed/ivadomed/issues/749)
2. It must be possible to call `ivadomed.inference.segment_volume` without needing `torch` or `torchvision`
    - This would require an immense refactoring effort on ivadomed's side of things, because all `sct_deepseg` models rely on ivadomed's `torchvision`-based pre/postprocessing, even when inference is run using ONNX. 
3. It must be possible to install `ivadomed` without needing `torch` or `torchvision`
    - This would require an immense refactoring effort on ivadomed's side of things, because the package would be need to split up into a "training" version of ivadomed, and a lighter "ONNX inference only" version of ivadomed.

We can keep an eye on:

- https://github.com/ivadomed/ivadomed/issues/795

But from SCT's perspective, I don't think there's anything we can on our side here without pouring years of development resources into completely overhauling `ivadomed`. And... I don't think that's a worthwhile (or even possible) endeavour?

**Comment by jcohenadad** [comment]
Agreed. For information, I am currently experiencing training/testing models using MONAI instead of ivadomed (here: https://github.com/jcohenadad/model-seg-ms-mp2rage-monai). I'll see if it gets me to a place where removing ivadomed dependency could be considered.
