### ISSUE TITLE
FSLeyes integration script is not compatible with FSLeyes v1.0

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3426]
### Description

Trying to load `sct_plugin.py` using "Run script" results in the following error dialog:

![Screenshot from 2021-06-18 12-35-44](https://user-images.githubusercontent.com/16181459/122592023-c579c980-d031-11eb-9018-643f075a10ac.png)

The full traceback is:

```python
 WARNING         runscript.py  107: __doAction      - Script (/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py) could not be executed: 'FSLeyesFrame' object has no attribute 'getAuiManager'
Traceback (most recent call last):
  File "/home/joshua/miniconda/envs/fsleyes-1.0.11-test/lib/python3.9/site-packages/fsleyes/actions/runscript.py", line 101, in __doAction
    runScript(self.__frame,
  File "/home/joshua/miniconda/envs/fsleyes-1.0.11-test/lib/python3.9/site-packages/fsleyes/actions/runscript.py", line 169, in runScript
    exec(code, _globals)
  File "/home/joshua/repos/spinalcordtoolbox/contrib/fsl_integration/sct_plugin.py", line 36, in <module>
    aui_manager = frame.getAuiManager() # from FSLeyes context
AttributeError: 'FSLeyesFrame' object has no attribute 'getAuiManager'
```

### Steps to Reproduce

Note: If you installed FSLeyes via FSL, and you have FSL v6.0.4 installed (the most recent version at time of writing), you will have gotten FSLeyes v0.34.2. And, upgrading inside the FSL install is not straightforward. 

So, to reproduce, the easiest way is to install FSLeyes v1.0 directly. I simply created a new conda env and installed it as follows:

```
conda create --name fsleyes-1.0.11-test
conda activate fsleyes-1.0.11-test
conda install -c conda-forge fsleyes==1.0.11
```

**Comment by joshuacwnewton** [comment]
`FSLeyesFrame.getAuiManager` was [deprecated in FSLeyes v0.16 and removed in v1.0](https://github.com/pauldmccarthy/fsleyes/blob/3a968497cb5d4a98228143105abe4f4f2caf3135/fsleyes/frame.py#L439-L444).

I will take the steps to update the script so that it will be compatible with both v0.34 and v1.0. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
The script has fallen out of date in more ways than just this. I'll try to fix all of the assorted issues, but...

As an aside, it doesn't sit right with me that we advertise the FSLeyes integration as a major feature, yet don't test it at all. That said, I can't really think of a good way to approach the problem, given the complexity of testing FSLeyes.

`sct_script.py` is heavily dependent on the FSLeyes context (`frame`, `displayCtx`, etc.) and I get the sense that mocking these things would a beastly undertaking. Skimming FSLeyes' own [test suite](https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/-/tree/master/fsleyes/tests), I see more complexity than I can handle with my current (limited) understanding of GUI testing. My gut feeling is that trying to automate this would be far more trouble than it's worth. :sweat: 

So, at the moment, the best compromises I can think of would be to:

* Accept that the script will inevitably break, but make manual testing a task for each stable release, just so that we ensure that each release has a functional version of the script. That's still hours of work, but once every 1-2 months, rather than on a per-PR basis.
* Reflect on whether this script is worth maintaining. (How valuable is it to users? Valuable enough to dedicate that kind of time?) I have a feeling the answer is "Yes", but I thought I would ask just to be thorough. :sweat_smile:

**Comment by jcohenadad** [comment]
> So, at the moment, the best compromises I can think of would be to:
> 
> * Accept that the script will inevitably break, but make manual testing a task for each stable release, just so that we ensure that each release has a functional version of the script. That's still hours of work, but once every 1-2 months, rather than on a per-PR basis.
> * Reflect on whether this script is worth maintaining. (How valuable is it to users? Valuable enough to dedicate that kind of time?) I have a feeling the answer is "Yes", but I thought I would ask just to be thorough. 😅

I would definitely go with the first option. A few users _love_ this FSLeyes integration and it is a great way to promote SCT when doing demos/presentations. So far we didn't have too much problem with FSLeyes upgrades. In fact, it is the first time that an upgrade causes cross-compatibility issue with the SCT script, so I don't anticipate things breaking every months.

**Comment by joshuacwnewton** [comment]
> In fact, it is the first time that an upgrade causes cross-compatibility issue with the SCT script, so I don't anticipate things breaking every months.

It turns out that it was not just the FSLeyes upgrade that was an issue. I uncovered 4 other bugs in my testing (see: the commits in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3427) which seem to have accumulated over the months/years. :sweat_smile:

**Comment by jcohenadad** [comment]
> > In fact, it is the first time that an upgrade causes cross-compatibility issue with the SCT script, so I don't anticipate things breaking every months.
> 
> It turns out that it was not just the FSLeyes upgrade that was an issue. I uncovered 4 other bugs in my testing (see: the commits in #3427) which seem to have accumulated over the months/years. 😅

Ooopsi 😬 . Well, I still think it is worth keeping the GUI in the loop. Our coding practices have largely improved (partly thanks to you @joshuacwnewton) so I anticipate less introduction of GUI-related bugs (and yes, more "manual" testing before big releases).
