### ISSUE TITLE
Add visualization of the centerline smoothed in RL direction in `sct_qc`

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3431]
## Context
With the new method measuring CSA from distance of PMJ (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3429), the distance is measured along the extrapolated centerline. Visual assessment of the extrapolated centerline is important to detect if there is failure.

## Suggestion
As suggested in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3429#commitcomment-52668990, a solution to visually assess the quality of the extrapolated centerline would be to smooth the centerline in the RL direction and display the sagittal view in the QC.

**Comment by sandrinebedard** [comment]
@jcohenadad 
I don't remember if we wanted the graphs from sct_process_segmentation (1) or the centerline fitting  (2) to include at the top of the QC?

(1)
![image](https://user-images.githubusercontent.com/71230552/123847741-f0430800-d8e4-11eb-82ab-b7dd589a3b55.png)

(2)
![image](https://user-images.githubusercontent.com/71230552/123847664-d7d2ed80-d8e4-11eb-91cd-77c0a0d91d56.png)

**Comment by jcohenadad** [comment]
Good question. I would put from top to bottom: 
- graphs from sct_process_segmentation
- sagittal MRI view of centerline (R-L translated to align centerline in the medial plane)
- centerline fitting

**Comment by sandrinebedard** [comment]
> Good question. I would put from top to bottom:
> 
> * graphs from sct_process_segmentation
> * sagittal MRI view of centerline (R-L translated to align centerline in the medial plane)
> * centerline fitting

Ok so we have a lot of things to display! I think we'll have to scroll since it is all in the same page ifwe want to see the graphs, I can shrink them down too

**Comment by sandrinebedard** [comment]
For QC in `sct_process_segmentation`, if the flag `-pmj`is specified, the qc will have the following elements:
1. Display graph (of sct_process_segmentation)
2. Display sagittal MRI view flattened along the centerline (with `sct_flatten_sagittal`) and centerline smoothed RL direction
3. Display centerline fitting graphs

Here are 2 options for display:

#### Option 1 🚀  : display elements one after the other
![image](https://user-images.githubusercontent.com/71230552/123855565-0e613600-d8ee-11eb-93b3-463202a780e9.png)
![image](https://user-images.githubusercontent.com/71230552/123855655-2638ba00-d8ee-11eb-9191-615dcce5b587.png)
![image](https://user-images.githubusercontent.com/71230552/123855688-2cc73180-d8ee-11eb-822d-cb289be57948.png)

#### Option 2 🎉: display graphs from sct_process_segmentation next to sagittal MRI view of centerline

![image](https://user-images.githubusercontent.com/71230552/123855978-8b8cab00-d8ee-11eb-9cee-05242178bd42.png)
![image](https://user-images.githubusercontent.com/71230552/123855881-67c96500-d8ee-11eb-9f84-594289c0e1a0.png)

**Comment by sandrinebedard** [comment]
## UPDATE
If the flag `-pmj` isn't specified, no QC will be generated (right now the graphs are displayed)
If the flag `-pmj` is specified, the qc of `sct_process_segmentation`will include:
* sagittal MRI view of centerline (R-L translated to align centerline in the medial plane)
* Binary mask of extent where CSA is computed

![image](https://user-images.githubusercontent.com/71230552/123969554-56cc3280-d986-11eb-87e1-dbbe6d044ffc.png)

One remaining question, do we want the overlay to only be the mask or the centerline or both together?

**Comment by jcohenadad** [comment]
> One remaining question, do we want the overlay to only be the mask or the centerline or both together?

I would say both. 

Another thing that comes to my mind: given that the QC is now made specific to the PMJ option, how about we also display the location of the PMJ, so that it saves time QCing `sct_detect_pmj` as well?

**Comment by sandrinebedard** [comment]
> Another thing that comes to my mind: given that the QC is now made specific to the PMJ option, how about we also display the location of the PMJ, so that it saves time QCing sct_detect_pmj as well?

Yes we could! However, it may be confusing when using the interactive feature (✅/❌/⚠️), do we assess the location of PMJ or the extrapolation of the centerline...
(when interpolating between PMJ coordinate and the centerline, if PMJ detection fails, the centreline won't be good that's for sure, in that case it would be ok I think to include the PMJ in the QC)

**Comment by jcohenadad** [comment]
> However, it may be confusing when using the interactive feature (✅/❌/⚠️), do we assess the location of PMJ or the extrapolation of the centerline...

oh! good thinking. Well, in that case I agree it would cause too much confusion. So OK, let's keep it separate: one QC for `sct_detect_pmj` and another one for `sct_process_segmentation`. That being said, we should still display the PMJ on the `sct_process_segmentation` QC so that if a bad PMJ detection was missed during a first QC, then it could be spotted in the 2nd pass. That way, the QC procedure is also made more robust (less human-error prone).

**Comment by sandrinebedard** [comment]
> oh! good thinking. Well, in that case I agree it would cause too much confusion. So OK, let's keep it separate: one QC for `sct_detect_pmj` and another one for `sct_process_segmentation`. That being said, we should still display the PMJ on the `sct_process_segmentation` QC so that if a bad PMJ detection was missed during a first QC, then it could be spotted in the 2nd pass. That way, the QC procedure is also made more robust (less human-error prone).

Great! To review, the QC for `sct_process_segmentation` will display 3 overlays:
* sagittal MRI view of centerline (R-L translated to align centerline in the medial plane)
* Binary mask of extent where CSA is computed
* PMJ

![image](https://user-images.githubusercontent.com/71230552/123985351-669e4380-d993-11eb-8d29-7bb3a0a0e591.png)
