### ISSUE TITLE
Unpin `onnxruntime` due to OpenMP requirement being removed in v1.7.0

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3433]
We're currently pinning `onnxruntime==1.4.0` to avoid the OpenMP dependency from `onnxruntime>=1.5.1`. (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3033)

However, [`onnxuntime==1.7.0`](https://github.com/microsoft/onnxruntime/releases/tag/v1.7.0) removed this requirement, so we no longer have to pin.

This was one of the blockers for Python 3.9 support (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3367), so huzzah!

**Comment by joshuacwnewton** [comment]
I think it actually may be better to pin `onnxruntime>=1.7.0`, to avoid any releases with the OpenMP requirement. But, I can't open a PR for that right now, as ivadomed will have to change their version pinning first (to avoid dependency conflicts).

**Comment by jcohenadad** [comment]
> I can't open a PR for that right now, as ivadomed will have to change their version pinning first

Is ivadomed's team aware? @dyt811

**Comment by dyt811** [comment]
Yuan's PR is pinning IvadoMed at onnxruntime 1.7.0. So we are aligned on that.

**Comment by joshuacwnewton** [comment]
> Yuan's PR ([ivadomed/ivadomed#819](https://github.com/ivadomed/ivadomed/pull/819)) is pinning IvadoMed at onnxruntime 1.7.0. So we are aligned on that.

This has now been merged, so as soon as a new version of `ivadomed` is released, we can go forward with unpinning `onnxruntime` in SCT. (No rush for this, though... we're still far from supporting Python 3.9 on SCT's end.)
