### ISSUE TITLE
PMJ wrongly displayed in QC report

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3441]
### Description
When running QC report for `sct_detect_pmj`, the X that labels PMJ is not the same as the label displayed in fsleyes. Looks like the X isn't centered on the PMJ coordinate. 

Here is the PMJ label when I open it in fsleyes:
(sub-1000032 of uk-biobank-processed)
![image](https://user-images.githubusercontent.com/71230552/124517949-45828c00-ddb3-11eb-99f8-7d09967b7787.png)

Here is what the QC displays:
![image](https://user-images.githubusercontent.com/71230552/124517832-02c0b400-ddb3-11eb-9d23-a17f1822f51a.png)

### Steps to Reproduce

0. Install SCT git-sb/3063-csa-measure-from-pmj-cc56d4a39f8c65d5d91d0b361e42740c7888b2ac

1. run `sct_detect_pmj`

2. Check qc report index.html

3. Open PMJ label in fsleyes

**Comment by jcohenadad** [comment]
wow, great catch! This is definitely a bug
