### ISSUE TITLE
Remove mirror neuro.polymtl.ca

### ISSUE THREAD

**Issue by alexfoias** [spinalcordtoolbox/spinalcordtoolbox#3443]
Remove mirror neuro.polymtl.ca because our dokuwiki migrated to gitbook.io

**Comment by taowa** [comment]
I'd like to try to *replace* neuro.polymtl.ca and not remove it outright. OSF is the only other mirror for at least a couple models, and I think that we should try to make them available ourselves. I outlined one of our options for doing that on `#website`, but am open to others.

**Comment by joshuacwnewton** [comment]
> I'd like to try to _replace_ neuro.polymtl.ca and not remove it outright. OSF is the only other mirror for at least a couple models, and I think that we should try to make them available ourselves. I outlined one of our options for doing that on `#website`, but am open to others.

The mirrors are mainly relevant for SCT's custom download manager, `sct_download_data`. But, just to mention one alternative, @kousu has also been taking a stab at hosting/versioning/distributing the models via `pip` as a more long-term solution. It's a little nonstandard, but would solve a big packaging blocker for #1526. 

(There's further context in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2669, https://github.com/spinalcordtoolbox/spinalcordtoolbox-data-template/pull/1.)

**Comment by kousu** [comment]
Thanks for poking me about that @joshuacwnewton.

And there's another problem: the backup mirror doesn't seem to be working? There's been a few reports on the forum like https://forum.spinalcordmri.org/t/installation-failed-at-the-end/496:

> Exception: (‘Download error’, [SSLError(MaxRetryError(‘HTTPSConnectionPool(host=‘osf.io’, port=443): Max retries exceeded with url: /mka78/?action=download (Caused by SSLError(SSLError(“bad handshake: SysCallError(-1, ‘Unexpected EOF’)”,),))’,),), HTTPError(‘403 Client Error: Forbidden for url: https://www.neuro.polymtl.ca/_media/downloads/sct/20200420_sct_binaries_linux.tar.gz 1’,)])

It seems to be mixing up the two domains somehow, but only when it has to fall back. If that's true, it means www.neuro.polymtl.ca/_media/downloads hasn't been used in months, maybe years. I haven't debugged this. I tried to reproduce it a bit but just didn't finish before going to do something else.

**Comment by joshuacwnewton** [comment]
> And there's another problem: the backup mirror doesn't seem to be working?

I just found this issue you opened for the problem: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3106
