### ISSUE TITLE
Add field in QC .yml list for `sct_detect_pmj` in QC report

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3445]
## Context
Currently, the .yml list output from the interactive QC report has 4 fields --> (see [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0ae8e92283add0f581a7af7964fdd115ebebee41/spinalcordtoolbox/reports/assets/index.html#L326-L347)):
- FILES_GMSEG
- FILES_SEG
- FILES_LABEL
- FILES_TIMESERIES

 With `sct_detect_pmj`, it outputs `FILES_GENERATED_BY_sct_detect_pmj_FILE_KIND_UNKNOWN:` since the type is not specified

Would be nice to have a specific field for it. Could directly be `FILES_PMJ`. We could also use `FILES_LABEL`, but I think it will be confusing if you want to differentiate with vertebral labels.

**Comment by sandrinebedard** [comment]
I also noticed that for `sct_register_multimodal `and `register_to_template` the seg type is also `FILES_SEG`, there could be another type to differentiate failed registration and failed segmentation.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0ae8e92283add0f581a7af7964fdd115ebebee41/spinalcordtoolbox/reports/assets/index.html#L326-L347

Also, some of those functions don't even have a qc report

**Comment by joshuacwnewton** [comment]
Possibly related: https://github.com/spine-generic/spine-generic/issues/248. 

I wonder if it would be easier to just use SCT function itself as the YAML header. (Since, originally in spine-generic, the "FILES_SEG" and "FILES_GMSEG" and "FILES_LABEL" strings are just mappings to SCT functions anyway...)

```python
     if task == 'FILES_SEG': 
         return 'sct_deepseg_sc' 
     elif task == 'FILES_GMSEG': 
         return 'sct_deepseg_gm' 
     elif task == 'FILES_LABEL': 
         return 'sct_label_utils'
```

If we just used the SCT functions directly in the YAML file, we wouldn't have to repeatedly update the QC html whenever we add a new function. (Though, changing the YAML structure would require changes to the manual correction scripts, hence https://github.com/spine-generic/spine-generic/issues/248.)

**Comment by sandrinebedard** [comment]
> I wonder if it would be easier to just use SCT function itself as the YAML header. (Since, originally in spine-generic, the "FILES_SEG" and "FILES_GMSEG" and "FILES_LABEL" strings are just mappings to SCT functions anyway...)
> 
> ```python
>      if task == 'FILES_SEG': 
>          return 'sct_deepseg_sc' 
>      elif task == 'FILES_GMSEG': 
>          return 'sct_deepseg_gm' 
>      elif task == 'FILES_LABEL': 
>          return 'sct_label_utils'
> ```
From what I see [here](https://github.com/spine-generic/spine-generic/blob/e6f7da5a62c0aa1fdfc11f121c7c9ed17fb13727/spinegeneric/cli/manual_correction.py#L237-L238)
this is only used to create a new QC report of the corrections, FILES_SEG and FILES_LABEL are used to know what task to do (open a viewer with `sct_label_utils `or open fsleyes or itksnap to correct a segmentation), it is also used to know what to call the manual label

Even if we use SCT functions, we would still have know the task to perform, this is tricky.
However, not all sct functions that are in the YAML file are relevant for manual correction (e.g. `sct_register_multimodal`) so it would still be less heavy to use the SCT functions directly in the YAML and translate to the task in manual correction script

Also related to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3353
