### ISSUE TITLE
Add possibility for output TXT

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3453]
**Feature justification**

Function `sct_compute_snr` outputs results in the Terminal:
~~~
julien-macbook:~/temp/20210712_gmchallenge/data_processed/9418 $ sct_compute_snr -i data_concat.nii.gz -method mult -m data1_crop_wmseg_erode.nii.gz 

--
Spinal Cord Toolbox (git-jca/sb/3063-csa-measure-from-pmj-05976283f121899e8903e8bb8222dce004940236)

sct_compute_snr -i data_concat.nii.gz -method mult -m data1_crop_wmseg_erode.nii.gz
--


SNR_mult = 20.003156441135573
~~~

When implementing pipelines, one needs to access this Terminal output and use it for making statistics. This currently requires an ugly regex manipulation to access the float value from stdout. 

**Describe the solution you'd like**

A new flag `-o` where user could indicate a TXT file name where results are output. The TXT file would only contain the number, so it can conveniently be opened by any Python script.

**Additional context**

The need for this feature came up while working on the [GM challenge project](https://github.com/sct-pipeline/gm-challenge).

**Comment by santoshdvc** [comment]
Hi, 
I browsed through the `sct_compute_snr` in the `spinalcordtoolbox`. I came up with the following - 
```
optional.add_argument(
        '-o',
        type=str,
        help='Add output to text file.',
        default=""
```

Is this what is needed? I know another function must be written which will process the argument provided, but can't figure out where to write the function.

**Comment by santoshdvc** [comment]
Hi, 
I have made few changes for the above issues in the code. Before, creating a pull request, I would like to draft the pull request and get through the changes properly. Can I submit a draft pull request now?
