### ISSUE TITLE
Improve right-left placement of PMJ detection

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3456]
**Feature justification**

Currently, PMJ is detected using `sct_detect_pmj`. The algorithm works by:
- getting the mid-sagittal slice (averaged across a few adjacent slices)
- running a 2D CNN to detect the PMJ

Problem: if the mid-sagittal slice does not correspond to the anatomical medial plane, then the detected PMJ will be "off" in the right-left direction.

**Describe the solution you'd like**

A second module that would fine-tune the right-left location of the PMJ.

The algorithm could be based on a 3D sliding window, going in the R-L direction and computing the cross-correlation with a mirrored window in order to find the symmetry in the image (ie: we assume the PMJ to be located at the most symmetrical point, ie: medial plane).

For inspiration, you can look at the following code that also does sliding window to detect vertebral discs:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0bef2991f0c05251fbf43df8d1fc0360960565c2/spinalcordtoolbox/vertebrae/core.py#L382

In the case of PMJ detection however, we could start from the detected point and create a box of ~2x2x2cm around that point, and mirror it and compute similarity metric between the box and its mirror.

**Comment by sandrinebedard** [comment]
> Problem: if the mid-sagittal slice does not correspond to the anatomical medial plane, then the detected PMJ will be "off" in the right-left direction.

`sct_detect_pmj` can also can find the 2D sagital slice with the spinal cord segmentation (with the flag `-s`), that would resolve the problem? It would still be off if the head is tilted, but the slidding window would also not resolve that.

**Comment by jcohenadad** [comment]
> > Problem: if the mid-sagittal slice does not correspond to the anatomical medial plane, then the detected PMJ will be "off" in the right-left direction.
> 
> `sct_detect_pmj` can also can find the 2D sagital slice with the spinal cord segmentation (with the flag `-s`), that would resolve the problem? It would still be off if the head is tilted, but the slidding window would also not resolve that.

I would need to see what the code does, but IIRC it just crops around the SC for improving the robustness of PMJ detection. So this flag does _not_ ensure the PMJ is placed at the middle (which is what we aim for with the sliding window approach).

**Comment by sandrinebedard** [comment]
> I would need to see what the code does, but IIRC it just crops around the SC for improving the robustness of PMJ detection. So this flag does _not_ ensure the PMJ is placed at the middle (which is what we aim for with the sliding window approach).

yeah it uses R-L coordinate of the center of mass of the segmentation instead of the mid-sagittal slice
