### ISSUE TITLE
Implement SNR_single

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3476]
context: https://github.com/sct-pipeline/gm-challenge/issues/58

i'll fill up more context when i have time

**Comment by joshuacwnewton** [comment]
If I'm understanding correctly, you want to take the function from https://github.com/sct-pipeline/gm-challenge/issues/58#issuecomment-882111266 and expose it via an option in SCT?

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/858d2255e256d18dc3733c93276f1526469bd277/spinalcordtoolbox/scripts/sct_compute_snr.py#L60-L66

Something like `sct_compute_snr -method single`?
