### ISSUE TITLE
What is the proper way to compute the SNR?

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3481]
### Description

While working on https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3479, I noticed discrepancies between the SNR_single method and two other methods (which give similar results): SNR_mult and SNR_diff. 

Originally, I was basing myself on this only article from [Dietrich et al 2007](https://paperpile.com/app/p/d1f035d3-0f3c-00b4-9c5a-c4bf326a57ab).

However, I then discovered discrepancies in the SNR equations, and notably the correction factors for the diff method.

In Dietrich et al, and [this website](http://mriquestions.com/signal-to-noise.html), SNR_diff should be corrected by a factor 1/sqrt(2):
![image](https://user-images.githubusercontent.com/2482071/126855882-e61bfe1c-3baa-4262-bf76-1b14de97cd8f.png)

However, in [Firbank et al](https://paperpile.com/app/p/bc249716-905b-0f5a-b977-93a4a4e9e0de) the correction factor is sqrt(2):
![image](https://user-images.githubusercontent.com/2482071/126855875-1958b5c2-894d-4ad9-bca8-23af4c3f25a2.png)

And even more confusing, in [Steckner et al](https://paperpile.com/app/p/a67fa625-accf-01fe-aad5-c46170dcca17), they look at different factors and pick the best one:
![image](https://user-images.githubusercontent.com/2482071/126855858-607752f3-4c6d-46dd-b5d8-8469b0f96535.png)

Shouldn't there be only _one_ solution based on mathematical (not empirical) considerations?

**Comment by joshuacwnewton** [comment]
Regarding the table from [Steckner et al](https://paperpile.com/app/p/a67fa625-accf-01fe-aad5-c46170dcca17):

> ![image](https://user-images.githubusercontent.com/2482071/126855858-607752f3-4c6d-46dd-b5d8-8469b0f96535.png)

Skimming the paper, these 8 correction factors each correspond to one of 8 different SNR measurement methods surveyed by the paper. And, these correction factors differ depending on nature of each specific SNR method:

> * (a) for SNR measurements using the full (two times FOV) data sets, SNR is sqrt(2) higher because there are twice as many data points,
> * (b) for SNR measurements using difference of images, the subtraction process increases the standard deviation noise estimate by sqrt(2),
> * (c) for SNR measurements using the mean of a back-ground region free of artifacts (beside the phantom in
> the read direction), the mean value is 2.74 times larger than the standard deviation for a four channel coil, according to Rician distribution statistics, and
> * (d) for SNR measurements using the standard deviation of a background region free of artifacts (beside the phantom in the read direction), the measured standard deviation is 0.695 times the “true standard deviation,” according to Rician distribution statistics.

Based on the "(factors Nos. a, c)" annotations for each entry in the table, the authors appear to mix and match (a)-(d) to arrive at the 8 correction factors for each SNR method.

----

If we compare the 4 justifications, (a)-(d), to the 3 other linked sources...

1. The explanation in Firbank et al. suggests to me that they are following **(b)** -->  **(6)** and **(7)** from the table:

    > Using the dual acquisition, subtraction method, the SNR dual was calculated thus:
    > ![image](https://user-images.githubusercontent.com/2482071/126855875-1958b5c2-894d-4ad9-bca8-23af4c3f25a2.png)
    > where S1 is the mean signal intensity in the ROI on the first image, and SD 1−2 is the standard deviation in the ROI on the subtraction image. The √2 factor arises because the noise is derived from the difference image.

2. The explanation from [Dietrich et al 2007](https://paperpile.com/app/p/d1f035d3-0f3c-00b4-9c5a-c4bf326a57ab) also suggests **(b)**:
    > The SNRdiff in an ROI is calculated as the quotient of the mean value (with respect to the ROI) of the signal in the
sum image and the SD (evaluated in the same ROI) of the signal in the difference image, divided by the factor sqrt(2).

    However, there is an extra 1/2 in the numerator _(why? I'm not quite sure...)_. But, hence the change in the factor from √2 -> 1/√2.

    > ![image](https://user-images.githubusercontent.com/2482071/126855882-e61bfe1c-3baa-4262-bf76-1b14de97cd8f.png)

3. The [mriquestions.org page](http://mriquestions.com/signal-to-noise.html) is a little vague/imprecise about its explanation, but it also appears to be based on **(b)**:

    > But because this calculation involves a difference operation, the true SNR must be corrected by a factor of 1/√2 ≈ 0.71. 

So, all three sources seem to be specifically connected to the "difference of images" correction factor (and therefore unrelated to **(a)**, **(c)**, and **(d)** from Steckner et al. if I'm understanding correctly).

**Comment by joshuacwnewton** [comment]
> While working on #3479, I noticed discrepancies between the SNR_single method and two other methods (which give similar results): SNR_mult and SNR_diff.

Just to double-check the context here, was this initial observation related to the `#TODO` comment left in #3479?

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4c9543c521afbab50bbd47e80cb527ee9717e768/testing/cli/test_cli_sct_compute_snr.py#L251-L253

(For anyone else reading, in this case, the calculated SNR is ~1200 while the actual SNR is ~1400). Hence setting `rel=0.5` for the `single` tests, but `rel=0.05` for the tests for the other methods.)

**Comment by valosekj** [comment]
Hm, really interesting discussion. I can maybe add another paper which I have in my library which uses factor 0.655 for computing SNR from single image - [Zhang et al., 2018](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8267028):

![image](https://user-images.githubusercontent.com/39456460/126978389-58c0c23b-6ea6-4369-8279-6f1785d7ee7e.png)

I personally use this equation (2) when I need to compute SNR from single brain MRI image.

**Comment by joshuacwnewton** [comment]
> I can maybe add another paper which I have in my library which uses factor 0.655 for computing SNR from single image - [Zhang et al., 2018](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8267028):

I believe this is similar (if not the same?) as a separate correction factor mentioned by Dietrich et al.. Though, they specify a Rayleigh distribution, rather than a Rician distribution:

![Screenshot from 2021-07-26 08-19-17](https://user-images.githubusercontent.com/16181459/126987523-663b0ce9-9721-49c9-aef7-c4622fde88dc.png)

![Screenshot from 2021-07-26 08-17-14](https://user-images.githubusercontent.com/16181459/126987437-a9d8561a-ae3c-4a4e-8d08-ddb03730c72a.png)

@jcohenadad's PR #3479 is currently following A12 right now:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4c9543c521afbab50bbd47e80cb527ee9717e768/spinalcordtoolbox/scripts/sct_compute_snr.py#L260-L262

`np.sqrt((4 - np.pi) / 2)` = ~0.655 as well, so I believe these are the same correction factors. (I'm not super familiar with the subtle distinctions [between Rayleigh and Rician distributions](https://www.usna.edu/EE/ee433/Handouts/Lecture%2014%20-%20Rayleigh%20and%20Rician%20RV.pdf), though.)

**Comment by valosekj** [comment]
@joshuacwnewton yes, you are right, 0.655 =~ sqrt((4 - pi) / 2). 

Based on [Gudbjartsson 1995](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2254141/) it looks that _Rayleigh distribution_ is special case of _Rician distribution_:

"
A special case of the Rician distribution is obtained in image regions where only noise is present, A = 0. This is better known as the Rayleigh distribution...
"

**Comment by joshuacwnewton** [comment]
> Actually my issue is that Firbank suggests to correct by sqrt(2) while Dietrich and mriquestions.com (and other papers) suggest to correct by 1/sqrt(2). There must be a mistake somewhere, unless i misread something...

Thank you for specifying. Yes, agreed.

I think I have a hunch, though. If you look at Dietrich et al., they originally start with 1/√2 in the denominator (which would == √2 in the numerator). However, they then do some simplification, combining the  1/√2 term with the 1/2 term in the numerator from S_diff.

> ![image](https://user-images.githubusercontent.com/2482071/126855882-e61bfe1c-3baa-4262-bf76-1b14de97cd8f.png)

If you compare with Firbank et al, they never substitute the S term in. They just leave it as S_1:

> ![image](https://user-images.githubusercontent.com/2482071/126855875-1958b5c2-894d-4ad9-bca8-23af4c3f25a2.png)

So, I have a feeling the discrepancy might just be due to the fact that one paper substitutes + simplifies the terms, and the other does not.

**Comment by joshuacwnewton** [comment]
> while mriquestions.com [...] suggest to correct by 1/sqrt(2). 

I also want to mention that mriquestions.com's wording is a little vague:

> But because this calculation involves a difference operation, the true SNR must be corrected by a factor of 1/√2 ≈ 0.71.

This could mean "multiply by 1/√2 " or it could mean "there is a 1/√2 factor that needs to be corrected, therefore multiply by √2." 

If they meant the latter, then all 4 the sources (including Steckner et al.) would have the same conclusion:

```
SNR = (√2)   * S / SD
    = (1/√2) * m / SD

**Comment by jcohenadad** [comment]
> (Note that S_diff has become m_sum in the final equation!)

ah!!! of course, you're right. It is the sum, not the diff. Thank you @joshuacwnewton 🎉

**Comment by jcohenadad** [comment]
closing because we now figured it out
