### ISSUE TITLE
Implement a statistical model to normalize cord CSA results

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3483]
## Context

Currently, `sct_process_segmentation` outputs CSA values, but it is up to the researcher to normalize them using metrics such as age, height, sex, etc.

There are normalization models being developed, and it would be great to implement one of these models into the function, so that the output could be normalized.

## Suggestions

- Implement the statistical model (@sandrinebedard)
- Add a flag `-normalize`, with various possible values corresponding to the regressors to consider. 
  - One possibility would be to list the regressors to use. Eg: `-normalize age sex height`
- Output CSV file. Few possibilities:
  - Add a column with the normalized CSA
  - Use the current column that displays the average CSA "MEAN(Area)". --> I would be in favour of that, to minimize conflicts with unit testing, documentation, etc.

**Comment by joshuacwnewton** [comment]
> Add a flag `-normalize`, with various possible values corresponding to the regressors to consider.
> 
>     * One possibility would be to list the regressors to use. Eg: `-normalize age sex height`

To get this metadata, would `sct_process_segmentation` look for BIDS json sidecar files alongside the NIfTI files, like was done with `sct_compute_mtr`? e.g.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1ee7a54452956f17c59ba048f62ebe54d69bb529/spinalcordtoolbox/scripts/sct_compute_mtsat.py#L62-L67

**Comment by jcohenadad** [comment]
> To get this metadata, would sct_process_segmentation look for BIDS json sidecar files alongside the NIfTI files, like was done with sct_compute_mtr? e.g.

good guess @joshuacwnewton , this is _almost_ what we had in mind 😊 . But participant-specific information would rather be contained in the `participants.tsv` file which is at the root of a BIDS dataset. The JSON sidecar are more related to the acquisition parameters of a specific image.

**Comment by joshuacwnewton** [comment]
Ah, oops. Thank you for the clarification. :sweat_smile:

**Comment by sandrinebedard** [comment]
Other things we need to consider:

- if the user wants normalization for 1 subject, they could input `-normalize sex 0 age 45 ...` (we may or not want to include that)
- The names of the parameters may vary
- For the normalization, we need the mean of each parameter, the coefficients of the multilinear regression for each combination of parameters and simple linear regression

**Comment by jcohenadad** [comment]
> * if the user wants normalization for 1 subject, they could input `-normalize sex 0 age 45 ...` (we may or not want to include that)

I'm not sure I understand this suggestion. Are you suggesting that the user would have the possibility to input one value after each field, in order to bypass the TSV file?  If this is what you suggested, I like the idea.

> * The names of the parameters may vary

What do you mean by that? Are you suggesting that a parameter could be written in different ways? (eg: "age" and "Age"). If this is what you suggested, I recommend we only stick with one way of writing the parameters so as not to introduce too much confusion.

> * For the normalization, we need the mean of each parameter, the coefficients of the multilinear regression for each combination of parameters and simple linear regression

Right. So this is something you will calculate based on your project, and then hard-code inside the script. Is that what you had in mind?

**Comment by sandrinebedard** [comment]
> > * if the user wants normalization for 1 subject, they could input `-normalize sex 0 age 45 ...` (we may or not want to include that)
> 
> I'm not sure I understand this suggestion. Are you suggesting that the user would have the possibility to input one value after each field, in order to bypass the TSV file? If this is what you suggested, I like the idea.

Yes this was exactly the idea!

**Comment by sandrinebedard** [comment]
> > * The names of the parameters may vary
> 
> What do you mean by that? Are you suggesting that a parameter could be written in different ways? (eg: "age" and "Age"). If this is what you suggested, I recommend we only stick with one way of writing the parameters so as not to introduce too much confusion.

This is more for when we read `participants.tsv` that the names of the paramter may vary from what we decide, I would also stick to one way of writing it. We could just add a remark in the function to assure that the fields in `participants.tsv` have the same names.

**Comment by sandrinebedard** [comment]
> > * For the normalization, we need the mean of each parameter, the coefficients of the multilinear regression for each combination of parameters and simple linear regression
> 
> Right. So this is something you will calculate based on your project, and then hard-code inside the script. Is that what you had in mind?

yep this is what I had in mind!

**Comment by sandrinebedard** [comment]
## UPDATE:
Intergrating `participants.tsv` in the pipeline wouldn't work for parameters like brain and thalamus volume which require processing steps. (`participants.tsv` doesn't include processed data). 

I propose to only include the option that the user specifies a value for each parameter:

~~~
-normalize sex 0 brain-volume 632731 thalamus-volume 77281
~~~

**Comment by joshuacwnewton** [comment]
> (`participants.tsv` doesn't include processed data).

Where could I find a source for this? (Asking as I don't see any mention of this limitation in the [`participants.tsv`](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file) section of the BIDS docs.)

**Comment by sandrinebedard** [comment]
> > (`participants.tsv` doesn't include processed data).
> 
> Do you have a source for this? (Asking as I don't see any mention of this limitation in the [`participants.tsv`](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file) section of the BIDS docs.)

I'll check for this!
However just within the logic of the processing pipeline, the user that wants to normalize CSA will need to compute the brain volume too in the processing pipeline (it is less likely that the user already has that result and it is in `particpant.tsv`), using `particpants.tsv` would complicate the workflow (need to add it before running `sct_process_segmentation` ...)

**Comment by joshuacwnewton** [comment]
> However just within the logic of the processing pipeline, the user that wants to normalize CSA will need to compute the brain volume too in the processing pipeline (it is less likely that the user already has that result and it is in `particpant.tsv`), using `particpants.tsv` would complicate the workflow (need to add it before running `sct_process_segmentation` ...)

Ahh, good point! 

Just to make sure I understand, then, how are brain volume/thalamus volume typically computed, and how are they typically stored? (e.g. CSV output to `derivatives/` using another non-SCT tool of some kind?)

**Comment by sandrinebedard** [comment]
> Just to make sure I understand, then, how are brain volume/thalamus volume typically computed, and how are they typically stored? (e.g. CSV output to `derivatives/` using another non-SCT tool of some kind?)

you could use software like Freesurfer or FSL for that, not sure what is exactly the output however, could be .csv, .txt files
