### ISSUE TITLE
gray color not displayed in  `https://spinalcordtoolbox.com`

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3487]
### Description
This is the page I get on https://spinalcordtoolbox.com/en/latest/ , the color gray is not there in the TOC on the left:
![image](https://user-images.githubusercontent.com/71230552/127551024-3f46d188-e8c2-44c3-a8c0-7c3185a9371d.png)

**Comment by sandrinebedard** [comment]
when I try the dark mode, there are some other issues: 

![image](https://user-images.githubusercontent.com/71230552/127551729-c9c38bcf-1136-4707-8841-8ff22352c0be.png)

**Comment by joshuacwnewton** [comment]
I have the same logo issue with the dark theme. and I see the same light theme issues. :sweat: 

<details>


![Screenshot from 2021-07-29 18-00-18](https://user-images.githubusercontent.com/16181459/127571359-e6547c87-61ac-44fd-bbc6-00cecc5bd10e.png)
![Screenshot from 2021-07-29 17-59-58](https://user-images.githubusercontent.com/16181459/127571360-c866461f-4686-4a29-a0cc-f9b691e21260.png)

</details>

**Comment by ahill187** [comment]
The logo issue is expected, I forgot we needed to make a dark logo as well; we can open a PR for that. As for the TOC, I'm quite baffled since locally it builds fine for me and also the PR it built fine as well. Is there something different between the tests run for RTD on the PR and the actual build?

**Comment by ahill187** [comment]
Created an issue for the dark logo: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3492

**Comment by joshuacwnewton** [comment]
This issue didn't get linked to the PR before it was merged, so it wasn't auto-closed.
