### ISSUE TITLE
Morphological operation alters integrity of the image due to issues with quantization

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3488]
### Description

When applying operation (eg dilation) via `sct_maths` on an image, the output image is _slightly_ wrong. Example:

![Screen Shot 2021-07-29 at 8 33 20 PM](https://user-images.githubusercontent.com/2482071/127582399-7166522a-5c90-4541-a4e5-407c91b402ea.png)

The input image (in white) shows value of `1.0` and the output image (in red) shows a value of `1.000000118277967`. 

I think this issue is caused by numerical precision issue related to the conversion of dtype when doing the morphological operation (here: dilation).

### Steps to Reproduce

- Get this data: [sub-cardiff03_T2star_crop_wmseg.nii.gz.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6904378/sub-cardiff03_T2star_crop_wmseg.nii.gz.zip)
- Unzip
- Run:
~~~
sct_maths -i sub-cardiff03_T2star_crop_wmseg.nii.gz -erode 1 -o sub-cardiff03_T2star_crop_wmseg_erode.nii.gz
~~~
- Observe that the discrepancies between the input and output data (eg using a NIfTI viewer like FSLeyes)

### More context

The input dataset is encoded as UINT8 and is generated by doing the subtraction between these two images: 
[Archive.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/6904399/Archive.zip) via this command:
~~~
sct_maths -i sub-cardiff03_T2star_seg_crop.nii.gz -sub sub-cardiff03_T2star_gmseg_crop.nii.gz -o sub-cardiff03_T2star_crop_wmseg.nii.gz
~~~
The image `sub-cardiff03_T2star_seg_crop.nii.gz` is output by `sct_deepseg_sc` and is encoded as UINT8 while `sub-cardiff03_T2star_gmseg_crop.nii.gz` is output by `sct_deepseg_gm` and is encoded as INT16. Maybe the issue originates from this discrepancy of encoding type?

**Comment by jcohenadad** [comment]
ahah! indeed a dtype issue. When converting one of the image being subtracted to an UINT8:
~~~
sct_image -i sub-cardiff03_T2star_gmseg_crop.nii.gz -type uint8 -o sub-cardiff03_T2star_gmseg_crop_uint8.nii.gz
sct_maths -i sub-cardiff03_T2star_seg_crop.nii.gz -sub sub-cardiff03_T2star_gmseg_crop_uint8.nii.gz -o sub-cardiff03_T2star_crop_wmseg-uint8.nii.gz
sct_maths -i sub-cardiff03_T2star_crop_wmseg-uint8.nii.gz -erode 1 -o sub-cardiff03_T2star_crop_wmseg-uint8_erode.nii.gz
~~~

The erosion produces an uncorrupted image:

![Screen Shot 2021-07-29 at 8 52 23 PM](https://user-images.githubusercontent.com/2482071/127584345-a22489ee-e5ce-4d77-91bb-5755927a1115.png)

**Comment by joshuacwnewton** [comment]
@jcohenadad This got closed via the gm-challenge commit -- do we want to leave this open for `sct_deepseg_gm`'s datatype issues?

**Comment by jcohenadad** [comment]
> @jcohenadad This got closed via the gm-challenge commit -- do we want to leave this open for `sct_deepseg_gm`'s datatype issues and etc.

ooops! that's a mistake-- i didn't want to close it. I should have written "Hack for issue #blabla" in the commit message instead of "fixes issue #blabla" 😅

**Comment by joshuacwnewton** [comment]
I believe this issue was actually the same issue as https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3232. Meaning, this issue has also been fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3944

<details>

As a sanity check, if I retry the reproduction steps, the eroded image has a value of `1.0` on the voxel `27,42,11`, shown in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3488#issue-956305938.

![image](https://user-images.githubusercontent.com/16181459/212382743-95c35980-2738-456b-a0ca-8942f41f4c5b.png)

And we can see the warning about the header datatype change:

```
Image header specifies datatype 'uint8', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.
Image header specifies datatype 'uint8', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.
```

(As a reminder, in previous SCT versions, int header + float array = scaling issues, as per #3232)

</details>

So, I'm closing this issue as resolved.
