### ISSUE TITLE
White highlight on white text in TOC of Read the Docs

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3494]
### Description

When passing the cursor over the TOC in Read the Docs, it highlights the content in white, but it's also written in white, so it is unreadable:

https://user-images.githubusercontent.com/71230552/127901518-1b236d53-cb7b-4070-af8a-55dd84164b3d.mp4

**Comment by ahill187** [comment]
Oh yes! I did update that but I'm guessing the CSS I added is being ignored. I'll take a look 😃
