### ISSUE TITLE
Add tutorial for PMJ-based CSA in RTD

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3496]
## Description
Now that the PMJ-based method used to compute CSA in `sct_process_segmentation` is completed (#3478), we can add a tutorial for it.

## Suggestion
As described in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3478#discussion_r679311470, 

We can:
* Add a new page for [4. Computing shape metrics for PAM50-registered data](https://spinalcordtoolbox.com/en/latest/user_section/tutorials/shape-metric-computation.html) "4.5 CSA (Region based on distance from PMJ)"
* Explain rationale for the method
* `sct_detect_pmj`
* Explain `sct_process_segmentation` with flags `-pmj`, `-pmj-distance`, `-pmj-extent`

**Comment by joshuacwnewton** [comment]
Ah! This was fixed by #3542, but the issue never got linked in GitHub's interface. Closing. :tada:
