### ISSUE TITLE
Error is thrown for WSL during matplotlib GUI check, but isn't caught by try/except

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3501]
Currently, in `sct_check_dependencies`, we try to catch exceptions raised when opening a plot with matplotlib:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65c0b8be3b1be19fbb901be817a198f08a23c8c7/spinalcordtoolbox/scripts/sct_check_dependencies.py#L322-L335

By catching exceptions this way, we can simply print `FAIL` rather than erroring out (that way the installer will successfully conclude without an "Installation failed!" message).

However, a user on the forum reported this installation failure:

```
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened with matplotlib.......qt.qpa.screen: QXcbConnection: Could not connect to display 127.0.0.1:0.0
Could not connect to any X display.

Installation validation Failed!


Installation failed!

Please copy the output of this Terminal (starting with the command install_sct) and upload it as a .txt attachment in a new topic on SCT's forum:

--> http://forum.spinalcordmri.org/c/sct
```

Questions:

* Why wasn't the error caught by our try/except?
* Why is this error being thrown in the first place? (Especially given the changes in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3420/.)

**Comment by kousu** [comment]
> Why wasn't the error caught by our try/except?

Weird! Maybe it's not actually raising an exception. That error is probably deep in some C++ code, printing directly to stderr, and python is unaware of it.

> Especially given the changes in ..

This is the weirdest thing to me about this. My understanding was https://matplotlib.org/stable/tutorials/introductory/usage.html#selecting-a-backend 

> If no backend is explicitly set, Matplotlib automatically detects a usable backend based on what is available on your system and on whether a GUI event loop is already running. On Linux, if the environment variable DISPLAY is unset, the "event loop" is identified as "headless", which causes a fallback to a noninteractive backend (agg); in all other cases, an interactive backend is preferred (usually, at least tkagg will be available).

WSL2 is a franken-windows-linux hybrid; is it possible that *matplotlib* itself has a bug in this case?

If so, we should be able to identify it lile this:

```
$ python -c 'import matplotlib; print(matplotlib.get_backend())'
Qt5Agg
$ MPLBACKEND=agg python -c 'import matplotlib; print(matplotlib.get_backend())'
agg
$ MPLBACKEND=qt5agg python -c 'import matplotlib; print(matplotlib.get_backend())'
Qt5Agg
$ MPLBACKEND=cocoa python -c 'import matplotlib; print(matplotlib.get_backend())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/matplotlib/__init__.py", line 1095, in <module>
    rcParams['backend'] = os.environ.get('MPLBACKEND')
  File "/usr/lib/python3.9/site-packages/matplotlib/__init__.py", line 597, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key backend: 'cocoa' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

So, on WSL2 I wonder 

a. what it is defaulting to
b. what the valid options it thinks it has are

**Comment by kousu** [comment]
My other theory is that WSL2 is setting `DISPLAY` when it should not be setting DISPLAY. This is pretty subtle, but I notice it says "127.0.0.1:0.0". The *default* display is always called ":0.0" (which is..not a TCP port, though it looks like it wants to be), so if that's not the string its using I wonder if maybe WSL2 has gone and tried to helpfully predict what its users want. Except it doesn't actually bundle an X server so doing that would be broken.

**Comment by joshuacwnewton** [comment]
I ran into this again while testing the various WSL-related issues, but here's the catch: I ran into it on WSL1, _not_ WSL2!

Will dig deeper tomorrow. :)
