### ISSUE TITLE
How to get an URL to RTD without the "en/latest/" fields?

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3516]
Very often we share RTD's URL (in forums, in grants, in papers, etc.). By default, the fields "en/latest/" are added, which takes unecessary space (because we only have one language, and because we do want to point to the latest by default).

Is there a way to prevent having these fields in the URL, so they can be shortened?

Also relevant for https://ivadomed.org project

**Comment by joshuacwnewton** [comment]
The ["single version"](https://docs.readthedocs.io/en/latest/single_version.html) documentation option might be worth considering.

> By default, all documentation served by Read the Docs has a root of `/<language>/<version>/`. But, if you enable the “Single Version” option for a project, its documentation will instead be served at `/`.

I can start by enabling this in our RTD admin panel, and if we find that there are unintended side effects, we can switch back. I think it should be safe to change, though, because they offer backwards compatibility:

> Documentation at `/<language>/<default_version>/` will still be served for backwards compatibility reasons.

**Comment by joshuacwnewton** [comment]
I've enabled the following setting on [this page](https://readthedocs.org/dashboard/spinalcordtoolbox/advanced/):

![Screenshot from 2021-09-09 10-18-37](https://user-images.githubusercontent.com/16181459/132703132-789500da-58dd-411f-90e9-d05c8ef6d436.png)

As expected, the "version dropdown" changed from this:

![Screenshot from 2021-09-09 10-20-19](https://user-images.githubusercontent.com/16181459/132703660-8d5d8635-b0d5-4c7a-9e16-71c9c8774520.png)

To this:

![Screenshot from 2021-09-09 10-24-36](https://user-images.githubusercontent.com/16181459/132704139-b9b36c06-9865-4e74-bf0a-cb5510a2010e.png)

And the URL now excludes the `/en/latest/` bit:

![Screenshot from 2021-09-09 10-25-32](https://user-images.githubusercontent.com/16181459/132704258-ac399603-e6c9-4d56-b1f4-e0df6ef6d93a.png)

**Comment by joshuacwnewton** [comment]
I think in an ideal world, it would be beneficial to show the docs for multiple versions of SCT (to support users who are still on older versions of SCT, just in case something changes between versions). 

But, practically speaking, I'm not sure these older docs would be viewed by our users anyway. :thinking:

**Comment by kousu** [comment]
Even with multiple versions enabled you don't need to write the URL down like that. Clicking https://ivadomed.org automatically redirects you to /fr/latest or /en/latest depending on your system locale. You can use https://spinalcordtoolbox.org and https://ivadomed.org and https://shimming-toolbox.org as the official citations and leave RTD to handle actually getting people where they need to go.

**Comment by joshuacwnewton** [comment]
> Even with multiple versions enabled you don't need to write the URL down like that. Clicking https://ivadomed.org automatically redirects you to /fr/latest or /en/latest depending on your system locale.

That only works for the main page, sadly. https://ivadomed.org/ indeed redirects to https://ivadomed.org/en/latest/, but https://ivadomed.org/installation.html leads to a 404, rather than https://ivadomed.org/en/latest/installation.html 

(As an aside, ivadomed [doesn't have a `/fr/` version](https://ivadomed.org/fr/latest/), does it? AFAIK the language tags are for language translations, rather than system locales.)

**Comment by jcohenadad** [comment]
with this change, i am just afraid of the multiple URLs that we dispatched in the nature (SCT forum, emails, etc.). I guess there is no way to get the best of both world? (ie enable removing en/latest but keep retrocompat)?

**Comment by joshuacwnewton** [comment]
> with this change, i am just afraid of the multiple URLs that we dispatched in the nature (SCT forum, emails, etc.). I guess there is no way to get the best of both world? (ie enable removing en/latest but keep retrocompat)?

TBH, when I enabled this change, I was under the impression that backwards compatibility would be preserved... 

> Documentation at `/<language>/<default_version>/` will still be served for backwards compatibility reasons. ([source](https://docs.readthedocs.io/en/latest/single_version.html))

If the old links don't work, then I agree that this change might be worth reverting.

**Comment by jcohenadad** [comment]
> If RTD's documentation is incorrect, and the old links won't work, then I agree that we should possibly undo this setting.

looks like it's broken, right?

![image](https://user-images.githubusercontent.com/2482071/133490964-c84102c7-b3b3-4437-bdb9-c7e6bf0a327a.png)

**Comment by joshuacwnewton** [comment]
Aha! Setting up redirects allow the old `/en/latest/` links to work. (e.g. https://spinalcordtoolbox.com/en/latest/overview/studies.html)

Notably, though, RTD's "redirect page" user interface comes out looking a bit funky:

![Screenshot from 2021-09-15 16-19-29](https://user-images.githubusercontent.com/16181459/133503848-12225e6b-6140-4814-9ead-4a01f1b89def.png)

![Screenshot from 2021-09-15 16-15-28](https://user-images.githubusercontent.com/16181459/133503410-200dc709-169b-4493-883f-70d6a4e88387.png)

It's a bit unintuitive that you have to set up the `/en/latest` links to redirect to themselves! But, without setting this, the links will 404. :P

**Comment by joshuacwnewton** [comment]
I think we can close this issue, as now both URL formats (`/en/latest/` and `/`) point to the shorter URL.

**Comment by jcohenadad** [comment]
amazing-- thank you for finding this perfect solution!
