### ISSUE TITLE
Remove any mention of the Docker SCT image

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3519]
to avoid this: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3518#issuecomment-919503596

**Comment by alexfoias** [comment]
I changed the readme on the docker-hub https://hub.docker.com/r/neuropoly/sct

**Comment by jcohenadad** [comment]
information has no "s"-- also i would be more specific-- eg: 

This docker repository is no longer maintained.
Please visit SCT's documentation for installation options. 

and redirect to the installation page directly

**Comment by alexfoias** [comment]
Fixed

**Comment by joshuacwnewton** [comment]
I've also archived the [`sct_docker`](https://github.com/spinalcordtoolbox/sct_docker) repository and added a similar warning to the README. 

I think this can be closed, now. :slightly_smiling_face:
