### ISSUE TITLE
Wrong visualization of vertebral levels on the QC

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3529]
### Description

The generated QC report of vertebral labeling, when using a discfile, is wrong (notice C6-C7 which are fused, and the color of the text does not match the color of the levels):
![image](https://user-images.githubusercontent.com/2482071/135945432-10654090-114e-4be9-bf67-cb19aac4bf0b.png)

I know the problem comes from the QC report and not the output file itself, because the labeled segmentation on FSLeyes looks good:
![Screen Shot 2021-10-04 at 9 14 20 PM](https://user-images.githubusercontent.com/2482071/135945416-444e1d33-5a54-443a-ba35-9de611681a1c.png)

### Steps to Reproduce

0. Install SCT 666237aeb31246ff163905c7f3cf6cbe8d696e44

1. Download: [Archive.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/7282118/Archive.zip)

2. Run:
   ~~~
   sct_label_vertebrae -i sag_cervical.nii.gz -s sag_cervical_seg.nii.gz -c t2 -discfile labels_disc.nii.gz -qc qc
   ~~~

### Possible cause

I suspect the problem is caused by the labeling not starting by level 1 (but I could be wrong...)

Related to https://forum.spinalcordmri.org/t/a-few-questions-regarding-the-use-of-sct-for-quantitative-analysis-of-spinal-cord-mri/749/4

**Comment by sandrinebedard** [comment]
> ### Possible cause
> I suspect the problem is caused by the labeling not starting by level 1 (but I could be wrong...)

In the UK- Biobank project, my manual disc labels also started at 2 and I never had this problem, and I also ran:

~~~
sct_label_vertebrae -i ${file}.nii.gz -s ${file_seg}.nii.gz -discfile ${FILELABEL}.nii.gz -c t1
~~~ 
![image](https://user-images.githubusercontent.com/71230552/136042804-f6079df7-2569-4007-8fb9-13e9bf57ec05.png)

I can dig a bit!

**Comment by sandrinebedard** [comment]
But when adding the lablel 1, it works:

![image](https://user-images.githubusercontent.com/71230552/136052824-e50b86c9-2f34-40c3-9fd0-d97385ca37e1.png)

**Comment by jcohenadad** [comment]
Thanks for digging @sandrinebedard ! 🙏
