### ISSUE TITLE
Remove `flirtsch/` after link has been changed in NeuroImage paper

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3559]
This is a follow-up to https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3461#discussion_r672328846. @alexfoias has sent a message to the publishers:

> We have migrated the content from link 1 https://github.com/neuropoly/spinalcordtoolbox/blob/master/flirtsch/schedule_TxTy.sch to the new location https://github.com/neuropoly/neuroimage-fsl-flirt-schedule-files.
> 
> Would it be possible to change the link in the article ?

Once the link is changed, we will no longer need to store the `flirtsch/` schedule files in the SCT repo.

**Comment by jcohenadad** [comment]
> Once the link is changed, we will no longer need to store the flirtsch/ schedule files in the SCT repo.

the publisher won't change the link (too late). However it's fine to move it somewhere else. In case ppl click on the link and find there is a problem, they will hopefully contact us. I think there is more pros than cons in removing this folder

**Comment by joshuacwnewton** [comment]
> However it's fine to move it somewhere else. In case ppl click on the link and find there is a problem, they will hopefully contact us. I think there is more pros than cons in removing this folder

I'm glad to hear this. I'll add this change to #3461. :)
