### ISSUE TITLE
Argparse's default formatters are not sufficient for our formatting needs

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3562]
Before our switch to Python 3.7, SCT had copy-pasted some methods from argparse:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/be7057cbe57270e20b2e0185a00a63e83b13be38/spinalcordtoolbox/utils/shell.py#L215-L252

These copy-pasted methods broke with Python 3.7, because they used the deprecated `_textwrap` (#2782). Because of the comments (e.g. `# this is the RawTextHelpFormatter._fill_text`), I assumed these methods had been copied and pasted as-is, so I switched to inheriting directly from `RawTextHelpFormatter`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/081078d85c852afede913064ef7f4d9e45623f46/spinalcordtoolbox/utils/shell.py#L199

However, I now realize that these methods _weren't_ originally copied as-is, and so my change doesn't function exactly the same: we now no longer have nice text wrapping (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3561#issuecomment-958584367). 

This problem is described further in [this Python stdlib issue](https://bugs.python.org/issue12806):

> When using argparse I frequently run into situations where my helper text is a mix of prose and bullets or options. I need the RawTextFormatter for the bullets, and I need the default formatter for the prose (so the line wraps intelligently).

So, it looks like we will have to go back to modifying the default formatters (rather than simply inheriting from them).

**Comment by joshuacwnewton** [comment]
Alternatively, this comment was recently posted on that stdlib issue:

> For those looking for a solution now, see https://pypi.org/project/argparse-formatter/

This looks nice. It's also been submitted in a (stalled) [stdlib PR](https://github.com/python/cpython/pull/22129) -- it's basically just adding more default formatters to the existing default set of formatters.

> The FlexiFormatter
> 
> [...] A rich formatter that has been long proposed for inclusion in Python.
> 
> This module provides that FlexiFormatter class, with some modifications. This formatter preserves line feeds and indentation, and understands bullet lists.
> 
> FlexiFormatter has been submitted for inclusion in Python3.9 - PR22129. It would be good for this formatter to be merged - it eliminates the API-migration risk.

I'd be open to trying out this little utility as opposed to rolling our own, since formatter classes are quite self-contained, and this looks well maintained/tested.

**Comment by joshuacwnewton** [comment]
I tried `FlexiFormatter` out, then compared with the textwrapping we had previously in SCT v5.4:

https://www.diffchecker.com/E7KSsIXx

It's _close_, but `FlexiFormatter` treats newlines _slightly differently_ -- it will only insert a newline if it starts an entirely new paragraph (with a blank line inbetween). So, unfortunately, something like:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7fd2ea718751dd858840c3823c0830a910d9777c/spinalcordtoolbox/scripts/sct_register_to_template.py#L155-L158

Will show up like this:

```
  -l <file>             One or two labels (preferred) located at the center of the spinal cord, on
                        the mid-vertebral slice. Example: anat_labels.nii.gz For more information
                        about label creation, please see: https://www.icloud.com/keynote/0th8lcatyVP
                        kM_W14zpjynr5g#SCT%5FCourse%5F20200121 (p47)
```

Rather than this (which is what we had before):

```
  -l <file>             One or two labels (preferred) located at the center of the spinal cord, on
                        the mid-vertebral slice. Example: anat_labels.nii.gz
                        For more information about label creation, please see: https://www.icloud.co
                        m/keynote/0th8lcatyVPkM_W14zpjynr5g#SCT%5FCourse%5F20200121 (p47)
```

To avoid having to rework newlines across our documentation, I think it might be better to just roll our own formatter like we were doing before.

**Comment by davesteele** [comment]
The rework is just adding another newline before the new paragraph.

**Comment by joshuacwnewton** [comment]
> The rework is just adding another newline before the new paragraph.

That's true! But, I believe making that change would add an extra blank line between our paragraphs within arguments, e.g.:

<details>

```
  -l <file>             One or two labels (preferred) located at the center of
                        the spinal cord, on the mid-vertebral slice. Example:
                        anat_labels.nii.gz 

                        For more information about label creation, please see: 
                        https://www.icloud.com/keynote/0th8lcatyVPkM_W14zp
                        jynr5g#SCT%5FCourse%5F20200121 (p47)
  -ldisc <file>         File containing disc labels. Labels can be located
                        either at the posterior edge of the intervertebral
                        discs, or at the orthogonal projection of each disc onto
                        the spinal cord (e.g.: the file
                        'xxx_seg_labeled_discs.nii.gz' output by
                        sct_label_vertebrae). 

                        If you are using more than 2 labels, all discs covering the 
                        region of interest should be provided. E.g., if you are interested 
                        in levels C2 to C7, then you should provide disc labels 2,3,4,5,6,7. 
                        For more information about label creation, please refer to h
                        ttps://www.icloud.com/keynote/0th8lcatyVPkM_W14zpjynr5g#
                        SCT%5FCourse%5F20200121 (p47)
  -lspinal <file>       Labels located in the center of the spinal cord, at the
                        superior-inferior level corresponding to the mid-point
                        of the spinal level. Example: anat_labels.nii.gz 

                        Each label is a single voxel, which value corresponds to 
                        the spinal level (e.g.: 2 for spinal level 2). If you are
                        using more than 2 labels, all spinal levels covering the
                        region of interest should be provided (e.g., if you are
                        interested in levels C2 to C7, then you should provide
                        spinal level labels 2,3,4,5,6,7).
```
</details>

It's a nitpick (and personal preference, of course), but I find it a bit jarring to see full blank lines in the middle of an argument's description, particularly when there are no blank lines _between_ arguments. It groups text across arguments, which I find a bit harder to parse. 

Instead, I would expect either no blank lines at all (which is what we had before):

<details>

```
  -l <file>             One or two labels (preferred) located at the center of
                        the spinal cord, on the mid-vertebral slice. Example:
                        anat_labels.nii.gz 
                        For more information about label creation, please see: 
                        https://www.icloud.com/keynote/0th8lcatyVPkM_W14zp
                        jynr5g#SCT%5FCourse%5F20200121 (p47)
  -ldisc <file>         File containing disc labels. Labels can be located
                        either at the posterior edge of the intervertebral
                        discs, or at the orthogonal projection of each disc onto
                        the spinal cord (e.g.: the file
                        'xxx_seg_labeled_discs.nii.gz' output by
                        sct_label_vertebrae). 
                        If you are using more than 2 labels, all discs covering the 
                        region of interest should be provided. E.g., if you are interested 
                        in levels C2 to C7, then you should provide disc labels 2,3,4,5,6,7. 
                        For more information about label creation, please refer to h
                        ttps://www.icloud.com/keynote/0th8lcatyVPkM_W14zpjynr5g#
                        SCT%5FCourse%5F20200121 (p47)
  -lspinal <file>       Labels located in the center of the spinal cord, at the
                        superior-inferior level corresponding to the mid-point
                        of the spinal level. Example: anat_labels.nii.gz 
                        Each label is a single voxel, which value corresponds to 
                        the spinal level (e.g.: 2 for spinal level 2). If you are
                        using more than 2 labels, all spinal levels covering the
                        region of interest should be provided (e.g., if you are
                        interested in levels C2 to C7, then you should provide
                        spinal level labels 2,3,4,5,6,7).
```

</details>

Or additional line-breaks that separate the arguments, too:

<details>

```
  -l <file>             One or two labels (preferred) located at the center of
                        the spinal cord, on the mid-vertebral slice. Example:
                        anat_labels.nii.gz 

                        For more information about label creation, please see: 
                        https://www.icloud.com/keynote/0th8lcatyVPkM_W14zp
                        jynr5g#SCT%5FCourse%5F20200121 (p47)

  -ldisc <file>         File containing disc labels. Labels can be located
                        either at the posterior edge of the intervertebral
                        discs, or at the orthogonal projection of each disc onto
                        the spinal cord (e.g.: the file
                        'xxx_seg_labeled_discs.nii.gz' output by
                        sct_label_vertebrae). 

                        If you are using more than 2 labels, all discs covering the 
                        region of interest should be provided. E.g., if you are interested 
                        in levels C2 to C7, then you should provide disc labels 2,3,4,5,6,7. 
                        For more information about label creation, please refer to h
                        ttps://www.icloud.com/keynote/0th8lcatyVPkM_W14zpjynr5g#
                        SCT%5FCourse%5F20200121 (p47)

  -lspinal <file>       Labels located in the center of the spinal cord, at the
                        superior-inferior level corresponding to the mid-point
                        of the spinal level. Example: anat_labels.nii.gz 

                        Each label is a single voxel, which value corresponds to 
                        the spinal level (e.g.: 2 for spinal level 2). If you are
                        using more than 2 labels, all spinal levels covering the
                        region of interest should be provided (e.g., if you are
                        interested in levels C2 to C7, then you should provide
                        spinal level labels 2,3,4,5,6,7).
```
</details>

For the latter format, I suppose we could add newlines at the end of every argument description, too...

But, FWIW, we also have >45+ CLI scripts in our package, and combing through all of the descriptions to find instances of this and then tweak newlines felt like a more tedious and time consuming solution than just overriding the `_fill_text` and `_split_lines` methods ourselves to get the behavior we expect. 

(I imagine it's probably not a big deal either way, though...)

**Comment by davesteele** [comment]
Ok. What you are looking for is probably a [two-line change](https://github.com/davesteele/argparse_formatter/blob/main/argparse_formatter/paragraph_formatter.py#L19-L20).
