### ISSUE TITLE
WSL builds failing with `OSError: [Errno 40] Too many levels of symbolic links` for ncurses-6.3

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3564]
I've hit "Re-run jobs" a few times and no dice: https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/4087550544?check_suite_focus=true#step:6:340

I'll try to dig in deeper as soon as I can.

**Comment by joshuacwnewton** [comment]
ncurses+miniconda might be relevant here, see also: https://github.com/rstudio/reticulate/issues/982

**Comment by joshuacwnewton** [comment]
[Diffing the logs](https://www.diffchecker.com/utCMgTTf) against the last working CI run, I see some key differences:

```diff
# OS Type changed
- fv-az30-432 
+ fv-az71-870

# ncurses-6.3 now gets installed via conda instead of ncurses-6.2
- ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
+ ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_0
```

Since this change is pretty recent (<24hr), this is probably an upstream breaking change of some kind. Still digging.

**Comment by joshuacwnewton** [comment]
Possible solution: https://github.com/conda/conda/issues/10333#issuecomment-919739093

> I changed the installation path from /mnt/d/... to ~/..., and it works now

Since our current install path path is `/mnt/d/a/spinalcordtoolbox/spinalcordtoolbox/`, this looks possibly applicable.

**Comment by kousu** [comment]
We don't even _use_ curses, why is it there?

It's not installed by default by conda:

```
(base) [kousu@requiem ~]$ conda create -n whatever 
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/whatever



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate whatever
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [kousu@requiem ~]$ conda list whatever
# packages in environment at /home/kousu/src/neuropoly/spinalcordtoolbox/python:
#
# Name                    Version                   Build  Channel
(base) [kousu@requiem ~]$ conda activate whatever
(whatever) [kousu@requiem ~]$ conda list
# packages in environment at /home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/whatever:
#
# Name                    Version                   Build  Channel
```

...but it is if you ask for python

```
(base) [kousu@requiem ~]$ conda create -n whatever2 python=3.7 
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/whatever2

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-4.5          |            1_gnu          22 KB
    ca-certificates-2021.10.26 |       h06a4308_2         115 KB
    certifi-2021.10.8          |   py37h06a4308_0         151 KB
    ld_impl_linux-64-2.35.1    |       h7274673_9         586 KB
    libgcc-ng-9.3.0            |      h5101ec6_17         4.8 MB
    libgomp-9.3.0              |      h5101ec6_17         311 KB
    libstdcxx-ng-9.3.0         |      hd4cf53a_17         3.1 MB
    ncurses-6.3                |       h7f8727e_0         789 KB
    openssl-1.1.1l             |       h7f8727e_0         2.5 MB
    python-3.7.11              |       h12debd9_0        45.3 MB
    setuptools-58.0.4          |   py37h06a4308_0         775 KB
    sqlite-3.36.0              |       hc218d9a_0         990 KB
    tk-8.6.11                  |       h1ccaba5_0         3.0 MB
    wheel-0.37.0               |     pyhd3eb1b0_1          33 KB
    ------------------------------------------------------------
                                           Total:        62.4 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.10.26-h06a4308_2
  certifi            pkgs/main/linux-64::certifi-2021.10.8-py37h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_0
  openssl            pkgs/main/linux-64::openssl-1.1.1l-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.0.1-py37h06a4308_0
  python             pkgs/main/linux-64::python-3.7.11-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-58.0.4-py37h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.36.0-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.11-h1ccaba5_0
  wheel              pkgs/main/noarch::wheel-0.37.0-pyhd3eb1b0_1
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
libstdcxx-ng-9.3.0   | 3.1 MB    | ################################################################################################################################################### | 100% 
_openmp_mutex-4.5    | 22 KB     | ################################################################################################################################################### | 100% 
wheel-0.37.0         | 33 KB     | ################################################################################################################################################### | 100% 
libgomp-9.3.0        | 311 KB    | ################################################################################################################################################### | 100% 
setuptools-58.0.4    | 775 KB    | ################################################################################################################################################### | 100% 
certifi-2021.10.8    | 151 KB    | ################################################################################################################################################### | 100% 
tk-8.6.11            | 3.0 MB    | ################################################################################################################################################### | 100% 
sqlite-3.36.0        | 990 KB    | ################################################################################################################################################### | 100% 
ncurses-6.3          | 789 KB    | ################################################################################################################################################### | 100% 
ld_impl_linux-64-2.3 | 586 KB    | ################################################################################################################################################### | 100% 
ca-certificates-2021 | 115 KB    | ################################################################################################################################################### | 100% 
python-3.7.11        | 45.3 MB   | ################################################################################################################################################### | 100% 
libgcc-ng-9.3.0      | 4.8 MB    | ################################################################################################################################################### | 100% 
openssl-1.1.1l       | 2.5 MB    | ################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate whatever2
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

probably because curses is in the Batteries Included stdlib: https://docs.python.org/3/library/curses.html#module-curses

**Comment by kousu** [comment]
Looking for a workaround:

You can _remove_ it after the fact -- breaking anything that tries to use it, but not python in general:

```
(whatever2) [kousu@requiem ~]$ conda uninstall --force ncurses


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/kousu/src/neuropoly/spinalcordtoolbox/python/envs/whatever2

  removed specs:
    - ncurses


The following packages will be REMOVED:

  ncurses-6.3-h7f8727e_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Can you... `conda env create -n something python=3.7 -ncurses`? no... doesn't seem like it.

**Comment by kousu** [comment]
> Possible solution: [conda/conda#10333 (comment)](https://github.com/conda/conda/issues/10333#issuecomment-919739093)
> 
> > I changed the installation path from /mnt/d/... to ~/..., and it works now
> 
> Since our current install path path is `/mnt/d/a/spinalcordtoolbox/spinalcordtoolbox/`, this looks possibly applicable.

I'm sure this will fix it

**Comment by joshuacwnewton** [comment]
I'm having trouble figuring out how to configure [Vampire/setup-wsl](https://github.com/marketplace/actions/setup-wsl) to do what we want here. I'm having trouble figuring out...

* How the mount point is set 
* How users are created
* How the working directory is set

(I know all of this relatively well as far as usual GH runners go, but WSL-based runners are a little more complicated. The inner workings are a bit opaque to me? I'm sorta just... fumbling around here, aha. )

I tried setting the [`wsl-shell-user`](https://github.com/Vampire/setup-wsl#wsl-shell-user) here, thinking it might give us a nice user directory, but all it did was make the entire Dependency installation step [stall out](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1418930945). :confused:

**Comment by joshuacwnewton** [comment]
I've been testing both WSL1 and WSL2 tonight to try to pinpoint the various WSL-related issues that have arisen over the past week or so.

In testing WSL2 on my local machine, I ran into this bug. Yet, I didn't run into it on WSL1. That might suggest that our WSL runners are on WSL2, which might explain why they didn't catch #3571.

Either way, I want to dig a little deeper into our WSL runners to make sure they line up with the versions of WSL that we claim to support. Ideally, we could come out of the other end of this being able to support all combinations of `WSL{1,2}`+`Ubuntu{18.04, 20.04}`.

**Comment by joshuacwnewton** [comment]
Re: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3564#issuecomment-960076920, switching the working directory indeed fixed this issue. We can leave `ncurses` alone. :)

**Comment by gitfourteen** [comment]
> Re: [#3564 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3564#issuecomment-960076920), switching the working directory indeed fixed this issue. We can leave `ncurses` alone. :)

this does not address the bug.
[(https://github.com/rstudio/reticulate/issues/982#issuecomment-2351539339)]

**Comment by gitfourteen** [comment]
> Re: [#3564 (comment)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3564#issuecomment-960076920), switching the working directory indeed fixed this issue. We can leave `ncurses` alone. :)

Change back miniconda3 installation directory to '/home/<user>/minicond3' is not a satisfied answer for me.
facts and concern:
1. when installing anaconda3 in WSL 2 Ubuntu 18.04 or 20.04, there is no such OSError.
2. we choose to install under a specified directory, eg., `/mnt/d/miniconda3`, because we would rather not eat up `c drive` capacity: `C:\Users\<USERNAME>\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_[CODE]\LocalState\rootfs\`, where WSL locates.

Until today, this bug of Miniconda still exits when one creates a new environment.
`OSError: [Errno 40] Too many levels of symbolic links: '/mnt/d/anaconda/pkgs/ncurses-6.4-h6a678d5_0/share/terminfo/n/ncr260vt300wpp'`


Then run `conda doctor`, get this:

"""Environment Health Report for: /mnt/d/miniconda3

Altered Files:

✅ There are no packages with altered files.

Environment listed in environments.txt file: ✅

Missing Files:

ncurses-6.4-h6a678d5_0: 2"""
