### ISSUE TITLE
Error installing SCT on WSL2 - Miniconda related

### ISSUE THREAD

**Issue by sercharpak** [spinalcordtoolbox/spinalcordtoolbox#3571]
### Description

When running the `./install_sct` script on WSL I ran into the systematic issue of conda failing to get anything.

At the end I pinpointed the issue to this [issue](https://github.com/conda/conda/issues/9948) from conda itself.
The current workaround I adopted (one suggested in https://github.com/conda/conda/issues/9948#issuecomment-655087415) is to download an old version of `miniconda` and then run the `conda update` command. This worked for me.

### Steps to Reproduce the error

0. Install SCT <5.4>
```./install_sct```

**Installation interrupted:** 

An HTTP error occurred when trying to retrieve this URL. HTTP errors are often intermittent, and a simple retry will get you on your way. If your current network has https://www.anaconda.com blocked, please file a support request with your network engineering team. 'https://repo.anaconda.com/pkgs/main/linux-64'

### Steps to fix the error

Modified the `install_sct ` script in the **Dowload Miniconda section** (lines 583-600 approx).
Replaced :
` download "$TMP_DIR/"miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh`
by this line:
`download "$TMP_DIR/"miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh`

And, after the installation (of miniconda) I added this line:
`python/bin/conda update conda`

Here's my install_sct_mod [script](https://gist.github.com/sercharpak/bd3c329671c2deecdee8d6e3489f6019)

**Comment by joshuacwnewton** [comment]
Thank you so much for taking the time to investigate and share your findings.

Coincidentally, our lab has also been investigating this very issue within the last week. We had tried some of the workarounds listed in https://github.com/conda/conda/issues/9948 (linked above), but I don't think we've tried the specific workaround you've proposed, so I think this gives us a new lead! :slightly_smiling_face: 

> cc: @kousu. (The relevant branches here are [`ng/pin-python-to-test-wsl`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/ng/pin-python-to-test-wsl) and [`jn/fix-wsl-install-maxime`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/jn/fix-wsl-install-maxime).)

**Comment by joshuacwnewton** [comment]
I had a chance to try out your proposed fix on ([`jn/3571-wsl-install-older-conda`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/tree/jn/3571-wsl-install-older-conda)). On WSL2, it fixed the error perfectly. 

I can also confirm that a separate fix from https://github.com/conda/conda/issues/9948 (in [`jn/fix-wsl-install-maxime`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/jn/fix-wsl-install-maxime)) also fixes the issue on WSL2. 

On WSL1, however, both fixes lead to a second error: 

```
Installing Python dependencies...


Using requirements.txt (git installation)

Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93a9f1b50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/colored/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93a9f1f50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/colored/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa042d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/colored/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa04610>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/colored/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa04950>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/colored/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa0e0d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa0e410>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa0e750>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa04490>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cpu/torch_stable.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fd93aa04790>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cpu/torch_stable.html
ERROR: Could not find a version that satisfies the requirement colored
ERROR: No matching distribution found for colored

Failed running pip install: 1


Installation failed!

Please copy the output of this Terminal (starting with the command install_sct) and upload it as a .txt attachment in a new topic on SCT's forum:

--> http://forum.spinalcordmri.org/c/sct
```

Notably, we ran into this exact same error [internally](https://neuropoly.slack.com/archives/C0135PQ0XGT/p1635988895009100?thread_ts=1635288906.002400&cid=C0135PQ0XGT) when we tried a separate fix from [`jn/fix-wsl-install-maxime`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/commits/jn/fix-wsl-install-maxime). 

Since the investigations in https://github.com/conda/conda/issues/9948#issuecomment-906410470 (and by @kousu) suggest that this is a permission issue, I'm going to try reapplying the `touch` fix from https://github.com/conda/conda/issues/9948#issuecomment-909989810 after the `conda` env is created, but before the `pip` requirements are installed to see if that fixes it.
