### ISSUE TITLE
WSL2 - GUI - FSLeyes

### ISSUE THREAD

**Issue by sercharpak** [spinalcordtoolbox/spinalcordtoolbox#3572]
**Add additional instructions for WSL2 & Fsleyes.**

When updating from WSL1 to WSL2 the GUI management becomes a little bit problematic.

After installing `fsleyes `as recommended (for instance, through _conda-forge_) the following error appears:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 8748 error_code 154 request_code 149 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Found a workaround following this [issue](https://github.com/microsoft/WSL/issues/5535) and setting the shortcut of xlaunch as indicated in this [tutorial](https://www.digitalcitizen.life/shortcut-arguments-parameters-windows).

You could summarize the fix with:

1. Adding: 
```
export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=0
```
to `~/.bashrc`.

2. Source the file:
```
source ~/.bashrc
```

3. Setting up your firewall to accept xlaunch  following this [guide](https://github.com/cascadium/wsl-windows-toolbar-launcher#firewall-rules)

4. When opening xlaunch, select the tick for and un-select the tick for 

a. 
![image](https://user-images.githubusercontent.com/4550752/93567255-a957d780-f98e-11ea-9fac-fe8b0f5c80b2.png)
b. 
![image](https://user-images.githubusercontent.com/4550752/93567290-b5dc3000-f98e-11ea-9726-4c8f5cfe9a78.png)
c.
![image](https://user-images.githubusercontent.com/4550752/93567333-c391b580-f98e-11ea-811d-71f5b2bea0c0.png)

**Comment by joshuacwnewton** [comment]
Thank you so much for digging into this and providing such a detailed set of instructions!

Our WSL-related documentation has mainly focused on WSL1 so far, so I'm grateful that you took the time to troubleshoot the installation of SCT/FSLeyes on WSL2. 

We'll have to see if we can incorporate your recommendations into SCT's installation page. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
We have another WSL GUI related issue open (#3501), and I think both issues might have the same solution, since the steps you've shared overlap with: https://github.com/microsoft/WSL/issues/4793#issuecomment-577232999.
