### ISSUE TITLE
Performance issues on WSL2

### ISSUE THREAD

**Issue by kousu** [spinalcordtoolbox/spinalcordtoolbox#3575]
### Description

Following the [windows instructions](https://spinalcordtoolbox.com/user_section/installation/windows.html) as written on WSL2.

I know the instructions say to use WSL1 but 2 is going to become more and more common.

### Steps to Reproduce

0. Install WSL 2
1. Start WSL 2
2. You will be in `/mnt/c/<something>`
3. Follow the SCT installation:

```
git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox.git sct
cd sct
git checkout X.Y.Z
./install_sct -y
cd ~
source .profile
source .bashrc
```
4. Try running some commands:

```
sct_deepseg_sc -i ... <???>
```

**Expected behavior:**

The command should start running within a couple of seconds.

**Actual behavior:**

It takes over a minute before `sct_deepseg_sc` prints its introductory info. Once it gets going it doesn't seem to be especially slow, though.

Some other symptoms are: `./install_sct` gets stuck for upwards of 10 minutes at the `pip install` step.

**Comment by kousu** [comment]
@gaspardcereza, can you post the exact full `sct_deepseg_sc` command you had the problem with when you have a moment?

**Comment by kousu** [comment]
This fixed it:

```diff
+cd ~
 git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox.git sct
 cd sct 
 git checkout X.Y.Z
 ./install_sct -y
-cd ~
 source .profile
 source .bashrc
```

Since we use `conda` to install a completely isolated environment in the current folder, instead of in more standard places (like `/usr/local/bin/` or `~/.local/bin`), starting any SCT program requires loading a ton of program data into memory from `/mnt/c/` -- from the underlying Windows filesystem -- and it seems that this file system glue layer in WSL2 can be extremely slow.

We should move the `cd ~` instruction in our WSL docs. And we could augment them to explain how people should make sure get their data into WSL by running `cd ~ && explorer .` and copying into the folder it gives (`\\wsl$\home\UserName` (?)) instead of working in the default folder WSL2 boots into. TODO: screenshots)

A problem Gaspard had

**Comment by joshuacwnewton** [comment]
> We should move the cd ~ instruction in our WSL docs.

I came to the same conclusion: 2e75e3e

**Comment by joshuacwnewton** [comment]
Also, I overhauled the WSL docs in #3573 too, so you two may have been following outdated steps (especially given some of the details you're referencing). 

See also: https://spinalcordtoolbox--3573.org.readthedocs.build/user_section/installation/windows.html

**Comment by kousu** [comment]
Okay cool! Well then #3573 will fix this I think!

**Comment by gaspardcereza** [comment]
@kousu I don't know if you still need it but the command I was trying to run is: 

```bash
(base) gaspard@PC-Gaspard:/mnt/c/Users/gaspa/Desktop$ sct_deepseg_sc -i ./test.nii.gz -c t1 -o ./test_seg.nii
``` 
 It took ~1:30min to start the segmentation when `SCT` was installed in the Windows file system, and starts it directly when it is installed on the \\wsl$\ "network".

**Comment by kousu** [comment]
> @kousu I don't know if you still need it but the command I was trying to run is:
> 
> ```shell
> (base) gaspard@PC-Gaspard:/mnt/c/Users/gaspa/Desktop$ sct_deepseg_sc -i ./test.nii.gz -c t1 -o ./test_seg.nii
> ```
> 
> It took ~1:30min to start the segmentation when `SCT` was installed in the Windows file system, and starts it directly when it is installed on the \wsl$\ "network".

Perfect, that's what I wanted. It's really good to have that for the record in case this comes up again :)
