### ISSUE TITLE
`sed_i` polyfill does not work as expected in `install_sct`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3590]
Currently, we use the following polyfill, to make sure `sed -i` (in-place) works across platforms.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c9e4e80128f31755c6c9348e13de90b2364d5aee/install_sct#L330-L338

However, for [a user on the forum](https://forum.spinalcordmri.org/t/installation-failed-in-mac-10-14-6/776), this polyfill doesn't work:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c9e4e80128f31755c6c9348e13de90b2364d5aee/install_sct#L616

Error message:

```
sed: can't read s/^ENABLE_USER_SITE.*$/ENABLE_USER_SITE = False/: No such file or directory
```

**Comment by joshuacwnewton** [comment]
This error suggests that the command being run is the `Darwin` case in the polyfill:

```
sed -i '' "$@" 
```

For macOS's `sed`, this [_should work_](https://code-examples.net/en/q/56e314). But, for Linux's `sed` this will fail:

```console
joshua@tadpole:~/Desktop$ ./sed_i.sh 's/^ENABLE_USER_SITE.*$/ENABLE_USER_SITE = False/' test_file 
sed: can't read s/^ENABLE_USER_SITE.*$/ENABLE_USER_SITE = False/: No such file or directory
```

Seeing as the error messages are identical, this leads me to believe that perhaps this user has the Linux `sed` on their macOS machine. :thinking:

**Comment by joshuacwnewton** [comment]
The article that @kousu referenced when implementing the polyfill gives the following advice:

> My recommendation, for what it is worth, is not to update-in-place with `sed` (which has complex failure modes), but to generate new files and rename them afterwards. In other words: avoid `-i`.


So, perhaps we could replace the internals of the `sed_i` function with commands that do exactly this.

**Comment by kousu** [comment]
I've also learned lately that you can replace sed with perl almost directly in most cases (perl was designed as sort of like a superset of awk + sed + sh). And there's only one perl, unlike there being two seds.

I think perl comes with macOS?

**Comment by kousu** [comment]
Internally write a tmpfile and rename it on success is exactly what `perl -i` and `sed -i` do.

**Comment by kousu** [comment]
Is this somehow a mac M1 issue? Did they change `sed`?

**Comment by joshuacwnewton** [comment]
> Is this somehow a mac M1 issue? Did they change `sed`?

I should have clarified -- the user is on macOS 10.14. (And, I don't believe other 10.14 users have run into this issue?)

**Comment by kousu** [comment]
Maybe...they [`brew install gnu-sed`](https://formulae.brew.sh/formula/gnu-sed)'d? So we're accidentally mixing two dialects?

**Comment by kousu** [comment]
Or yeah, just reimplementing `-i` ourselves in a cross-platform way might be the most reliable....

**Comment by kousu** [comment]
but it also means more code to write and maintain? o.O

**Comment by kousu** [comment]
Also obviously the only reason we need this is because we're not using `pip` properly....

**Comment by kousu** [comment]
I've given the user the patch as a copy-pastable script in https://forum.spinalcordmri.org/t/installation-failed-in-mac-10-14-6/776/3. That way they don't need to wait for sct 5.5.

**Comment by joshuacwnewton** [comment]
> I've given the user the patch as a copy-pastable script in https://forum.spinalcordmri.org/t/installation-failed-in-mac-10-14-6/776/3. That way they don't need to wait for sct 5.5.
> 
> I had to edit the patch to make it copy-pastable, escaping every `$` and `\` and `` ` ``, but I did that in the hopes it would be easily applicable.

What about just applying the fix yourself to `install_sct`, then telling them to run `./install_sct_with_fix`? :yum:
