### ISSUE TITLE
`pip==21.2` is taking many hours to resolve dependencies

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3593]
I encountered this last night when trying to install SCT on my macOS VM, and now I'm seeing the same issue [in our runners](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/1476103218).

[Diffing the install logs](https://www.diffchecker.com/5a3Si3Gn), it looks like `pip` updated from `21.0.1` to `21.2.2` in our install environment. Searching for `21.2`-related issues, I found https://github.com/pypa/pip/issues/10201.

What I'm getting from the very long discussion in that issue is that `pip`'s dependency resolver algorithm got a lot worse from 21.1 -> 21.2, but after a _lot_ of feedback, was improved in `21.3` (https://github.com/pypa/pip/issues/9187#issuecomment-940484928). So, we should make sure we specify, say, `pip!=21.2` to avoid the version of pip containing the poorly-performing algorithm.

**Comment by joshuacwnewton** [comment]
We may also want to consider reviewing our dependencies to make sure that we're not casting too wide of a net with our allowable dependency versions (so that we're not overwhelming `pip` with too many options).

But, that would be a more involved effort, and possibly unnecessary if the issue is specific to this version of pip.

**Comment by kousu** [comment]
Classic `pip`.

**Comment by kousu** [comment]
conda does the same thing, but they've never fixed it :thinking: 
If you specify the 'right' combination of versions, conda is instant. But if there's an ambiguity I've seen it take over 30 minutes to resolve. It actually runs a SAT solver to do it, which is NP-hard.
