### ISSUE TITLE
Provide solutions for registration of lumbar data

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3599]
We should provide a satisfactory solution for every users working with thoraco/lumbar data. Currently, registration to the template is not easy.

Subtasks:
- [ ] https://github.com/spinalcordtoolbox/PAM50/issues/26
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4180

Ref:
- https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/5

**Comment by joshuacwnewton** [comment]
Migrated to https://github.com/neuropoly/idea-projects/issues/12.
