### ISSUE TITLE
update usage to inform user that using more than 2 labels will produce weird results

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3602]
usage says:
~~~
If more than two labels (only with the parameter '-disc') are used, a non-linear registration will be applied to align the each intervertebral disc between the subject and the template, as described in sct_straighten_spinalcord. This the most accurate and preferred method. This feature does not work with the parameter '-ref subject', where only a rigid registration is performed.
~~~

we should add a disclaimer--  something like:
~~~
Due to the non-linear registration in the S-I direction, the warping field will be cropped above the top label and below the bottom label. This will result in a strange-looking registered image that has the same value above the top label and below the bottom label. But if you are not interested in these regions, you do not need to worry about it.
~~~

context:
- https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/5?u=jcohenadad

**Comment by joshuacwnewton** [comment]
I started to add this suggestion to the CLI usage, but I'm noticing that the usage is getting quite long! So, I am reminded of:

* #3095

----

Additionally, the tutorials also cover some of this information. For example, the [How many vertebral labels should I use for registration?](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/how-many-labels-for-registration.html) page says:

> If you plan on using the labeled spinal cord to perform registration, you don’t necessarily have to label every vertebrae. Instead, you can choose to work with a subset of labels:
> 
> 3+ labels
> 
> This is the most accurate method for matching the vertebral levels of the anatomical image to the levels of the template. However, there is a key downside to this approach: Because more than two points must be matched, the level-matching transformation cannot be affine. As a result, the output warping field will be undefined for regions above the top label and below the bottom label.

But, I worry that this page is not in a good place to be easily discoverable by users. I'm thinking that it might be good to move the page inside the template registration tutorial instead. 

(Also, https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3095#issuecomment-958061803 should help with making the tutorials more discoverable.)
