### ISSUE TITLE
Indicate default value for `-brain` argument in `sct_deepseg_sc`

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3607]
![image](https://user-images.githubusercontent.com/2482071/144084469-0b77d3b9-32a7-4590-92c0-d7bbf3482b35.png)

**Comment by joshuacwnewton** [comment]
Looks like `-brain` doesn't have a default value set at all:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/422d91afd1236edfab7b7634112b16a2420a1d47/spinalcordtoolbox/scripts/sct_deepseg_sc.py#L74-L79

Many of the remaining arguments in your arguments do show default values, though. For example:

```
  -kernel {2d,3d}       Choice of kernel shape for the CNN. Segmentation with 3D kernels is slower than
                        with 2D kernels. (default: 2d)
```

**Comment by jcohenadad** [comment]
ah! yes you are right... this is not very intuitive 😅  ... anyways, at some point this function will be deprecated

**Comment by joshuacwnewton** [comment]
> ah! yes you are right... this is not very intuitive sweat_smile

Normally default values are handled by `argparse.DefaultHelpTextFormatter` (it will fetch the default value from the argument, then append it to each description). Since we don't have a single default value here, we could always manually display the default like so:

```python
     help='Indicate if the input image contains brain sections (to speed up segmentation). Only use with ' 
          '"-centerline cnn". (default: 1 for T1/T2 contrasts, 0 for T2*/DWI contrasts)', 
```
