### ISSUE TITLE
Default resampling (`0.6mm`) for `sct_get_centerline` QC report mangles the centerline mask

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3625]
While writing a test for #3560, I noticed that in some slices of the QC report, the centerline was missing. So, I tried the full `t2s.nii.gz` image from `sct_example_data`, and encountered the same behavior:

<details> 

sct_testing_data:

![Screenshot from 2021-12-14 08-21-03](https://user-images.githubusercontent.com/16181459/146006169-f2206691-848c-4baa-a260-490795a38642.png)

sct_example_data:

![Screenshot from 2021-12-14 08-21-47](https://user-images.githubusercontent.com/16181459/146006309-548dab4f-f480-4590-8594-4761ef8b7513.png)

</details>

The actual centerline images are OK -- no discontinuities. So, I traced the QC report code and identified this line to be the problem:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/685ab17ff9bebeb38228d52a55b2507b60b52446/spinalcordtoolbox/reports/slice.py#L60

We can see why when we compare the nonzero coordinates of `img` to `img_r`:

<details> 

![Screenshot from 2021-12-14 08-26-34](https://user-images.githubusercontent.com/16181459/146007115-69fb27a8-bd2a-423e-923b-73017bbf1a9b.png)

</details>

If we skip resampling (via `p_resample=None`), then the centerline is properly displayed:

![Screenshot from 2021-12-14 08-28-45](https://user-images.githubusercontent.com/16181459/146007445-58af5475-a1cd-46c5-a195-4d605c439c0d.png)

However, I'm not sure that skipping resampling here is a valid solution. I get the sense that there are images that might be poorly cropped if not resampled.

**Comment by joshuacwnewton** [comment]
Ah! 

Duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2813.

**Comment by joshuacwnewton** [comment]
Ah, interesting. The issue in #2813 identifies the same problematic line of code, but with two different results:

* For `t2.nii.gz`, the resampling causes doubled centerline pixels.
* For `t2s.nii.gz`, the resampling causes missing centerline pixels.

It depends on the original resolution of the data vs. the resampled resolution, I suppose?

**Comment by jcohenadad** [comment]
> It depends on the original resolution of the data vs. the resampled resolution, I suppose?

yup!

**Comment by joshuacwnewton** [comment]
This issue was fixed by: 

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3626

But the issue wasn't linked.
