### ISSUE TITLE
Do we want to re-introduce `sct_testing`?

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3631]
To verify an installation, do we want to re-introduce the `sct_testing` function? It would basically run these 3 lines of code listed in the [wiki](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Testing%3A-Running-the-test-suite#running-unitfunctional-tests).

**Comment by joshuacwnewton** [comment]
A few days ago, I opened a PR to do exactly this! :wink: 

See: #3605 and #3532.

**Comment by jcohenadad** [comment]
amazing! i guess we can close this then. Thank you @joshuacwnewton !
