### ISSUE TITLE
Vertebrae labeling in subject with strongly curved spine

### ISSUE THREAD

**Issue by mgaubert** [spinalcordtoolbox/spinalcordtoolbox#3635]
Hello,

I wanted to report an issue and ask a question.

For the issue:
using _sct_computre_mtr_, I have an issue with the results when using short (4) NIFTI images for MT0 and MT1. The values I obtained are inconsistent (very small negatives or very big positives) for many slices but not all slices. At the end, when comparing with manual computing of MTR, a lot of voxels have wrong values.
I changed the type of the MT0/MT1 images from short to float and the result is correct, meaning similar to what I got with manual computing of MTR, and this for all slices and voxels.
Maybe is there a reason for this behavior?

For the question:
I have a subject with a strongly curved spine. I try to get the vertebrae labeling using _sct_label_vertebrae_ but the result is never good. I tried to help the program by adding a single point between vertebrae for either 3, 4, 5, 6 or 7, but it is still not sufficient. For example, here is what I obtained (${t2sagC} is a t2 acquired in sagittal) without single point in disc, one label in disk 6 and one label in disk 3:

- for _sct_label_vertebrae -i ${t2sagC}.nii.gz -s ${t2sagC}_seg.nii.gz -c t2 -qc ../qc/_ (default)

![image](https://user-images.githubusercontent.com/93723496/147082459-39e0c1b7-36a5-486a-926f-9715d61ed2d4.png)

- for _sct_label_utils -i ${t2sagC}.nii.gz -create-viewer 6 -o label_c5c6.nii.gz -msg "Click at the posterior tip of C5/C6 inter-vertebral disc"_

![image](https://user-images.githubusercontent.com/93723496/147083216-10e6254e-0c43-48ab-a00f-2ea57607d2e7.png)

followed by _sct_label_vertebrae -i ${t2sagC}.nii.gz -s ${t2sagC}_seg.nii.gz -c t2 -initlabel label_c5c6.nii.gz -qc ../qc/_

![image](https://user-images.githubusercontent.com/93723496/147083355-cc743eff-2b6a-459d-826f-e8176e4ee497.png)

- for _sct_label_utils -i ${t2sagC}.nii.gz -create-viewer 3 -o label_c2c3.nii.gz -msg "Click at the posterior tip of C2/C3"_

![image](https://user-images.githubusercontent.com/93723496/147083730-73cb98ac-cfc0-4183-a884-3d3f203e9f91.png)

_sct_label_vertebrae -i ${t2sagC}.nii.gz -s ${t2sagC}_seg.nii.gz -c t2 -initlabel label_c2c3.nii.gz -qc ../qc/_

![image](https://user-images.githubusercontent.com/93723496/147083856-1dd955e5-d287-4bb3-adcb-3b8c6cc95fbc.png)

Did I make a mistake somewhere? Or is there another way to help the program to segment correctly the vertebrae?

Best,
Malo

**Comment by jcohenadad** [comment]
@mgaubert thank you for reporting these issue. For the sake of clarity, given that these two issues are different, we prefer to separate them into two separate issue tickets. Therefore, I copied your first issue in this new issue (with the appropriate title): https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3636

Also in the future, please feel free to use our forum, so that our answers can also benefit the SCT community (most users see the forum, but don't see the issues on the github repository, which are more directed towards the core developers). Thank you for you understanding.

**Comment by mgaubert** [comment]
@jcohenadad : ok, noted for next time ! 

Regarding the curved spine, it works well with your advises, thanks! Just a note: I was not able to use the option "-create 3:9" for _sct_label_utils_, the following error occured:

_sct_label_utils: error: argument -create: invalid list_typecast_func value: '2:9'_
(command: _sct_label_utils: error: argument -create: invalid list_typecast_func value: '2:9'_)

Anyways, "-create-viewer 3:9" works fine.

**Comment by jcohenadad** [comment]
> Regarding the curved spine, it works well with your advises, thanks! Just a note: I was not able to use the option "-create 3:9" for sct_label_utils, the following error occured:

my bad, i was on my phone without being able to check on the terminal the proper command-- you are right, the proper syntax is `-create-viewer`. I have now edited my post https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3635#issuecomment-999685297

**Comment by jcohenadad** [comment]
This issue being solved, we can now close it
