### ISSUE TITLE
Inconsistent MTR values when calculated from short dtype

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3636]
### Description

> Note: This issue was originally created in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3635#issue-1086726238

using sct_computre_mtr, I have an issue with the results when using short (4) NIFTI images for MT0 and MT1. The values I obtained are inconsistent (very small negatives or very big positives) for many slices but not all slices. At the end, when comparing with manual computing of MTR, a lot of voxels have wrong values.
I changed the type of the MT0/MT1 images from short to float and the result is correct, meaning similar to what I got with manual computing of MTR, and this for all slices and voxels.
Maybe is there a reason for this behavior?

**Comment by jcohenadad** [comment]
@mgaubert could you please send me your MTR image so I can try to reproduce your issue and implement a fix for it?

**Comment by mgaubert** [comment]
Dear Julien,

Thank you for your answer.

I send you MT0 and MT1 per email.

Malo

**Comment by jcohenadad** [comment]
@mgaubert I am able to reproduce this bug, and as you suspected the problem is very likely related to the input type (in your case int16) being not properly converted before calculating MTR. This will be a simple fix.
Thank you for reporting this issue 🙏

**Comment by RignonNoel** [comment]
@jcohenadad I read the documentation about the software architecture, installed all the requirements on my station, and did some rampup on the medical knowledge yesterday. I think i have a fix already done, i will do the testing today and create a pull-request 😉
