### ISSUE TITLE
`install_sct` should run from any directory

### ISSUE THREAD

**Issue by abelfodil** [spinalcordtoolbox/spinalcordtoolbox#3647]
Hi, thanks for reporting an issue, please take some time to consider the applicable guidelines:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#reporting-a-bug-or-requesting-a-feature
(about how to suitably describe issues or requests) prior to deleting this blurb when about to submit the issue.

### Description

I would like to execute the script from anywhere. Having to `cd` or `pushd` is a minor inconvenience.

Instead, the source directory can be retrieved using any of the methods [here](https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel).

The fixes would be to either:
-  `pushd` at the beginning and `popd` at the end of the script
- Set the source dir as the working dir for the different commands (ex: `pip install -e $SCT_SOURCE_LOC`, etc.)

This would make the script more robust.

### Steps to Reproduce

1. Go outside the repo

2. Try to install SCT

**Expected behavior:** <What you expect to happen>

Installation succeeds

**Actual behavior:** <What actually happens>

Error message telling me "The install_sct script must be executed from the source directory"

**Comment by joshuacwnewton** [comment]
I think this is a perfectly reasonable suggestion, and like you say, should be quite quick to fix and merge. :)
