### ISSUE TITLE
`-symmetrize` in `sct_maths` is always aplied on the first dimension 

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3649]
### Description

When using the command `sct_maths -symmetrize <dim>` the symmetry is always applied on the same dimension, following the code:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/304a934b3bb57b24885f6359a2cc35f6dc9c7033/spinalcordtoolbox/scripts/sct_maths.py#L377-L378

The argument of `-symmetrize` is never used and the transformation is always applied on the first dimension.

**Comment by joshuacwnewton** [comment]
Oh dear... Nice catch, though! :tada:
