### ISSUE TITLE
pyramid_expand() got an unexpected keyword argument 'channel_axis when using `sct_process_segmentation`

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3651]
### Description

When running `sct_process_segmentation` an unexpected agument is given to the function `skimage.transform.pyramid_expand`, `channel_axis` in the API script `process_seg.py`.
See below the terminal in *Steps to reproduce*.
### Steps to Reproduce

0. Install SCT `git-master-304a934b3bb57b24885f6359a2cc35f6dc9c7033`

1. Go to sct example data:
     `cd $SCT_DIR/sct_example_data/t2`

2. Run `sct_process_segmentation`
    `sct_process_segmentation -i t2_seg.nii.gz -perslice 1`

Terminal output:

```python
(base) sabeda@DESKTOP-JQ8A4UV:/mnt/c/Users/sb199/spinalcordtoolbox/sct_example_data/t2$ sct_process_segmentation -i t2_seg.nii.gz -perslice 1

--
Spinal Cord Toolbox (git-master-304a934b3bb57b24885f6359a2cc35f6dc9c7033)

sct_process_segmentation -i t2_seg.nii.gz -perslice 1
--

Compute shape analysis:   0%|                         | 0/240 [00:00<?, ?iter/s]
Traceback (most recent call last):
  File "/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 502, in <module>
    main(sys.argv[1:])
  File "/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 416, in main
    verbose=verbose)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/process_seg.py", line 106, in compute_shape
    shape_property = _properties2d(current_patch_scaled, [px, py])
  File "/mnt/c/Users/sb199/spinalcordtoolbox/spinalcordtoolbox/process_seg.py", line 173, in _properties2d
    image_crop_r = transform.pyramid_expand(image_crop, upscale=upscale, sigma=None, order=1, channel_axis=None)
TypeError: pyramid_expand() got an unexpected keyword argument 'channel_axis'

```
`Solution`

The fix is simple to just remove the argument `channel_axis`, however, there was a comment in the code:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/304a934b3bb57b24885f6359a2cc35f6dc9c7033/spinalcordtoolbox/process_seg.py#L171-L173

It may be worth to check if this skimage function is used elsewhere in SCT.

**Comment by joshuacwnewton** [comment]
https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3615!

**Comment by sandrinebedard** [comment]
In the code, it refers to https://github.com/scikit-image/scikit-image/issues/6092

**Comment by jcohenadad** [comment]
Thanks for reporting it @sandrinebedard and for cross-referencing @joshuacwnewton . Just curious: is it caught by our CI?

**Comment by joshuacwnewton** [comment]
It isn't... Is it possible you might have an outdated version of `scikit-image`, @sandrinebedard?

When I check the current source code, `pyramid_expand` does indeed have the `channel_axis` parameter, so this code should work in theory!

Could you please run `sct_check_dependencies` and share the output?
