### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by etetteh** [spinalcordtoolbox/spinalcordtoolbox#3659]
### Description
AttributeError when using sct_deepseg_sc, following the tutorial [here](https://spinalcordtoolbox.com/user_section/tutorials/segmentation/sct_deepseg_sc-example-t1.html)

### Steps to Reproduce

0. Install SCT <Spinal Cord Toolbox (git-master-afdbadc6b511db7d66db7804cc061ef711a83a3b)>

1. clone the above version of the repo, cd to the cloned repo and run `./install_sct` .

2.  The code uses data available [here](https://github.com/spinalcordtoolbox/sct_tutorial_data/releases/download/SCT-Course-20211116/data_spinalcord-segmentation.zip)
3. cd to `{PATH_TO_DOWNLOADED_DATA}/single_subject/data/t1` 
4. run `sct_deepseg_sc -i t1.nii.gz -c t1 -ofolder deepseg -qc ~/qc_singleSubj` in the terminal

**Expected behavior:** 
I expected the code to successfully and run and output some results

**Actual behavior:**
I got the following output: 
```
Traceback (most recent call last):
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 214, in <module>
    main(sys.argv[1:])
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg_sc.py", line 199, in main
    threshold_seg=threshold, remove_temp_files=remove_temp_files, verbose=verbose)
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/spinalcordtoolbox/deepseg_sc/core.py", line 506, in deep_segmentation_spinalcord
    im_in=im_norm_in)
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/spinalcordtoolbox/deepseg_sc/core.py", line 347, in segment_2d
    seg_model.load_weights(model_fname)
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/enoch/NeuroPoly/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/site-packages/keras/engine/saving.py", line 1183, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by joshuacwnewton** [comment]
That's odd. We've run into this issue before (#2987), but I had presumed that pinning `h5py==2.10.0` fixed it.

Could you please run the command `sct_check_dependencies` in your terminal, then copy and paste the output?

**Comment by etetteh** [comment]
Sorry for the late response:
Please, here is the output
```--
Spinal Cord Toolbox (git-master-afdbadc6b511db7d66db7804cc061ef711a83a3b)

sct_check_dependencies 
--

SCT info:
- version: git-master-afdbadc6b511db7d66db7804cc061ef711a83a3b
- path: /home/enoch/NeuroPoly/spinalcordtoolbox
OS: linux (Linux-4.19.0-18-amd64-x86_64-with-debian-buster)
CPU cores: Available: 8, Used by ITK functions: 8
RAM: Total: 15919MB, Used: 7022MB, Available: 7306MB
Check Python executable.............................[OK]
  Using bundled python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] at /home/enoch/NeuroPoly/spinalcordtoolbox/python/envs/venv_sct/bin/python3.7
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.3)
Check if dipy is installed..........................[OK] (1.4.1)
Check if h5py is installed..........................[OK] (3.6.0)
Check if Keras (2.3.1) is installed.................NumExpr defaulting to 8 threads.
[OK] (2.3.1)
Check if ivadomed is installed......................[OK] (2.7.4)
Check if matplotlib is installed....................[OK] (3.5.0)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.21.2)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.3.5)
Check if psutil is installed........................[OK] (5.9.0)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.2.5)
Check if pytest-cov is installed....................[OK] (3.0.0)
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.27.1)
Check if requirements-parser is installed...........[OK]
Check if scipy is installed.........................[OK] (1.7.3)
Check if scikit-image is installed..................[OK] (0.19.1)
Check if scikit-learn is installed..................[OK] (1.0.2)
Check if tensorflow is installed....................[OK] (1.15.5)
Check if torch (1.5.0+cpu) is installed.............[OK] (1.5.0+cpu)
Check if torchvision (0.6.0+cpu) is installed.......[OK] (0.6.0+cpu)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.62.3)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.7)
Check if pytest_console_scripts is installed........[OK]
Check if wquantiles is installed....................[OK] (0.4)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened with matplotlib.......Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[OK] (Using GUI backend: 'QtAgg')
Check if figure can be opened with PyQt.............[OK]
Check FSLeyes version...............................[OK] (1.3.3)
```

**Comment by joshuacwnewton** [comment]
Yes, something definitely went wrong with your installation. The version of `h5py` that should get installed is `2.10.0`, since that is what we have pinned currently:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/cbe2e481e4e82796d866e692205555839c7c9741/setup.py#L34

However, somehow you have version `3.6.0` installed. :thinking: 

----

Just to check, how did you install FSLeyes? Did you activate `venv_sct` then install FSLeyes into SCT's conda environment? Because that is one common way that this problem can occur. See: #3262.

**Comment by joshuacwnewton** [comment]
Also, as a quick fix, you can follow the instructions from https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3262#issuecomment-819656637 to restore the older version of `h5py`. :slightly_smiling_face:

**Comment by etetteh** [comment]
Okay. I think I installed FSLeyes inside the `venv_sct` using conda. There was an issue installing it from the setup file. 
I manually installed the h5py I think, because there was no distribution available for my system (MacOS M1).
I will check everything, and update you.

**Comment by joshuacwnewton** [comment]
> Okay. I think I installed FSLeyes inside the `venv_sct` using conda. There was an issue installing it from the setup file.
> I manually installed the h5py I think, because there was no distribution available for my system (MacOS M1).

Thank you for the clarification. This would definitely explain things. :)

I'm happy to help troubleshoot if you run into more issues. But, you should be okay as long as you are able to find a way to install `h5py==2.10.0`.

**Comment by joshuacwnewton** [comment]
Closing, as @etetteh was able to successfully reinstall SCT without running into this error.
