### ISSUE TITLE
Ubuntu 20.04 runners are intermittently stalling out during the runs of the test suite

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3661]
I've noticed this on a few PRs, most notably https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3660#discussion_r792733908. But, it seems to be intermittent, as I've seen it pass without issue after restarting a job, and I've also seen it pass fine on master recently.

So, this probably requires further investigation. :thinking:

**Comment by mguaypaq** [comment]
On #3660, I noticed that the Ubuntu 20.04 runner seems to either succeed in under 20 minutes (like the other runners), or else it goes for hours, stuck at the "Run pytest test suite (with code coverage)" step without any output.

**Comment by mguaypaq** [comment]
The step which stalls is different on Ubuntu 20.04 than the other runners, changed recently in #3463 ([the specific lines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3463/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR213-R215)). Maybe related?

On [the Actions tab](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/workflows/tests.yml) I see there are currently two stalled runs (spinning yellow bullet points), but there's no output to see.

**Comment by joshuacwnewton** [comment]
Ah! That's a really good insight, and makes perfect sense as to why the Ubuntu runners specifically are stalling. I'm willing to bet that it very much has to do with the addition of coverage.

**Comment by mguaypaq** [comment]
[This cancelled run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/4944025569?check_suite_focus=true) has output logs for the "Run pytest test suite (with code coverage)" step, shows it was 81% done after 6 hours. I don't remember whether I cancelled it manually, or else it timed out by itself.

[This currently stuck run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/4954284311?check_suite_focus=true) has been running for almost 5 hours. I'll check again tomorrow to see its fate.

**Comment by joshuacwnewton** [comment]
> [This cancelled run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/runs/4944025569?check_suite_focus=true) has output logs for the "Run pytest test suite (with code coverage)" step, shows it was 81% done after 6 hours. I don't remember whether I cancelled it manually, or else it timed out by itself.

I noticed it stalled at that one test in multiple runs? I can't remember where else I saw it (it might have been a run that I cancelled and restarted). 

Specifically, it's this one:

```
testing/api/test_process_seg.py::test_compute_shape[im_seg11-expected11-params11] PASSED [ 81%]
```

I'm curious if running the `pytest` command with coverage is enough to reproduce this locally, too? :thinking: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7c4f081a0cb566fd8f4702a7e0f8b43bcb02b412/.ci.sh#L45

**Comment by joshuacwnewton** [comment]
So, I ran the following locally:

```
pytest --cov=spinalcordtoolbox --cov-config setup.cfg --cov-branch --cov-report=xml:cov-api.xml testing/api/test_process_seg.py::test_compute_shape
```

And I received the following warning:

```
testing/api/test_process_seg.py::test_compute_shape[im_seg11-expected11-params11] PASSED [100%]/home/joshua/sct_5.5/python/envs/venv_sct/lib/python3.7/site-packages/coverage/control.py:785: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```

This warning also appears when I run other tests, though, so I don't think this is the issue here. 

But, FWIW, it's a little thing that's easy to fix -- adding `__init__.py` to the `testing` folder suppresses the warning, as per [this SO post](https://stackoverflow.com/a/62487381).

**Comment by joshuacwnewton** [comment]
Actually, I'm fairly certain it doesn't actually have to do with `test_process_seg.py::test_compute_shape`, but instead the test that comes immediately after (since `test_compute_shape` `PASSES` just fine).

**Comment by joshuacwnewton** [comment]
> Actually, I'm fairly certain it doesn't actually have to do with `test_process_seg.py::test_compute_shape`, but instead the test that comes immediately after (since `test_compute_shape` `PASSES` just fine).

Yep, I can reproduce the stalling on my laptop. It has to do specifically with [`testing/api/test_qc_parallel.py::test_many_qc`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fc34ee93cf0073a2abaca9f786aa0f794101e0c4/testing/api/test_qc_parallel.py#L26-L34). I can run it fine without the coverage flags, but with coverage it stalls.

When exiting the test using a keyboard interrupted, I noticed it was hanging here:

```
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

Googling around for general multiprocessing issues related to hanging at `os.waitpid()`, I found https://github.com/pytorch/pytorch/issues/48382. One comment on that issue recommends:

> I bet this is because you're initializing threads prior to forking, which leaves the forked thread in a bad state. The size matters because we don't initialize OpenMP unless the input is large enough. Try adding
> 
> ```
>     mp.set_start_method('spawn')
> ```
> 
> to the start of your program

I tried adding this to the start of the test, and it now passes without hanging. I still don't quite understand the interaction between `multiprocessing` and `pytest --cov`, but at least we have a fix for now.

**Comment by dyt811** [comment]
Could it also be GitHub Action platform issue as well? Just past few hours, we started notice stalling on GitHub Actions for mostly Ubuntu based CI stalling across multiple PRs without altered GitHub Actions on ivadomed: 

Time stamped result: 2022-01-31T151529EST across about 5 PRs stuck for total of: 

* 3.7 Ubuntu 18
* 3.8 Ubuntu 18 x 2
* 3.9 Ubuntu 18 x 3
* 3.8 Ubuntu 20
* 3.9 Ubuntu 20 x 3

Also noted GitHub status page has not been perfectly stellar SLA uptimes in the past few months 
* ![image](https://user-images.githubusercontent.com/6720068/151871572-846207e2-efd6-4743-ac72-5daae1d084c0.png)

Most notably, restart has shown different unit test being stuck in our case:
* was 3.8 on Ubuntu 18.04  stuck
* restarted cause 3.7 on Ubuntu 20.04 to be stuck while 3.8 Ubuntu 18.04 now passes
* Since each OS are technically independent, we were leaning heavily this being a platform issue at the moment in our case. 

See attempts at: 
* https://github.com/ivadomed/ivadomed/actions/runs/1773786867/attempts/1 
* https://github.com/ivadomed/ivadomed/actions/runs/1773786867/attempts/2

**Comment by joshuacwnewton** [comment]
Hmmm... I don't _think_ it's due to GitHub Actions, mainly because I was able to reproduce the stall locally for the same test that the CI stalled on. :thinking;

**Comment by mguaypaq** [comment]
In the spirit of digging a little more, it's possible that this is an interaction between `fork`ing in `multiprocessing`, and [`flock`ing in `qc.py`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/17afec65e8ab674cb487b743231aea8d7e33e593/spinalcordtoolbox/reports/qc.py#L641-L653)? According to [the manpage for `flock`](https://www.man7.org/linux/man-pages/man2/flock.2.html):

    Locks created by flock() are associated with an open file
    description (see open(2)).  This means that duplicate file
    descriptors (created by, for example, fork(2) or dup(2)) refer to
    the same lock, and this lock may be modified or released using
    any of these file descriptors.

Based on what [the manpage for `fork`](https://www.man7.org/linux/man-pages/man2/fork.2.html) says, there are some other specific classes of gotchas that we could be hitting:

       *  The child process is created with a single thread—the one that
         called fork().  The entire virtual address space of the parent
         is replicated in the child, including the states of mutexes,
         condition variables, and other pthreads objects; the use of
         pthread_atfork(3) may be helpful for dealing with problems
         that this can cause.

       *  After a fork() in a multithreaded program, the child can
         safely call only async-signal-safe functions (see
         signal-safety(7)) until such time as it calls execve(2).

      *  The child inherits copies of the parent's set of open file
         descriptors.  Each file descriptor in the child refers to the
         same open file description (see open(2)) as the corresponding
         file descriptor in the parent.  This means that the two file
         descriptors share open file status flags, file offset, and
         signal-driven I/O attributes (see the description of F_SETOWN
         and F_SETSIG in fcntl(2)).

**Comment by joshuacwnewton** [comment]
> In the spirit of digging a little more, it's possible that this is an interaction between `fork`ing in `multiprocessing`, and [`flock`ing in `qc.py`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/17afec65e8ab674cb487b743231aea8d7e33e593/spinalcordtoolbox/reports/qc.py#L641-L653)? According to [the manpage for `flock`](https://www.man7.org/linux/man-pages/man2/flock.2.html):

Thank you for the diligence! Just as a quick test, I tried commenting out the lines of code in `qc.py` related to `fcntl.flock`, but was still able to reproduce the stalling. 

At this point, I wanted to try creating a minimum reproducible example. I slowly removed bits and bits of the test, until I was able to reproduce the behavior even for this tiny snippet:

```python
import multiprocessing

def test_multiprocessing_print():
    with multiprocessing.Pool(2) as p:
        p.map(print, ["hey", "hi", "hello"])
```

Unfortunately (or fortunately), however, I also tried the `spawn` fix inside this example, and I was still able to reproduce the same stalling behavior.

Notably, though, I also found the stalling to be a bit sporadic. Sometimes the tests would pass fine? (This also mimics the behavior we saw in the CI, I think, as the Ubuntu runner didn't _always_ stall.) 

But, I think this sporadic behavior was how I fooled myself into thinking that `spawn` was a fix when it wasn't.

----

At this point, I was thinking it might just be an interaction between `multiprocessing` and `pytest-cov`, so I tried drilling down into that a little more, and found [this page](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#if-you-use-multiprocessing-pool), which says:

> pytest-cov automatically registers a multiprocessing finalizer. The finalizer will only run reliably if the pool is closed. 

Mimicking the code example they provide, I refactored my minimum reproducible example as follows:

```python
import multiprocessing


def test_multiprocessing_print_with_close():
    p = multiprocessing.Pool(2)
    try:
        p.map(print, ["hey", "hi", "hello"])
    finally:
        p.close()  # Marks the pool as closed.
        p.join()   # Waits for workers to exit.


def test_multiprocessing_print():
    with multiprocessing.Pool(2) as p:
        p.map(print, ["hey", "hi", "hello"])
```

And was able to get myself into this situation somewhat reliably:

![Screenshot from 2022-02-03 09-23-27](https://user-images.githubusercontent.com/16181459/152361294-c7cca2ba-900f-43c7-8ead-b266bae75d7f.png)

It was still sporadic, but the results I got were either both stalling, or just the second test stalling, but _never_ the first test stalling.

So, bringing things back around, I think it's just a matter of refactoring the test to follow `pytest-cov`'s recommendations?

**Comment by joshuacwnewton** [comment]
At this point, I was thinking it might just be an interaction between `multiprocessing` and `pytest-cov`, so I tried drilling down into that a little more, and found [this page](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#if-you-use-multiprocessing-pool), which says:

> pytest-cov automatically registers a multiprocessing finalizer. The finalizer will only run reliably if the pool is closed. 

Mimicking the code example they provide, I refactored my minimum reproducible example as follows:

```python
import multiprocessing


def test_multiprocessing_print_with_close():
    p = multiprocessing.Pool(2)
    try:
        p.map(print, ["hey", "hi", "hello"])
    finally:
        p.close()  # Marks the pool as closed.
        p.join()   # Waits for workers to exit.


def test_multiprocessing_print():
    with multiprocessing.Pool(2) as p:
        p.map(print, ["hey", "hi", "hello"])
```

And was able to get myself into this situation somewhat reliably:

![Screenshot from 2022-02-03 09-23-27](https://user-images.githubusercontent.com/16181459/152361294-c7cca2ba-900f-43c7-8ead-b266bae75d7f.png)

It was still sporadic, but the results I got were either both passing, or just the second test stalling, but _never_ the first test stalling.

So, bringing things back around, I think it's just a matter of refactoring the test to follow `pytest-cov`'s recommendations?

**Comment by joshuacwnewton** [comment]
Side note: If you're wondering "Why isn't the `with` context manager good enough?" like I was, I also stumbled across an older version of `pytest-cov`'s docs where they used to recommend that instead: https://pytest-cov.readthedocs.io/en/v2.6.1/mp.html#ungraceful-pool-shutdown 

My best guess is that the `pytest-cov` folks realized this wasn't adequate, and then rewrote their recommendations to ditch the `with` context manager:

> If you use multiprocessing.Pool.terminate **or the context manager API (__exit__ will just call terminate)** then the workers can get SIGTERM and then the finalizers won’t run or complete in time.

(emphasis mine)
