### ISSUE TITLE
Consider splitting 'Tutorials' and 'Courses' in the website

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3665]
When clicking on 'Tutorials and Courses' in the website, we see this:

![Screen Shot 2022-01-26 at 4 05 14 PM](https://user-images.githubusercontent.com/2482071/151246929-004976a6-6f88-4873-9dde-c8069168d106.png)

Which is a bit overwhelming if people are only interested in quickly get to the course recording. Ie: it is not intuitive (at least not for me) that people have to scroll down to finally see the courses.

therefore, i suggest making an entry 'Courses' in the TOC, so that when ppl click on 'Courses', they immediately see the courses

**Comment by joshuacwnewton** [comment]
I definitely support this change. Your reasoning makes perfect sense to me. :)

**Comment by RignonNoel** [comment]
I will create a PR on this with some proposition
