### ISSUE TITLE
Broken link to neuro.polymtl.ca in `landmarks.py`

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3685]
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2ad706e2859e3d7b29789cad370a1ac52de4e57e/spinalcordtoolbox/registration/landmarks.py#L11

**Comment by joshuacwnewton** [comment]
Easy-peasy: https://intranet.neuro.polymtl.ca/geek-tips/image-processing-software/advanced-normalization-tools-ants.html#itk-transform-file
