### ISSUE TITLE
TypeError: 'Namespace' object is not subscriptable

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3686]
### Description

Crash when using `-d` parameter. Probably a regression bug. 

Posted by: https://forum.spinalcordmri.org/t/sct-propseg-error-with-d-parameter/815

### Steps to Reproduce

Probably any image will do:

```bash
julien-macbook:~/Desktop $ sct_propseg -i t2s.nii.gz -c t2s -d 10

--
Spinal Cord Toolbox (git-jca/deepseg-mp2rage-49cd829c639d5ee89f51a950febc09c3a601510f)

sct_propseg -i t2s.nii.gz -c t2s -d 10
--

Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_propseg.py", line 684, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_propseg.py", line 671, in main
    img_seg = propseg(img_input, arguments)
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_propseg.py", line 547, in propseg
    cmd += ["-d", str(arguments["-d"])]
TypeError: 'Namespace' object is not subscriptable
```

**Comment by joshuacwnewton** [comment]
This is a lingering bug that was introduced 17 months ago (:fearful:) when we adopted `argparse` across all of our scripts with PR #2824.

In the git blame, all of the arguments were updated... except `-d`, which must have been missed at the time.

![Screenshot from 2022-02-10 17-13-23](https://user-images.githubusercontent.com/16181459/153505664-91bca18d-a6a6-4ff0-b42e-941fe79523d7.png)

This is a quick fix!
