### ISSUE TITLE
On Windows, saving an `Image` to a file with an open file pointer causes `OSError: [Errno 22] Invalid argument`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3695]
> * **Note:** This issue is the cause of 4 of the 13 remaining test failures described in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3682#issuecomment-1042079185.

In many places within SCT, we open an image file using our `Image` class, do some processing, then save the image to the same filename, overwriting it. On our unix platforms, this doesn't seem to cause any issues. However, on Windows, _sometimes_ an error like this is thrown:

```
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Joshua\\AppData\\Local\\Temp\\sct-20220218135625.068144-label_vertebrae-ezuo8o0i\\segmentation_labeled.nii'
```

I was able to narrow down the cause of this vague error by trying to call `os.remove` instead of `Image.save()`:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Joshua\\AppData\\Local\\Temp\\sct-20220218135625.068144-label_vertebrae-ezuo8o0i\\segmentation_labeled.nii'
```

So, I believe the cause of the initial error is due to attempting to overwrite a file that has a currently-open file pointer. 

I then found that open file-pointers are often caused via either:

1. The `im_file` property of SCT's `Image` objects, which [stores the original `nibabel` object](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f1766ed3f63b4d83fecb7a382b357a2427d8e6c2/spinalcordtoolbox/image.py#L405) inside of our `Image` objects.
    * I was able to get rid of some errors in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/e50e7f3ea17a85a84963e78cd94609f9317bf858 by refactoring `Image` to no longer store the `nibabel` object.
2. Nibabel loading the data array as an `np.memmap` object, rather than loading it into memory, then we [store it](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f1766ed3f63b4d83fecb7a382b357a2427d8e6c2/spinalcordtoolbox/image.py#L406).
    * I was able to get rid of some additional errors in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/23738acb278291cb37ad867a2cada82c0ad7850d by conditionally loading the `np.memmap`'d data into memory before saving.

However, even with these two changes, 4 test failures still remain. Related to 2., there is a much bigger hammer we could use here: _Unconditionally_ avoiding memory-mapped data using the following option:

```diff
- self.im_file = nib.load(path)
+ self.im_file = nib.load(path, mmap=False)
```

Making this change indeed fixes all of the `Invalid argument` errors. However, I'm unsure of the implications here, and wanted to discuss beforehand to see if we could identify any other approaches.

**Comment by mguaypaq** [comment]
Or, as a hybrid of these options:
```py3
import sys
self.im_file = nib.load(path, mmap=(sys.platform != 'win32'))
```

**Comment by joshuacwnewton** [comment]
> Or, as a hybrid of these options:
> 
> ```python
> import sys
> self.im_file = nib.load(path, mmap=(sys.platform != 'win32'))
> ```

I like this suggestion a lot. 

* On the one hand, it's still quite a heavy-handed solution, and I'm worried about the performance implications of always loading data into memory. (Ideally, we could address the individual instances of file overwriting without having to resort to this.)
* On the other hand, I get the sense that native Windows installations of SCT will be quite experimental + suboptimal at first, given that our test suite is (admittedly) lacking, and we don't have the years of user experience and testing on Windows like we do with our Linux/Mac users. With that in mind, a solution like this that removes a blocker on the Windows side of things while leaving the mac/linux experience untouched feels like a safe way to move forward. Especially since this will take care of any instances that our test suite _didn't_ catch, too.

**Comment by mguaypaq** [comment]
Some more points:
- My understanding is that mmap is a very Unix-y thing, and at least [some people on StackOverflow agree](https://stackoverflow.com/questions/2136527/how-portable-is-mmap). So, I went digging to see how nibabel uses mmap.
- After chasing through all the indirection, I believe [this](https://github.com/nipy/nibabel/blob/1e93bd5dbcda21907f04b8f12f43d0d01e6c7e0d/nibabel/volumeutils.py#L441-L446) is essentially where nibabel uses mmap: by passing it through to numpy.
- In turn, numpy [import the mmap package from the standard lib](https://github.com/numpy/numpy/blob/4adc87dff15a247e417d50f10cc4def8e1c17a03/numpy/core/memmap.py#L211) and then [calls mmap.mmap](https://github.com/numpy/numpy/blob/4adc87dff15a247e417d50f10cc4def8e1c17a03/numpy/core/memmap.py#L267).
- In the Python standard library, the mmap module [has two versions of the mmap constructor](https://docs.python.org/3/library/mmap.html#mmap.mmap), one for Windows and one for Unix. They take the same number of arguments, but with different meanings, and numpy seems to only use the Unix version.

Given this, I think using mmap on Windows is asking for trouble.
