### ISSUE TITLE
`gaussian_std` parameter is ignored

### ISSUE THREAD

**Issue by mguaypaq** [spinalcordtoolbox/spinalcordtoolbox#3698]
The script `sct_label_vertebrae` accepts a parameter call `gaussian_std`, with default value `1.0`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f1766ed3f63b4d83fecb7a382b357a2427d8e6c2/spinalcordtoolbox/scripts/sct_label_vertebrae.py#L44
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f1766ed3f63b4d83fecb7a382b357a2427d8e6c2/spinalcordtoolbox/scripts/sct_label_vertebrae.py#L185-L188

However, the library code ignores this value, and hard-codes the value `999` instead:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f1766ed3f63b4d83fecb7a382b357a2427d8e6c2/spinalcordtoolbox/vertebrae/core.py#L164-L168

I can think of a few ways to address this discrepancy:

1. Replace the hard-coded value by `param.gaussian_std` in the library code, keep the default value of `1.0`. This would be a change in behaviour, probably not what we want.
2. Replace the hard-coded value by `param.gaussian_std` in the library code, update the default value to `999`.
3. Get rid of the `gaussian_std` parameter, if it's not being used. We can still accept the command-line parameter for backwards compatibility, and emit a warning that it's ignored and deprecated.

From looking at #1422, it looks like `gaussian_std` has never been taken into account, and from looking at #1423, it looks like it was already obsolete 5 years ago, so I'm leaning towards option 3.

**Comment by joshuacwnewton** [comment]
Ahh, good catch!!

I do have one slight addendum, though:

> From looking at https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/1422, it looks like gaussian_std has never been taken into account

I was able to find one place in #1422 where `gaussian_std` was taken into account:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/3c0d6c4c6e85d3c0d80427744df7a12de6720541/scripts/sct_label_vertebrae.py#L453

However, like you suggested, this was made obsolete when #1423 was addressed. But, just to be specific, it was removed 3 years ago when automatic c2c3 detection was introduced in #2084.

![image](https://user-images.githubusercontent.com/16181459/155180348-bb9378bc-1515-41dc-a74b-8186fabd85a9.png)

Once that snippet was removed, then the parameter was indeed ignored entirely.
