### ISSUE TITLE
Consider setting `-clean-labels 1` by default

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3702]
Context: https://forum.spinalcordmri.org/t/seg-and-label-seg-mismatch/820/5?u=jcohenadad

Considering that:
- these segmentation issues could happen (ie: spurious voxels in the labeled segmentation)
- many users are not as careful as the user who reported the issue (ie: it requires QCing the selected slices, understand what it means)

I suggest to set `-clean-labels 1` by default.

I would like it if we could trace back the decision we set it to 0 (maybe there was a good reason to do so...).

**Comment by mguaypaq** [comment]
The `-clean-labels` flag was added in #2990, with a default value of `0`, but it looks like the previous code called `clean_labeled_segmentation` unconditionally, so this was a change in behavior. That pull request also introduced a test which compares the cleaned and the non-cleaned versions, and checks that the cleaned version has a higher dice score.

The discussion includes a pair of comments about `clean_labeled_segmentation` causing a problem: [first comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2990#issuecomment-726354270), [second comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2990#issuecomment-726395216).

**Comment by mguaypaq** [comment]
Right now, the options are:
- `-clean-labels 0` (default): do nothing
- `-clean-labels 1`: do AND operation + dilation

You're suggesting an extra tier like this, yes?
- `-clean-labels 0`: do nothing
- `-clean-labels 1` (new default): do AND operation
- `-clean-labels 2`: do AND operation + dilation

If we expect that the AND operation is what people always want, how about just these two tiers:
- `-clean-labels 0` (default): do AND operation
- `-clean-labels 1`: do AND operation + dilation

I'm fine doing it either way, but if one of the options would never be reasonable, let's not leave it lying around.

**Comment by jcohenadad** [comment]
i like the solution with values 0,1,2, because going with "-clean-labels 0 (default): do AND operation" is confusing (ie: there _is_ some cleaning being done, so why is that "0").
