### ISSUE TITLE
Output from `isct_propseg` C++ binary overwrites any existing files with the same names

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3716]
### Description

When using `-o` flag from `sct_propseg`, I suspect that the function internally produces the file `inputimage_seg.nii.gz` and _then_ rename it with what is specified in `-o`.

The problem is that if a file `inputimage_seg.nii.gz` _already_ exists in the current directory, it is overwritten. This is annoying and defeats the purpose of the `-o` flag (ie: a user who does _not_ want an image to be overwritten).

I don't have the time to write a 'how to reproduce' blurb but i'm sure it can easily be reproduced with the testing dataset.

Context: https://forum.spinalcordmri.org/t/propseg-fails-to-segment-entire-t2-cord/831/7

**Comment by mguaypaq** [comment]
This seems to be the case, yes, for both `inputimage_centerline.nii.gz` and `inputimage_seg.nii.gz`:
[https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a237194d3d37f5bc4223d73e276e26d82ba72d96/spinalcordtoolbox/scripts/sct_propseg.py#L630-L636](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a237194d3d37f5bc4223d73e276e26d82ba72d96/spinalcordtoolbox/scripts/sct_propseg.py#L630-L636)

Steps to reproduce:
```bash
# get a sample file
cd "$(mktemp -d)"
cp "${SCT_DIR}/data/sct_example_data/t2/t2.nii.gz" ./t2.nii.gz

# create placeholder files t2_centerline.nii.gz and t2_seg.nii.gz
echo original_centerline > t2_centerline.nii.gz
echo original_seg > t2_seg.nii.gz

# run sct_propseg
source "${SCT_DIR}/python/etc/profile.d/conda.sh"
conda activate venv_sct
sct_propseg -i t2.nii.gz -c t2 -o desired_output.nii.gz
# lots of output...

# check whether t2_centerline.nii.gz got overwritten: yes
echo original_centerline | cmp - t2_centerline.nii.gz
# output: - t2_centerline.nii.gz differ: byte 1, line 1

# check whether t2_seg.nii.gz got overwritten: yes, also deleted
echo original_seg | cmp - t2_seg.nii.gz
# output: cmp: t2_seg.nii.gz: No such file or directory
```

**Comment by joshuacwnewton** [comment]
Here's what I might propose for this:

Before:

1. Pass user-requested output directory to `-o` argument of `propseg`.
2. Rename files that were output to the user-requested output directory.

After:

1. Pass temporary directory for `-o` argument of `propseg`.
2. Rename files that were output to the temporary directory
3. Copy all files from the temporary directory to the user-requested output directory.
