### ISSUE TITLE
Add normalized metrics for degenerative cervical myelopathy (DCM)

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#3733]
# DCM project
This project aims to add relevant metrics to assess cervical spinal cord compression for degenerative cervical myolopathy in collaboration with Allan Martin.

Objectives:
1. Normalize with PAM50 template relevant metrics to assess compression.
2. Add other relevant metrics.
3. Compare on a pathological dataset the normalized MSCC vs non-normalized. 

## Normalize metrics with PAM50 template

Normalize each metric from `sct_process_segmentation` with the corresponding level in PAM50 template. After, use the .csv file in `sct_compute_mscc` and specify the compressed level, upper and lower.

![image](https://user-images.githubusercontent.com/71230552/157465338-47a558a9-0fd3-44b6-8035-f4ceb3f521d4.png)

In `sct_process_segmentation`, add the option `-normalize PAM50`. Maybe only use with perlevel?

In `sct_compute_mscc`:

**Input** : 
* `.csv` output file from `sct_process_segementation`
*  Compressed level(s)

### CSA for R-L

Compute CSA for right and left spinal cord by seperating from mid-point of R-L diameter.

![image](https://user-images.githubusercontent.com/71230552/157468825-d4da1214-f453-46f4-9fb9-63544789a17f.png)

**TODO**: Check in scikit-image how to extract the mid point (we use scikit-image to get the axes for AP/RL diam, so it’s a matter of fetching more outputs from that library)

### Triangular compression
Compression can also have a triangular shape. However, metrics like symmetry/solidity would not be able to detect this compression.

**Proposition:**
1. With the spinal cord segmentation, scale compressed spinal cord to PAM50 using CSA. 
2. Register to PAM50 template (center of mass or centermassrot)
3. Compute similarity metric (Dice, Hausdorff )

![image](https://user-images.githubusercontent.com/71230552/157473701-dfd1930a-881c-440e-9507-37ffa9f4e96b.png)

**TODO**: Make sure there isn’t a metric that can already assess this triangulation (another that is currently not implemented in process_seg)

**Comment by joshuacwnewton** [comment]
Re-opening, as there is more work to be done in #4003.
