### ISSUE TITLE
Volume values rescaled by sagittal flattening

### ISSUE THREAD

**Issue by gaspardcereza** [spinalcordtoolbox/spinalcordtoolbox#3737]
### Description

I tried using `sct_flatten_sagittal` on a UNI volume acquired as part of a MP2RAGE sequence. The values stored in the original UNI volume  range from 0 to ~4000 (see below).

![image](https://user-images.githubusercontent.com/54723104/158477669-150da4af-a075-45e0-a7a9-08ad7452286d.png)

However once flattened, the values range from -1 to 1 (see below)

![image](https://user-images.githubusercontent.com/54723104/158477812-f2c7de31-381c-4e4e-a6c2-f3d968b55e24.png)

Shouldn't the values remain the same ?

I use the following line of code:

```bash
sct_flatten_sagittal -i UNI.nii.gz -s UNI_seg.nii.gz
```
The files are linked here:
[UNI_seg.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/8257482/UNI_seg.nii.gz)
[UNI.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/8257481/UNI.nii.gz)

**Comment by jcohenadad** [comment]
thank you for reporting this issue, @gaspardcereza . I suspect there is something fishy with dtype conversion

**Comment by joshuacwnewton** [comment]
It seems like this was intentional: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/84060e21e95ec75a0b0c2df195ac1d95a8ca5fab/spinalcordtoolbox/flattening.py#L48-L51

It looks like the scaling was done to address the errors from #1790/#2069.

But, given that we know the min/max of the data, we should be able to easily rescale the image back to its original scale, no?

**Comment by jcohenadad** [comment]
> But, since we have the min/max of the data, we can just do the inverse scaling after processing is finished, right?

that is correct. 

> (I imagine this wasn't caught until now because sct_flatten_sagittal is primarily a visual inspection tool, i.e. the precise intensity values are typically ignored for flattened images?)

also correct
