### ISSUE TITLE
Add support for ITK-Snap in the `display_viewer_syntax` function

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3745]
> **Note:** This has already been discussed in SCT meetings -- I'm just creating an issue for documentation purposes.

Our current `display_viewer_syntax` function only provides support for fslview/fsleyes. But, these tools aren't available on Windows.

Now that we (experimentally) support a native installation of SCT on Windows, it would be nice to also output syntax for ITK-SNAP, so that Windows users can view output images, too.

Note that ITK-SNAP is also supported on macOS/Linux, and it's possible that a user may have both FSLeyes and ITK-SNAP installed, so we may want to consider displaying the syntax for all available viewers.

**Comment by jcohenadad** [comment]
> so we may want to consider displaying the syntax for all available viewers.

I'm afraid doing that will clutter the stdout. On the other hand, we don't want to 'force' a particular viewer. We could also create a config variable for users to choose their preferred viewer, but that will add to the "art of properly using SCT", soooo i'm not sure what's the best approach here 🤔

**Comment by joshuacwnewton** [comment]
> I'm afraid doing that will clutter the stdout.

Just as a quick mockup, it would go from:

```console
> # Done! To view results, type:
fsleyes warp_straight2curve_vec_X.nii.gz warp_straight2curve_vec_Y.nii.gz warp_straight2curve_vec_Z.nii.gz &
```

To, for example:

```console
> # Done! To view results, type either of the following commands (depending on your preferred viewer):
fsleyes warp_straight2curve_vec_X.nii.gz warp_straight2curve_vec_Y.nii.gz warp_straight2curve_vec_Z.nii.gz &
itk-snap -g warp_straight2curve_vec_X.nii.gz -o warp_straight2curve_vec_Y.nii.gz warp_straight2curve_vec_Z.nii.gz
```

(Though, the colour highlighting is just an approximation, since we use neon green.)

**Comment by jcohenadad** [comment]
hum, it's actually not that bad at all!
