### ISSUE TITLE
Codecov uploader action intermittently fails with "Unable to locate build via Github Actions API"

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3751]
The issue is a mild annoyance for PRs, and is precisely what's described in: 

* https://github.com/codecov/codecov-action/issues/557#issuecomment-1077292985

Despite the issue being marked as solved on codecov's end, we see this from time to time, as do other users:

> TBH, this proved to be a major cause of build failures and the solution would be to make the action itself have an implicit retry logic with delay, maybe even with 5min.
> 
> 99% of failures are transient and retries would succeed, so I hope they will do the right think and implement that, especially as it is impossible for the consumers to do the same, due to the limitation of workflows.

Just making this issue for documentation purposes (so we can point to it whenever it happens, or potentially check in with the above link from time to time).

**Comment by mguaypaq** [comment]
We stopped running `codecov` automatically in #3837, so this is maybe not relevant anymore.
