### ISSUE TITLE
Migrate WIP native Windows installation instructions to our ReadTheDocs

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3755]
Currently, the native Windows installation instructions are stored in a personal Gist: https://gist.github.com/joshuacwnewton/b0e7ae866a56c78d951fd88e43eefc9b. This was just for ease of editing -- rapid changes could be made while ironing out the kinks in the installation process. 

But, now that we've ironed out many kinks already, we're getting close to being able to open up a PR so that we can display the instructions more prominently in our documentation. 

Some considerations:

* What kind of warning/note should we give about the new/experimental nature of the installation? 
    * (As discussed in the 2022-04-05 SCT meeting: This should be as light/friendly as possible as to not scare people off from properly trying out the new installation method.)
* How should we provide the `install_sct.bat` script to users? (attached to releases? [downgit link](https://downgit.github.io/#/home?url=https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/install_sct.bat) pointing to master?) 
* How should we handle the way we select the commit for the script to `git clone`? (Hardcoded git ref that we manually edit when attaching the script to a release?)

**Comment by mguaypaq** [comment]
> * What kind of warning/note should we give about the new/experimental nature of the installation?
>   
>   * (As discussed in the 2022-04-05 SCT meeting: This should be as light/friendly as possible as to not scare people off from properly trying out the new installation method.)

How about: "We have less experience with running SCT on Windows natively (that is, without WSL), so if you encounter any bugs, please tell us! (For example, by posting on the [Spinalcordmri.org forum](https://forum.spinalcordmri.org/c/sct/8).)"
In particular, this reinforces the message that we want to hear about problems.

> * How should we provide the `install_sct.bat` script to users? (attached to releases? [downgit link](https://downgit.github.io/#/home?url=https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/install_sct.bat) pointing to master?)
>
> * How should we handle the way we select the commit for the script to `git clone`? (Hardcoded git ref that we manually edit when attaching the script to a release?)

I vote for `install.bat` with a hardcoded git ref (to a tag) attached to the github release.

**Comment by joshuacwnewton** [comment]
> "We have less experience with running SCT on Windows natively (that is, without WSL), so if you encounter any bugs, please tell us! (For example, by posting on the [Spinalcordmri.org forum](https://forum.spinalcordmri.org/c/sct/8).)"

Ahhh, good thinking! I like the framing that focuses on the newness of the feature, as opposed to framing the feature as buggy/untested.

One small nitpick, though: The phrase "we have less experience" almost sounds to me like we're saying we're inexperienced as developers. :V

Given that, how do you feel about this wording (put into context, with a sample page header):

> ### Windows (native, non-WSL)
>
> > **Note:** This installation method is new to SCT as of version 5.6. (Previous versions of SCT required the use of [WSL](https://spinalcordtoolbox.com/user_section/installation/windows.html#option-1-install-on-windows-10-with-wsl) or [Docker](https://spinalcordtoolbox.com/user_section/installation/windows.html#option-2-install-with-docker) in order to support Windows.) 
> >
> > Because this method is new to SCT, we would greatly appreciate your feedback. If you have any questions or concerns, feel free to post them to the [Spinalcordmri.org forums](https://forum.spinalcordmri.org/c/sct/8), and we will be happy to help.
