### ISSUE TITLE
Priorities for SCT v5.7 Release

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3765]
### Context

After the release of SCT v5.5, we devoted the [2022-02-08 dev meeting](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.wv502cs9nk0k) to [ranking the larger projects](https://docs.google.com/document/d/17Ma3xP5LQL0DUIZnp9xNKXyMKOya5TmpzErXB1YJq3g/edit#heading=h.r499xqaduhre) in priority. This helped us to settle on a focus for the development of SCT v5.6.

Given that v5.6 will be released soon, I think it would be helpful to continue ranking priorities for planning the July/August SCT v5.7 release. However, this time, in the interest of transparency, I'm creating a GitHub issue instead of using a Google Doc.

### Projects to consider for 5.7 release

1. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3768
2. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3764
3. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3760
4. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3353
5. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526
6. https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3095
7. Script reproducibility
   - https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3597
   - https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3194

Please feel free to suggest additional projects prior to the [2022-05-03 dev meeting](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.ydiakt8onjff)!

#### Ranking of priorities

TBD: _ -> _ -> _ -> _ -> _ -> _ -> _ -> _ -> _

#### Projects to focus on

- [ ] TBD
- [ ] TBD

**Comment by RignonNoel** [comment]
+1 for the usage of Github in place of Google doc. 

I think it will be really nice for contributors and users to see the pinned issue and be aware of the release content.

**Comment by joshuacwnewton** [comment]
Closing this issue, as during the meeting, we agreed that https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3760 would be the focus for this release cycle, and that all other issues had roughly the same priority, and would depend on the interests and motivations of the devs themselves.
