### ISSUE TITLE
`realpath python` filepath check fails on mismatch between uppercase and lowercase usernames

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3800]
Forum link: https://forum.spinalcordmri.org/t/failed-installation-on-macos-big-sur-version-11-6-1/880/5?u=joshuacwnewton

Error log:

```
Validating that conda environment can be activated...

Error: Activating venv_sct failed to switch Python interpreter to Miniconda. (Incorrect interpreter loaded: /Users/Fmuhamma/sct_5.6/python/envs/venv_sct/bin/python3.7)
```

Relevant lines in `install_sct`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20d2f599c6bccffbcc0a852ad6acd3b71d509457/install_sct#L615-L622

It may also be possible that this is due to our polyfill for `realpath` on macOS:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20d2f599c6bccffbcc0a852ad6acd3b71d509457/install_sct#L317-L332

**Comment by joshuacwnewton** [comment]
When I run the 2 `realpath` commands on my local installation of SCT, I get the following:

```console
(venv_sct) joshua@tadpole:~/repos/spinalcordtoolbox$ echo "$(realpath "$(command -v python)")" 
/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/bin/python3.7

(venv_sct) joshua@tadpole:~/repos/spinalcordtoolbox$ echo "$(realpath "$(command -v python/envs/venv_sct/bin/python)")" 
/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/bin/python3.7
```

The `ACTUAL_PYTHON` value reported by the user is:

```console
/Users/Fmuhamma/sct_5.6/python/envs/venv_sct/bin/python3.7
```

So, the `ACTUAL_PYTHON` value seems to be correct (and the installation should be able to continue without error if we were to skip the `exit 1` called by SCT). In other words, the mismatch seems to actually be with the _`EXPECTED_PYTHON`_ value, which would be determined using: 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20d2f599c6bccffbcc0a852ad6acd3b71d509457/install_sct#L617

The problem is, our error logging doesn't actually tell us what _`EXPECTED_PYTHON`_ is, so debugging this is tricky without asking the user for more information, etc.

In order to understand the problem, I think it might be best to make the following changes to our logging, then supply the user with an updated `install_sct` file to run:

```diff
 # double-check conda activated (it can be glitchy): https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3029 
 print info "Validating that conda environment can be activated..." 
 EXPECTED_PYTHON="$(realpath "$(command -v python/envs/venv_sct/bin/python)")" 
 ACTUAL_PYTHON="$(realpath "$(command -v python)")" 
- if [ "$ACTUAL_PYTHON" != "$EXPECTED_PYTHON"  ]; then 
-   echo "Error: Activating venv_sct failed to switch Python interpreter to Miniconda. (Incorrect interpreter loaded: $ACTUAL_PYTHON)" >&2 
-   exit 1 
- fi 
+ if [ "$ACTUAL_PYTHON" != "$EXPECTED_PYTHON"  ]; then 
+   echo "Mismatch between expected and actual python!"
+   pwd
+   echo "Expected Python: $EXPECTED_PYTHON"
+   echo "Actual Python: $ACTUAL_PYTHON"
+ fi 
```

That way, we can see what the mismatch actually is, as well as see what happens when the installation is allowed to continue.

**Comment by joshuacwnewton** [comment]
Aha! The log reported in [this forum reply](https://forum.spinalcordmri.org/t/failed-installation-on-macos-big-sur-version-11-6-1/880/6?u=joshuacwnewton) shows:

```
+ echo 'Expected Python: /Users/fmuhamma/sct_5.6/python/envs/venv_sct/bin/python3.7'
Expected Python: /Users/fmuhamma/sct_5.6/python/envs/venv_sct/bin/python3.7
+ echo 'Actual Python: /Users/Fmuhamma/sct_5.6/python/envs/venv_sct/bin/python3.7'
Actual Python: /Users/Fmuhamma/sct_5.6/python/envs/venv_sct/bin/python3.7
```

Fascinating. One returned an lowercase username (`fmuhamma`) while the other returned a uppercase username (`Fmuhamma`). 

Certainly not a fatal error (the rest of the installation was successful for the user), but definitely something curious to see if we can improve in our check.

**Comment by jcohenadad** [comment]
wow! nice bug that you caught @joshuacwnewton

**Comment by joshuacwnewton** [comment]
> Though, truthfully I feel like this will likely end up being a low-priority/`WONTFIX` unless it comes up again for another user, or unless we can (easily) pinpoint why exactly the two commands functioned this way.

Given this, I've removed it from the 5.7 milestone.

**Comment by joshuacwnewton** [comment]
Good thinking. :)

**Comment by joshuacwnewton** [comment]
Returning to this issue, I'm not sure there's much we can actually do here that's realistic:

1. Allowing case-insensitivity in our path check
    * While this would solve this specific issue, it may trigger unintended behavior in other long-tail, niche cases. It's hard to say if solving a (known) niche issue is worth risking other (unknown) niche errors?
2. Only throwing a warning, rather than throwing an error, and letting the installer fail on its own at a later point
    * This would also solve this specific issue. 
    * But, looking at the issue that prompted us adding the check in the first place (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3029), the fail case is pretty disastrous (installing SCT's packages to the user's `(base)` conda environment). So, I'd prefer to continue to fail the installer on a mismatch.

Given this, I think it may just be easier to close this issue and mark it as a `WONTFIX`? But perhaps there's another option I'm missing.
