### ISSUE TITLE
Make it possible to loop across `sub-*` without considering `ses-*` if present

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3809]
As of SCT v5.4, whenever a `ses-` folder is present under a `sub-*` folder, it will consider it and aggregate subject and session, eg: `sub-01/ses-01` and use this instance inside the script being run.

A problem could occur if a script is supposed to act at the subject levels instead of at the session level. For example, if a script is responsible for registering data between session 1 and session 2, there is no way of doing it with the current implementation of how sessions are dealt with.

Note that this was not a problem in SCT v5.3.0 and before.

My suggestion would be to add a flag that would create a clause here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/5caa7d93c67454ac5835d14590d1202195c6b147/spinalcordtoolbox/scripts/sct_run_batch.py#L433-L447

That would bypass this 'is there a session' finding, and force each subject to be treated as a single instance for the script. It would then be the responsibility of the script to dive into session folders appropriately.

**Comment by joshuacwnewton** [comment]
> As of SCT v5.4, whenever a ses- folder is present under a sub-* folder, it will consider it and aggregate subject and session, eg: sub-01/ses-01 and use this instance inside the script being run.

I have been looking at this behavior as part of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3598, too, so I would be happy to self-assign this issue as well. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
> My suggestion would be to add a flag that would create a clause here that would bypass this 'is there a session' finding, and force each subject to be treated as a single instance for the script.

So, something like:

```python
parser.add_argument('-ignore-ses', action='store_true',
                    help="By default, if 'ses' subfolders are present, then 'sct_run_batch' will run the script "
                         "within each individual 'ses' subfolder. Passing `-ignore-ses` will change the behavior "
                         "so that 'sct_run_batch' will not go into each 'ses' folder. Instead, it will run the "
                         "script on just the top-level subject folders.")
```
