### ISSUE TITLE
Adapt standalone script into SCT feature for stitching MRI stacks to a single image

### ISSUE THREAD

**Issue by jqmcginnis** [spinalcordtoolbox/spinalcordtoolbox#3828]
**Feature justification: Is your feature request related to a problem? Please describe.**

Together with some of the PhD students of Julien's group, we currently have a collaboration between NeuroPoly and the Technical University of Munich to develop some deep learning models for spinal cord lesion detection in multiple sclerosis research.

For this, we (will) have a large-scale clinical dataset of spine MRIs of multiple sclerosis patients. However the scans differ in terms of imaging modalities (I believe) to some of the data you have been using so far, it will require some pre-processing in order to leverage SCT's fucionality (vertebrae labeling and PAM50 registration + subsequent analysis). 

In clinical routine, neuroradiologists currently acquire T2w scans with anisotropic resolution, both axially and sagittaly for multiple sclerosis patients. This ensures that a maximum of lesions can be detected while allowing an efficient clinical workflow, as described for example in this [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7960307/pdf/zj4963.pdf). 

**Galler, S., et al. "Improved lesion detection by using axial T2-weighted MRI with full spinal cord coverage in multiple sclerosis." 
American Journal of Neuroradiology 37.5 (2016): 963-969.**

***Why does the data have to be pre-processed?***

Due to the field of view of the scanner, it is advisable/necessary for the full coverage of the spine to acquire multiple scans of different spine parts in one session. For example, a stack of an axial or sagittal MRI could consist of chunk-1 (C1-C7), chunk-2 (T1-T9), chunk-3 (T10-L1). Please consider that the exact number of vertebrae in a scan is influenced by patient size and medical condition, thus chunks might comprise different regions as well. A visualization of this, indicated by red bounding boxes can be found [here](https://ars.els-cdn.com/content/image/1-s2.0-S2213158222000717-gr1.jpg). 

Finally, the resulting scans of one session might translate into the following data:

```
└── sub-019774
    ├── ses-20080415
    │   ├── sub-019774_ses-20080415_acq-ax_chunk-1_T2w.json
    │   ├── sub-019774_ses-20080415_acq-ax_chunk-1_T2w.nii.gz
    │   ├── sub-019774_ses-20080415_acq-ax_chunk-2_T2w.json
    │   ├── sub-019774_ses-20080415_acq-ax_chunk-2_T2w.nii.gz
    │   ├── sub-019774_ses-20080415_acq-ax_chunk-3_T2w.json
    │   ├── sub-019774_ses-20080415_acq-ax_chunk-3_T2w.nii.gz
    │   ├── sub-019774_ses-20080415_acq-sag_chunk-1_T2w.json
    │   ├── sub-019774_ses-20080415_acq-sag_chunk-1_T2w.nii.gz
    │   ├── sub-019774_ses-20080415_acq-sag_chunk-2_T2w.json
    │   └── sub-019774_ses-20080415_acq-sag_chunk-2_T2w.nii.gz
```

**Describe the solution you'd like**

To use SCT's registration and subsequent analysis pipeline, it is required to process these scans as one axial and one sagittal image and run the pipeline on the stitched scans. 

After discussing this with Julien Cohen-Adad, we wanted to propose this as a new feature in order to discuss if this would be a valuable development, and if so, how we would address it from an architectural perspective and which libraries should be used to comply with SCT's current plans (e.g. using ANTs over simpleITK, and other decisions).

I could potentially envision a `sct_stitch` script encapsulating the code base as an interface to the user, and several registration/interpolation/processing scripts in the toolbox that will do the tricks.  

**Describe alternatives you've considered**

Currently we register the scans via simpleITK in a common space and use some methods for interpolation of overlapping regions. It is a standalone script ([`stitch.py`](https://github.com/sct-pipeline/bavaria-quebec/blob/main/source/stitching/stitch.py)) that pre-processes the scans and save the images to the disk, so no interaction with SCT so far. We plan to improve the current stitching algorithm (especially the interpolation parts), and for this we would like to heavily utilize the tools provided in SCT that facilitate this (image conversion, image registration, quality check etc.).

**Additional context**

Having discussed this project in the BIDS forum to determine naming conventions for the stacks, I have also been contacted by a researcher from Vanderbilt University who requires something similar for his pipeline. All in all, I have the feeling this could be something useful for other groups as well, requiring even less effort to run SCT's established routines on newly acquired data.

Let me know what you think and how we would follow up on this,

Cheers, 
Julian

**Comment by jcohenadad** [comment]
> I don't know what `sct_merge_images` does exactly, but it sounds pretty close to your proposal; could you say what the differences are?

Currently, the usage of this function is unclear and should be clarified (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3829). In brief, the original purpose of `sct_merge_images` is to transform labels from several rated (ie: source in the same space) to a destination space. So this function should be seen as a "label fusion", or "image fusion" in general. It could work for the "stitching" capabilities discussed here, however there would _not_ be a requirement for an input warping field. Also, if we go in this direction, we might want to consider changing the name `sct_merge_images` for something more intuitive.

`sct_image` would be another viable option. I could see an option "stitch" under the "IMAGE OPERATIONS:" usage:
~~~
IMAGE OPERATIONS:
  -pad <list>           Pad 3D image. Specify padding as: "x,y,z" (in voxel). Example: "0,0,1"
  -pad-asym <list>      Pad 3D image with asymmetric padding. Specify padding as:
                        "x_i,x_f,y_i,y_f,z_i,z_f" (in voxel). Example: "0,0,5,10,1,1"
  -split {x,y,z,t}      Split data along the specified dimension. The suffix _DIM+NUMBER will be
                        added to the intput file name.
  -concat {x,y,z,t}     Concatenate data along the specified dimension
  -remove-vol <list>    Remove specific volumes from a 4d volume. Separate with ",". Example:
                        "0,5,10"
  -keep-vol <list>      Keep specific volumes from a 4d volume (remove others). Separate with ",".
                        Example: "1,2,3,11"
  -type {uint8,int16,int32,float32,complex64,float64,int8,uint16,uint32,int64,uint64}
                        Change file type
~~~

`sct_maths` would be slightly out of scope (more reserved for mathematical operations), IMO, although a counterargument is that `sct_maths IMAGE1 -add IMAGE2` would be pretty close to the stitching feature...

**Comment by jqmcginnis** [comment]
Please bare in mind that I am relatively new to SCT, so I do not have a very detailed understanding of the architecture (yet) and how the modularity will be affected by this feature and the proposed changes. So any feedback regarding the proposed ideas of mine is very much appreciated, and please take my ideas with a grain of salt :slightly_smiling_face: 

Utilizing the `sct_image -stitch` would be a nice option in my opinion:

1) the stitching feature will probably rely on some padding, so having the stitched feature in the same utility function might be an intuitive decision.

2) the function as such refers to the modification of images, so it feels very intuitive to locate it there as well.

Another idea might be to include the `sct_merge_images` in the `sct_label_utils`? If label fusion is the primary use case, perhaps it would be convenient to have it there as well? However, the `sct_merge_images` might also be used in other areas, so not sure if relocating it makes a lot of sense. Again, I have the feeling that someone more experienced could evaluate this idea far better than I can, but perhaps people with little SCT experience might share a similar intuition for this as well.

If we take the necessity for interpolation of the different stacks into consideration, perhaps `sct_maths IMAGE1 -add IMAGE2 `would be a bit confusing, as from a mathematical viewpoint, it can not be considered to be a mere addition?

@mguaypaq  Also, I will be happy to share the code as it is part of one of the repos in sct_pipeline as well and will link to it in this issue, once the appropriate PRs are merged! Thank you!

**Comment by mguaypaq** [comment]
Since the [sct-pipeline/bavaria-quebec](https://github.com/sct-pipeline/bavaria-quebec) repository is public, we can link to it. I guess the file [stitch.py](https://github.com/sct-pipeline/bavaria-quebec/blob/main/source/stitching/stitch.py) is what you're talking about (although that may be an older version than what you're using)?

**Comment by jqmcginnis** [comment]
@mguaypaq indeed that is the script I am referring. However, I would say it is still very experimental at the moment, so not advisable to merge into SCT - I would propose the following:

1. We decide how/where we will include the stitching function in SCT (will it be `sct_image`?)
2. We use the initial script, include it into the SCT environment (e.g. to use SCT's Image Classes etc.) and I will work on the branch/PR for the updates of this function. We might replace the current solution completely, e.g. by using other libraries or implementations described in other papers. 
3. Once we have reached / implemented a solution that satisfies the SCT quality standard and addresses the current issues of intensity mismatch and overlap sufficiently well, we can start merging this functionality into SCT.

Does this sound like a good plan?

**Comment by jqmcginnis** [comment]
@jcohenadad @mguaypaq @joshuacwnewton 

Hi everyone, hope you've been having a great summer :slightly_smiling_face: 

I have been testing different algorithms until now, and I have been getting consistently good results with the [Glocker at al.](https://github.com/biomedia-mira/stitching) approach. It's a small library written in C++ (thus excellent run time performance) and is released under the Apache 2.0 License.

After some testing, I believe it would be a great tool for the sct toolchain, and I would like to use some of sct's features such as the quality check to ensure the stitching process is working properly, especially for a multi patient cohort.

To get accustomed to SCT a bit (as I will be hopefully working a lot with you soon), I would propose that I include it in a fork and let you evaluate it, once everything runs smoothly. Otherwise I would be happy to showcase the algorithm's performance to you in a meeting, or send some test data over a private channel. Please let me know what you think!

However, to ensure I start of the implementation/integration process correctly, I have several questions that should be addressed prior to starting this:

1. LICENSE - will Apache 2.0 work ? do you see any problems including an Apache 2.0 licensed module in SCT? If so, I can reach out to the author and ask if something else would be possible as well!
2. How do you currently interface non-python code from sct? What options would you consider? (python/c bindings, pre-compiled binary call, ...?)
3. The module operates on axial images, e.g. to run on sagittal slices I rotate the image using [this](https://github.com/sct-pipeline/bavaria-quebec/blob/main/source/utility/reorient.sh) fsl-based script. Do you see any problems with this?

Thank you very much for your help,

Cheers,
Julian

**Comment by joshuacwnewton** [comment]
Hi @jqmcginnis! Thank you so much for the detailed post, and for checking with us regarding your software dependencies. This makes our lives as SCT devs much, much easier. :heart: 

> 1. LICENSE - will Apache 2.0 work ? do you see any problems including an Apache 2.0 licensed module in SCT? If so, I can reach out to the author and ask if something else would be possible as well!

The Apache 2.0 license is very permissive, and it's easy to follow its requirements. (For other C++ binaries that SCT distributes, we include a copy of the licenses alongside the binaries.) So, I don't think this should be a problem?

> 2. How do you currently interface non-python code from sct? What options would you consider? (python/c bindings, pre-compiled binary call, ...?)

For our other C++ dependencies, currently we are using pre-compiled binaries + a `subprocess` call. For example, we redistribute some ANTs binaries that we compile ourselves for various platforms. (See: [this Wiki page](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Packaging%3A-How-to-compile-C---binaries-(ANTs,-isct)) for more information.)

Perhaps we can do something like we did with [`build-ants.yml`](https://github.com/spinalcordtoolbox/build_ANTs/blob/master/.github/workflows/build-ants.yml), and automate the build environment for `stitching`, too. 

<details>
<summary> Aside: Sitching's third-party dependencies </summary>

> Looking at the `stitching` project, my initial concern is its dependencies:
> 
> > * [Eigen](https://github.com/biomedia-mira/stitching/blob/master/eigen.tuxfamily.org)
> > * [Boost](http://www.boost.org/) (tested up to v1.58)
> > * [ITK](http://itk.org/) (tested up to [v4.13.2](https://sourceforge.net/projects/itk/files/itk/4.13/InsightToolkit-4.13.2.tar.gz))
> 
> SCT targets Linux, macOS, and native Windows, but the `stitching` project mentions `apt` as a way to install Boost.
> 
> Thankfully, the [Boost download page](https://www.boost.org/users/download/) provides downloads for "unix" and "windows", so I'm hopeful that we can still set up a build environment.

</details>

> 3. The module operates on axial images, e.g. to run on sagittal slices I rotate the image using [this](https://github.com/sct-pipeline/bavaria-quebec/blob/main/source/utility/reorient.sh) fsl-based script. Do you see any problems with this?

Your FSL-based script uses `fslswapdim` and `fslorient -forceneurological`:

1. `fslswapdim` is [equivalent to `sct_image -setorient`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3741#issuecomment-1078072221), so no issues there.

2. I'm less familiar with `fslorient -forceneurological`. The `--help` string says:

    ```
        -forceneurological     (makes FSL neurological header - not Analyze)
    ```
    
    Admittedly, I don't understand what this means (is this referring to [neurological convention rather than radiological convention](https://nipy.org/nibabel/neuro_radio_conventions.html)?)  I'm not sure SCT has any equivalent tools to `-forceneurological`. But, @jcohenadad might be able to help me out here. :sweat_smile:

**Comment by jqmcginnis** [comment]
@joshuacwnewton thank you very much for the detailed roadmap and instructions, I will be implementing this in forks on my own account and will reach out to you once I believe I have a good working state :slightly_smiling_face: !

Anyhow, I am amazed how well all of these steps are documented in different READMEs, great job!

Regarding some of your comments, here my feedback:

> Thankfully, the [Boost download page](https://www.boost.org/users/download/) provides downloads for "unix" and "windows", so I'm hopeful that we can still set up a build environment.

Exactly what I was hoping to go for as well :slightly_smiling_face: 

> 1. `fslswapdim` is [equivalent to `sct_image -setorient`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3741#issuecomment-1078072221), so no issues there.

perfect :+1: 


> 2\. Admittedly, I don't understand what this means (is this referring to [neurological convention rather than radiological convention](https://nipy.org/nibabel/neuro_radio_conventions.html)?)

exactly, it's mainly used to switch from RAL to LAS. As `sct_image -setorient` can already do that, this should not be a problem :+1:

**Comment by joshuacwnewton** [comment]
>  I will be implementing this in forks on my own account and will reach out to you once I believe I have a good working state :slightly_smiling_face:!

From what I understand, there are 2 main tasks here, I think?

1. Creating pre-compiled `stitching` binaries for each OS (Linux, macOS, Windows)
2. Creating a new SCT function that wraps the `stitching` binary and adding that function to the CLI (e.g. `sct_image`)
    * In other words, [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3828#issuecomment-1182999854).

Were you planning to do both of these tasks yourself?

If so, I would love to offer to help out with creating the cross-platform build environment (task 1), that way you can have more time to focus on adding `stitching` to SCT (task 2).

**Comment by jqmcginnis** [comment]
@joshuacwnewton thank you very much for offering your help, it's highly appreciated! That would be great!

I have started to work on task 1 [here](https://github.com/jqmcginnis/build_biomedia_stitching), similar to [your approach](https://github.com/spinalcordtoolbox/build_ANTs), but have not started with windows and the other platform support. Moreover, I would also like to have your opinion whether we should use the apt packages if they are available, or switch to sources for all platforms to keep it consistent? You're welcome to look, improve and develop :slightly_smiling_face: !

Another question, since this discussion is increasing by the day, do you think it would be better to address task 1 and task 2 in separate issues, or should we keep everything in this issue for now?

**Comment by joshuacwnewton** [comment]
> Moreover, I would also like to have your opinion whether we should use the apt packages if they are available, or switch to sources for all platforms to keep it consistent? 

I would say to switch to sources for consistency's sake, as you say. 

> Another question, since this discussion is increasing by the day, do you think it would be better to address task 1 and task 2 in separate issues, or should we keep everything in this issue for now?

I would suggest to create a new branch in the [`build_biomed_stitching`](https://github.com/jqmcginnis/build_biomedia_stitching) repo (e.g. a `develop` branch), then open a PR from that branch to `main`. That would allow us to move our binary-related discussion to be within the PR, so that the comments stay beside the work we're doing. :)

**Comment by joshuacwnewton** [comment]
It looks like this issue wasn't properly linked to the associated PR (#3865), which has been merged. 

Closing this issue as resolved.
