### ISSUE TITLE
Replace `printv(type='error')` with proper exceptions

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3861]
In many places in SCT's code, we have `printv` statements that have `type='error'` specified. For example:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/98872496fb8325686c1d3e2c9602e20e4d960c26/spinalcordtoolbox/utils/fs.py#L98-L102

The intent here is to exit the program, but `printv` doesn't actually raise an exception, so execution will continue until... something else breaks. This will usually result in some sort of unexpected/unintentional/buggy behavior.

We've been slowly tackling these as we've come across them in other PRs, but we might want to try to tackle these all in one go by replacing them with proper exceptions, then getting rid of `type='error'` entirely.

----

By my count, there are 61 instances:

![image](https://user-images.githubusercontent.com/16181459/185143550-ca746ac6-fa69-4181-a5d4-f8ac92b0dde1.png)

Given the scope of these changes, we might want to also consider simply raising an exception within `printv`. It won't be as nice as raising properly-typed exceptions at the source, but it will make the change a one-liner, and let us more easily see what might break as a result of these changes. Could be a good intermediate/testing step?

**Comment by joshuacwnewton** [comment]
I ran into this while reviewing #3860:

If you pass a nonexistent file to `sct_process_segmentation -i`, `get_absolute_path` will return `None`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/56421f9dc4562ad04aeef82f44803e543453fbda/spinalcordtoolbox/scripts/sct_process_segmentation.py#L362

Then, the failure will happen later on, when you try to create an `Image` from `None`. This confused me a little until I realized it was `printv` at it again. :wink:

**Comment by mguaypaq** [comment]
Yes! I was just thinking that we should fix this, thanks for opening an issue.

**Comment by joshuacwnewton** [comment]
This cropped up again in https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/12 -- an `ERROR:` message was printed without throwing an exception, and processing continued further than it should have.
