### ISSUE TITLE
`algo=dl` abruptly stops with no error message when used on images that are too large

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3867]
As discovered in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3865#issuecomment-1232161658, when the following command is run:

```
sct_register_multimodal -i _VISTA_Lspine_SENSE_20210922113031_2001.nii -d _VISTA_Tspine_SENSE_20210922113031_1901.nii -param step=1,type=im,algo=dl
```

The output of `sct_register_multimodal` abruptly stops when trying to predict using the second VxmDense model:

```
Load data to register...

 Creating data tensors...

 Input shape for fixed tensor: torch.Size([1, 1, 64, 304, 304])

 Input shape for moving tensor: torch.Size([1, 1, 64, 304, 304])

 Creating VxmDense models with arguments:

{'inshape': [64, 304, 304], 'int_steps': 5, 'int_downsize': 2, 'unet_half_res': True, 'nb_unet_features': ([256, 256, 256, 256], [256, 256, 256, 256, 256, 256])}

 Loading first VxmDense model...

 Loading second VxmDense model...

 Predicting using first VxmDense model...
```

There is no indication of what went wrong, so some investigation is needed.

> **NB:** This dataset is internal/private, and can be found on `duke` in `projects/template_dog_virginiatech`

**Comment by joshuacwnewton** [comment]
When I try to debug this in PyCharm, it seems like this is caused by the OOM killer:

```
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

We were aware of this possibility when developing the approach, and reported the issue upstream: https://github.com/voxelmorph/voxelmorph/issues/434

**Comment by joshuacwnewton** [comment]
By definition, `SIGKILL`s [can't be caught by the Python process](https://stackoverflow.com/questions/30732683/python-sigkill-catching-strategies). So, we would need to either:

1. Emit a warning before the SIGKILL occurs
2. Run the inference in a subprocess, so that we can return to the parent Python subprocess and emit an error upon failure.

I think the first option would be easiest in the short-term?

**Comment by joshuacwnewton** [comment]
Previously, I debugged the performance of the model using inputs of varying dimensions here: https://github.com/voxelmorph/voxelmorph/issues/434#issuecomment-1142392972

Given this data, we could perhaps create a rough heuristic for total image volume, then compare that value to the total available RAM. Then, we could emit a warning right before prediction if we expect it to exceed the available RAM. Something like:

```
WARNING: Input image dimensions [64, 304, 304] with total volume 5.9M voxels requires ~10GB of RAM but only ~8GB is free. Please consider cropping your images around the spinal cord prior to registration to reduce input size.
```

I do wish there was a better solution for https://github.com/voxelmorph/voxelmorph/issues/434, but we weren't able to come up with a suitable solution at the time, and I'm not sure how useful my efforts will be now, either.

**Comment by jcohenadad** [comment]
> I think the first option would be easiest in the short-term?

Agreed

**Comment by joshuacwnewton** [comment]
I've been taking measurements to try and establish a relationship between `input image size` and `RAM usage`.

While doing this, I noticed something quite crucial: 

* **RAM usage stacks** when both the first and second models are kept within the same function. 
* In other words, by splitting up the two models into separate functions, you can practically cut RAM usage in half.

This is an easy refactor that will help avoid this issue in the future. (Though, I will make sure to still add a warning.)
