### ISSUE TITLE
SCT's `scripts/` folder contains outdated/neglected scripts that are not exposed to users

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3884]
```diff
joshua@tadpole:~/repos/spinalcordtoolbox$ diff <(ls spinalcordtoolbox/scripts | rev | cut -c 4- | rev | sort) <(sed -n '59,115p;116q' setup.py | cut -c 18- | rev | cut -c 3- | rev | sort)
1,2d0
< __init__
< isct_check_detection
4d1
< isct_get_fractional_volume
7,10d3
< matlab_batcher
< msct_base_classes
< msct_gmseg_utils
< __pycach
```

~~((You can ignore the last 3 scripts; this is just because `setup.py` isn't in [proper alphabetical order](https://www.diffchecker.com/XnAUyRlf). :sweat_smile:))~~

```
isct_check_detection
isct_get_fractional_volume
matlab_batcher
msct_base_classes
msct_gmseg_utils
```

I would reckon that these scripts aren't in use at all. In fact, looking at our old codecov metrics:

![image](https://user-images.githubusercontent.com/16181459/191558506-16172c7b-ae02-44c8-85e6-bd946a0cd342.png)

All 4 Python scripts are untouched by our test suite, too. 

We should possibly consider deleting these files, then moving them to https://github.com/spinalcordtoolbox/spinalcordtoolbox-dev, assuming they no longer have a place in SCT.

**Comment by mguaypaq** [comment]
As discussed in the SCT developer meeting today, we can safely move these vestigial scripts to the spinalcordtoolbox-dev repository.

**Comment by joshuacwnewton** [comment]
> vestigial scripts

Good word! :smile:
