### ISSUE TITLE
label-based registration outputs mat instead of txt file causing crash of ANTs function

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3893]
### Description

When using `sct_register_multimodal` with the type `label`, the function crashes:

~~~
Description: itk::ERROR: TransformFileReaderTemplate(0x600002cf3a80): Transform IO: MatlabTransformIOTemplate
failed to read file: warp_forward_0.mat
~~~

### Steps to Reproduce

~~~bash
# Download testing data
sct_download_data -d sct_testing_data
# go to the test data
cd $SCT_DIR/data/sct_testing_data/t2
# Run command
# note: here we register the image on itself, which is irrelevant in general, but convenient here to show the crash
sct_register_multimodal -i t2.nii.gz -d t2.nii.gz -ilabel labels.nii.gz -dlabel labels.nii.gz -param step=0,type=label,algo=rigid
~~~

<details><summary>Terminal output</summary>

```console
julien-macbook:~/code/sct/data/sct_testing_data/t2 $ sct_register_multimodal -i t2.nii.gz -d t2.nii.gz -ilabel labels.nii.gz -dlabel labels.nii.gz -param step=0,type=label,algo=rigid

--
Spinal Cord Toolbox (git-master-00ca428f20b522dd940db46cbf41f1ae233fb5a2)

sct_register_multimodal -i t2.nii.gz -d t2.nii.gz -ilabel labels.nii.gz -dlabel labels.nii.gz -param step=0,type=label,algo=rigid
--


Input parameters:
  Source .............. t2.nii.gz
  Destination ......... t2.nii.gz
  Init transfo ........ 
  Mask ................ 
  Output name ......... 
  Remove temp files ... 1
  Verbose ............. 1

Check if input data are 3D...
Creating temporary folder (/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20220929175346.938519-register-1zhn1y9q)

Copying input data to tmp folder and convert to nii...

--
ESTIMATE TRANSFORMATION FOR STEP #0
Registration parameters:
  type ........... label
  algo ........... rigid
  slicewise ...... 0
  metric ......... MI
  samplStrategy .. None
  samplPercent ... 0.2
  iter ........... 0
  smooth ......... 0
  laplacian ...... 0
  shrink ......... 1
  gradStep ....... 0.5
  deformation .... 1x1x0
  init ........... 
  poly ........... 5
  filter_size .... 5
  dof ............ Tx_Ty_Tz_Rx_Ry_Rz
  smoothWarpXY ... 2
  rot_method ..... pca
Labels src: [[6.2192840576171875, -0.7866058349609375, 24.678329467773438], [6.2192840576171875, 0.2133941650390625, -10.321670532226562]]
Labels dest: [[6.2192840576171875, -0.7866058349609375, 24.678329467773438], [6.2192840576171875, 0.2133941650390625, -10.321670532226562]]
Degrees of freedom (dof): Tx_Ty_Tz_Rx_Ry_Rz
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 1
         Function evaluations: 55
Matrix:
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
Center:
 [ 6.21928406 -0.28660583  7.17832947]
Translation:
 [[0. 0. 0.]]

--
ESTIMATE TRANSFORMATION FOR STEP #1

Apply transformation from previous step

Parse list of warping fields...

Get dimensions of data...
  60 x 55 x 52 x 1

Apply transformation...

Apply transformation and resample to destination space...
/Users/julien/code/sct/bin/isct_antsApplyTransforms -d 3 -i src.nii -o src_reg.nii -t warp_forward_0.mat -r dest_RPI.nii -n 'BSpline[3]' # in /private/var/folders/s8/4qnm5q1n261ch35b5kkclsb00000gn/T/sct-20220929175346.938519-register-1zhn1y9q
Traceback (most recent call last):
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 443, in <module>
    main(sys.argv[1:])
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_register_multimodal.py", line 421, in main
    path_out=path_out)
  File "/Users/julien/code/sct/spinalcordtoolbox/registration/core.py", line 176, in register_wrapper
    '-w'] + warp_forward
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 360, in main
    transform.apply()
  File "/Users/julien/code/sct/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 224, in apply
    ] + fname_warp_list_invert + ['-r', fname_dest] + interp, is_sct_binary=True)
  File "/Users/julien/code/sct/spinalcordtoolbox/utils/sys.py", line 414, in run_proc
    raise RuntimeError(output)
RuntimeError: Transform reader for warp_forward_0.mat caught an ITK exception:

itk::ExceptionObject (0x7fe65eb04b20)
Location: "unknown"
File: /Users/runner/work/build_ANTs/build_ANTs/antsbin/ITKv5/Modules/IO/TransformBase/src/itkTransformFileReader.cxx
Line: 144
Description: itk::ERROR: TransformFileReaderTemplate(0x600002cf3a80): Transform IO: MatlabTransformIOTemplate
failed to read file: warp_forward_0.mat
```

</details>

### Suggestion

The crash occurs because the function `isct_antsApplyTransforms` is expecting a file ending with '.txt' suffix. A simple fix is to rename the file:
~~~
cp warp_forward_0.mat warp_forward_0.txt
antsApplyTransforms -d 3 -i src.nii -o src_reg.nii -t warp_forward_0.txt -r dest_RPI.nii -n 'BSpline[3]'
~~~
--> that works

Note: this is already what we do here:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c70dad6be6721e52eac93336afda31563b43465f/spinalcordtoolbox/registration/core.py#L433-L437

which is why `sct_register_to_template` does not crash (even though it relies on landmark-based registration), but for some reasons when using `sct_register_multimodal` it does crash. 

I think it should be a very simple fix

**Comment by joshuacwnewton** [comment]
The problem stems from the fact that we're combining `type=label` with `algo=rigid`:

<details>

> 
> The output transformation is given 2 different names:
> 
> 1. `warp_forward_out`: This name is given by the inner registration functions. It takes the form `'step000GenericAffine.ext'`.
> 2. `warp_forward`: This name is given by the outer `register` func. It renames the output into `'warp_forward_0.ext'`.
> 
> For ANTs-based registration, if `algo=rigid`, then the assumption is that:
> 
> 1. `warp_forward_out` will have the `.mat` file type:
> 
>     https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c70dad6be6721e52eac93336afda31563b43465f/spinalcordtoolbox/registration/algorithms.py#L264-L267
> 
> 2. `warp_forward` assumes the output file type is `.mat`, and tries to preserve it
> 
>     https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c70dad6be6721e52eac93336afda31563b43465f/spinalcordtoolbox/registration/core.py#L427-L431
> 
> However, because `type=label`, the actual `warp_forward_out` (1.) is determined by `register_step_label` instead:
> 
> https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c70dad6be6721e52eac93336afda31563b43465f/spinalcordtoolbox/registration/algorithms.py#L329-L330
> 
> As a result, `step000GenericAffine.txt` gets renamed to `warp_forward_0.mat` under a faulty assumption.

</details>

To fix this, I think it makes sense to perform the renaming by simply preserving the file type, rather than making assumptions about file type based on  `algo` and/or `type`

**Comment by jcohenadad** [comment]
Thank you for looking into this, @joshuacwnewton . I agree with the approach.

**Comment by joshuacwnewton** [comment]
Actually, wait a minute here. Can `'type='label'` even be properly combined with `algo='rigid'`?

When I trace the code, it seems like `type='label'` has its own dedicated ITK-based [landmark registration function](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c70dad6be6721e52eac93336afda31563b43465f/spinalcordtoolbox/registration/landmarks.py#L44-L102), completely separate from ANTs-based registration (which is where `algo='rigid'` would get used). 

In fact, `type='label'` supersedes _every_ kind of `algo`, even:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c70dad6be6721e52eac93336afda31563b43465f/spinalcordtoolbox/registration/core.py#L340-L349

So, I'm pretty certain this is (also) a usage problem? In the sense that, `algo='rigid'` is entirely ignored when passed alongside `type='label'`.

**Comment by joshuacwnewton** [comment]
To me, this begs the question: Why isn't `type='label'` actually `'algo='label'` instead? 

My thinking is, if `'type='label'` is mutually exclusive with any sort of `algo`, then shouldn't it just... be an `algo` itself?

But this is a larger refactor/API change, so it might be best to leave things as-is and fix the immediate problem first.

**Comment by jcohenadad** [comment]
oh geeze, you are right. I had vague memory of this while I was using the 'label' type, not being sure what algo I should use with it, given the important 'dof' parameter, which does contradict with the algo (because, eg: putting algo=rigid with dof=SxSySz would be a paradox). So yes, it does make sense that algo is bypassed, and yes, I agree that we should find a more elegant way to deal with this confusion but this is beyond the scope of this issue.
