### ISSUE TITLE
Clean up the "Pathology" and "Tools" columns in "studies_citing_SCT"

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3897]
In https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3896, we began displaying statistics graphs from our "studies_citing_SCT" Google Sheets spreadsheet. For example:

![image](https://user-images.githubusercontent.com/16181459/194329867-1ea32de7-478f-44d1-b5e0-a1a19957c27b.png)

But, I noticed in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3857#issuecomment-1261200743 that there were some issues with the data we're keeping:

> One thing we might want to do before publishing is to go through the Pathology and Tools charts and make sure they've been entered and parsed correctly. Some immediate thoughts:
> 
> 1. We use acronyms for pathology, but it might not be 100% clear what each of these is referring to, so we may want to swap e.g. HC for Healthy Control for clarity purposes, assuming it fits space-wise on the chart.
> 2. Many of the entries for "tools used" are something like "sct_register_to_template, sct_dmri_compute_dti", but I don't think these are parsed as individual tools for the chart, meaning we get a lot of duplicate/overlapping one-off entries. So, we might want to figure out how to get Google Sheets to properly parse comma-delimited entries as individual counts for the chart.
> 3. Also, a lot of "tools used" entries are tool names ("sct_X") while others are descriptors ("Segmentation", "CSA") so we might want to unify these, too.

This is a follow-up issue to address these concerns.

**Comment by joshuacwnewton** [comment]
> 2. Many of the entries for "tools used" are something like "sct_register_to_template, sct_dmri_compute_dti", but I don't think these are parsed as individual tools for the chart, meaning we get a lot of duplicate/overlapping one-off entries. So, we might want to figure out how to get Google Sheets to properly parse comma-delimited entries as individual counts for the chart.

I've found a way to address this!

In a separate sheet, I joined all of the cells using commas for delimiting, then I split the cell based on comma-delimiting. By doing this, I was able to isolate each individual entry within cells. 

![image](https://user-images.githubusercontent.com/16181459/194330542-ee5ace40-64be-4e76-bbda-69cc96107be4.png)

This caused the graph to go from this:

![image](https://user-images.githubusercontent.com/16181459/194330748-96cc448e-516b-4fa2-a23b-3c38a900926c.png)

To this: 

![image](https://user-images.githubusercontent.com/16181459/194330820-caf10fdb-945b-4469-a4de-668f3bb7910f.png)

However, this is only a small improvement. The gargantuan task her is cleaning up these entries, ensuring that we use consistent terminology for tools used.

**Comment by joshuacwnewton** [comment]
One tricky thing here is that terms like "Segmentation", "Template" and "Atlas" are ambiguous:

* "Segmentation" could be referring to `sct_propseg` or `sct_deepseg_sc` (or potentially one of our other segmentation tools, though I'm presuming spinal cord segmentation here).
* "GM seg" could be referring to both `sct_segment_graymatter` (old) or `sct_deepseg_gm` (new)
* "Template" could be referring to the MNI-Poly-AMU template (2014-2017) or the PAM50 template (2017-present)
* "Atlas" could be referring to the Probabilistic atlas (AMU40), the white matter atlas (pre-PAM50), or the PAM50 atlas.

So, trying to actually identify the specific tools used requires understanding the state of SCT at the time of publication, which is no small feat. :sweat:

**Comment by jcohenadad** [comment]
about https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3897#issuecomment-1270091563: i don't think it is worth it to track the SCT tools used-- because: 
- large task
- published articles do not always describe the used tools accurately (ie: bias in the report)
- large effort task vs. small reward

**Comment by jcohenadad** [comment]
> and my efforts may be better spent elsewhere?

oh yes! definitely

**Comment by joshuacwnewton** [comment]
In that case, it might be easier to go in the opposite direction: Rename any instances of specific tools (`sct_deepseg`, `sct_register_to_template`, etc.) into the broader, descriptive categories (segmentation, registration, motion correction, etc.), that way we don't have to worry about any of the ambiguity and specificity.

**Comment by jcohenadad** [comment]
> In that case, it might be easier to go in the opposite direction: Rename any instances of specific tools (sct_deepseg, sct_register_to_template, etc.) into the broader, descriptive categories (segmentation, registration, motion correction, etc.). That way we don't have to worry about any of the ambiguity/need for specificity, and it's also makes it easier to tell from publications what SCT was used for (when using broader categories).

i think we don't even need to bother with that

**Comment by joshuacwnewton** [comment]
> i think we don't even need to bother with that

Thankfully, it only took ~5m because it was just a matter of finding and replacing tools with their purpose. 

(NB: I preserved the original data in their own column, so nothing has been lost, either.)

The before/after result is as follows:

![image](https://user-images.githubusercontent.com/16181459/195109455-9d46d7e0-8f7f-4ca9-85d1-7c7db427bcff.png)

This still isn't perfect, as the data is missing for many publications in the sheet, but I think this looks a lot better, and for very little effort.
