### ISSUE TITLE
`'git' is not recognized` even when `git --version` shows that `git` is accessible

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3912]
_Originally posted by @mchen1110 in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3900#issuecomment-1277712054_

> I'm trying the Native Windows installation method and I encountered an error when I try to download the install_sct.bat script:
> 
> ```
> C:\Users\miche> python --version
> Python 3.7.9
> 
> C:\Users\miche> git --version
> git version 2.38.0.windows.1
> 
> ### Downloading SCT source code (@ ) to \Users\miche\spinalcordtoolbox...
> 'git' is not recognized as an internal or external command,
> operable program or batch file.
> Failed with error #1.
> Press any key to continue . . .
> ```
>

**Comment by joshuacwnewton** [comment]
@mchen1110 Could you please retry installing SCT by:

* Redownloading the `install_sct-5.7_win.bat` file. (I've updated [v5.7](https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases/tag/5.7) to include the fix for [#3890](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3890).)
* Running the installer by typing:
   ```
   git --version && install_sct-5.7_win.bat
   ```

Thank you!

**Comment by mchen1110** [comment]
I still get an error:

C:\Users\miche> git --version && install_sct-5.7_win.bat
git version 2.38.0.windows.1
'install_sct-5.7_win.bat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by joshuacwnewton** [comment]
> ```
> 'install_sct-5.7_win.bat' is not recognized as an internal or external command,
> operable program or batch file.
> ```

Ah! Is `install_sct-5.7_win.bat` present in the `C:\Users\miche` folder? 

You can double check this by running `dir` first: 

```console
joshua:C:\Users\joshua\OneDrive\Desktop$ dir
 Volume in drive C has no label.
 Volume Serial Number is 6E62-26A5

 Directory of C:\Users\joshu\OneDrive\Desktop

10/13/2022  11:09 AM    <DIR>          .
10/13/2022  11:09 AM    <DIR>          ..
10/13/2022  10:55 AM             4,427 install_sct-5.7_win.bat
               1 File(s)          4,427 bytes
               2 Dir(s)  91,708,416,000 bytes free
```

**Comment by mchen1110** [comment]
Oh right! I moved it from Downloads to my Users folder and it worked, up until this error message:

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\miche\AppData\Local\Temp\pip-install-rhnbt0cf\dipy_beab77c0e379483da39f52dd9d6aa5b5\setup.py", line 34, in <module>
          from cythexts import cyproc_exts, get_pyx_sdist
        File "C:\Users\miche\AppData\Local\Temp\pip-install-rhnbt0cf\dipy_beab77c0e379483da39f52dd9d6aa5b5\cythexts.py", line 7, in <module>
          from packaging.version import Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed with error #1.
Press any key to continue . . .

**Comment by mguaypaq** [comment]
I manually added what appeared to be a missing dependency on [the `packaging` package](https://pypi.org/project/packaging/), and we got further in the installation, but then it complained that `onnxruntime` requires Python at least 3.8, whereas [the installation instructions specify Python 3.7.9](https://spinalcordtoolbox.com/user_section/installation/windows.html#python-3-7). We'll try again with a more recent version of Python.

**Comment by mguaypaq** [comment]
Hrm, some dependencies want Python at least 3.8, and others (ivadomed specifically) want Python strictly less than 3.9, so we're trying again with Python 3.8.10 (the latest 3.8.* which has a windows installer).

**Comment by mchen1110** [comment]
Success! Thank you @joshuacwnewton and @mguaypaq for your help!

**Comment by joshuacwnewton** [comment]
I'm glad to hear that the `git` issues have been fixed, but I'm very confused about the installer not liking Python 3.7.9. 

Just yesterday I double-checked the installation on a local Windows 10 machine, and it worked fine? No need for `packaging`, no complaints about `onnxruntime`... 

I'm curious about what's different with @mchen1110's Windows environment compared to my Windows environment (and GitHub Actions' CI runners)... :thinking:

**Comment by mguaypaq** [comment]
I should note that the error with `packaging` was only for Python 3.7.9. When we tried with Python 3.10.8 and 3.8.10, `packaging` didn't cause any errors (and I believe we start with a fresh venv for every installation?)

**Comment by joshuacwnewton** [comment]
The user [has reported](https://forum.spinalcordmri.org/t/failed-windows-sct-5-7-installation/971/3?u=joshuacwnewton) that running the installer a second time has fixed the problem.

Given that, in both cases, the issue resolved itself after some time... my theory is that there is some intermediate step (e.g. rebooting, closing and reopening Command Prompt, etc.) that is necessary between the installation of Git and the installation of SCT.

In that case, perhaps we should recommend a "Reboot your computer" step after the Git installation step, but before the SCT installation step?

**Comment by joshuacwnewton** [comment]
One other thing we could consider doing is manually appending the default installation location of Git (`C:\Program Files\Git`) to the PATH (which is a change only scoped to the batch script).

That way, even if some intermediate step _is_ needed to make `git` available to the batch script, we can force its presence in the PATH ourselves.

**Comment by kousu** [comment]
This is a crazy bug. I'm sorry I don't have any insight.

**Comment by joshuacwnewton** [comment]
One madcap solution could be to stop relying on `git` as a prerequisite for stable releases (e.g. by downloading the source code zip for stable releases, and only using `git` for dev releases)

The downside to this is that the Git Windows installer is our easiest route to providing our users with unix tools, which are necessary for `sct_run_batch` to function correctly.

**Comment by joshuacwnewton** [comment]
Ultimately, though, I think I might just try adding `PATH=%PATH%;C:\Program Files\Git` to the script, then close this issue until we receive another report of it in the future.
