### ISSUE TITLE
Minor fix: naming convention output by `sct_get_centerline`

### ISSUE THREAD

**Issue by NadiaBlostein** [spinalcordtoolbox/spinalcordtoolbox#3913]
Running`sct_get_centerline -i input.nii.gz -c contrast` yields the following output: 
* `input_centerline.nii.gz`
* `input_centerline.nii.gz.csv`. \
It is a little bit confusing to have a NIFTI extension preceding a CSV extension; could be worth changing such that the output is named as follows:
* `input_centerline.nii.gz`
* `input_centerline.csv`.

**Comment by joshuacwnewton** [comment]
Ah! Thank you so much for the suggestion. This should be a very easy fix. :smile:
