### ISSUE TITLE
Creating Multiple Sclerosis lesion quantification

### ISSUE THREAD

**Issue by yw7** [spinalcordtoolbox/spinalcordtoolbox#3914]
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/d17e52f90a971cb778d93d88306b102254e9ba2f/spinalcordtoolbox/scripts/sct_merge_images.py#L166-L169

Hi

I'm trying to create Multiple Sclerosis lesion quantification as in https://github.com/neuropoly/lesion-mapping (Not exactly the same because I'm using 2d sagittal images).
When I use sct_merge_images with 2 lesion segmentation files and 2 corresponding wraping to PAM50 I get value close to 1 in voxels that have only one of the lesion segmentation valued to 1 (I was expecting to get value of 0.5).
Also if I use the default interpolation (linear) the result merged image get off the spinal cord on PAM50.

Thank you

**Comment by yw7** [comment]
Thank you @jcohenadad. Is it ok to send the data by email?
I'm trying to investigate for solution with @mguaypaq now.

**Comment by yw7** [comment]
this is the command I used:
[1:26](https://neuropoly.slack.com/archives/D046AQ412AY/p1665595598707879)
sct_merge_images -i sub-133421_ses-20190616_stir_sag_cervical_lesionseg.nii.gz sub-133504_ses-20190923_stir_sag_cervical_lesionseg.nii.gz -d PAM50_t2.nii.gz -w sub-133421_ses-20190616_stir_sag_cervical_warp_anat2template.nii.gz sub-133504_ses-20190923_stir_sag_cervical_warp_anat2template.nii.gz -x nn

**Comment by jcohenadad** [comment]
> Thank you @jcohenadad. Is it ok to send the data by email?

Yes it is.

**Comment by joshuacwnewton** [comment]
> @joshuacwnewton do you know if this binarization was introduced recently (ie past 2 years)?

Binarization in `sct_merge_images` has been present since the very beginning of the script (6 years ago): https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/410dc9aa6469880614b2f4dfa6c1171793b3b5bd

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/410dc9aa6469880614b2f4dfa6c1171793b3b5bd/scripts/sct_merge_images.py#L138-L142

**Comment by jcohenadad** [comment]
Thank you for checking @joshuacwnewton . So, maybe we are not properly understanding the purpose of these lines:
https://github.com/neuropoly/lesion-mapping/blob/bec9e39117aab93064f0d1cfe84e9db270d4a9d5/spinalcord/1_register_data.py#L82-L85

Maybe this is not for merging lesion, and merging lesion is done at a subsequent step? @charleygros if you are seeing this your help would be greatly appreciated ❤️

**Comment by jcohenadad** [comment]
> Maybe this is not for merging lesion, and merging lesion is done at a subsequent step?

Indeed! That script `1_register_data.py` is only used to merge images (not lesion). Merging lesions is done with https://github.com/neuropoly/lesion-mapping/blob/master/spinalcord/3_generate_LFM.py. 

@yw7 could you please try that script, and once you figure out, could you please update the README which does not describe these steps (open a PR). Thanks!

**Comment by joshuacwnewton** [comment]
As this is a documentation issue with the `lesion-mapping` repo, and not an SCT issue, I have opened:

* https://github.com/neuropoly/lesion-mapping/issues/8

As a replacement for this issue.
