### ISSUE TITLE
Missing '_' in native_bin.nii.gz file name

### ISSUE THREAD

**Issue by yw7** [spinalcordtoolbox/spinalcordtoolbox#3920]
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/7b9e09112a1d907ddbeb71381f684436498ebea1/spinalcordtoolbox/scripts/sct_merge_images.py#L170

Hello SCT team,

Should it be `out.save(path=f"src_{i_file}_native_bin.nii.gz")`  like '_template_partialVolume'?
Also in line 174.

Thanks

**Comment by joshuacwnewton** [comment]
For more context, `i_file` in this case is just an integer `0, 1, 2, 3`. So, the filename would be:

* Before: `src_1native_bin.nii.gz`
* After: `src_1_native_bin.nii.gz`

I agree that this looks better! 

Though, my guess is that the original intent was for this to be the intended filename:

```python
 out.save(path=f"src{i_file}_native_bin.nii.gz") 
```

In other words, it would be  `src1_native_bin.nii.gz` (i.e. `src1`, `src2`, etc.)

Either way, I agree that the current filename doesn't look very good.
