### ISSUE TITLE
Reconsider how we test `matplotlib` and `pyqt5` on non-headless machines

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3926]
Currently, `sct_check_dependencies` includes two tests that validate whether figures can be opened in both `matplotlib` and `pyqt5`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/19e792cba3943bfd06ed792998a5054efb78d474/spinalcordtoolbox/scripts/sct_check_dependencies.py#L353-L380

However, on headless machines, these two checks will fail (due to having no display):

![image](https://user-images.githubusercontent.com/16181459/199052301-1e8a512e-ff70-45c9-a517-1c478295b6a5.png)

Considering that our test suite is headless, we fully accept these failures by intentionally not setting `e = 1` in the case of failure so that `sct_check_dependencies` will return error code `0` regardless of whether these checks fail.

Unfortunately, this also means that our test suite isn't actually testing figure-display in a useful way, meaning that errors/warnings will only reveal themselves on the machines of actual users:

* https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3925
* https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3927

This issue is for thinking about how we should test `matplotlib` and `pyqt5` so that we can mitigate issues like these.

**Comment by mguaypaq** [comment]
That sounds like a great pre-release task, yes: simply running `sct_check_dependencies` on a specific list of machines (or VMs? although I've basically never run VMs so I'm not sure how easy/hard it is to get the required licenses etc., but it would be a more reproducible test) and manually inspecting the output.

**Comment by joshuacwnewton** [comment]
> That sounds like a great pre-release task, yes: simply running `sct_check_dependencies` on a specific list of machines (or VMs? although I've basically never run VMs so I'm not sure how easy/hard it is to get the required licenses etc., but it would be a more reproducible test) and manually inspecting the output.

I've expanded the "Step 0" of our [release procedures](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Packaging:-How-to-create-a-new-SCT-release) to include both matplotlib and pyqt5 in addition to the typical FSLeyes testing.

As you say, I'd like to get a good set of instructions down for working with VMs, because it's difficult to figure everything out yourself from scratch, and it would be nice to have some sort of standardized procedures to follow.

But, I figure this could be done later this month, during the process of actually working on the pre-release tasks, so I've left it as a TODO inside the documentation for now.
