### ISSUE TITLE
Discuss relevance in adding SCT templates in https://www.templateflow.org/

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#3951]

**Comment by joshuacwnewton** [comment]
I think this is a duplicate of https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3220?

**Comment by jcohenadad** [comment]
> I think this is a duplicate of:

yes it is-- i vaguely remembered opening an issue on this in the past, but i was not sure. I saw a tweet today praising TemplateFlow so i thought it might be a good opportunity for us to be part of this initiative--
