### ISSUE TITLE
`flake8: error: unrecognized arguments: --diff` during linting CI test

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3961]
Our linting check has started failing on recent PRs. ([Example run](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/3535457184/jobs/5933500966)) 

The error given is:

```bash
##[debug]Evaluating condition for step: 'Lint with flake8'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Lint with flake8
##[debug]Loading inputs
##[debug]Loading env
Run git diff origin/master... | flake8 --diff
##[debug]/usr/bin/bash -e /home/runner/work/_temp/4a22afc9-d7d5-45e4-90ec-ba759be1d28b.sh
usage: flake8 [options] file file ...
flake8: error: unrecognized arguments: --diff
Error: Process completed with exit code 2.
##[debug]Finishing: Lint with flake8
```

Looking at the installed version of `flake8` before/after failing runs shows that automatic upgrade to `flake8=6.0.0` was the cause here. I'll see if I can find an upstream issue to link this to.

I presume we can pin to `flake8<6.0.0`, but I'm curious if `flake8` provides an alternative option to `--diff`... :thinking:

**Comment by joshuacwnewton** [comment]
I asked in https://github.com/PyCQA/flake8/issues/1749 and got an answer... sort of...

> please read the issue linked in the changelog
> 
> this is not coming back

The changelog for v6.0.0 says:

> Remove --diff option (See also [#1389](https://github.com/pycqa/flake8/issues/1389), [#1720](https://github.com/pycqa/flake8/pull/1720)).

It looks like this was deprecated in v5.0.0 via https://github.com/PyCQA/flake8/pull/1441, but we didn't get any warnings in our CI...

Oh well! Time to take a stab at understanding exactly _how_ the old `-diff` functionality was broken... :thinking:

**Comment by joshuacwnewton** [comment]
> Oh well! Time to take a stab at understanding exactly _how_ the old `-diff` functionality was broken... :thinking: 

The toy example given is:

> ```diff
>  import os
>  
>  def main():
> -    print(os.getcwd())
> +    print('hi')
> ```
> 
> `flake8 t.py` reports F401 on line 1, but `flake8 --diff` silently passes (even though the diff _caused_ that new issue)

Ah... yep. This _does_ slip through... Huh. Well, that's good to know!

I'm still fine with pinning `flake8<6.0.0` and keeping the old (but flawed) behavior, but I can also try to see if there are alternative linting checkers out there that will play nicely with git diffs.

**Comment by joshuacwnewton** [comment]
What we could do is pin `flake8` for now, then in the future, try to go ham and get SCT to a point where the whole project passes PEP8 checks.

Then, once we're at a clean slate, we can check _entire files_ that are touched by diffs, that way we catch linting errors like the one in the toy example above.

**Comment by joshuacwnewton** [comment]
> if we really want to address the faulty linting behavior described above

Ah! Or, we could create our own little set of steps to solve the above problem:

* Get a list of the changed files between `master` and the PR branch.
* Lint the changed files on `master` (to identify the existing linting issues in the files).
* Lint the changed files on the PR's branch.
* Report the _difference_ in linting issues (i.e. the new issues introduced by the PR).

This feels like it should be doable in a couple of `bash` lines?

**Comment by mguaypaq** [comment]
I think the following line would be roughly equivalent to what we had before?
```bash
git diff --name-only --diff-filter=d --merge-base master | grep '\.py$' | xargs --delimiter='\n' --no-run-if-empty flake8
```
This should list all files that differ between `HEAD` and the commit where `HEAD` split off from `master`, except files that were deleted (and so no longer exist at `HEAD`); then keep only files that end in `.py`; then run `flake8` on those entire files.

**Comment by joshuacwnewton** [comment]
Even though this issue has been resolved, I'm going to reopen this issue -- just to indicate that an alternate solution is being worked on in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3963.
