### ISSUE TITLE
Investigate weight-loading model code for `algo='dl'` method

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3964]
The algo='dl' feature was introduced in SCT v5.7 (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3807), and was tweaked in PR https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3953.

During the review process for the second PR, a few suspect lines of code were identified:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8dad90a8c6515f7e6a2bfae046dcbc2f773bb926/spinalcordtoolbox/registration/algorithms.py#L525-L543

> This seems like a convoluted way to do a fairly simple thing, but I can't say that I understand PyTorch and VoxelMorph enough to suggest a much cleaner way. Certainly out of scope for this PR, which is moving this bit of code rather than changing it.
> > _Originally posted by @mguaypaq in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3953#discussion_r1029891356_

This issue is for following up on that discussion: 

- [x] Try to better understand PyTorch conventions
- [x] Update the code if need be

**Comment by joshuacwnewton** [comment]
Typically, a model's [state dict](https://pytorch.org/tutorials/beginner/saving_loading_models.html#what-is-a-state-dict) will be saved and loaded in its entirety:

```python
# Save:
torch.save(model.state_dict(), PATH)
# Load:
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()
```

However, the `algo='dl'` function in SCT _doesn't_ follow this pattern. Instead, it loads only a subset of the trained parameters.

Take this snippet of code:

```python
    i_max = len(list(pt_model.named_parameters()))
    torchparam = pt_model.state_dict()
    for k, v in torchparam.items():
        if i < i_max:
            torchparam[k] = weights_model[i]
            i += 1
```

The full `state_dict` contains 24 entries, but the number of named parameters (`i_max`) is only equal to `22`. Meaning that: 

* The first 22 of 24 entries in `torchparam` are named parameters, copied from `trained_state_dict`.
* The last 2 of 24 entries in `torchparam` aren't copied, and instead preserved from `pt_model.state_dict()`. These are:
    * `integrate.transformer.grid`
    * `transformer.grid`

I dug into the VoxelMorph source code to try to see what's going on here, and I found [this](https://github.com/voxelmorph/voxelmorph/blob/9e205ca2a9403313d441d6772540cc0f67bc2e76/voxelmorph/torch/modelio.py#L58-L67) snippet of code:

```python
    def save(self, path):
        """
        Saves the model configuration and weights to a pytorch file.
        """
        # don't save the transformer_grid buffers - see SpatialTransformer doc for more info
        sd = self.state_dict().copy()
        grid_buffers = [key for key in sd.keys() if key.endswith('.grid')]
        for key in grid_buffers:
            sd.pop(key)
        torch.save({'config': self.config, 'model_state': sd}, path)
```

I don't think we ever actually used this function when saving `algo='dl'`? (We used PyTorch's `model.state_dict()` instead.)

But! The VoxelMorph source code at least implies that the transformer `.grid` parameters shouldn't be saved/loaded, which would explain the behavior of the weight-loading model code.

**Comment by joshuacwnewton** [comment]
> * The first 22 of 24 entries in `torchparam` are named parameters, copied from `trained_state_dict`.
> * The last 2 of 24 entries in `torchparam` aren't copied, and instead preserved from `pt_model.state_dict()`.

Given the above understanding, I think we can rewrite the weight-loading code as follows:

```python
    # Load the PyTorch model architecture
    pt_model = vxm.networks.VxmDense(**reg_args)

    # Copy over named parameters from the trained model file
    torchparam = pt_model.state_dict()
    trained_state_dict = torch.load(sct_dir_local_path('data', 'deepreg_models', fname_model))
    for (name, parameter) in pt_model.named_parameters():
        torchparam[name] = trained_state_dict[name]
    # NB: The process above will *not* copy the two unnamed parameters from the trained `state_dict`:
    #   1. 'integrate.transformer.grid'
    #   2. 'transformer.grid'
    # This is intentional; they should be preserved in their original state from `pt_model.state_dict()`.

    # Load the parameters into the model
    pt_model.load_state_dict(torchparam)
    pt_model.to(device)
    pt_model.eval()
```

This approach ditches the "list creation + loop indexing" of the original snippet, and instead explicitly transfers parameters by name. As far as I can tell, this approach produces identical results while being much easier to understand.

**Comment by mguaypaq** [comment]
Thanks for digging into this. It also looks like [`load_state_dict()` supports a `strict=False` option](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict), which might be exactly what we need? In fact this seems to be the approach taken [near the code snippet you found](https://github.com/voxelmorph/voxelmorph/blob/3f035a115d68658089795b347a985a67f3bb0664/voxelmorph/torch/modelio.py#L76). We could even check whether the non-strictness is what we expect, but maybe this is overkill and/or brittle:
```py3
    # Load the PyTorch model architecture
    pt_model = vxm.networks.VxmDense(**reg_args)

    # Copy over named parameters from the trained model file
    trained_state_dict = torch.load(sct_dir_local_path('data', 'deepreg_models', fname_model))
    missing_keys, unexpected_keys = pt_model.load_state_dict(trained_state_dict, strict=False)
    if sorted(missing_keys) != ['integrate.transformer.grid', 'transformer.grid']:
        # TODO: log something? raise an exception?
    if unexpected_keys:
        # TODO: log something? raise an exception?

    pt_model.to(device)
    pt_model.eval()
```

**Comment by mguaypaq** [comment]
That makes sense! In that case, your code snippet seems really good.
