### ISSUE TITLE
Potentially wrong date (2017) for PAM50 citation in `citing_sct.rst` page

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#3965]
In our [`citing_sct.rst`](https://spinalcordtoolbox.com/user_section/citing_sct.html#template-and-atlas) page, the PAM50 template reference has a listed date of 2017:

![image](https://user-images.githubusercontent.com/16181459/204042700-db66ee1f-1191-4c8d-9737-925f9bcbed8c.png)

However, the actual publication date is 2018:

![image](https://user-images.githubusercontent.com/16181459/204042543-15775502-328a-4ec4-97bd-63d77ccdc76b.png)

And, when this paper is cited in [other Elsevier studies](https://www.sciencedirect.com/science/article/pii/S1053811922008722#bib0019), it gets auto-linked as having a 2018 date:

![image](https://user-images.githubusercontent.com/16181459/204042750-775d6e47-f0f1-4bcc-aeef-56d16dd08165.png)

![image](https://user-images.githubusercontent.com/16181459/204042639-8b902177-b98b-462b-a85c-668a98fb824d.png)

Should this be corrected?

**Comment by jcohenadad** [comment]
oh! good catch. Yes, it should be corrected. Thanks!
