### ISSUE TITLE
`sct_propseg` - wrong name of temp centerline folder

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#3978]
### Description

Temporary folder created by `sct_propseg` to store a centerline includes misleading `-label_vertebrae-` string in its name:

```
$ sct_propseg -i sub-mon001_ses-M0_T2w.nii.gz -c t2

--
Spinal Cord Toolbox (git-master-3cfab1dbff6a1467ca2fad03d070eb2762dfa5e1*)

sct_propseg -i sub-mon001_ses-M0_T2w.nii.gz -c t2
--

Image header specifies datatype 'int16', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221208085800.685980-propseg-36oudp7g)
Image header specifies datatype 'int16', but array is of type 'float64'. Header metadata will be overwritten to use 'float64'.
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221208085800.797748-label_vertebrae-pf839gpv)
Creating temporary folder (/var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221208085800.798363-qkrg225b)
Remove temporary files...
...
```

Since the temporary folder contains a centerline:

```
$ ls /var/folders/v8/8v423b3x4g58mp5g1p33wsh00000gn/T/sct-20221208085800.797748-label_vertebrae-pf839gpv
centerline_optic.nii.gz
```

It should include `-centerline-` in its name instead of `-label_vertebrae-`.

Maybe related to https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3975

**Comment by joshuacwnewton** [comment]
Honestly, temporary folder names are pretty poor across the board (with `tmp_create` often being called with no identifying label). I had an urge during #3975 to rename the OptiC temporary folder, too.

So, this might be a good opportunity to go through all of the instances of `tmp_create` and make sure that they are using a sensible name.
