### ISSUE TITLE
Bypass dilation if the goal is to crop an image with larger input mask

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4020]
## Context

Usually in pipelines we segment the cord, dilate it, and then used the dilated cord as a mask to crop an image. See [example](https://github.com/ivadomed/model_seg_ms_mp2rage/blob/33a3a717e9b9677622b57d09980d121bf5ec0bad/preprocessing/preprocess_data.sh#L123-L127). 

While this approach works well, it is highly inefficient because the dilation can take a _looooong_ time (>1min), which is unnecessary because the cropping algorithm only needs xmin/xmax, ymin/ymax, etc.

## Solution

From the input segmentation (or whatever binary mask) and an input 'dilation', which adds a value to the max coordinate and subtract a value to the min coordinate (ie: exactly what the dilation filter would do), get the updated box coordinates for the cropping.

Example:
```
sct_crop_image -i IMAGE -m MASK -dilate 20x20x5 -o IMAGE_CROPED
```

Here, if the mask defines xmin and xmax, the output image is cropped around xmin-20 and xmax+20.

**Comment by joshuacwnewton** [comment]
I'm a bit confused: If dilation is so slow, then why are we creating the cropping mask using dilation in the first place? 

Is `sct_create_mask` not sufficient? (It's currently used in [a few of our tutorials](https://spinalcordtoolbox.com/user_section/tutorials/diffusion-weighted-mri/preprocessing.html#creating-a-mask-around-the-spinal-cord) for a similar purpose.)

**Comment by joshuacwnewton** [comment]
Also, I'm a little surprised that dilation takes as long as it does. I would have assumed it would be one of those fast array operations optimized by the underlying numerical analysis libraries (`numpy`, `scipy`, `skimage`, etc.).

When I try [the steps linked above](https://github.com/ivadomed/model_seg_ms_mp2rage/blob/33a3a717e9b9677622b57d09980d121bf5ec0bad/preprocessing/preprocess_data.sh#L123-L127) on the full-sized `t2.nii.gz` from `sct_example_data`:

```
sct_deepseg_sc -i t2.nii.gz -s t2_seg.nii.gz
sct_maths -i t2_seg.nii.gz -dilate 2 -shape ball -o t2_seg_dilate.nii.gz
sct_maths -i t2_seg_dilate.nii.gz -dilate 32 -dim 1 -shape disk -o t2_seg_dilate.nii.gz
```

The latter command (`-dilate 32`) takes ~1m as suggested.

I tried looking into this and found https://github.com/scikit-image/scikit-image/issues/1190/https://github.com/scipy/scipy/issues/13991. Specifically, it mentions that `skimage` morphological operations are much slower, the larger the structuring element gets.

So, it might be better to fix the problem at the source (slow dilation) before we consider introducing new features.

**Comment by joshuacwnewton** [comment]
Digging into this a little further -- the options `-dilate 32 -dim 1 -shape disk` result in SCT's code creating a structuring element that is `[65, 65, 65]`! This is _huge_.

However, the structuring element is just a disc -- the vast majority of slices are are `0`.

![image](https://user-images.githubusercontent.com/16181459/215591474-3617491d-ba93-430e-a90c-965d74c4759e.png)

So, do we really need an SE this large? Surely there are ways we can optimize our code to not perform a 3D convolution for what is essentially a 2D slicewise operation...

**Comment by joshuacwnewton** [comment]
Sticking with the (seemingly inefficient) 3D structuring element for now, I'm going to try the first workaround from https://github.com/scikit-image/scikit-image/issues/1190#issuecomment-57939158:

> If you use uint8 or uint16 images, you should be using skimage.filters.rank.{minimum,maximum}.

Trying this with our `65x65x65` SE:

```python
    footprint = _get_footprint(shape, size, dim)
    out_1 = filters.rank.maximum(data, footprint)
    out_2 = dilation(data, footprint=footprint, out=None)
```

`filters.rank.maximum` is _significantly_ faster, taking only 6s, as opposed to >4m. And, the results seem to be identical:

![image](https://user-images.githubusercontent.com/16181459/215594322-7d597521-084c-4d9d-a2f7-cfe2ef83a7a8.png)

I want to dig deeper, but at the very least, we have some proof that we're doing a lot more computation than we need to be doing.

**Comment by jcohenadad** [comment]
Thank you for digging @joshuacwnewton . Before digging further I’d like to propose that we change our approach for cropping: dilation should not be necessary. Adding a parameter in sct_crop_image to add a margin on the input mask will do the job waaaay faster (and it one less syntax for users to execute)

**Comment by joshuacwnewton** [comment]
> Adding a parameter in sct_crop_image to add a margin on the input mask will do the job waaaay faster (and it one less syntax for users to execute)

Would we also apply this workflow to our tutorials (e.g. [DMRI](https://spinalcordtoolbox.com/user_section/tutorials/diffusion-weighted-mri/preprocessing.html))?

- Current: Segmentation -> `sct_create_mask` -> `sct_crop_image -m` 
- Proposed: Segmentation -> `sct_crop_image`

Essentially cutting out the middle `sct_create_mask` step?

**Comment by mguaypaq** [comment]
I can take this on in the next few days.

**Comment by mguaypaq** [comment]
Now that the feature is implemented, are there specific people or projects we should tell so that they can get the speedup?

**Comment by joshuacwnewton** [comment]
> Now that the feature is implemented, are there specific people or projects we should tell so that they can get the speedup?

The example that @jcohenadad mentioned (that triggered this issue, I assume) was [`model_seg_ms_mp2rage`](https://github.com/ivadomed/model_seg_ms_mp2rage), which I think Julien was working on alone? (Please correct me if I'm wrong, though!)

I'm not sure if that script was based off of some sort of example/template script that we could update.

We may also want to consider updating any tutorials and/or `batch_processing.sh` that were previously using `sct_create_mask` for this purpose. (I think it's just the dMRI and fMRI sections, but it would be good to double-check?)

**Comment by jcohenadad** [comment]
> We may also want to consider updating any tutorials and/or batch_processing.sh that were previously using sct_create_mask for this purpose. 

Yes! 💯
