### ISSUE TITLE
Remove the `round_and_clip` function from `centerline/core.py`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4029]
In https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4026#discussion_r1096182595, some confusion arose due to the `round_and_clip` function, which calls `np.round` and `np.clip`, but adds some subtle behavior changes, most notable a `-1`.

On further inspection, though, this function's existence is confusing, as there's not really any added benefit/functionality beyond the underlying `numpy` functions themselves:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0f228da127cc78408462b824624564ea7e09a7ba/spinalcordtoolbox/centerline/core.py#L275-L278

Why not just call `np.round` and `np.clip` individually when needed?

Additionally, `round_and_clip` is only truly called twice, both in the context of `centerline/core.py`, so its usage isn't even widespread:

![image](https://user-images.githubusercontent.com/16181459/217347842-e9beab93-5546-40b9-ad5b-63443c21f901.png)

Given that it's a source of confusion, I would suggest to get rid of it entirely?

**Comment by mguaypaq** [comment]
There's also not much sense having a function called `round_and_clip` which defaults to _not_ clipping.

**Comment by co-decode** [comment]
Hi, I would like to give this a shot.
