### ISSUE TITLE
Ensemble/bagging for model inference

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4036]
# Context / Description

When training several deep learning models in production (split 80/20/0) with different seeds, the idea is to average all predictions to generate a more reliable soft prediction. This approach is called ensemble/bagging.

It would be good to have an option in `sct_deepseg` to select ensemble, if more than one model is present. Example:

This feature is relatively high priority, because it is in the context of a collaboration with a team of researchers in Basel, Switzerland. 

Also, given the upcoming drop of ivadomed's dependency (and the quasi-null number of users for `sct_deepseg`), I would find it acceptable to put together a 'quick' prototype, that could then be tested and improved in future PRs.

# Suggestion

## Store multiple models

> **Note**
> Model file name should have the same name as the parent folder (eg: `model_blabla/model_blabla.pt`)

Because the `ivadomed.inference.segment_volume()` function expects the model file to have the same name as the parent folder, models could be stored as:
```
├── seed10
│   └── model_seg_lesion_mp2rage
│       ├── model_seg_lesion_mp2rage.json
│       └── model_seg_lesion_mp2rage.pt
├── seed11
│   └── model_seg_lesion_mp2rage
│       ├── model_seg_lesion_mp2rage.json
│       ├── model_seg_lesion_mp2rage.onnx
│       └── model_seg_lesion_mp2rage.pt
├── seed7
│   └── model_seg_lesion_mp2rage
│       ├── model_seg_lesion_mp2rage.json
│       └── model_seg_lesion_mp2rage.pt
├── seed8
│   └── model_seg_lesion_mp2rage
│       ├── model_seg_lesion_mp2rage.json
│       └── model_seg_lesion_mp2rage.pt
└── seed9
    └── model_seg_lesion_mp2rage
        ├── model_seg_lesion_mp2rage.json
        └── model_seg_lesion_mp2rage.pt
```

Currently, single models are stored as:
```
julien-macbook:~/code/spinalcordtoolbox/data $ tree deepseg_models/
deepseg_models/
├── mice_uqueensland_gm
│   ├── mice_uqueensland_gm.json
│   └── mice_uqueensland_gm.pt
├── mice_uqueensland_sc
│   ├── mice_uqueensland_sc.json
│   └── mice_uqueensland_sc.pt
├── model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg
│   ├── README.md
│   ├── image.gif
│   ├── model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.json
│   └── model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.pt
└── t2star_sc
    ├── t2star_sc.json
    └── t2star_sc.pt
```

So the proposed change implies one additional directory depth, which we need to account for in the code.

Modification in the list of model:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aef83eb1482ea9360065ac8d8913aaf18edd4ce8/spinalcordtoolbox/deepseg/models.py#L90-L99

Would be replaced by:
```python
    "model_seg_ms_lesion_mp2rage": {
        "url": [
            "https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20211223/model_seg_ms_lesion_mp2rage_seed1.zip",
            "https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20211223/model_seg_ms_lesion_mp2rage_seed2.zip",
            "https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20211223/model_seg_ms_lesion_mp2rage_seed3.zip",
            "https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/r20211223/model_seg_ms_lesion_mp2rage_seed4.zip",
        ],
        "description": "Segmentation of multiple sclerosis lesions on cropped MP2RAGE spinal cord data. To crop the "
                       "data you can first segment the spinal cord using the model 'model_seg_ms_sc_mp2rage' and "
                       "then crop the MP2RAGE image using 'sct_crop_image -i IMAGE -m IMAGE_seg'",
        "contrasts": ["mp2rage"],
        "default": False,
    },
```

## Modify `sct_deepseg.py` script

Interestingly, the script already accommodates multiple models:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aef83eb1482ea9360065ac8d8913aaf18edd4ce8/spinalcordtoolbox/scripts/sct_deepseg.py#L187

The only missing part, is a piece of code, after running all inferences, that averages all inferences, _only if the ensemble feature was selected_. 

## Modify UI

Example of usage:

```console
# Default behavior, only use the first model
sct_deepseg -i IMAGE -task TASK 
# Specifying ensemble feature, how many models to run
sct_deepseg -i IMAGE -task TASK -ensemble 5
```

# Testing

The feature can be tested with the (draft) models: https://github.com/ivadomed/model_seg_ms_mp2rage/releases/tag/untagged-30de7f9b3e6d2ae55210
Models are called `model_seg_lesion_mp2rage_seed7.zip`, `model_seg_lesion_mp2rage_seed8.zip`, etc.

**Comment by jcohenadad** [comment]
> 1. The 'url' field is being used for 2 separate things: Download mirror URLs and ensemble model URLs:

Ah! Very good point! Given that (i) there are very few users of sct_deepseg (ie: behaviour can change) and (ii) mirror is likely not required because GH is fairly stable and accessible, I would suggest to get rid of the 'mirror' feature and use multiple URLs for ensemble.

> 2. If a user runs sct_deepseg -install-task, will it download all of the models at once?

Yes. Let's go simple.

> 3. What should the default behavior of the -ensemble flag be?

see below 

> 4. Do we even need an -ensemble flag?

Actually, this is a good point. Let's keep things simple, and always do inference on all the available models. If ppl want to experiment with less models, they can always manually remove them from the SCT/data/models_deepseg directory. 
Oh but wait: that wouldn't work, because the number of models is dictated by the models.py file (is that right?), if that's the case, maybe we can change that behaviour and simply run all models that are present in a directory (but that could be a feature for later...).

> 5. Do we actually need to change the directory structure?

Based on ivadomed's restriction (ie: model file name should be the same as enclosing directory name), I think we do. But I agree, this is a bit cumbersome. While working on the MONAI transition, we should revisit this requirement.

**Comment by joshuacwnewton** [comment]
> >  4. Do we even need an -ensemble flag?
> Let's keep things simple, and always do inference on all the available models. If ppl want to experiment with less models, they can always manually remove them from the SCT/data/models_deepseg directory. 

:+1: 

> Oh but wait: that wouldn't work, because the number of models is dictated by the models.py file (is that right?),

Not necessarily! `models.py` is just used for downloading/extracting the models (i.e. `-install-task`).

But, in terms of actually running the `-task`, at runtime, we could load only the models present in the directory. (Meaning that removing a model would function as you suggest.) Then, we could print a warning saying something like:

```python
print(f"WARNING: Expected {n_in_models.py} models but only found {n_files}. "
      f"Ensembled inference will be run using only {n_files} total models. If this is unexpected, "
      f"please re-run 'sct_deepseg -install-task {task_name}' to reinstall all {n_in_models.py} models.")
```

I think there is some flexibility here -- I will play around with it in my WIP demo.

----

> > 5. Do we actually need to change the directory structure?
> 
> Based on ivadomed's restriction (ie: model file name should be the same as enclosing directory name), I think we do. But I agree, this is a bit cumbersome. While working on the MONAI transition, we should revisit this requirement.

Just to clarify, by "ivadomed restriction", do you mean:

1. The `.zip` archives are structured in a specific way to meet ivadomed requirements, or:
2. The `ivadomed.inference.segment_volume()` function expects the model filepath to have a specific structure

I think we could work around either of these restrictions fairly easily? (I'd have to test / demo just to be sure.)

But, I might be misunderstanding, and maybe there is a third restriction that I'm not thinking of.

**Comment by jcohenadad** [comment]
> The ivadomed.inference.segment_volume() function expects the model filepath to have a specific structure

that one, unfortunately

**Comment by joshuacwnewton** [comment]
> > 1. The 'url' field is being used for 2 separate things: Download mirror URLs and ensemble model URLs:
> 
> Ah! Very good point! Given that (i) there are very few users of sct_deepseg (ie: behaviour can change) and (ii) mirror is likely not required because GH is fairly stable and accessible, I would suggest to get rid of the 'mirror' feature and use multiple URLs for ensemble.

There is a small issue with this suggestion: Right now, `sct_deepseg` reuses the same internal download logic as `sct_download_data`. This means that the behavior of "interpret a list of URLs as mirrors and fallback if failure" can't be removed without also affecting `sct_download_data`.

That's okay, though. I have an alternate solution that allows us to keep both the "mirror URL" functionality and the "list of seed URLs" functionality.

**Comment by joshuacwnewton** [comment]
> The feature can be tested with the (draft) models: https://github.com/ivadomed/model_seg_ms_mp2rage/releases/tag/untagged-30de7f9b3e6d2ae55210

There is a small issue with this: "draft" releases seem to 404 with download utilities like `sct_download_data` or even `wget`:

<details>

```console
(venv_sct) jn/4036-add-ensembling-to-sct_deepseg|joshua@tadpole:~/repos/spinalcordtoolbox$ wget https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/untagged-30de7f9b3e6d2ae55210/model_seg_lesion_mp2rage_seed7.zip
--2023-02-14 16:07:26--  https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/untagged-30de7f9b3e6d2ae55210/model_seg_lesion_mp2rage_seed7.zip
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-14 16:07:26 ERROR 404: Not Found.

(venv_sct) jn/4036-add-ensembling-to-sct_deepseg|joshua@tadpole:~/repos/spinalcordtoolbox$ sct_deepseg -install-task seg_ms_lesion_mp2rage

--
Spinal Cord Toolbox (git-jn/4036-add-ensembling-to-sct_deepseg-de6ed459ac51154bc585ece7146d05f5bad0d409*)

sct_deepseg -install-task seg_ms_lesion_mp2rage
--


INSTALLING MODEL: model_seg_ms_lesion_mp2rage
    Installing 'seed7'...
Removing existing destination folder '/home/joshua/repos/spinalcordtoolbox/data/deepseg_models/model_seg_ms_lesion_mp2rage'
Trying URL: https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/untagged-30de7f9b3e6d2ae55210/model_seg_lesion_mp2rage_seed7.zip
Link download error, trying next mirror (error was: 404 Client Error: Not Found for url: https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/untagged-30de7f9b3e6d2ae55210/model_seg_lesion_mp2rage_seed7.zip)
Traceback (most recent call last):
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 251, in <module>
    main(sys.argv[1:])
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 154, in main
    models.install_model(name_model)
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/deepseg/models.py", line 275, in install_model
    download.install_data(model_urls, folder(name_model))
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/download.py", line 286, in install_data
    tmp_file = download_data(url)
  File "/home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/download.py", line 222, in download_data
    raise Exception('Download error', exceptions)
Exception: ('Download error', [HTTPError('404 Client Error: Not Found for url: https://github.com/ivadomed/model_seg_ms_mp2rage/releases/download/untagged-30de7f9b3e6d2ae55210/model_seg_lesion_mp2rage_seed7.zip')])
```

</details>

I am going to try change the release from "Draft" to "Published, but pre-release" that way the downloads will work for testing, but the release will be hidden from the main repo page.

**Comment by joshuacwnewton** [comment]
There is another small issue with the draft models. Between the last release and this new draft release, the name of the model was subtly changed from `model_seg_ms_lesion_mp2rage` to `model_seg_lesion_mp2rage`. 

<details>

Before:

![image](https://user-images.githubusercontent.com/16181459/218870198-ce1a94e8-4ef0-428d-860f-a3ccdc173510.png)

After:

![image](https://user-images.githubusercontent.com/16181459/218869751-fcca253e-ad8a-45f3-82f5-f18faf7fd6e7.png)

</details>

This means that we need to change the name of the existing entry for `model_seg_ms_lesion_mp2rage`, since it no longer matches the model name:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aef83eb1482ea9360065ac8d8913aaf18edd4ce8/spinalcordtoolbox/deepseg/models.py#L90

Not a huge deal, but I thought I would point it out.
