### ISSUE TITLE
Add  `data_normalize_metric_pam50` in `sct_download_data`

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#4044]
## Description

Related to the `sct_compute_compression `function #4003 , we added some morphometrics of healthy controls to normalize compression morphometrics in https://github.com/spinalcordtoolbox/data_normalize_metric_pam50. We ow need to add the download in `sct_download_data` during installation.

**Comment by mguaypaq** [comment]
I'll unassign myself, since this is being done as part of #4003 (after [this merge commit](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4003/commits/124cf661520019ade1ef7cbb5204082f6a10ebf2)).
