### ISSUE TITLE
New option `-centerline-soft` will quietly output binary segmentation if `-method fitseg` is not specified

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4062]
I wanted to try out `-centerline-soft`, but accidentally forgot to specify `-method fitseg`, so the default value of `-method optic` was used instead.

Despite specifying the wrong command, the script will continue, quietly outputting a binary segmentation, and will even apply the `red-yellow` colormap to this binary segmentation. This goes against user expectations. 

I would suggest to add a small error that prevents `-centerline-soft` from being used with non-fitseg methods.

**Comment by valosekj** [comment]
Great catch!

> I would suggest to add a small error that prevents `-centerline-soft` from being used with non-fitseg methods.

Agree!
