### ISSUE TITLE
Wrong description for deepseg model

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4064]
### Description

When working on #4042, I edited the model description:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c59867e436cb0b4bb5c3c23d9074ebf250e1b7a7/spinalcordtoolbox/deepseg/models.py#L102-L107

But was then surprised to discover that it is not listed when doing: 
```console
sct_deepseg -list-tasks-long
TASK:             seg_ms_lesion_mp2rage
LONG_DESCRIPTION: This segmentation model for MP2RAGE MS lesion segmentation uses a Modified3DUNet architecture, and was created with the `ivadomed`
                  package. Training data consisted of 30 multiple sclerosis (MS) patients that included manual segmentations of the spinal cord and MS
                  lesions. The dataset was preprocessed to crop around the spinal cord prior to training. This dataset was provided by the University
                  of Basel.
URL:              https://github.com/ivadomed/model_seg_ms_mp2rage
INSTALLED:        Yes
```

After looking to make sure i have the correct version running locally, etc. I realized that there are two descriptions, one for the model and one for the task. The task description is here:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/c59867e436cb0b4bb5c3c23d9074ebf250e1b7a7/spinalcordtoolbox/deepseg/models.py#L185-L189

And this one _also_ needed to be updated.

### Suggestions

Short term: Fix the long description.

Long term: re-think the locations of "descriptions" for models and tasks, as it is currently confusion and error-prone.

**Comment by joshuacwnewton** [comment]
> Long term: re-think the locations of "descriptions" for models and tasks, as it is currently confusion and error-prone.

Are the "model" descriptions even used for anything? They're not displayed for `-list-tasks` or `-list-tasks-long` (instead, the task descriptions are used). So, I'm wondering what their purpose even is.

If there's no good use for the model descriptions, then I would suggest removing them entirely. Or, making them an inline comment instead, that way it's clear that these are developer-only descriptions.

**Comment by jcohenadad** [comment]
> Are the "model" descriptions even used for anything? They're not displayed for -list-tasks or -list-tasks-long (instead, the task descriptions are used). So, I'm wondering what their purpose even is.
If there's no good use for the model descriptions, then I would suggest removing them entirely. Or, making them an inline comment instead, that way it's clear that these are developer-only descriptions.

Agreed-- this could be implemented when comes the time to transition to MONAI models.
