### ISSUE TITLE
ReadTheDocs builds are failing due to upstream `PATH` issues

### ISSUE THREAD

**Issue by mguaypaq** [spinalcordtoolbox/spinalcordtoolbox#4082]
It seems that there's a failure when building ReadTheDocs pages for SCT affecting all PRs (for example, #4078, #4074). Looking at the build logs (for example, [the 4078 log](https://readthedocs.org/api/v2/build/19933629.txt) and [the 4074 log](https://readthedocs.org/api/v2/build/19934014.txt)), I see the following clue:
```
119: WARNING: Command ['sct_analyze_lesion', '-h'] failed: [Errno 2] No such file or directory: 'sct_analyze_lesion'
125: WARNING: Command ['sct_analyze_texture', '-h'] failed: [Errno 2] No such file or directory: 'sct_analyze_texture'
131: WARNING: Command ['sct_apply_transfo', '-h'] failed: [Errno 2] No such file or directory: 'sct_apply_transfo'
137: WARNING: Command ['sct_compute_ernst_angle', '-h'] failed: [Errno 2] No such file or directory: 'sct_compute_ernst_angle'
143: WARNING: Command ['sct_compute_hausdorff_distance', '-h'] failed: [Errno 2] No such file or directory: 'sct_compute_hausdorff_distance'
...
```
So it looks like the SCT scripts are not being found on the PATH in the step which generates [the command-line help page](https://spinalcordtoolbox.com/user_section/command-line.html).

**Comment by mguaypaq** [comment]
For contrast, here are the build logs for some **previous successes** on the same pull requests:
- [4078 passing](https://readthedocs.org/api/v2/build/19932219.txt)
- [4074 passing](https://readthedocs.org/api/v2/build/19923076.txt)

**Comment by joshuacwnewton** [comment]
I tried running a local Sphinx build of the documentation on `master` by running:

```bash
pip install -e ".[docs]"
cd documentation
make html
```

And it ran fine without errors. (I also ran it again on the branch for #4078, using `make clean html`, and again, no errors.)

Given this, plus the lack of dependency changes between passing and failing runs on the PR branches, I'm wondering if this is some kind of issue internal to RTD... :thinking:

**Comment by joshuacwnewton** [comment]
For now, what do you say to going ahead and merging PRs using administrative privileges for any PR that doesn't touch the documentation?

**Comment by joshuacwnewton** [comment]
It looks like RTD [just deployed some changes to how the PATH is computed](https://github.com/readthedocs/readthedocs.org/issues/10203#issuecomment-1487467158), which would explain the issue we're facing here.

**Comment by joshuacwnewton** [comment]
This has been [fixed upstream](https://github.com/readthedocs/readthedocs.org/issues/10203#issuecomment-1487502493). Retriggered builds are now passing. :tada:
