### ISSUE TITLE
Get rid of `# Modified by:`, `# Author:`, `# Copyright <date>`, etc. in script headers

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4117]
Ever since SCT's beginning, CLI script authors have followed a template for the header of each script, containing lines referencing authors/dates. 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/822d1a34bd672d288ccf6c56316833f030a195fa/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L5-L7

These lines tend to raise questions when making updates (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4112#discussion_r1195012975), as we don't really have a protocol for updating dates/authors.

Additionally, because we have git, the record of when and who modified a file is already present.

So, to avoid future confusion, we could do a full sweep of all CLI scripts to remove author/date information from each script. (Question: Which information to remove, and which to keep?)

**Comment by joshuacwnewton** [comment]
I'm glad to see that the blog post emphasizes using [only the creation date](https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#why-not-bump-the-year-on-change). That makes it so that we won't have to continuously update the date on scripts. 

Thank you so much for taking the time to dig to find this blog post! It seems like a very helpful resource. :blush:

**Comment by mguaypaq** [comment]
I just updated [the recommended copyright and license header in the dev wiki](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming:-CLI-script-structure#1-setup-description-and-attribution). I'll make a PR to update the individual files next.
