### ISSUE TITLE
emoji improperly displayed

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4140]
![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/dd39a81c-a77f-4baf-a825-5695dadfc729)

**Comment by mguaypaq** [comment]
Some initial observations:
- This is the only instance of `:tada:` in the documentation.
- The corresponding source file is somewhat special: it's a symbolic link to [CONTRIBUTING.rst](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/CONTRIBUTING.rst) in the root of the SCT repo (outside of the documentation subtree).
- Github's `.rst` renderer does handle `:tada:` in the expected way.
- After a quick look, I only found [one other docs page](https://spinalcordtoolbox.com/overview/testimonials.html) with emojis. In the corresponding source file, the emojis are just embedded directly in utf-8, not encoded as `:something:`.

I'm not sure if this particular emoji has ever worked in the ReadTheDocs version, but it looks like the simplest fix is to use the utf-8 encoding in the source. I'll do that now.

(Another fix might be to add the [sphinxemoji](https://sphinxemojicodes.readthedocs.io/en/stable/) extension, but I'm not sure it's worth adding a new dependency for a single character on one page.)
