### ISSUE TITLE
Backport fixes for ivadomed and submodule access to v5.8

### ISSUE THREAD

**Issue by mguaypaq** [spinalcordtoolbox/spinalcordtoolbox#4163]
This issue is here to summarize two fixes backported to v5.8. See [the wiki page](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Packaging%3A-Backporting-bugfixes) for the process.

1. To deal with #4148, we bumped the version of `ivadomed` in `requirements-freeze.txt` from 2.9.7 to 2.9.8.
    The [changelog](https://github.com/ivadomed/ivadomed/blob/master/CHANGES.md#v298-2023-01-04) is pretty small, and doesn't look like it introduces significant changes that would alter any results from SCT v5.8.
   Also, checking `pip freeze` on two fresh installs of SCT v5.8, with and without the patch, shows that no other dependencies' versions got affected.

2. As suggested in [this comment on #3972](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3972#issuecomment-1625716497), we cherry-picked the fix from #3973 to some bad module imports.

Fixes #4148.

**Comment by joshuacwnewton** [comment]
> Also, checking pip freeze on two fresh installs of SCT v5.8, with and without the patch, shows that no other dependencies' versions got affected.

Oh, thank goodness! Such good news. :tada:

**Comment by mguaypaq** [comment]
Done in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/b8be5c4debcb2cbe3a02636d7a0b78172b411876, published as [SCT v5.8](https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases/tag/5.8).
