### ISSUE TITLE
`sct_propseg` issue with '.' in command line

### ISSUE THREAD

**Issue by plbenveniste** [spinalcordtoolbox/spinalcordtoolbox#4167]
### Description

There is a problem with `sct_propseg`when using './folder/data/image.nii.gz' for the output. The '.' is the reason for the problem. 

### Steps to Reproduce

0. Install SCT 6.0
1. Perform the following command on Joplin : 
  `sct_propseg -i sub-edm143_ses-M0_PSIR.nii.gz -c t1 -o ./test/sub-edm143_ses-M0_PSIR_seg.nii.gz`

More information can be found [here](https://github.com/ivadomed/canproco/issues/37#issuecomment-1646115232)

I also noted that, by iterating over files in a Python script, the following poses a problem `/home/GRAMES.POLYMTL.CA/` as it contains '.' in the file name. 

**Expected behavior:** 

I expected to get the output of the segmented image

**Actual behavior:** 

Segmentation incomplete because of output folder

**Comment by joshuacwnewton** [comment]
As another short-term fix, you can also use `test/sub-edm143_ses-M0_PSIR_seg.nii.gz` (excluding the `./`) part. 

But, the cases you point out (especially `/home/GRAMES.POLYMTL.CA`) are especially concerning, so I'll look into this right away. :)

**Comment by mguaypaq** [comment]
Ah, `sct_propseg` has both `-o` and `-ofolder` options, and we've discussed the potential for confusion before, in #4070. I haven't looked at the linked PR yet, but the quickest fix is to use the options as intended: `-o` should be just the output file _name_ (with no path), and `-ofolder` should give the output _path_ (which will contain the segmentation with the name given in `-o`, and the centerline with the non-customizable name `<inputname>_centerline.nii.gz`).
