### ISSUE TITLE
Add SCT tutorial about registering lumbar images using 2 labels

### ISSUE THREAD

**Issue by mguaypaq** [spinalcordtoolbox/spinalcordtoolbox#4180]
This is a feature request that came out of the SCT dev meeting on 2023-07-27 ([minutes](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.3jazj3wbpm6z)), motivated by several discussions at recent conferences.

We should add explicit tips in SCT tutorials and courses about registration of lumbar images using 2 labels. There's already an explanation of this in a forum post ([link](https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/8?u=valosekj)), but most people don't see it (understandably!). Maybe we should also update the usage string for `sct_register_to_template`?

For context:
- Possibly related to #2607 and #3073 about running `sct_label_vertebrae` in the lumbar FOV?
- For using **more than 2** labels, this is related to the documentation update in #3602.
- For the lumbar SC segmentation of T2w images, we have a deepseg model since #3766.
- This is _almost_ a duplicate of #3599, which is about the same problem, but from the technical side, rather than the documentation/training side.

**Comment by jcohenadad** [comment]
Related to https://github.com/spinalcordtoolbox/PAM50/issues/19

**Comment by joshuacwnewton** [comment]
Note that we now have a [second, additional forum post](https://forum.spinalcordmri.org/t/registration-of-lumbar-data-to-pam50/1109/6) for lumbar registration, alongside new replies with recommendations from @jcohenadad. Additionally, several of the wonky bugs have been ironed out on both the SCT and PAM50 side. So, I think writing this tutorial should be even easier now.

Assuming this is something we still want for the 6.1 milestone and/or SCT course, I could try taking a stab at writing it? :)

**Comment by jcohenadad** [comment]
> Assuming this is something we still want for the 6.1 milestone and/or SCT course, I could try taking a stab at writing it? :)

that would be absolutely amazing!

**Comment by joshuacwnewton** [comment]
One thing that we will need to figure out is which image to use as "example data", as the current tutorial dataset does not contain images with visible lumbar regions.

For now, I can temporarily use data from the forum posts (only locally -- not committed to git -- just to create a draft/skeleton of the tutorial), then we can substitute proper example data. But, I'm not sure where to source the example data from...

**Comment by joshuacwnewton** [comment]
Another point of contention: Our lumbar segmentation tool (`sct_deepseg -task seg_lumbar_sc_t2w`) was trained only on T2 data, as far as I understand.

Does this mean that, if users have have T1/T2*-like data, they must manually segment their lumbar images? (deepseg_sc/propseg seemed ill-equipped to segment the lumbar region when testing on one user's data)

If this is the case, then we will need to use T2 example data for the tutorial (to demo `sct_deepseg`), while also being explicit about what our recommendations will be for images that cannot be segmented by `sct_deepseg`.

**Comment by jcohenadad** [comment]
> One thing that we will need to figure out is which image to use as "example data", as the current tutorial dataset does not contain images with visible lumbar regions.

ah! good point. @NathanMolinier can you please identify one of the Montreal PAM50 data, you can crop to only keep the lumbar part so it is not a gigantic image (or maybe only select the lower part, before stitching)-- thx!

**Comment by joshuacwnewton** [comment]
I am having some trouble understanding what the desired registration results should be for the first forum post ([data here](https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/13?u=joshuacwnewton)). 

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/a6664887-6773-4a03-abbd-e3b6227d020b)

- **Left:** PAM50 (T2 + cord, cursor placed at cauda equinea label `[70, 70, 40]`)
    - In the PAM50 case, the cord extends all the way to the cauda equinea label.  
    - Also, note that the conus medullaris is about even with the L1-L2 disc (`21`).
- **Right:** User data (T2 + cord, cursor placed at user's chosen cauda equinea label `[32, 236, 439]`)
    - In the user's case, the automatic cord segmentation ends prior to the L1-L2 disc.
    - In such a case, using the bottom of the automatic cord segmentation as a registration landmark causes a mismatch of the discs:
    ![lumber-registration_disc-mismatches](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/c2a7563a-58fc-4179-970c-cb5f03ba8c13)
    - Note: We are limited by where we can place the cauda equinea label, because if it is placed below the bottom of the segmentation, we will run into issue [#3873](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3873).
    - In spite of this, the user placed their cauda equinea label below the bottom of the segmentation, and then supposedly "[fixed the segmentation](https://forum.spinalcordmri.org/t/labels-for-lumbar-spinal-level/737/14?u=joshuacwnewton)" such that registration wouldn't fail. (I am unclear what their fixed segmentation looks like.)

So, my main question is: How should we approach this situation?

1. Place the label at the bottom of the cord segmentation (as in my first attempt), and accept that there will be mismatched discs.
2. Place the label below the automatic cord segmentation, and manually extend the segmentation (as the user did).
3. Some alternative?

Depending on the answer, my recommendations in the tutorial will differ. (I'm assuming there will naturally be some variation in the positioning of the conus medullaris relative to the discs, and so I want to provide some guidance for how to handle this variation when manually placing labels for registration.)

**Comment by jcohenadad** [comment]
> So, my main question is: How should we approach this situation?
1. Place the label at the bottom of the cord segmentation (as in my first attempt), and accept that there will be mismatched discs.
2. Place the label below the automatic cord segmentation, and manually extend the segmentation (as the user did).
3. Some alternative? (e.g. fixing the registration script so that labels outside the segmentation are OK)

Excellent question. This is a tricky one. I would say, a combination of 1 and 2, ie: fix the segmentation (to make sure it goes all the way to the cauda  equinea) and place the label at the bottom of the segmentation (which then corresponds to the cauda equinea).

**Comment by joshuacwnewton** [comment]
In that case, I presume that it's expected that the discs would be misaligned? If so, I can add a note to the tutorial saying something like:

> If you choose to use the cauda equinea as a registration landmark, please be aware that there may be a misalignment between the PAM50 discs and your subject's discs. This is unavoidable, due to natural inter-subject variability in the position of the cauda equinea relative to the L1-L2 disc, which may not match the relative position for the PAM50 template.)

That way, users have a clear understanding of what landmarks the registration was optimized for (and what landmarks are disregarded).

**Comment by NathanMolinier** [comment]
> ah! good point. @NathanMolinier can you please identify one of the Montreal PAM50 data, you can crop to only keep the lumbar part so it is not a gigantic image (or maybe only select the lower part, before stitching)-- thx!

I tried to identify lumbar scans in our current datasets and I found some subjects in `sct-testing-large` with the name `sub-ivdm3seg*`. I will try to dig deeper into the PAM50 data, but the `whole-spine` dataset do not contain the lumbar region.

**Comment by jcohenadad** [comment]
> but the whole-spine dataset do not contain the lumbar region.

sure it does, that’s how we built the PAM50 template (which contains the lumbar cord)

**Comment by joshuacwnewton** [comment]
> do not contain the lumbar region.

> (which contains the lumbar cord)

That might be the confusion? We do not need the whole lumbar region necessarily (L1-L5), just the portion that contains the spinal cord.

**Comment by joshuacwnewton** [comment]
Feel free to message me on Slack! I'm happy to take care of uploading the image to the sct_tutorial_data dataset. :)

Also, if possible, could you share both the cropped and uncropped image with me? (I'd like to play around with sct_deepseg's capabilities, and see how much of the cord it can segment beyond the lumbar region.)
