### ISSUE TITLE
Update figure in "Other shape metrics" tutorial

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4183]
Update the figure in the [Other shape metrics](https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/shape-metric-computation/other-shape-metrics.html) tutorial:

![](https://raw.githubusercontent.com/spinalcordtoolbox/doc-figures/master/shape-metric-computation/sct_process_segmentation-shape-metrics.png)

Metric thumbnails can be replaced with:

<img width="1275" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/a592eb10-4730-4cc8-8d87-1eccb0b8bf2c">
 
And combined with charts from https://github.com/spinalcordtoolbox/PAM50-normalized-metrics/pull/10:

![image](https://github.com/spinalcordtoolbox/PAM50-normalized-metrics/assets/39456460/fcffc40b-2a54-4eb1-a0bb-4e4cd020fbe6)

**Comment by valosekj** [comment]
@jcohenadad, @joshuacwnewton, @sandrinebedard, what do you think about something like this?

<img width="1341" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/fef1b46d-911c-4ce9-bb88-4d747414a634">

**Comment by joshuacwnewton** [comment]
I think that looks absolutely gorgeous. Though, one nitpick: We could crop the in-image caption, then add the same caption as text in Sphinx's figure directive. (That way, the link is clickable, and the text is copy-pastable.)

**Comment by sandrinebedard** [comment]
This looks really great! Thanks @valosekj !

**Comment by valosekj** [comment]
I updated the figure based on the discussion during the 2023-10-19 SCTdev meeting.

Namely, I:
- Reorganized the figure so that pairs of graphs and cord diagrams are side by side
- Used the original charts and red dashed lines for the “compression site”
- Removed compression ratio and added orientation

@jcohenadad, @joshuacwnewton, @sandrinebedard, @NathanMolinier, what do you think?

<img width="1159" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/3e4deb6d-b6de-4650-8c3f-6278abe2a21f">

**Comment by jcohenadad** [comment]
very nice! Few comments:
- xlabel: "Slice #" --> "Axial Slice #"
- orientation equation: use the same font size as the other equations above (move things around if necessary, eg crop the green and red bars if you need space to move things up)
- add a fat dashed red contour on the axial view MRI to make it clearer connection between the image and the plot

**Comment by joshuacwnewton** [comment]
> reduce space between schematic and graph, to minimize confusion about which graph corresponds to which schematics

I very much agree with this. And, to make this easier, you could change the text labels for the first 3 schematics to be:

```bash
# before
AP Diameter (mm)

# after
AP Diameter
      (mm)
```

That way you have a little more horizontal space to work with.

**Comment by joshuacwnewton** [comment]
> reduce space between schematic and graph, to minimize confusion about which graph corresponds to which schematics

I very much agree with this. And, to make this easier, you could change the text labels for the first 3 schematics to be:

```bash
# before
AP Diameter (mm)

# after
AP Diameter
      (mm)
```

That way you have a little more horizontal space to work with.

**Comment by joshuacwnewton** [comment]
One tiny tiny tiny nitpick, but I think the RL schematic is slightly misaligned with the AP and CSA schematics in the column.

**Comment by sandrinebedard** [comment]
Looks great @valosekj ! I agree with @jcohenadad and @joshuacwnewton 's comments. I think the font size of `mm `for AP and RL is slightly smaller than for CSA, we should ensure font sizes are consitent.

**Comment by valosekj** [comment]
Thanks for the feedback! I addressed your comments:

<img width="1009" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/1ef5d4fe-ad9e-4afb-bdea-ebfbaafa7b77">

> where is the source file? in case we want to change it in 5y?

On G Drive: `Projects / SCT / Courses / 2023-11-20_Online / figures`

**Comment by joshuacwnewton** [comment]
> On G Drive: Projects / SCT / Courses / 2023-11-20_Online / figures

I see the individual schematics in this folder, but where is the full image? 

_(Small suggestion: It might be good to work on this full image inside of the [SCT course slide deck](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.p74) -- that way, when we take a screenshot for the web tutorials, we know it matches the slides 100%.)_

----

Also, I had one last set of minor, minor suggestions:

1. We could put the Orientation labels above the spinal cord, that way all of the cords line up (see [this slide](https://docs.google.com/presentation/d/1bTZd90zu_m0UkgAhEVS9L1RcLf9BNCNr/edit#slide=id.g2923bdae307_0_0))
   ![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/440bf5b0-aeb0-4a56-bb1a-cd16fdbe20d8)
2. We could add the dashed line to the sagittal view as well as the axial view:
   ![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/f9d89e31-bc8f-4ad7-a43b-d4ec6813c2ee)
   The only issue is that it sort of obscures the compression site in the sagittal plane.

----

Other than this, it LGTM! Thank you so much for taking care of all of the nitpicky feedback :hearts:.

**Comment by jcohenadad** [comment]
Thank you @valosekj ! Another nitpick: you could remove the y-label on each graph, since it is already listed on below each schematic spinal cord

**Comment by valosekj** [comment]
> I see the individual schematics in this folder, but where is the full image?

There should be two files (one PowerPoint, second Apple Keynote):

<img width="300" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/cbbbccfa-5f63-4ef7-bec3-010014239fe5">

> (Small suggestion: It might be good to work on this full image inside of the [SCT course slide deck](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.p74) -- that way, when we take a screenshot for the web tutorials, we know it matches the corresponding slide 100%.)

Good idea! I changed the layout of my slide (`sct_course_morphometric_meassures.key`) from 16:9 to 4:3 to match the SCT course slides.

---

I put the Orientation labels above the spinal cord, added the dashed line to the sagittal view, and removed the y-labels:

<img width="1000" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/e85af11c-52bc-48ce-90de-30ca65d6358b">

**Comment by jcohenadad** [comment]
> I think this should now be good to add to the doc-figures repo, so that we can merge https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4262.

@valosekj in case you've never done that you can simply drag/drop directly on GH (instead of cloning, etc)

**Comment by valosekj** [comment]
Thanks! PR created: https://github.com/spinalcordtoolbox/doc-figures/pull/5
