### ISSUE TITLE
Finalize SCT course material and link to workshop page

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4186]
## 1. Announcements

 - [x] Mailing list
 - [x] [Forum](https://forum.spinalcordmri.org/c/announcements/5)
 - [ ] 2w before course: ask participants to install SCT and FSLeyes and write to us if they encounter issues
 - [ ] 2d before course: send course material

## 2. Website changes

 👉 [Workshop page (GitHub)](https://github.com/spinalcordmri/spinalcordmri.github.io/blob/master/_posts/2023-11-20-sct-course.md)
 👉 [Workshop page (html site)](https://spinalcordmri.org/2023/11/20/sct-course.html)

  - [x] Under "How to connect", add a link: "If you cannot connect, please contact: XXX". 
      - https://github.com/spinalcordmri/spinalcordmri.github.io/pull/88

### 3.1 New features (v6.1) to highlight

We should add pages and/or sections to teach users about features that have been added recently:

- [x] Updated PAM50 (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4215)
- [x] Spinal cord morphometry normalization to the PAM50 (`sct_process_segmentation -normalize-PAM50` and [interactive preprint](https://neurolibre.org/papers/10.55458/neurolibre.00017))
- [x] Normalization of morphometrics (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4162)
- [x] Stitching algorithm (@joshuacwnewton)

### 3.2 Future features (v6.2 and beyond)

We should add a "Coming soon" section that highlights the following upcoming features:

- [x] #4244
- [x] #4243
- [x] #4245
- [x] MP2RAGE MS lesion segmentation
- [x] #4239
- [x] #4240
- [x] #4242
- [x] #4241
- [ ] Other??

### 3.3 Updates to existing slides

- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4263
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4183
- [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4155

## 4. Polling participants

We should use the SCT course as an opportunity to poll users about the desire for certain features:

- [ ] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4179
- [ ] Should we keep "Spinal Cord MRI" Slack? It is unused and we would like to redirect the community to the forum (https://forum.spinalcordmri.org/). 
- [ ] preferred image viewer (FSLeyes, ITK-Snap, 3D Slicer, JIM, other)

## 5. Discussion needed

- [ ] https://github.com/ivadomed/model-spinal-rootlets/issues/13

**Comment by joshuacwnewton** [comment]
The SCT course has been migrated to Google Slides: [SCT_Course_2023-11-20](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit?usp=sharing)

We will need to update outdated info. :)

**Comment by joshuacwnewton** [comment]
Given that:

- The documentation/slides can be updated after v6.1 is released
- The SCT course date (November 20th) is more than a month after the 6.1 release date (October 12th) 

I'm going to remove this issue from the 6.1 milestone (since all of these tasks do not need to be completed by October 12th).

**Comment by jcohenadad** [comment]
@joshuacwnewton about the stitching function, i made a slide for the bavaria meeting last week, feel free to use it-- (we need to add the appropriate ref on the slide) here: [20231018 Bavaria Extract.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/13165837/20231018.Bavaria.Extract.zip)

**Comment by joshuacwnewton** [comment]
Thank you so much! :hearts:
