### ISSUE TITLE
Clarification of `sct_run_batch -script-args` input flag help

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4187]
When helping @rohanbanerjee with passing extra arguments to a script from the `sct_run_batch` wrapper, I found that the help for the `-script-args`  input flag does not correspond to the actual usage.

Instead of current `-script-args "-foo bar -baz /qux"`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5de501d3fe98c53861b54c60b9f5f5b96732772/spinalcordtoolbox/scripts/sct_run_batch.py#L131-L133

We used: `-script-args <PATH_TO_CONFIG_FILE>`, i.e., just providing an argument.

The `PATH_TO_CONFIG_FILE` is then passed to a script as `${2}` variable.

---

Analogical example usage from the `contrast-agnostic` project:

Calling `sct_run_batch` using [this line](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/ca81e3e51d027346e4726224a4a15ef5bb7a5c2c#launch-processing):

```
sct_run_batch ... -script-args exclude.yml
```

And then retrieving the variable using [these lines](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/ca81e3e51d027346e4726224a4a15ef5bb7a5c2c/processing_spine_generic/process_data.sh#L32-L34):

```
# Retrieve input params
SUBJECT=$1
EXCLUDE_LIST=$2
```

---

Based on these findings, I would suggest updating the `-script-args`  input flag help:

```
A quoted string with extra flags and arguments to pass to the script.
For example 'sct_run_batch -path-data data/ -script-args "VARIABLE1 VARIABLE2" process_data.sh'. 
The variables are then retrieved by a script as '${2}', '${3}', etc.') 
```

**Comment by sandrinebedard** [comment]
I would suggest:

~~~
A quoted string with extra flags and arguments to pass to the script.
For example 'sct_run_batch -path-data data/ -script-args "VARIABLE1 VARIABLE2" -script process_data.sh'. 
The variables are then retrieved by a script as '${2}', '${3}', etc.') 
~~~
