### ISSUE TITLE
Migrate deprecated RTD settings into `.readthedocs.yml`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4205]
From https://readthedocs.org/dashboard/spinalcordtoolbox/advanced/:

> Default settings
> 
> Usage of the below settings is deprecated and support for these fields will be removed on September 25th, 2023.
> 
> For more information, see our blog post: [migrating your configuration to .readthedocs.yaml](https://blog.readthedocs.com/migrate-configuration-v2/).

We have a `.readthedocs.yaml` file:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/33c924edc56d3e2f67e50b281c6e9b302afedf18/.readthedocs.yml#L1-L25

But it's possible there are settings we have in the dashboard that still need to be moved into the `.yaml` file.

**Comment by mguaypaq** [comment]
I was just looking into this :sweat_smile: since I'm doing it for spine-generic, I might as well do it for SCT too.
