### ISSUE TITLE
Consider adding opening of QC viewer at the end of `process_data.sh` tutorial for `sct_run_batch`

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4217]
Adding this code at the end: 
~~~
# Display syntax to open QC report on web browser
if uname -a | grep -i  darwin > /dev/null 2>&1; then
  # OSX
  open_command="open"
elif uname -a | grep -i  linux > /dev/null 2>&1; then
  # Linux
  open_command="xdg-open"
fi
echo "To open Quality Control (QC) report on a web-browser, run the following:"
echo "$open_command $PATH_QC/index.html"
~~~

**Comment by joshuacwnewton** [comment]
Good idea! Though, I notice that `sct_run_batch` itself seems to have a prompt for opening the QC report:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/100087e7ca90f3ea91e6921b71ef443228828c1d/spinalcordtoolbox/scripts/sct_run_batch.py#L581-L582

What would be the difference between the script prompt and the `sct_run_batch` prompt?

**Comment by jcohenadad** [comment]
> Good idea! Though, I notice that sct_run_batch itself seems to have a prompt for opening the QC report:

ah! my bad-- i forgot that-- i guess we can forget about my comment then 😅
