### ISSUE TITLE
New test failures: `The truth value of an array with more than one element is ambiguous`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4220]
I'm seeing a few test failures for tests on PRs + Scheduled `master` runs. The errors affect all OSs, and started happening 3 days ago. 

```
____________________ test_sct_dmri_display_bvecs_png_exists ____________________
Traceback (most recent call last):

  [...]

  File "/home/runner/sct_6.1.dev0/testing/cli/test_cli_sct_dmri_display_bvecs.py", line 17, in test_sct_dmri_display_bvecs_png_exists
    sct_dmri_display_bvecs.main(argv=['-bvec', sct_test_path('dmri', 'bvecs.txt')])
  File "/home/runner/sct_6.1.dev0/spinalcordtoolbox/scripts/sct_dmri_display_bvecs.py", line 176, in main
    ax.scatter(x[i], y[i], z[i], color=shell_colors[bvals[i]], alpha=0.7)
  File "/home/runner/sct_6.1.dev0/python/envs/venv_sct/lib/python3.9/site-packages/matplotlib/__init__.py", line 1465, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/runner/sct_6.1.dev0/python/envs/venv_sct/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2377, in scatter
    if kwargs.get('color', None):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I don't think this is due to any sort of change in the codebase, so I'm assuming it's due to an upstream change of some kind. I'll try to pin it down and fix it. :)

**Comment by joshuacwnewton** [comment]
[Diffing the install logs](https://www.diffchecker.com/07qf4ry4/), it looks like matplotlib updated from `3.7.3` to `3.8.0`. This makes sense, given the error is happening within `matplotlib` code itself.

A quick look at recent MPL issues and I'm not seeing anything relating to this error. So, I'm going to try to create a reproducible example and report it upstream. 

For now, we can pin to `<3.8`?

**Comment by joshuacwnewton** [comment]
After some fiddling, there's an easier solution: Just pass a list to `color` instead of a numpy array.

I'll submit a PR. :)

**Comment by jcohenadad** [comment]
My heart almost stopped after sending the SCT course announcement and seeing that CI is failing 😅
