### ISSUE TITLE
Move "Labeling" section outside of "Registration" in the web tutorials

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4236]
Currently vertebral labeling is inside registration to template:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/21a16dbb-fe65-49c4-a0b5-3b3ef74d88df)

given that ppl might want to label vert/discs without doing reg to template, i suggest moving this section to headings1

collateral benefits: the labeling convention will be more visible (https://github.com/spinalcordtoolbox/PAM50/pull/27#issuecomment-1747417942)

**Comment by joshuacwnewton** [comment]
I very much agree with this suggestion. 

(For context: The only reason it was like this to begin with was to mimic the structure of the SCT Course, which includes vertebral labeling under the "Registration" header, and does not have a vertebral labeling header.)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/0bbb6454-e2b2-4cf6-b9cb-04892704bac8)

But, I think the restructure would be very good.

**Comment by joshuacwnewton** [comment]
This suggestion was applied to the SCT Course, and I think it worked quite well, so I'm adding it to 6.2 as a post-SCT Course task.

(There are a few issues in the vein of "Port new changes from Course Slides to Web Tutorials" and I'm going to group them together.)
