### ISSUE TITLE
Hide 'hidden' slides from the google slides

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4237]
After porting the slides to gslides, the 'hidden slides' are visible, even in 'view' mode:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/06d6d901-cad5-44f7-b176-3265e4ad156c)

It would be great to find a way to properly hide them. If not, let's get rid of them

**Comment by joshuacwnewton** [comment]
It seems like the only way to truly hide the slides [is to delete them](https://support.google.com/docs/answer/1694830?hl=en&co=GENIE.Platform%3DDesktop&sjid=13247948303505768182-NA#), as you say.

> You can skip a slide when you present a presentation. The slide won’t be deleted, and if you share your presentation with others, people will be able to see the skipped slides.

It might be worthwhile to back up the slides before we delete them (either by setting a "Named snapshot" in the history section of the slide deck, or by copying slides into their own presentation).

**Comment by joshuacwnewton** [comment]
Given that we have decided to back up the old course and delete the hidden slides, I think we can mark this as completed.
