### ISSUE TITLE
Make it easier to navigate between the different sections in the SCT Course Google Slides

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4238]
currently all slides are flat:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/9e8bd4c9-23cb-4f4b-af42-6e4d22fa138f)

On keynote (and possibly PPT) it is possible to indent slides so they pertaind to a section, and we can display/hide all slides from a full section-- this is very useful for large slide decks

**Comment by jcohenadad** [comment]
:-( https://support.google.com/docs/thread/115613746/google-slides-how-to-organize-into-sections?hl=en

**Comment by jcohenadad** [comment]
i guess we can close this then ☹

**Comment by joshuacwnewton** [comment]
Reopening this issue while I explore alternate solutions (e.g. making the table of contents hyperlinkable, to make it easier to jump back and forth between sections)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/759c95ca-a9a4-411e-bf3e-c7abad6d471f)

**Comment by joshuacwnewton** [comment]
Given that we've hyperlinked the TOC in the course slides, and given that there isn't really any feature in Google Slides that matches the old Keynote behavior, I think we can close this.
