### ISSUE TITLE
Add course slide: Spinal rootlets segmentation (Jan, Theo)

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4239]

**Comment by joshuacwnewton** [comment]
Completed (checked in list).

**Comment by valosekj** [comment]
[Slide](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.g290a9ece2eb_9_0)
