### ISSUE TITLE
Nilser AMU template @Nilser3 pls add a slide in the course material

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4241]

**Comment by Nilser3** [comment]
@jcohenadad @joshuacwnewton 

I have created a slide referring to the AMU7T template 
https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.g288751e93c7_39_201 


for the moment I put it before "What's next?" part:

**Comment by jcohenadad** [comment]
Awesome! Thank you Nilser 😊
