### ISSUE TITLE
Update documentation for new spinal levels

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4247]
Alongside https://github.com/spinalcordtoolbox/PAM50/pull/18, update the documentation to reflect the changes, notably: the pictures, the references to Cadotte et al. and any reference to a "separate" spinal level folder. Also make sure to remove the term "probabilistic" spinal levels.

TODO:

- [x] update figure
- [x] replace paperpile links with open-access links when applicable
- [ ] Fix "14, point-wise spinal level labels, PAM50_label_spinal_levels.nii.gz" in info_label
- [ ] Add correct entry in info_label

**Comment by RaphaSchl** [comment]
Hi,

I was reading through [the PAM50 Template - Spinal Levels section](https://spinalcordtoolbox.com/overview/concepts/pam50.html#spinal-levels) of the SCT website and found the following sentence, that I believe to be incorrect : 

_The spinal levels are estimated from the intervertebral discs, using a methods described in [Frostell et al. (2016)](https://www.frontiersin.org/articles/10.3389/fneur.2016.00238/full)._

From what is explained in the [issue #16](https://github.com/spinalcordtoolbox/PAM50/issues/16) and [the script](https://github.com/spinalcordtoolbox/spinalcordtoolbox-dev/tree/master/dev/spinal_level), the levels are computed based on the relative length of each spinal level with respect to the length of the full spinal cord  (expressed as a percentage), found in Table 3 of the article by Frostell et al., 2016.

I thought it might be important to update this ☺️

**Comment by jcohenadad** [comment]
Thank you for your comment @RaphaSchl (and sorry for the late response)-- I have updated the doc here: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4449

**Comment by joshuacwnewton** [comment]
>  the references to Cadotte et al.

There is still an old reference to Cadotte et al. in the "citing_sct.rst" page. Reopening just to follow up on this.
