### ISSUE TITLE
Update SCT course for new spinal levels

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4248]
Alongside https://github.com/spinalcordtoolbox/PAM50/pull/18, update the SCT course to reflect the change. Any reference to a "separate" spinal level folder. Also make sure to remove the term "probabilistic" spinal levels.

**Comment by joshuacwnewton** [comment]
Ditto for the tutorials, as they mimic the SCT course, and I'm fairly certain the FMRI tutorial is designed with warping the spinal levels in mind.

**Comment by jcohenadad** [comment]
> I'm fairly certain the FMRI tutorial is designed with warping the spinal levels in mind.

it is 😊

**Comment by jcohenadad** [comment]
@joshuacwnewton I'm ready to tackle this issue now. For the fMRI part, I was thinking of proposing two types of registration:
- the 'classic' one, based on the discs, where the new spinal levels would be used (in fact, they have already been warped at a previous step-- but not for the tutorial, right? because these are standalone data packages)
- a spinal level based registration, similar to the lumbar-based registration. Have you already done the lumbar seg? If so maybe we should move it to the [fMRI section](https://spinalcordtoolbox.com/user_section/tutorials/other-features/processing-fmri-data.html). And BTW, maybe we should move that section one level down so it appears in the TOC.

**Comment by joshuacwnewton** [comment]
> Have you already done the lumbar seg?

Yes! :smile: 

- Web tutorials: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4250
- SCT Course: [Additional registration approaches](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.g29079583b15_1_69) section, specifically [page 94](https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.p75)

**Comment by joshuacwnewton** [comment]
I believe this is done (for the SCT course), but I'm keeping it open and adding the milestone 6.2 so that it isn't forgotten. We can port the changes to the web tutorials when the more urgent work is complete.
