### ISSUE TITLE
Error (`missing xcrun`) after updating to MacOS 14.0 (Sonoma)

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4265]
### Description

Following https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Documentation%3A-Building-the-documentation, I ran into:

```
(venv_sct) julien-macbook:~/code/spinalcordtoolbox/documentation $ make clean html
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

Note: The problem appeared after upgrading to macOs sonoma 14.0

**Comment by joshuacwnewton** [comment]
It looks like others are experiencing this error after updating to Sonoma as well: https://developer.apple.com/forums/thread/673827

[This StackExchange thread](https://apple.stackexchange.com/a/432153) seems informative, and contains two commands that may fix the issue:

```
sudo xcode-select --reset
xcode-select --install
```

Could you try both and see if this fixes your issue?

**Comment by jcohenadad** [comment]
> Could you try both and see if this fixes your issue?

It did! Thank you @joshuacwnewton
