### ISSUE TITLE
SCT course on google slide: Find a way to download PDF with the embedded presenter notes 

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4269]
in the past we would provide a PDF with each page showing the slide on top, and the notes at the bottom

is it possible to do it directly from gslide and if so what is the procedure?

if not, we need to download as pptx, and then from PPT export with the notes (but that might screw up the formatting)

**Comment by joshuacwnewton** [comment]
> is it possible to do it directly from gslide and if so what is the procedure?

- File -> Print preview
- In the newly visible menu bar, click on "1 slide without notes" and change to "1 slide with notes"
- (Presumably also uncheck "Include skipped slides")
- Download as PDF

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/2c3f3fb1-4ec5-4613-b436-2c631568ff39)

**Comment by jcohenadad** [comment]
thanks! i've added the instructions:
https://docs.google.com/presentation/d/1t40Fd0fS0SwWR5FU_GWKEvHkB9d96LVddLQW6L3QAx0/edit#slide=id.g29332cf712f_0_4
