### ISSUE TITLE
Low quality gray matter based registration on SCT course 2023

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4275]
Going through the slides, on the GM-based registration:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/5f82d85a-6f00-4ce4-badf-90f08937cdf0)

I noticed that the registration result is pretty bad:

![anim](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/a5a9a973-3b31-451c-91e2-beccd75220d7)

I am wondering if something has changed in SCT that made results worst compared to the previous SCT course in 2021. Or were results the same in 2021? How can we "easily" check that?

**Comment by joshuacwnewton** [comment]
> How can we "easily" check that?

The command appears to be identical compared to the [2021 course material](https://drive.google.com/file/d/1Oe9XHepUbd-nMNZvlNojh4YttEPep01P/view) (page 89):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/477c6502-7f6a-4f8d-a7f6-bd47780cf7dc)

So, I think the best way would be to install SCT v5.4, then try the command again.

**Comment by jcohenadad** [comment]
ok, i found a good syntax:
~~~
sct_register_multimodal -i "${SCT_DIR}/data/PAM50/template/PAM50_t2s.nii.gz" -iseg "${SCT_DIR}/data/PAM50/template/PAM50_wm.nii.gz" -d t2s.nii.gz -dseg t2s_wmseg.nii.gz -initwarp ../t2/warp_template2anat.nii.gz -initwarpinv ../t2/warp_anat2template.nii.gz -owarp warp_template2t2s.nii.gz -owarpinv warp_t2s2template.nii.gz -param step=1,type=seg,algo=rigid:step=2,type=seg,metric=CC,algo=bsplinesyn,slicewise=1,iter=3:step=3,type=im,metric=CC,algo=syn,slicewise=1,iter=2 -qc ~/qc_singleSubj
~~~

![anim](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/07ed1689-3eaa-4741-847b-a233dbc749b3)

Slide updated. @joshuacwnewton I guess we should also update the script?

**Comment by joshuacwnewton** [comment]
That would be good, yes! I'm happy to take care of that. :)

**Comment by joshuacwnewton** [comment]
I believe this is done (for the SCT course), but I'm keeping it open and adding the milestone 6.2 so that it isn't forgotten. We can port the changes to the web tutorials (assuming the old command was identical between the course/tutorials) when the more urgent work is complete.
