### ISSUE TITLE
Remove `multi_subject/manual_correction.py` script from the `sct_course_data` folder

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4283]
The `sct_course_data` folder downloaded by:

```
sct_download_data -d sct_course_data -o sct_course_data
```

contains the `multi_subject/manual_correction.py` script. This is, however, a (very) old version of the script. We now use the script from the [manual-correction repo](https://github.com/spinalcordtoolbox/manual-correction). To avoid confusion, I think we should delete the script from the `sct_course_data` folder.

**Comment by jcohenadad** [comment]
> To avoid confusion, I think we should delete the script from the sct_course_data folder.

yes we should absolutely do that

**Comment by joshuacwnewton** [comment]
Ah, right! Thank you for the assignment @valosekj, I missed this.

**Comment by joshuacwnewton** [comment]
Recreating the course dataset now: https://github.com/spinalcordtoolbox/sct_tutorial_data/actions/runs/6739353193
