### ISSUE TITLE
Add TSNR maps after motion correction for fMRI in qc report

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#4290]
## Description

Typically,  after motion correction of fMRI timeseries, we compare the TSNR maps to ensure that the TSNR is not lower than before motion correction. We could add this feature in the `sct_qc`.

An idea would be to overlay the axial TSNR map before motion correction and after:

* the color map goes from blue --> orange

![anim](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/71230552/7694d89f-33c3-4966-b879-4253f2032fd8)
 

Also tagging @dpfyffer

**Comment by sandrinebedard** [comment]
Here is a first prototype (before, after motion correction):

![anim](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/71230552/e11c9993-2df7-4180-9d61-01988b8747c6)


Next idea would be to write the mean TSNR inside the cord of both images.

We also need to figure out with what function to associate this feature!

**Comment by dpfyffer** [comment]
This will be really helpful, especially once we also have the mean tSNR as a quantitative measure added!
