### ISSUE TITLE
`sct_deepseg_lesion.py -h` - slightly confusing help

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4305]
"Input image. Example: t1.nii.gz" is slightly confusing since accepted contrasts are only `'t2', 't2_ax', 't2s'`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/ec93f822cd032c08a70026113d88b8f8e0438392/spinalcordtoolbox/scripts/sct_deepseg_lesion.py#L28-L39

**Comment by joshuacwnewton** [comment]
Thanks for this! I think for tiny tiny "safe" changes like this (small argparse help string tweak, no functional changes) it's OK to merge directly to master without a PR. So, I've updated it accordingly. :)

**Comment by valosekj** [comment]
Agree! Thanks for the update! 👍🏻
