### ISSUE TITLE
Edit Youtube video to add chapters per section

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4308]
After #4307

**Comment by valosekj** [comment]
Here are orientation time stamps. Maybe they will need a slight adjustment.

```
05:26 1. Introduction
18:39 2. Installation
31:37 3. Segmentation
47:35 4. Vertebral labeling
1:07:30 5. Shape-based analysis
1:31:03 6. Registration to template
2:55:44 7. Register additional contrasts
3:26:54 8. Gray matter segmentation
3:46:55 9. Atlas-based analysis
4:14:24 10. Diffusion-weighted MRI
4:44:37 11. Functional MRI
5:13:02 12. Other features
5:32:37 13. Analysis pipelines with SCT
7:01:55 14. What’s next?
7:38:27 15. Conclusions
```

**Comment by valosekj** [comment]
> I edited the description, the chapters should eventually appear. Once they do, this issue can be closed

Confirming! Chapters are there!

<img width="800" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/cb02f4be-ac46-4cf4-bac8-f752e3f1661f">
