### ISSUE TITLE
Create labeled segmentation from disc labels

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4323]
We already have a routine to project disc labels onto the spinal cord centerline with `sct_label_utils -project-centerline`. It would be nice to also have a routine to create a labeled segmentation from these labels, without having to go through a straightening procedure, as is currently the case with `sct_label_vertebrae -initdisc`, because it is _very_ slow, and prone to straightening errors.

Maybe we can have a new flag that says '-no-straightening' or something like that, to trigger this new behavior.

**Comment by valosekj** [comment]
I believe `sct_label_utils -disc` can be used to project disc labels onto the spinal cord segmentation. Example: https://github.com/sct-pipeline/dcm-metric-normalization/blob/main/scripts/process_data_dcm-zurich.sh#L171-L174

**Comment by jcohenadad** [comment]
Amazing! Thank you @valosekj I completely missed this feature, which is a problem likely related to the poor documentation. I've renamed this issue (originally: "Create labeled segmentation from disc labels") and I suggest changing the help.

Current help:
~~~
  -disc <file>          Create an image with regions labelized depending on values from reference
~~~

Suggestion:
~~~
  -disc <file>          Create a labeled segmentation based on disc labels. The disc labeling follows the convention: https://spinalcordtoolbox.com/user_section/tutorials/registration-to-template/vertebral-labeling/labeling-conventions.html
~~~

Note: the URL to the labeling convention will change with https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4311

**Comment by valosekj** [comment]
I agree that the help can be improved. Will do it next week.
