### ISSUE TITLE
`isct_spine_detect` call fails if the filepath to the binary contains a space

### ISSUE THREAD

**Issue by bhatrana** [spinalcordtoolbox/spinalcordtoolbox#4324]
Hi SCT Group, 

I am trying to use SCT in 3D Slicer environment. Installation works perfect.  
 
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/5b9f2451f40f5e45a3c04d2a9826f34b452d19e8/spinalcordtoolbox/vertebrae/detect_c2c3.py#L85

during 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/5b9f2451f40f5e45a3c04d2a9826f34b452d19e8/spinalcordtoolbox/utils/sys.py#L333

it tries to split cmd in couple of argument lists.

The problem for me is Slicer 5.6.1 has a space in between.
(example)
" 'C:\\Users\\admin\\AppData\\Local\\slicer.org\\Slicer 5.6.1\\lib\\Python\\Lib\\site-packages\\bin\\isct_spine_detect -ctype=dpdt "C:\\Users\\admin\\AppData\\Local\\slicer.org\\Slicer 5.6.1\\lib\\Python\\Lib\\site-packages\\data\\c2c3_disc_models\\t1_model" "data_midSlice" "data_midSlice_pred" " 

it will split environment path like this (C:\\Users\\admin\\AppData\\Local\\slicer.org\\Slicer) ;  which is wrong. 

first split I expect is something like this 

C:\\Users\\admin\\AppData\\Local\\slicer.org\\Slicer 5.6.1\\lib\\Python\\Lib\\site-packages\\bin\\isct_spine_detect

any advises to preserve split in between environment path ?

Can we refactor cmd_detection here 
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/5b9f2451f40f5e45a3c04d2a9826f34b452d19e8/spinalcordtoolbox/vertebrae/detect_c2c3.py#L81 as a lists before passing to run_proc ?

Raj

**Comment by joshuacwnewton** [comment]
Fixed by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4328.
