### ISSUE TITLE
Extend `sct_compute_compression` to MCC

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4330]
The `sct_compute_compression` function is currently meant to compute maximum spinal cord compression (MSCC) using the SC segmentation:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1be3969e6afa7448e0e285b7ea37d0f6e8d11f5f/spinalcordtoolbox/scripts/sct_compute_compression.py#L64-L67

But, if we replace the SC segmentation with CSF segmentation (representing the spinal canal), the `sct_compute_compression` function can also be used to compute maximum canal compromise (MCC). The CSF segmentation can be obtained manually or using `sct_propseg`.

TLDR: The only difference between MCC and MSCC is that the former uses the spinal canal while the latter uses the spinal cord:

<img width="600" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/39456460/e9c4b679-1aeb-46b8-8ba5-d5d19c4365fa">

[Figure source](https://pubmed.ncbi.nlm.nih.gov/17431129/) 

The only drawback for MCC is that we could not use the [`-normalize-hc` flag](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1be3969e6afa7448e0e285b7ea37d0f6e8d11f5f/spinalcordtoolbox/scripts/sct_compute_compression.py#L97-L101) because the [normative database](https://github.com/spinalcordtoolbox/PAM50-normalized-metrics) currently does not contain measures of the spinal canal.

What do you think? @sandrinebedard, @jcohenadad

**Comment by sandrinebedard** [comment]
It should be pretty easy to add!

**Comment by valosekj** [comment]
Okay! I will do it and open PR!
