### ISSUE TITLE
Integration of Zurich mouse nnUNet model in SCT

### ISSUE THREAD

**Issue by plbenveniste** [spinalcordtoolbox/spinalcordtoolbox#4348]
Hi ! 

I am creating this feature for the integration of the Zurich mouse nnUNet model in SCT. 
The code can be found here : https://github.com/ivadomed/model_seg_mouse-sc_wm-gm_t1 

Thanks :)

**Comment by joshuacwnewton** [comment]
Hi @plbenveniste! I'm trying out the most recent release of the model with the changes from #4345.

One thing I'm noticing is that the `model.zip` file has a `nnUNetTrainer__nnUNetPlans__3d_fullres` subfolder in it:

```tree
model/
└── nnUNetTrainer__nnUNetPlans__3d_fullres
    ├── crossval_results_folds_0_1_2_3_4
    │   ├── plans.json
    │   ├── postprocessing.json
    │   └── postprocessing.pkl
    ├── dataset.json
    ├── fold_4
    │   ├── checkpoint_best.pth
    │   ├── progress.png
    │   └── training_log_2023_7_4_04_02_51.txt
    └── plans.json
```

Would you be able to remove the subfolder from the release? It would make the SCT code a bit simpler if the model files were directly in the `model/` folder, like so:

```
model/
├── crossval_results_folds_0_1_2_3_4
│   ├── plans.json
│   ├── postprocessing.json
│   └── postprocessing.pkl
├── dataset.json
├── fold_4
│   ├── checkpoint_best.pth
│   ├── progress.png
│   └── training_log_2023_7_4_04_02_51.txt
└── plans.json
```

**Comment by joshuacwnewton** [comment]
Hrm. When trying to perform segmentation on a sample T1 image, it took quite a lot of time, and I ended up running out of memory before it could complete! (A step size of `0.9` did not help.)

The sample image is cropped (`t1.nii.gz` from `sct_testing_data`, `dim=41x75x76`). For other nnUNet models run on cropped testing images, I was able to segment them just fine without issue.

Perhaps the sample image is still too big? I wonder, do you have a sample image I could try inference on?

**Comment by plbenveniste** [comment]
Hi @joshuacwnewton ! 
I just changed the release folder format. 
Also, regarding the inference, you can use images from the `zurich-mouse` dataset (however, I am not sure that they can be publicly shares. Inference on CPU is quite long because the images are rather heavy (around 80 MB) (takes more dans 20 min) and on GPU in takes a few minutes (I think).

**Comment by joshuacwnewton** [comment]
Ahhhh, alright! 

In that case, it is probably not feasible to test this model in our automated testing suite. However, I can still include the new model rather easily in PR #4345. :)

**Comment by plbenveniste** [comment]
@joshuacwnewton ! BTW, the long inference time is linked to the fact that nnUNet resamples the images to a chosen voxel dimension (0.05mmx0.05mmx0.05mm in our case). Therefore, for large view images, it uses a lot of RAM and therefore either takes a long time or even crashes.

**Comment by joshuacwnewton** [comment]
Ahhh, that explains it! :hearts:

```json
            "spacing": [
                0.05000000074505806,
                0.05000000074505806
            ],
```

I should have checked the `plans.json` file, my apologies.  I see the `0.05` spacing now, compared to the other nnunet models being e.g. `0.5`, `0.75`, `0.8`, etc. That's a big difference!
