### ISSUE TITLE
Add rootlets to PAM50 and publish model

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4351]
This is a tracking issue to remind me: 
- [x] to include the latest model in a release of https://github.com/ivadomed/model-spinal-rootlets/
- [ ] to include the PAM50 rootlets into the [PAM50/template](https://github.com/spinalcordtoolbox/PAM50/tree/master/template) - PR: https://github.com/spinalcordtoolbox/PAM50/pull/29

**Comment by valosekj** [comment]
Published! @joshuacwnewton 

https://github.com/ivadomed/model-spinal-rootlets/releases/tag/r20240129

**Comment by valosekj** [comment]
> to include the PAM50 rootlets into the [PAM50/template](https://github.com/spinalcordtoolbox/PAM50/tree/master/template).

Before pushing the PAM50 rootlets, I want to confirm the filename to use. Possible options:
- `PAM50_t2_rootlets.nii.gz` - keeping `t2` would make explicit that the rootlets were segmented from `PAM50_t2.nii.gz`
-  `PAM50_rootlets.nii.gz` - omitting `t2`. And following a simple structure of other [PAM50/template](https://github.com/spinalcordtoolbox/PAM50/tree/master/template) files (`PAM50_cord`, `PAM50_gm`, ...)
- `PAM50_label-rootlets_dseg` - following our [BIDS convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#examples-and-use-cases)

**Comment by jcohenadad** [comment]
> Also, do we want to add to the PAM50 only rootlets or also spinal levels estimated based on the rootlets (Fig10 [here](https://arxiv.org/ftp/arxiv/papers/2402/2402.00724.pdf))?

nope-- we keep the Frostell levels only otherwise it's going to be confusing

**Comment by valosekj** [comment]
> i vote for `PAM50_rootlets.nii.gz`

👍🏻 PR opened: https://github.com/spinalcordtoolbox/PAM50/pull/29

**Comment by joshuacwnewton** [comment]
Given the feedback from https://github.com/spinalcordtoolbox/PAM50/pull/29 (as well as the likely required manual correction), does it still make sense to include this issue on the 6.2 milestone, timing-wise?

**Comment by valosekj** [comment]
> Given the feedback from [spinalcordtoolbox/PAM50#29](https://github.com/spinalcordtoolbox/PAM50/pull/29) (as well as the likely required manual correction), does it still make sense to include this issue on the 6.2 milestone, timing-wise?

Sorry for the delay on [spinalcordtoolbox/PAM50#29](https://github.com/spinalcordtoolbox/PAM50/pull/29). I will try to discuss it with Julien tomorrow. I will let you know.

**Comment by joshuacwnewton** [comment]
Not a worry! That PR had unxpected extra work come up -- on its face, it seemed like a very simple PR. So, I would understand if it doesn't make it in time. :)
