### ISSUE TITLE
QC for `sct_dmri_moco` shows dark images

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4366]
### Description

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/2632b235-0bc4-4573-b2dc-d9b4664f2b35)

### Steps to Reproduce

get data from: https://forum.spinalcordmri.org/t/dmri-moco-does-not-work-on-my-ivim-data/1208

```bash
# Average DWI scans together, using custom bval threshold
sct_dmri_separate_b0_and_dwi -i Ax_IVIM.nii.gz -bvec Ax_IVIM.bvec -bval Ax_IVIM.bval -bvalmin 200
# Segment spinal cord
sct_deepseg_sc -i Ax_IVIM_dwi_mean.nii.gz -c dwi -qc qc
# Crop IVIM scan using dilated segmentation for better and faster performance of moco algorithm
sct_crop_image -i Ax_IVIM.nii.gz -m Ax_IVIM_dwi_mean_seg.nii.gz -dilate 15x15x0
# Perform motion correction
sct_dmri_moco -i Ax_IVIM_crop.nii.gz -bvec Ax_IVIM.bvec -bval Ax_IVIM.bval -bvalmin 100 -g 1 -qc qc -qc-seg Ax_IVIM_dwi_mean_seg.nii.gz 
```

**Comment by joshuacwnewton** [comment]
Without looking deeply into it, my initial guess is that it has something to do with using A) a cropped image for moco and B) an uncropped image for `-qc-seg`.

(i.e. you would have to run `sct_crop_image` on the `mean_seg.nii.gz` image _using_ the `mean_seg.nii.gz` image)

But I'll test the commands to be 100% sure.

**Comment by joshuacwnewton** [comment]
![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/13991480-b2c9-4324-8a33-27e4f1bf2ae3)

Using the cropped seg for `-qc-seg` fixes the issue. :tada:

**Comment by jcohenadad** [comment]
amazing-- thank you @joshuacwnewton

**Comment by jcohenadad** [comment]
Uploading here because SCT's forum upload is limited to 4MB: [qc_20240209_131924.zip](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14225068/qc_20240209_131924.zip)
