### ISSUE TITLE
Slow imports

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4370]
This is a non-urgent issue that I noticed during #4345 -- running `sct_deepseg -h` takes a noticeably long time. 

I'm curious as to why this is, and I would love to try to reduce the "startup" time for scripts if I can.

**Comment by mguaypaq** [comment]
My first guess (but it's just a guess, [we should profile it](https://docs.python.org/3/library/profile.html)) would be that one or more of our `import` statements is heavy; probably one or more of the AI/ML frameworks we use. If that's the case, it should be easy to move the offending import statements inside the functions which actually use them.

**Comment by jcohenadad** [comment]
Yeah. I _think_ ivadomed plays a big role in the slow imports. Which is partly the reason we would like to remove that dependency.

**Comment by joshuacwnewton** [comment]
One thing to note is that we currently have a test that runs the help on all scripts:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/6962e03b5906ab3466e6e330438dbea58d949407/testing/cli/test_cli.py#L19-L22

We could repurpose this test to also check slow imports by [clearing `sys.modules`](https://stackoverflow.com/a/66617086) at the start of each test per script. This can be used to profile timing by passing, say, [`--durations=10 --durations-min=1.0`](https://docs.pytest.org/en/7.1.x/how-to/usage.html#profiling-test-execution-duration) (or a variation) to pytest.

Then, if we end up getting all of the slowest `-h` imports under a certain goal (e.g. 5s), we can preserve this maximum limit by using [`pytest.mark.timeout()`](https://stackoverflow.com/a/19527487) to fail a test if it crosses the threshold we've set for ourselves.

(Though, this may be tricky to enforce due to natural variance in OSs and runners. But, I imagine there are lots of solutions out there for handling slow tests!)

**Comment by joshuacwnewton** [comment]
Quick and easy profiling:

```bash
pip install tuna
PYTHONPROFILEIMPORTTIME=1 sct_deepseg -h 2> import.log
tuna import.log
```

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/0a64d5bb-d1af-4e89-8e6e-d16a70954b1b)

The biggest offenders seem to be `torch`, `torchvision`, `wandb`, and `monai`.

<details>
<summary> Digression about PEP 690 - Lazy Imports </summary> 

In terms of actually implementing lazy loading, I had the question: "Python style guides generally recommend keeping imports at the top of each module. Isn't lazy-loading incompatible with this? What is the "Pythonic" way to reduce import times?"

It turns out that [**PEP 690 – Lazy Imports**](https://peps.python.org/pep-0690/) (as well as [its rejection](https://discuss.python.org/t/pep-690-lazy-imports-again/19661/26)) explicitly references this dilemma:

> Common Python code style [prefers](https://peps.python.org/pep-0008/#imports) imports at module level, so they don’t have to be repeated within each scope the imported object is used in, and to avoid the inefficiency of repeated execution of the import system at runtime. This means that importing the main module of a program typically results in an immediate cascade of imports of most or all of the modules that may ever be needed by the program.
>
> Consider the example of a Python command line program (CLI) with a number of subcommands. Each subcommand may perform different tasks, requiring the import of different dependencies. But a given invocation of the program will only execute a single subcommand, or possibly none (i.e. if just --help usage info is requested). Top-level eager imports in such a program will result in the import of many modules that will never be used at all; the time spent (possibly compiling and) executing these modules is pure waste.

I couldn't have written a more accurate summary of our current issue.

The reason I bring this up is that I imagine that this PEP (and the associated [official discussion](https://discuss.python.org/t/pep-690-lazy-imports-again/19661) + [other discussions](https://news.ycombinator.com/item?id=34128944)) are perfect places to learn about alternative lazy-loading approaches. 

And, indeed, it mentions:

> The Python standard library already includes built-in support for lazy imports, via [importlib.util.LazyLoader](https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader).

</details>

The `importlib` documentation referenced by PEP 690 explicitly includes an [**Implementing Lazy Imports**](https://docs.python.org/3/library/importlib.html#implementing-lazy-imports) section. Additionally, the example code can also be written [as a class](https://stackoverflow.com/q/77319516) (with some additional discussion in that thread).

I tried focusing just on `sct_deepseg -h`, and I was able to cut the time down dramatically using `lazy_import` in just a few places (see [`jn/4370-fix-slow-imports`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/compare/master...jn/4370-fix-slow-imports) for the changes I made):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/d051ef27-c248-4149-aa71-15f86f8ea988)

From ~8.5s to under a second! (And, I could have kept going with `nibabel`, etc. to save even more time)

**Comment by jcohenadad** [comment]
ah! super interesting and encouraging, given that `ivadomed` is on the way out, and `wandb`... welll... there is no reason to have `wandb` here 😅  (it's only used for monitoring model training)
