### ISSUE TITLE
Displacement of a sub-panel in QC report

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4386]
### Description

I noticed a strange up-down displacement of some axial views of the QC report, eg (notice the black rectangle where this occurs):

<img width="1461" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/e7336245-92f7-478d-91d5-a2203554bf92">

<img width="1456" alt="image" src="https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/4d00c0bf-a2d0-4741-aea7-940b027e3756">

One particular aspect of this dataset that could potentially explain this behaviour (not seen previously), is the aggressive cropping of the data:
https://github.com/sct-pipeline/spine-park/blob/1b378e0d9ae743b8142716991956e1598dff5dd6/batch_processing.sh#L192

Related project: https://github.com/sct-pipeline/spine-park

**Comment by mguaypaq** [comment]
Maybe this is the bug?
https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4224#discussion_r1333655732
