### ISSUE TITLE
Broken link in `sct_register_to_template.py` help

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4393]
The link in `sct_register_to_template.py` help points to a no longer existing page:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/44587d4cb293e04e635e17fe56137a0c4aa28f8f/spinalcordtoolbox/scripts/sct_register_to_template.py#L122

The `vertebral-labeling` section was moved out from `registration-to-template` in https://github.com/spinalcordtoolbox/spinalcordtoolbox/commit/5b9f2451f40f5e45a3c04d2a9826f34b452d19e8.

**Comment by joshuacwnewton** [comment]
Thanks for catching this! I was inspired to write a quick link-checking utility after not being able to find a GitHub Action that could do this? (Uses: [check-url.sh](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14527038/check-url.sh.txt))


```bash
find . -type f \( -name "*.txt" -o -name "*.md" -o -name "*.py" -o -name "*.rst" \) | 
    xargs grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | 
    sed 's/:/;/' | 
    xargs -n 1 -P 8 ./check-url.sh
```

If I run it on `spinalcordtoolbox/`, it detects the broken link you found:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/d41cb515-b42d-438e-bd2b-73e9ea1e9819)

Perhaps we could add it to our linting CI to avoid breaking links in the future?
