### ISSUE TITLE
File permission error during SCT installation

### ISSUE THREAD

**Issue by mguaypaq** [spinalcordtoolbox/spinalcordtoolbox#4410]
@sandrinebedard reports a Windows installation bug, when installing from `master` under WSL. The installation crashes in one of the `sct_download_data` commands in a non-crucial step, but it stops the further installation steps. Specifically, there's a file permission error in one of these lines, where temporary files that were just created are being cleaned up:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/56c7f6cdb0f763f1e287a3255b25ab532e257a00/spinalcordtoolbox/download.py#L323-L324

We tested, and `rm -r $THE_FILES` works fine in the same terminal that was used for the installation attempt. Possibly this is because Windows refuses to delete files that are still open? I'll have to wait until I'm at an actual Windows machine to reproduce the bug and investigate.

In the meantime, we just commented out the two `shutil.rmtree` lines from Sandrine's local copy of SCT to unblock the installation.

**Comment by joshuacwnewton** [comment]
I'm not able to reproduce this issue on my own WSL installation? (WSL1, Windows 11)

But, regardless, maybe we should try to avoid failing entirely if `sct_download_data` fails. Ideally, we would keep going, then allow the user to re-run `sct_download_data` on their own post-install?

This would also mitigate network issues we've experienced in the past re: `sct_download_data`, where the installer gets interrupted and the user is left thinking their installation failed when the installation was in fact recoverable.
