### ISSUE TITLE
SCT installation fails with `Could not load the Qt platform plugin "xcb"` on WSL2

### ISSUE THREAD

**Issue by LouisThomasLapointe** [spinalcordtoolbox/spinalcordtoolbox#4413]
### Description

I followed the instructions for Windows Subsystem for Linux (WSL) installation of the spinalcordtoolbox. When running:

`./install_sct -y`

I get this error:
![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/146556291/7ec8a1f5-7081-4fc2-bfc2-33302f7285e7)

This is the `install_sct_log.txt` file:
[install_sct_log.txt](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14748121/install_sct_log.txt)

**Comment by mguaypaq** [comment]
Can you attach the file `install_sct_log.txt` to this issue?

**Comment by LouisThomasLapointe** [comment]
[install_sct_log.txt](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/14748096/install_sct_log.txt)

**Comment by joshuacwnewton** [comment]
- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3925

In the details of that issue, we see:

> ```
> Check if figure can be opened with PyQt.............qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> ```

Same error! Oddly though, the install log here reports:

```
Check if pyqt5 (5.12.3) is installed................[[92mOK[0m] (5.12.3)
```

**Comment by joshuacwnewton** [comment]
Can you try running the suggestion from https://askubuntu.com/a/1368783:

```
sudo apt install libxcb-xinerama0
```

If this works, then I think we can maybe close this issue as a subset of #3925. (Though, I'm curious why why pyqt5==5.12.3 is failing here, when I had presumed this was an issue only with `pyqt5==5.15.x` and above.)

If it turns out _not_ to be 5.15 specific, then this might open the door to us upgrading `pyqt5` (assuming we can ensure that the required dependency is present.)

**Comment by LouisThomasLapointe** [comment]
I tried running the command, the same error shows up.

**Comment by joshuacwnewton** [comment]
Hmm. Could you try running:

```
export QT_DEBUG_PLUGINS=1 
sct_check_dependencies
ldd $SCT_DIR/python/envs/venv_sct/lib/python3.9/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so
```

Then copy and paste the full output? This should provide further debug information about the source of the issue.

The debug output _should_ contain something along the lines of:

```
Cannot load library /home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)
```

Depending on that output, we should know what's missing?

> Side note: [This](https://askubuntu.com/a/1460390) AskUbuntu question suggests running `sudo apt install libxcb-xinerama0 libqt5x11extras5`, so you can try this too? But I wanted to start with the debug information first.

**Comment by LouisThomasLapointe** [comment]
I hadn't realise my Ubuntu was on the second version and not the first one. It is converting right now to Ubuntu1. If the error still persist after that I will try this line. If it is indeed only the Ubuntu version that was wrong, I am really sorry for the inconvenience.

**Comment by joshuacwnewton** [comment]
No no, not a worry! In theory, SCT _should_ be able to support both WSL1 and WSL2. 

So, if there are issues with WSL2, it would be good to understand what they are and how to fix them.

**Comment by joshuacwnewton** [comment]
Hi @LouisThomasLapointe. Just following up on this issue -- were you able to get SCT installed?

**Comment by LouisThomasLapointe** [comment]
No I wasn’t able to. I ran into some major hardware issues resulting in my PC to blue screen when trying to install SCT. Sorry I wasn’t able to help you guys further!

**Comment by joshuacwnewton** [comment]
Oh no! I'm so sorry to hear that...

I'm going to close this issue for now, then, but if we run into further Qt plugin errors on WSL2, I'll reopen this issue and we can debug further. :)
