### ISSUE TITLE
`sct_image` option `-transpose` doesn't transpose zooms (incorrect for anisotropic images)

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4417]
While working on https://forum.spinalcordmri.org/t/sct-deepseg-mouse-sc-segmentation-error/1237, I needed to fix the user's data using `-transpose` (which transposes the data array but not the header). But, I found that the results were stretched and skewed.

Before (`vol0001.nii`):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/ef5e5c54-d574-4d2f-b124-42c692893def)

After (`sct_image -i vol0001.nii -transpose x,z,y -o vol0001_transposed.nii`):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/609d7463-6294-4ccf-b8dd-52d074bdf065)

The issue here is that the data array was transposed, but the zooms were not. Meaning, for this anisotropic image, the wrong scaling is being applied to each axis.

After fixing the problem then re-running the command, the expected result is:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/8c6d9a9a-f92a-431c-9070-173662893eb2)

Since I implemented the fix to test the problem itself, this should be an easy PR to open.

**Comment by joshuacwnewton** [comment]
> @joshuacwnewton when you reoriented the data, did you make sure that the 0.08x0.08x1 mm physical dimentions correspond to RLxAPxSI ?

Yes, I did. I checked to make sure `dim` matched `pixdim` in the header at each step of the processing.

However, there is something curious I discovered with the user's data (see [here](https://forum.spinalcordmri.org/t/sct-deepseg-mouse-sc-segmentation-error/1237/3?u=joshuacwnewton)):

```
dim		[3, 39, 29, 12, 1, 1, 1, 1]
pixdim		[1.0, 0.078, 0.078, 1.0, 1.0, 1.0, 1.0, 1.0]
sform_name	Aligned Anat
sform_code	2
sto_xyz:1	0.078000 0.000000 0.000000 -3.523000 
sto_xyz:2	0.000000 0.000000 1.000000 -3.204000 
sto_xyz:3	0.000000 -0.078000 0.000000 5.270000 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
```

The original image has matching physical dimensions + RLxAPxSI. However, the affine is quite strange...  

I normally expect to see diagonal zooms. I don't intuitively understand how this affine would affect image loading (it seems to disagree with `pixdim`?). Still, I did observe that, in `ivadomed`, the zooms get swapped around on image load, and I think the affine is the culprit?

**Comment by mguaypaq** [comment]
Looking at the original forum issue, I'm noticing another wrinkle: I believe the axis naming conventions are different between human MRI images and mouse MRI images. Specifically, for humans the spinal cord goes along the SI direction (because it goes down from the brain when standing upright), whereas in mice I think the spinal cord goes in the AP direction (because it extends behind the brain when standing on four legs). If this is true (I'm really not sure), then I'm not sure the forum user's images are really transposed, but also I'm not sure what orientation assumptions SCT's mouse segmentation model makes.

**Comment by joshuacwnewton** [comment]
We can close this issue, as `-transpose` works as it should.

Though, I should probably take a second look at the forum post with the new knowledge I've gained from the discussion in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4434.
