### ISSUE TITLE
`git fetch` then re-running `sct_qc` may result in broken report due to mismatched asset versions

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4422]
> I cannot 'save all' (@joshuacwnewton would you mind looking into this?)
>
> _Originally posted by @jcohenadad in https://github.com/sct-pipeline/fmri-segmentation/issues/35#issuecomment-2037846826_

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/618f22a6-77e7-4826-8b86-e1b6ac917a64)

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1af24e30cdae0b465f6abd33c5633b6bcb71de39/spinalcordtoolbox/reports/assets/index.html#L313

**Comment by jcohenadad** [comment]
>  Perhaps this QC report was generated with mixed versions of SCT?

This is possible. @rohanbanerjee ?

**Comment by mguaypaq** [comment]
That's possible, since we know the QC report code only generates asset files (js, css, etc.) that are _missing_, and assumes the existing ones are up-to-date:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1af24e30cdae0b465f6abd33c5633b6bcb71de39/spinalcordtoolbox/reports/qc.py#L624-L625

If we want to guard against this, I guess we should embed some kind of version number in the asset file names, and bump it when we make changes.

**Comment by mguaypaq** [comment]
@jcohenadad there's a quick fix for the existing QC report: simply delete the `_assets` subfolder, and replace with a fresh copy of `$SCT_DIR/spinalcordtoolbox/reports/assets/_assets/` from a recent version of SCT.

**Comment by rohanbanerjee** [comment]
> This is possible. @rohanbanerjee ?
[I did a git fetch and a git pull before using SCT to generate the above report. When I run sct_check_dependencies, it shows the this SHA: git-master-7b8600645b9df14d18e79d3f78bc0c9fe80c3199](https://github.com/sct-pipeline/fmri-segmentation/issues/35#issuecomment-2037919046)

**Comment by joshuacwnewton** [comment]
> That's possible, since we know the QC report code only generates asset files (js, css, etc.) that are _missing_, and assumes the existing ones are up-to-date:

The one curious thing, though, is that in this case, `index.html` had the up-to-date function call, but `main.js` was outdated.

If only new assets are generated, then wouldn't both files be outdated? 

Ah, but wait. This must be a consequence of the fact that we _rewrite the index.html file_ every time (to regenerate the hardcoded `$sct_json_data` list of QC entries):

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1af24e30cdae0b465f6abd33c5633b6bcb71de39/spinalcordtoolbox/reports/qc.py#L611-L613

So, this issue stemmed from the fact that `index.html` will always be updated, but `main.js` won't, and the javascript functions are spread across both `index.html` and `main.js`. :thinking:
