### ISSUE TITLE
QC reports require locking `index.html` which doesn't function correctly on NFS-mounted drives

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4423]
## Background

Our QC reports contain a table of QC entries:

<details>

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/ca9d89c9-3828-4182-ac1c-89edbb80e6ee)

</details>

Each entry in the table is stored as simple JSON data listing the subject, date, CLI script, etc. We generate individual `.json` files for each entry via our `qc.py` module. 

However, when it comes to loading the data into a table in `index.html`, we store this JSON data _directly within a JavaScript variable inside the `index.html` file_. This means that every time we create a new QC entry using our Python script, we need to completely rewrite the `index.html` file, substituting the JSON data into a placeholder in the HTML template:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1af24e30cdae0b465f6abd33c5633b6bcb71de39/spinalcordtoolbox/reports/qc.py#L613

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/1af24e30cdae0b465f6abd33c5633b6bcb71de39/spinalcordtoolbox/reports/assets/index.html#L159

![untitled(2)](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/8bedf273-1ebd-4008-bd9d-a417abccbb2e)

## Problem

Because all new QC entries have the same destination file, concurrent writes can cause issues with corrupted/missing entries. So, we explicitly lock the `index.html` before writing to it.

However, in https://github.com/sct-pipeline/spine-park/issues/15#issuecomment-2038269172, we ran into some system errors when trying to lock and write to the `index.html` file while it was on a mounted drive.

## Proposed solution

Initially, I can think of two ways we could fix this issue:

- Lock and write to the `index.html` file in a tmpdir [on a non-mounted drive](https://github.com/sct-pipeline/spine-park/issues/15#issuecomment-2039987276), then copy the file to the destination directory when `sct_run_batch` is complete.
   - This may make the QC report folder difficult to access during processing, as pointed out by @jcohenadad in [this comment](https://github.com/sct-pipeline/spine-park/issues/15#issuecomment-2039987276). 
- ~Try to eliminate the need for locking entirely.~ EDIT: See [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4423#issuecomment-2048126245) for details on why loading the JSON data using client-side JavaScript probably isn't feasible.

**Comment by joshuacwnewton** [comment]
> * Instead of storing the JSON data directly in the `index.html` file, it would be nice if we could load the data directly from the existing `.json` files we have on disk when we load the page in the browser.

I don't know if this is possible. When I tried using [`fetch` boilerplate](https://stackoverflow.com/a/51859415), I got:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/joshua/Desktop/round_1_all_corrected/sample.json. (Reason: CORS request not http).

Presumably, injecting JSON directly into the `index.html` file is how we got around this in the first place.

**Comment by joshuacwnewton** [comment]
I've been poking at this again, and learning about JavaScript in the process:

- Our current QC implementation relies entirely on client-side, browser-based JavaScript.
- There's a big difference between "client-side JavaScript" and "server-side JavaScript". Searching for "how to do X in JavaScript" is largely unhelpful unless you know how to distinguish between the two types of JS (which I didn't until very recently). 
- Server-side JavaScript has _many_ more tools available to it via [Node.js](https://en.wikipedia.org/wiki/Node.js). In fact, the `fs` Node.js stdlib module can solve the problem in a simple, straightforward way:
    ```js
    // in './_assets/js/read_jsons.js':
    const fs = require("fs");
    let files = fs.readdirSync("../../_json");
    var sct_data = [];
    for (let i = 0; i < files.length; i++) {
        let data = fs.readFileSync(`../../_json/${files[i]}`);
        sct_data[i] = JSON.parse(data);
    }
    ```
* In comparison, client-side JavaScript is much more limited in what it can do, presumably for security reasons. For browser-based filesystem access, the tools available lean heavily on user consent (via things like file-picker dialogs).
  * Supported methods of filesystem interactions: [File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API) / [File API](https://developer.mozilla.org/en-US/docs/Web/API/File_API)
  * Trying to use network-based solutions (such as `fetch`, `XMLHttpRequest`, `
jQuery.getJSON()`, etc. via the `file://` protocol) fails for exactly the reasons I discovered previously ([non-http CORS requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp)).

I did find [this hub of information](https://stackoverflow.com/questions/7346563/loading-local-json-file) on SO for trying to load local JSON files. However, most of the responses are naive attempts that can be easily ruled out with the above knowledge of client-side JS limitations.

----

The only way I've found to get around these client-side limitations is exactly what we're already doing: [embedding the JSON data inside of the JavaScript via `var data = $json_data`](https://stackoverflow.com/a/57412903).

> As an aside, my next thought was: If we stick with the "JSON-as-JS" hack, what if we were to shift the "combine multiple JSON dicts into a single array" task to our client-side JavaScript (to avoid file locking on the Python side of things)? However, to do that, we would need a way to dynamically load JavaScript modules (and their variables) without knowing their names first (i.e. globbing), then we would need a way to combine these variables into a single array. And, after trying to research this, it feels like this is quite an arcane way of using JavaScript -- file globbing itself runs into the exact same "client-side JS is heavily restricted" issue that prevents us from loading the JSON files in the first place.

So, I think that whatever solution to file-locking we come up with will have to be done on the Python side. While doing filesystem work on the JavaScript side is _so_ tantalizing to me as a Python dev, it seems to be explicitly forbidden for client-side JavaScript no matter what angle I try to approach this from. :sweat:

**Comment by joshuacwnewton** [comment]
Returning back to the Python side of things... it's possible that `portalocker` doesn't actually work as we expect it to? (https://stackoverflow.com/a/39338942)

> To make sure your code works properly in both cases I would suggest encapsulating both of the open calls with the locker. 

@mguaypaq Do you think that this might have anything to do with the issue we ran into here: https://github.com/sct-pipeline/spine-park/issues/15#issuecomment-2038269172?

I notice that in our current portalocker code, we currently call `open` _then_ `lock`, whereas the example in the SO reply used `lock` as an "open"-style context manager. (I'm not 100% sure if these differ functionally, but they're implied to be different in Wolph's reply?)

**Comment by joshuacwnewton** [comment]
Alternatively, it may be that we're dealing with an NFS mount in this situation, in which case https://github.com/wolph/portalocker/issues/92 may apply here:

> Locking with NFS is rather problematic, while it's not entirely impossible to do it, it absolutely kills your performance in my experience.
> If at all possible I would highly recommend using Redis Locks instead: https://github.com/wolph/portalocker#redis-locks

I'll check in the other issue regarding this. :)

**Comment by mguaypaq** [comment]
Looking at the code in [`portalocker.utils::Lock`](https://github.com/wolph/portalocker/blob/cdbefd4a5f272b8ad8c4d0468931e97d01854e62/portalocker/utils.py#L152-L167), I see that internally it does the same thing: open the file, then lock (and this is basically required by the OS interface, because you can only a lock on an open file handle). So, I don't think that's the problem.

However, both the README and [the docs](https://portalocker.readthedocs.io/en/latest/#examples) say that "to customize the opening and locking a manual approach is also possible" and give the example of opening with mode `r+` (which is what we need), so I assumed this was the only way to specify a file opening mode. But in fact the `Lock` context manager has always supported a `mode` argument! I should have looked :disappointed_relieved:

So, I might switch to using `with Lock` instead of `open(); lock()` during the rest of the QC refactor, but I don't think it will fix this problem.

**Comment by joshuacwnewton** [comment]
Assuming the issue here is NFS mounts, then maybe all we need to do is avoid locking _on the NFS-mounted drive_.

Actually, wait a minute here...

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7e538cfb888f81e1e6612921f2a87873f61a566/spinalcordtoolbox/reports/qc.py#L576-L579

There are two distinct steps here:

1. Generating a new .json entry to the QC report's `_json` folder
2. Reading in all of the .json files on disk, dumping all of it into the index.html template, and writing the data to a file.
 
But, all that really matters is that the "reading" step is done sequentially, right? (In other words, generating the JSON files concurrently is OK, as long as each process waits to read in the JSON data to generate the new `index.html` file.)

In that case, does it even matter which file we perform the lock on? Like, if the goal is simply to force certain steps to be done sequentially... couldn't we lock a random file in the SCT source code or something? The end result would be the same, but it wouldn't matter if the destination was an NFS mount or not.

**Comment by joshuacwnewton** [comment]
I think I might have a solution that could kill 2 birds with one stone:

> 2. Reading in all of the .json files on disk, dumping all of it into the index.html template, and writing the data to a file.

What if we were to isolate this logic inside of a separate, standalone Python script (e.g. `refresh_qc_entries.py`)? Then, distribute it as an asset inside of the QC folder?

This would have two benefits:

- Users could re-run this script when they want to refresh the QC entries, which could solve https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4438. (The user can delete one or more json files, then re-run the script to copy the new json data to the html file.)
- We could use the aforementioned [`portalocker.BoundedSemaphore`](https://portalocker.readthedocs.io/en/latest/portalocker.html#portalocker.BoundedSemaphore) to only ever run one instance of `refresh_qc_entries.py` at a time. (And, the encapsulation of this separate script would ensure that we're locking the entire "read-JSON-write-HTML" cycle, without the need for `open(mode='r=")` tricks.)
