### ISSUE TITLE
Problems caused by `sct_image -copy-header` on mask with different array shape from image

### ISSUE THREAD

**Issue by plbenveniste** [spinalcordtoolbox/spinalcordtoolbox#4424]
Hi team ! 

I am reporting an issue which was caused by the use of `sct_image -i {image_path} -copy-header {file} -o {file}`. 
The problem is described in this issue : [#305](https://github.com/neuropoly/data-management/issues/305).

What I do is I reorient the mask (to the image orientation) and then I copy the image header to the mask. 
The problem comes from the fact that the copy of the header is forced on the mask even when the data arrays are not of the same shape. I don't really know what the purpose of `-copy-header` is, but it should check if the arrays are the same size.

What are your thoughts on this ? 

Thanks in advance for your hard work ! 😃

**Comment by joshuacwnewton** [comment]
Hi @plbenveniste! Thanks for the report! 

If I understand correctly, the problem is described in https://github.com/neuropoly/data-management/issues/305#issuecomment-2024185550:

> It seems that the [dataset_correction.py](https://github.com/ivadomed/ms-lesion-agnostic/blob/plb/dataset_aggregation/dataset_aggregation/dataset_correction.py) script iterated not only through PSIR/STIR images (used by Pierre-Louis for his trainings) but also through T2w images due to [line 22](https://github.com/ivadomed/ms-lesion-agnostic/blob/plb/dataset_aggregation/dataset_aggregation/dataset_correction.py#L20-L22). Then since the T2w SC segs had different orientation and resolution than the T2w images (because [reorientation and resampling were applied before SC seg](https://github.com/ivadomed/canproco/blob/8e1b2c35f96eeeb3838b512dd93eba25e5a5e97a/scripts-t2w_csa/sct-preprocess_data.sh#L162-L170)), the script incorrectly copied the T2w header to T2w SC seg ([line 64](https://github.com/ivadomed/ms-lesion-agnostic/blob/cf70c890e6402e61f573fa58a686277ebb1c6c62/dataset_aggregation/dataset_correction.py#L63-L64)).

In other words, `-copy-header` was accidentally run on the wrong images, but it wasn't detected.

And, in order to better catch improper usage of `-copy-header`, you're requesting that the SCT command should throw an error if the `-i` image and `-copy-header` image have different array shapes?

**Comment by plbenveniste** [comment]
No, I ran it on purpose on the entirety of the images (even though I wasn't using the T2w images) because, in my opinion, it makes sense to have images and masks with the same resolution/array shape/orientation. However, I didn't know that the T2w images and their respective masks didn't have the same array shapes. The difference of array shapes caused the error. 

What I am trying to say is that `-copy-header` should not be used when the two files don't have corresponding array shapes. If they have different array shapes `-copy-header` causes some errors.

**Comment by jcohenadad** [comment]
I'm not 100% convinced that we should create an error if the src-dest matrix shape does not match. I think it is the responsibility of the researcher to make sure to use the command properly. Also, the matrix shape is not a full-proof test, as other parameters could differ, eg the Txyz, or the orientation. Moreover, in some cases, we do want to force the header onto an image that does not have the same shape (like in this case, to fix the issue that was created in the first place). Other tools also force copying the header despite images having different array shape (eg: `fslcpgeom`, although, interestingly, they do have a flag `-d : don't copy image dimensions`).

**Comment by joshuacwnewton** [comment]
I think I agree with @jcohenadad here about allowing data shape overwrites.

> However, I didn't know that the T2w images and their respective masks didn't have the same array shapes. The difference of array shapes caused the error.

Thank you for clarifying, @plbenveniste. :heart: 

I was wondering, maybe we could throw a warning instead if we detect mismatches? ("WARNING: Image dimensions and zooms will be overwritten...") However, I notice that even in @plbenveniste's script, there seems to be [this exact warning](https://github.com/ivadomed/ms-lesion-agnostic/blob/cf70c890e6402e61f573fa58a686277ebb1c6c62/dataset_aggregation/dataset_correction.py#L194).

```python
    # check if the image and the label have the same dimensions
    if image.shape != mask.shape:
        print(f'Image {image_path.name} and {file.name} have different dimensions')
```

So, I'm not sure if an extra warning from SCT would have helped prevent this situation... :thinking:

**Comment by jcohenadad** [comment]
> Maybe the doc could be updated/improved ?

how about this? https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4429/commits/5e8f9ec03d00088d55f92430544250806043f9c8

**Comment by plbenveniste** [comment]
Great ! I think it's very clear now ! Thank you for your time 😃
