### ISSUE TITLE
Change `-install-task` to `-install`

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4435]
I personally find it more intuitive

**Comment by joshuacwnewton** [comment]
Argparse allows for synonyms, so this change could be made very painlessly:

```diff
    seg.add_argument(
-        "-install-task",
+        "-install", "-install-task",
        help="Install models that are required for specified task.",
        choices=list(models.TASKS.keys()))
```

Both `-install` and `-install-task` will work (for backwards compatibility, if that's something we care about), and only the first arg name listed will be shown in the help:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/c31551ec-5216-402f-8411-c7cde8a4a2ce)
