### ISSUE TITLE
Integrate latest version of contrast-agnostic model

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4440]
I need it fairly urgently (few days) for a [project](https://github.com/spinal-cord-7t/coil-qc-code) I'm working on.

**Comment by naga-karthik** [comment]
Ah okay! at least on the contrast-agnostic repo, a release can be done within minutes. But, the bigger question @sandrinebedard and I were discussing is whether a new release has to be created for SCT. 

I mean, we can update the URL pointing to the latest release of the contrast-agnostic repo but this will only be on the `master` branch. Maybe an intermediate release (i.e. `v6.2.1`) has to created? (note: we have also added this to the agenda for the SCT meeting on Wednesday to discuss it with the rest of the team)

**Comment by jcohenadad** [comment]
> But, the bigger question @sandrinebedard and I were discussing is whether a new release has to be created for SCT.

Not necessarily for my project, but eventually before ISMRM because people will want to try it out.

**Comment by joshuacwnewton** [comment]
> > But, the bigger question @sandrinebedard and I were discussing is whether a new release has to be created for SCT.
> 
> Not necessarily for my project, but eventually before ISMRM because people will want to try it out.

As in, [04-09 May 2024, Singapore](https://www.ismrm.org/24m/)?

**Comment by sandrinebedard** [comment]
Yes! Since I am presenting the contrast-agnostic project! We can discuss during the SCT dev meeting tomorrow.

**Comment by naga-karthik** [comment]
Just created a [release](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.3) with the new model. Will open a PR on the SCT repo before tomorrow's meeting!
