### ISSUE TITLE
`-c` (`contrast`) field is not useful or 95% of deepseg models (and is unintuitive for contributors)

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4445]
The `sct_deepseg` CLI script has a `-c` (contrast) option, which corresponds to the `contrasts` field for deepseg models, e.g.:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8f2b0e0eb956cbd12d1cabdfbee34e1ca8d99c34/spinalcordtoolbox/deepseg/models.py#L78-L79

The purpose of this argument/field is twofold:

1. The `-c` option specifies the order of images passed to multi-image, multi-contrast models.
   - This is only relevant for a single model (`model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel`). Since most models are single-contrast, this option isn't actually necessary for 95% of our models, and we say this, too:
    https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8f2b0e0eb956cbd12d1cabdfbee34e1ca8d99c34/spinalcordtoolbox/scripts/sct_deepseg.py#L43-L46   
2. The `contrasts` field gets displayed in the extended `-list-tasks` view only (but not the `-h` table)
   - Note: This "informative" purpose is kind of redundant, since the task names also contain the contrast:
     ![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/52baed0b-feb3-43aa-8904-15db9ddacf61)

This is kind of weird!

- Normally, in SCT, `-c` is used to specify which contrast to use for multi-contrast CLI scripts. But, this is _not_ the purpose here, so from the user perspective, this isn't super intuitive.
- Also, from the contributor perspective, when adding a model, it seems like you would list all supported contrasts by your model (e.g. https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4443/commits/4b1335fbead5642bbdbff08cf0007cc6769b4b94). But, if you do this, then `sct_deepseg` will expect 2+ images (and throw an error otherwise), which is completely unintuitive!
- In addition, the `-c` option isn't even in sync with newer models -- the "choices" are `('t1', 't2', 't2star')` but newer models feature `'mp2rage'`, `'any'`, etc. (not that it matters, since you would never specify `-c` for these models anyway).

If I had to guess, I think what happened is that we designed this behavior specifically for `model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel` to solve the problem of "which order are the 2 images passed"? But, no other deepseg model takes in 2 images with different contrasts, so the option is useless (and confusing!) for every other model.

If we were to hardcode the behavior for `model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel` so that the image order must be e.g. `-i t2.nii.gz t1.nii.gz`, then there would be no need for the `-c` option at all, and thus we could remove this neglected part of `sct_deepseg`.

**Comment by jcohenadad** [comment]
I agree with you @joshuacwnewton. Unfortunately we now have a case where `-c` does make sense (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4443#discussion_r1571197597), although it's the only one (within the ~5%). I'm wondering if there is an alternative strategy...

**Comment by joshuacwnewton** [comment]
In the short term, this issue is partially alleviated by clarifying the `-c` help text:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/72ff27030efda92431ee831b45f31e2858b8552d/spinalcordtoolbox/scripts/sct_deepseg.py#L47-L51

**Comment by joshuacwnewton** [comment]
I think we can close this issue. The help has been updated, and `-c` is in use for several models, so it can be kept.
