### ISSUE TITLE
Integration of EPI segmentation nnUNet model in SCT

### ISSUE THREAD

**Issue by rohanbanerjee** [spinalcordtoolbox/spinalcordtoolbox#4453]
I am opening this issue to inform the integration of the EPI spinal cord segmentation 3D nnUNetv2 model into SCT. The latest trained model can be found in the `v0.2` release here: https://github.com/sct-pipeline/fmri-segmentation/releases/download/v0.2/model-fmri-segmentation-v0.2.zip. I will opening up a PR for the integration. 

I am also uploading a sample image from my dataset for testing:

[spinefmri_sub-hamburgP23_task-pain_bold_0000.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/15095700/spinefmri_sub-hamburgP23_task-pain_bold_0000.nii.gz)

**Comment by mguaypaq** [comment]
Were you hoping to include this in the SCT v6.3 release, which we're doing today/tomorrow? Or can this wait until SCT v6.4?

**Comment by rohanbanerjee** [comment]
I'm in the process of pushing the PR now. If it's possible, we can go ahead with the v6.3 release itself otherwise v6.4 is okay too. Some people at ISMRM would find this use too (though I am not going) and we could start with the alpha testing then.

**Comment by mguaypaq** [comment]
Ok, if it's ready today, and if it's useful for ISMRM, then we can include it.
