### ISSUE TITLE
Fix issues with `sct_deepseg` rootlets QC report

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4461]
Most `sct_deepseg` models involve binary/soft segmentations within the spinal cord (full cord, gm/wm, lesions, etc.). So, the initial PR #4446 works well for most models.

However, the rootlets model is quite different:

- It outputs integer labels (2.0, 3.0, 4.0, etc.) instead of a binary/soft seg.
- The rootlets labels are outside the spinal cord, with variable center of mass.

This means that we get an inconsistent crop + wrong colormap with the current "universal" `sct_deepseg` QC.

**Comment by joshuacwnewton** [comment]
I started working on a branch for this, but realized this is a bit more involved than I realized:

- The "center of mass" issue was quite easy to fix -- just a simple call to `get_centerline`. 
- I noticed that the axial mosaic crop size of 30x30 is too small to fully show the rootlets seg (since they exist outside the cord, in the CSF region). Increasing it to 40x40 helped.
- However, the colormapping is trickier:
   - The resampling that we're currently doing messes up the label values. (For comparison, `sct_label_vertebrae` skips resampling.)
   - Even if the labels were perfect, matplotlib's colormaps aren't suited to our labels out of the box.

----

I think the main issue here is that the rootlets seg isn't a binary/softseg, it's a "labeled seg" (akin to `sct_label_vertebrae`). So, it's not straightforward to simply adapt the existing `sct_deepseg` SC/lesion seg QC to it; I think it requires an entirely separate QC report.

So, I think it might be better to fix this as part of the effort for bringing `sct_label_vertebrae`'s QC to the `qc2.py` rework.

**Comment by joshuacwnewton** [comment]
> So, I think it might be better to fix this as part of the effort for bringing `sct_label_vertebrae`'s QC to the `qc2.py` rework.

Just to confirm this, I tried passing a sample rootlets segmentation to `sct_qc -p sct_label_vertebrae`. However, this caused a very glitchy-looking QC report:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/51478bee-5688-42dc-9564-4de0a4f50e79)

In hindsight, I realize now that the `sct_label_vertebrae` QC report is a single (flattened) sagittal slice, whereas we probably want an axial mosaic for rootlets (since viewing each pair of rootlets looking down the LR plane is kind of useless).

So, I think what will end up happening is the colormap logic will be reused with `sct_label_vertebrae`, but the overall QC logic will not.

**Comment by joshuacwnewton** [comment]
This is a bit trickier than I expected, because:

- All "label" QCs based on `Sagittal.single` are using `p_resample=None`.
   - The reason we set `p_resample=None` in the first place is because resampling labeled segmentations is tricky, as nn, linear, spline are all not appropriate.
   - For point labels, we do have a custom `resample_labels` function in `registration/labeling.py`, but we don't have a parallel function for labeled _regions_.
- `p_resample=None` isn't compatible with axial mosaics, because currently we use an axial crop size that is hardcoded to match `p_resample=0.6`.

I can think of two ways to work around this:

1. Turn off resampling (as is done for the `Sagittal.single` QCs), and instead adapt the crop size to the original resolution (i.e. if `0.6mm -> 30x30`, then `0.5mm -> 36x36`, and so on).
   - Note: Because this may result in a smaller output image (e.g. 1.0mm images will be 0.5x the size), we might also want to resize (not resample) the output image to 2x the normal size, just for visual purposes.
2. Keep the resampling to `0.6mm`, but create a new resampling method specifically for resampling labeled segmentations. (e.g. split into separate segs, resample linearly + threshold, recombine)

Option 1 seems like the simplest to me? It didn't take too long to implement, but it isn't the clearest:

![Image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/c30be648-c32f-4e5b-99f8-65369077bb25)

I am still working out a colormap that contrasts against white *and* black... we might need to add a transparent layer to the "foreground" image to provide better contrast.

Also, given the pixelated nature of this QC report, I am wondering if going the more complicated route (custom resampling) would be best, or if I am missing something that's more straightforward.

**Comment by valosekj** [comment]
Thank you for digging into this, @joshuacwnewton! 

The following two things came to my mind (sorry if they are irrelevant):
1. Resampling: I believe that the most common image resolution we currently use for rootlets segmentation is 0.8 mm iso. Would it be possible to keep this resolution, i.e., not doing the interpolation at all? The interpolation might slightly change the rootlets' appearance. The user might thus get the feeling that there is a problem with the segmentation.  
2. Colormap: personally, I have found that the `matplotlib jet` colormap is quite good for visualizing rootlets. (At least in FSLeyes; [here](https://gist.github.com/valosekj/e9464071a07197f52a4526d8014e2e9a) is a code for how I brought the colormap to FSLeyes)

**Comment by joshuacwnewton** [comment]
> Resampling: I believe that the most common image resolution we currently use for rootlets segmentation is 0.8 mm iso. Would it be possible to keep this resolution, i.e., not doing the interpolation at all? The interpolation might slightly change the rootlets' appearance. The user might thus get the feeling that there is a problem with the segmentation.

Perfect! This is very helpful information, as it means that I can keep the "simpler" implementation, which involves only a few changes to the existing `sct_deepseg` QC report.



> Colormap: personally, I have found that the `matplotlib jet` colormap is quite good for visualizing rootlets. (At least in FSLeyes; [here](https://gist.github.com/valosekj/e9464071a07197f52a4526d8014e2e9a) is a code for how I brought the colormap to FSLeyes)

Ahh, lovely! I will test it out. Thank you for the recommendation!

-----

Also, FYI, FSLeyes actually supports matplotlib colormaps out of the box! I only discovered this recently, but you can pass the name of an MPL colormap to FSLeyes on the command line (not sure how to do it via the GUI). We use this in SCT for the [`YlOrRd` colormap](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65e44b5068fe5d8a094e3e0571566c01d2d460ab/spinalcordtoolbox/utils/shell.py#L55), and it seems to work for Jet too? 

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/3d14a845-0de8-447f-9ccc-8f824f0b0e59)


(Also, funny thing, when I google "fsleyes matplotlib colormap" your gist comes up!)

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/3e819ff9-5ea6-436a-8ef4-56eb19268ddb)

**Comment by valosekj** [comment]
> Also, FYI, FSLeyes actually supports matplotlib colormaps out of the box! I only discovered this recently, but you can pass the name of an MPL colormap to FSLeyes on the command line (not sure how to do it via the GUI). We use this in SCT for the [`YlOrRd` colormap](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65e44b5068fe5d8a094e3e0571566c01d2d460ab/spinalcordtoolbox/utils/shell.py#L55), and it seems to work for Jet too?

Interesting, thank you! I wasn't aware of this! 

> (Also, funny thing, when I google "fsleyes matplotlib colormap" your gist comes up!)

Haha, nice!

**Comment by joshuacwnewton** [comment]
Hmmm... Jet's definitely better? But, I find that there are are still some contrast issues:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/4a11602c-57bd-4d9e-84c6-288de1dc3313)

But, when I add a transparent black layer, it looks much more clear (n.b. slightly different blue):

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/fc5190a7-e5f6-4a78-9b4d-2508d9f2eb5b)

**Comment by valosekj** [comment]
Could you please also show what the rootlets look like on T2w with the transparent black layer? (i.e., just T2w image without rootlets segmentation). In other words, I am wondering what the contrast between rootlets and CSF is on the T2w image after adding the transparent black layer.

**Comment by joshuacwnewton** [comment]
> Could you please also show what the rootlets look like on T2w with the transparent black layer? (i.e., just T2w image without rootlets segmentation).

Thankfully, I only add the transparent background to the "segmentation" layer, so that the original image is unaffected. Here is a gif of how it looks in the report:

![ezgif-4-e0e6b073f4](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/936a3b26-af77-4c22-9188-c05790a576bf)
