### ISSUE TITLE
Custom argparse formatter fails for blank lines in multiline strings

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4471]
Normally, for argparse help descriptions, we use multiple single-line strings with explicit newlines:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2c0649b1cb97b4f11bab9f506b68633fa967907b/spinalcordtoolbox/scripts/sct_extract_metric.py#L63-L68

However, in PR #4302, a multi-line string was instead used:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/2c0649b1cb97b4f11bab9f506b68633fa967907b/spinalcordtoolbox/scripts/sct_compute_flow.py#L19-L25

Because there is a whitespace-only line, we get an error here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/069fe79472f3e7a664e0e38c4f123b149814aa59/spinalcordtoolbox/utils/shell.py#L331-L337

The issue is as follows:

- The line contains only whitespace (`'       '`).
- The line is non-empty, so it passes the `if len(li) > 0` check.
- But, because the line is only whitespace, `textwrap.fill(li, width_adjusted)` returns `''`, and `splitlines()` returns `[]`.
- Hence, `init_wrap[0]` is indexing an empty list.

I think this can be fixed easily by changing the check to `if len(li.strip()) > 0`. That way, the text wrapping will be skipped for whitespace-only lines.

**Comment by mguaypaq** [comment]
I wonder how much of the customization is still relevant. For example, our custom formatter explicitly uses `shutil.get_terminal_size()`, but apparently this is the default behaviour [as of 6 years ago](https://github.com/python/cpython/pull/8459).

**Comment by joshuacwnewton** [comment]
> I wonder how much of the customization is still relevant. For example, our custom formatter explicitly uses `shutil.get_terminal_size()`, but apparently this is the default behaviour [as of 6 years ago](https://github.com/python/cpython/pull/8459).

Even though this was just a simple example (and the rest of our hacks/tweaks should maybe be reconsidered as well)...

Oddly, it seems like the default argparse width is [2 less](https://github.com/python/cpython/pull/8459/files) than the terminal width (e.g. 78 vs. 80) which causes some unwanted wrapping, given many strings were written with `80` in mind (e.g. `sct_deepseg -h`). I have to extend the terminal to 82 to get the same output, hehe.
