### ISSUE TITLE
Straightening is not a bijective transformation

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4477]
### Description

While working on https://github.com/sct-pipeline/spine-park/issues/33, I realized that applying the warp_straight2curve transformation on a straightened spinal cord does not produce the same (or at least _very_ similar) curved image. However, this issue seems to be dependent on the data. For example, if I try to reproduce it using the testing data, the result is very similar:

~~~
cd $SCT_DIR/data/sct_testing_data/t2
sct_straighten_spinalcord -i t2.nii.gz -s t2_seg-manual.nii.gz 
sct_apply_transfo -i t2_straight.nii.gz -d t2.nii.gz -w warp_straight2curve.nii.gz
~~~

Comparing the original image and the curve2straight2curve image:
![ezgif-3-2b40623fbf](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/ebdad01c-05a9-4302-a60a-8fc903f93dd7)

However, when working on the larger-FOV image from https://github.com/sct-pipeline/spine-park/issues/33, the discrepancy is much visible:
![ezgif-3-56e1998e68](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/01d02d29-accb-4229-afdc-a2973bccb965)

**Comment by jcohenadad** [comment]
Input resolution of `sub-DEV169Sujet03_T2.nii.gz` is: 
~~~
pixdim1		0.781250
pixdim2		0.781250
pixdim3		0.800000
~~~

**Comment by jcohenadad** [comment]
Trying with another (longer FOV) file, from the spine-generic project, results are as expected (ie: _very_ similar original image vs. curve2straight2curve):

![ezgif-6-122a5a5205](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/a08c0292-1687-4b63-b82a-7d204656ced5)

dim:
~~~
pixdim1		0.799999
pixdim2		0.800000
pixdim3		0.800000
~~~

**Comment by jcohenadad** [comment]
Trying with another image from Lydia: `sub-BB277`: I notice the same issue:

![ezgif-6-a8a7d3cef7](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/675048c4-49af-4a98-a844-cdb5b161fa9f)

So, is this related to the slightly longer FOV on Lydia's images? Let's try with a bigger FOV from our database

**Comment by jcohenadad** [comment]
Another image from PAM50 data (larger FOV) no issue observed:

![ezgif-6-3c55f85f29](https://github.com/sct-pipeline/spine-park/assets/2482071/c0b7a38c-4cd5-472b-a11a-2e3d155db680)

**Comment by jcohenadad** [comment]
Resampled our internal image to the dimension of the image from Lydia, but it did not reproduce the issue:

```console
sct_resample -i sub-unf02_T2w.nii.gz -mm 0.78x0.78x0.8 
sct_deepseg -i sub-unf02_T2w_r.nii.gz -task seg_sc_contrast_agnostic
sct_straighten_spinalcord -i sub-unf02_T2w_r.nii.gz -s sub-unf02_T2w_r_seg.nii.gz 
sct_apply_transfo -i sub-unf02_T2w_r_straight.nii.gz -d sub-unf02_T2w_r.nii.gz -w warp_straight2curve.nii.gz 
```
![ezgif-2-99836d6db0](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/beb70e0a-ffff-43ef-8bb1-67524c069e28)

**Comment by mguaypaq** [comment]
A quick experiment:

Looking at sub-DEV202 and sub-DEV203, which have the same dimensions and very similar (but different) qforms:
* sub-DEV202 looks bijective
* sub-DEV203 shows the problem
* copying the header of sub-DEV202 to sub-DEV203 fixes the problem (looks bijective)
* copying the header of sub-DEV203 to sub-DEV202 **introduces** the problem

Looking at both versions of sub-DEV202, it looks like the problem shows up when there's a significant forward tilt. I don't know the cause yet, but maybe having the SI axis at a significant angle from vertical creates a problem? I'll look into it.

**Comment by jcohenadad** [comment]
tagging @benjamindeleener who implemented the method-- maybe he has some insights

**Comment by Kaonashi22** [comment]
I guess this is the same issue with this subject; the vertebral bodies don't align well between the UNI image (blue arrow) and the T1 template after registration (green)
![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/155473122/d3b26ae9-3d35-4925-a9fc-fa57a30c83ff).


[PAM50_t1_reg.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/15312743/PAM50_t1_reg.nii.gz)
[sub-AM273_UNIT1.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/15312747/sub-AM273_UNIT1.nii.gz)
[sub-AM273_UNIT1_crop.nii.gz](https://github.com/spinal
[sub-AM273_UNIT1_seg.nii.gz](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/15312749/sub-AM273_UNIT1_seg.nii.gz)
cordtoolbox/spinalcordtoolbox/files/15312748/sub-AM273_UNIT1_crop.nii.gz)
[batch_processing_sub-AM273.log](https://github.com/spinalcordtoolbox/spinalcordtoolbox/files/15312773/batch_processing_sub-AM273.log)

**Comment by joshuacwnewton** [comment]
(Quick sanity check: Installed SCT v5.0.0, and this behavior persists. So, I don't think it's been caused by any of the small tweaks/refactors to straightening since 2020.)

----

As another way of visualizing the problem: I tested the following command on the DEV202/DEV203 subjects highlighted by @mguaypaq's https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4477#issuecomment-2110818324:

```
sct_concat_transfo -d {input_img} -w warp_curve2straight.nii.gz warp_straight2curve.nii.gz
```

This produces a concatenated warping field that can be directly applied to the input image to reproduce the "sheared" results. If I open the concatenated `warp_final` in FSLeyes and set the brightness/contrast to `-0.5`/`0.5` minmax with a divergent colormap, I get:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/844b1931-65da-41bb-810d-6fc942ec0654)

(Left: DEV203, Right: DEV202)

DEV203 is much more extreme, but DEV202 still shows visible +/- shifts, indicated by the blue and red patterns. So, I reckon that whatever the issue is, the affected subjects are just the extreme versions of the behavior that already exists. In other words, _none_ of the curve2straight/straight2curve transform pairs are technically bijective, the effect is just much more pronounced for some subjects. 

_(Maybe this is stating something that was already apparent? But, I thought it would be helpful to potentially reframe the problem as "behavior inherent to `sct_straighten_spinalcord`'s algorithm" rather than "bug that is completely separate from the normal behavior". Meaning, there may not be a smoking gun that we can find here.)_

**Comment by jcohenadad** [comment]
> (Quick sanity check: Installed SCT v5.0.0, and this behavior persists. So, I don't think it's been caused by any of the small tweaks/refactors to straightening since 2020.)

Great! I was wondering this actually. Thank you for checking

**Comment by jcohenadad** [comment]
> none of the curve2straight/straight2curve transform pairs are technically bijective, the effect is just much more pronounced for some subjects

Right. Thank you for clarifying this, @joshuacwnewton. This is indeed what I meant.

**Comment by Kaonashi22** [comment]
Hi, any updates on this issue?

**Comment by joshuacwnewton** [comment]
> Hi, any updates on this issue?

We discussed this in our most recent SCT dev meeting ([2024-05-15](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.jol6bz910y1z)), and we came to the conclusion that debugging this issue would require a deeper understanding of the underlying straightening code (most likely [this transform step](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/straightening.py#L431-L490) of the [overall algorithm](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/straightening.py#L66-L78)). 

Fully understanding the underlying code may take some time, as the person who is looking into this issue (@mguaypaq) is a different person than the person who originally developed this method some years ago (@benjamindeleener).

----

> [!NOTE]
> Benjamin did share some thoughts in our internal Slack, which I can copy to this issue since Benjamin is currently locked out of his GitHub account:
>
> 
> > @benjamindeleener: To give some insights, straightening does not produce a bijective transformation. The script computes the two transformations by calculating them two times. The issue was known originally (I believe it is mentioned in the manuscript), but the results should be very close in most cases. We assumed it would not be a problem in the future. It is possible to transform the method to produce a bijective transformation but it may require some time, mainly because of edge issues (the problem is an ill-posed problem without regularization when calculating the transformation far from the centerline.
> >
> > @jcohenadad: for some reasons, some subjects are waaaaaaay less bijective than others. This is documented in the issue, with some examples. In some cases, depending on the q/form it seems (Mathieu did some tests), there is an abnormal shearing that is being applied on the transformation matrix. This is very strange, and i was wondering if you had some ideas about the cause for it

**Comment by Kaonashi22** [comment]
Thank you, hope the issue can be solved!

**Comment by mguaypaq** [comment]
I spent today working through the straightening code. I did find a few things that really look like bugs, but none of them improved the shearing effect we're seeing on the images here. I'll keep looking.

* In this code, there's a linear algebra mistake: the projection formula used only works when the vectors `self.derivatives[indexes]` are unit-length vectors. But (empirically) the vectors `self.derivatives[indexes]` are **not** unit-length.
  https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/types.py#L323-L324

* In this code, the `centerline_straight` is initialized with a mix of **physical** space points, and **voxel** space derivatives. I'm pretty sure the derivatives should also be given in physical space.
  https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/straightening.py#L346-L357

* This bit of code for `straight2curved` doesn't match the corresponding code for `curved2straight`. It should almost certainly be using `centerline_straight.get_inverse_plans_coordinates` instead of doing manual matrix manipulations.
  https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a7a3f8dd021b6b7f8d2b9fa2680002ed4b1c5f2c/spinalcordtoolbox/straightening.py#L481-L483

**Comment by benjamindeleener** [comment]
Thank you for finding those bugs!

Regarding the issue, my first suggestion would be to look into the centerline derivative for instabilities. Depending on the method used to extract / create the centerline, the smoothing method may introduce oscillations that are dependent on the length of the curve (e.g., a polynomial estimation with fixed end points). I believe we have a tool to display the centerline in the three 2D planes as well as the derivatives.

**Comment by jcohenadad** [comment]
> Regarding the issue, my first suggestion would be to look into the centerline derivative for instabilities. Depending on the method used to extract / create the centerline, the smoothing method may introduce oscillations that are dependent on the length of the curve (e.g., a polynomial estimation with fixed end points). I believe we have a tool to display the centerline in the three 2D planes as well as the derivatives.

Thank you for chipping in @benjamindeleener. I've (quickly) looked at the derivatives of the NURBS fitted centerline, and it looks OK to me (ie no oscillations, and value looks reasonable wrt. the centerline coordinates on X and Y), eg: https://github.com/sct-pipeline/spine-park/issues/33#issuecomment-2110173933

It seems like the issue has more to do with a systematic bias (eg shearing parameter), vs. instabilities (ie noise) in the estimate of the derivatives.

**Comment by mguaypaq** [comment]
Ok, I think I found something: the centerline derivatives returned by this call to `get_centerline` look very strange:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/bb479d82ea1e2076dd50343177056a61bd17e260/spinalcordtoolbox/straightening.py#L152-L157

Specifically, the centerline derivative at a point should be almost parallel to the difference between two consecutive points. But in this case, it's really not. On some example data, I picked the 100th point out of 297:
```py
>>> _, pts, der, _ = get_centerline(Image('t2_seg.nii.gz'), ParamCenterline(algo_fitting='nurbs'), space="phys")
>>> pts.shape, der.shape
((3, 297), (3, 297))
>>> pts[:, 101] - pts[:, 100]
array([0.7941607 , 0.01081829, 0.42369515])
>>> der[:, 100]
array([-0.01059804,  0.40128474,  0.799999  ])
```

By comparison, if I remove the `space="phys"` option, I get almost perfect agreement:
```py
>>> _, pts, der, _ = get_centerline(Image('t2_seg.nii.gz'), ParamCenterline(algo_fitting='nurbs'))
>>> pts.shape, der.shape
((3, 297), (3, 297))
>>> pts[:, 101] - pts[:, 100]
array([-0.01384741,  0.52808393,  1.        ])
>>> der[:, 100]
array([-0.0135655 ,  0.51364441,  1.        ])
```

So, there may be something seriously wrong with the `space="phys"` option to `get_centerline`.

**Comment by mguaypaq** [comment]
Yes, this is definitely _not_ the right way to adjust the derivatives to physical coordinates:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/bb479d82ea1e2076dd50343177056a61bd17e260/spinalcordtoolbox/centerline/core.py#L273-L281

**Comment by joshuacwnewton** [comment]
Side note: We had definitely done some refactoring related to `space="phys"` in recent years (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4010), but I don't think any of our refactoring was functional in nature? Urgh... maybe they were.

**Comment by mguaypaq** [comment]
Looking at that pull request, it looks like that bit of code was just moved, not really changed. Also, this would be consistent with "diagonal" qforms working right, and "slanted" qforms giving deformed results.

**Comment by mguaypaq** [comment]
Bingo! That fixed the issue. I'll make a pull request. I just hope that other code didn't rely on the buggy behaviour.

**Comment by Kaonashi22** [comment]
Thanks @mguaypaq !

**Comment by joshuacwnewton** [comment]
Amazing work, @mguaypaq!!! Thank you for such a thorough investigation of the problem, and for deeply interrogating the implementation of the straightening paper. :hearts:
