### ISSUE TITLE
Input requirements for `-x label` are unclear (what is a "single-voxel label"?)

### ISSUE THREAD

**Issue by naga-karthik** [spinalcordtoolbox/spinalcordtoolbox#4497]
### Description

I am running an experiment on lesion segmentation on straigtened spinal cords for which I used `sct_straighten_spinalcord`. I applied the resulting `warp_curve2straight.nii.gz` on the lesion mask to transform the lesion into the straightened space. I noticed that `sct_apply_transfo` gives 4 options for interpolation: `{nn, linear, spline, label}`. I have been using `linear` interpolation until now to transform labels but I tried the `-x label` option based on description:

```
The 'label' method is to be used if you would like to apply a transformation on a file that has 
single-voxel labels (classical interpolation methods won't work, as resampled labels disappear 
or their values be altered). The function will dilate each label, apply the transformation nearest 
neighbour interpolation, and then take the center-of-mass of each "blob" and output a single voxel per blob.
```

While this seems to be what I am looking for, the results are not as expected. I am basically seeing a point (single-voxel) output. 

<details>
<summary> output </summary>

![Screenshot 2024-05-28 at 4 14 03 PM](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/53445351/9355c05d-4d75-4e5e-b9d6-97ddb0b80e25)

</details>

<details>
<summary> Original label before straightening </summary>

![Screenshot 2024-05-28 at 4 16 14 PM](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/53445351/19ff7ca8-1106-43d9-9f29-1e5b1220984f)

</details>

SCT Version: Spinal Cord Toolbox (git-master-29476b99e05d59a2b42ed7d20d4f40a58a53c497)

Command used:
```
# Process with incrementing warp file names
sct_straighten_spinalcord -i ${file} -s ${base_name}_seg-manual.nii.gz -o ${base_name}_desc-straightened.nii.gz
mv warp_curve2straight.nii.gz warp_curve2straight_chunk-${counter}.nii.gz
mv warp_straight2curve.nii.gz warp_straight2curve_chunk-${counter}.nii.gz
mv straight_ref.nii.gz straight_ref_chunk-${counter}.nii.gz
    
# apply warping field to sc and lesion labels
sct_apply_transfo -i ${base_name}_seg-manual.nii.gz -d ${base_name}_desc-straightened.nii.gz -w warp_curve2straight_chunk-${counter}.nii.gz -x label -o ${base_name}_seg-manual_desc-straightened.nii.gz
sct_apply_transfo -i ${base_name}_lesion-manual.nii.gz -d ${base_name}_desc-straightened.nii.gz -w warp_curve2straight_chunk-${counter}.nii.gz -x label -o ${base_name}_lesion-manual_desc-straightened.nii.gz

```

Am I missing something in how the `label` arg must be used? Any help is appreciated, thank you! Tagging @jqmcginnis as he also faced the same issue first!

**Comment by jcohenadad** [comment]
you’re not missing anything— as the help says: the expected output of the ‘label’ option is a single point (ie: center of mass of the blob)

**Comment by joshuacwnewton** [comment]
I'll open up a quick PR to clarify the help and provide an example.

**Comment by naga-karthik** [comment]
Thank you for the clarification! I got it now. One of those situations where you hit _send_ and immediately realize what something actually means 😅

**Comment by jqmcginnis** [comment]
I think for me, I had the same misunderstanding as the [greedy registration tool](https://greedy.readthedocs.io/en/latest/quick_start.html#applying-warps-to-images-and-segmentations) has the option of specifying the label option for the interpolation mode as well, but here it is used in order to interpolate masks to a different space, which differs from the use case / or functionality provided with the `-x label` option for sct_apply_transfo's label option.

 I am unsure if other toolboxes have a similar understanding or if this is unique to greedy or SCT, respectively.

**Comment by jcohenadad** [comment]
I guess the problem comes from the word 'label', which is not specific at all to a 'single voxel'. It would have been better to call this option 'single-voxel', but it might be too late now (or is it? not so many people use this, so it won't break too many pipelines...)

**Comment by joshuacwnewton** [comment]
While I agree that `label` isn't the clearest name, I don't think it's _so_ bad that we need to change it? Personally, I'm happy with starting with documentation changes for now.
