### ISSUE TITLE
The threshold parameter of `sct_deepseg` doesn't work with the model `seg_sc_contrast_agnostic` for soft segmentation.

### ISSUE THREAD

**Issue by simonqueric** [spinalcordtoolbox/spinalcordtoolbox#4503]
There is an issue with the threshold parameter of `sct_deepseg`.
Setting it to 0 is supposed to perform soft-segmentation but it doesn't seem to work with the model `seg_sc_contrast_agnostic`.

Here is an example with a canproco volume : 

`sct_deepseg -task seg_sc_contrast_agnostic -thr 0 -i sub-mon003_ses-M0_PSIR.nii.gz`

What I get is a binary segmentation : 

![Capture d’écran du 2024-05-31 10-45-48](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/56970073/f294f186-f18a-4ac0-8238-275c239fa20d)

instead of a soft segmentation.

**Comment by joshuacwnewton** [comment]
Thank you for finding this issue! That's very strange....

Does `-thr 0.01` work for you?

**Comment by jcohenadad** [comment]
I _think_ @naga-karthik fixed it [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4482/commits/aadf57aa587f6cd921f0946514abb2c3a19e9d71)

**Comment by naga-karthik** [comment]
yes! But it was a _bad_ quick fix. Surely, a cleaner way exists ... 

@joshuacwnewton let me know if you're looking into it or should I. In case you _are_ looking into it, please note that the default threshold we decided was `0.1`. That means, if a user explicitly requires softseg then SCT should output a result with 0.1 threshold. This threshold value was chosen based on comparing different thresholds and their downstream effects on the spinal cord CSA! (details [here](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/98#issuecomment-1981945386))

**Comment by simonqueric** [comment]
> Thank you for finding this issue! That's very strange... I'm happy to investigate!
> 
> In the short term, does `-thr 0.01` work for you?

Yes this threshold works on the branch `master`. Notice that the soft-segmentation works on the branch `nk/4481-add-monai-postprocessing`.

**Comment by joshuacwnewton** [comment]
Taking a look at this now! My apologies for the delay.

**Comment by joshuacwnewton** [comment]
I was able to fix this issue and generate a softseg, and I'll be pushing a fix ASAP.

However, I noticed in the output softseg, there are negative values?

This surprised me, as I expect softsegs to be in the range `[0, 1]`. Have you experienced this from the contrast agnostic model in the past? I'm wondering if we should be clipping values `<0` to `0`.

**Comment by jcohenadad** [comment]
> However, I noticed when I test with t2.nii.gz, there are negative values in the output softseg? Also, the max value is > 1?

could this be caused by interpretation when the prediction is resampled back to the input image resolution? But this would only happen with spline interpolation of order 2+ (which should not be used for segmentation anyway)

**Comment by joshuacwnewton** [comment]
I think I have the cause, opening a new issue. :)
