### ISSUE TITLE
Thresholding during image registration

### ISSUE THREAD

**Issue by plbenveniste** [spinalcordtoolbox/spinalcordtoolbox#4504]
Opening this issue to investigate if there is a thresholding during image registration using `algo=centermass`. 
The investigation comes from the fact that we saw that the registration output of a registration done using a soft SC seg and the output of the registration done using a binary SC seg are identical. 

This is related to [issue 91](https://github.com/ivadomed/canproco/issues/91) and [PR 95](https://github.com/ivadomed/canproco/pull/95).

**Comment by joshuacwnewton** [comment]
It looks like there is a rounding step specifically for the PCA computation used by `centermass` and `centermassrot` here:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0481a037166257c15e5cdcbd43bfafde1784c9ea/spinalcordtoolbox/registration/algorithms.py#L1434

> [!NOTE]
> It turns out that for `sct_register_to_templtae`, there is also _another_ binarization step that gets performed on all segmentations (regardless of `algo`):
>
> https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0481a037166257c15e5cdcbd43bfafde1784c9ea/spinalcordtoolbox/scripts/sct_register_to_template.py#L451-L457
>
> But this does not occur for `sct_register_multimodal`.
