### ISSUE TITLE
Output softseg from MONAI inference is not in the range `[0, 1]`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4507]
When testing https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4503, I noticed that the output colormap used for the softseg was `grayscale`, indicating that `check_image_kind` did not see it as a softseg.

The cause was values outside of the range `[0, 1]`, which are present from the postprocessed MONAI input.

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/90e6e9d7-f7e9-4962-8a9f-0527a8203061)

However, interestingly, when I inspect the `batch['pred']` output from `sliding_window_inference`, I get the expected results:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/bc590580-bf21-4852-af07-c691be224f93)

This implies that something is going wrong in the MONAI postprocessing:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20be5e53d05d82b09b8027e59809356bda694b3b/spinalcordtoolbox/deepseg/inference.py#L165-L168

**Comment by joshuacwnewton** [comment]
As @jcohenadad suggested in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4503#issuecomment-2145742877:

> > However, I noticed when I test with t2.nii.gz, there are negative values in the output softseg? Also, the max value is > 1?
> 
> could this be caused by interpretation when the prediction is resampled back to the input image resolution? But this would only happen with spline interpolation of order 2+ (which should not be used for segmentation anyway)

This is exactly the cause. 

----

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20be5e53d05d82b09b8027e59809356bda694b3b/spinalcordtoolbox/deepseg/monai.py#L150-L158

[`nearest_interp=False`](https://docs.monai.io/en/stable/transforms.html#monai.transforms.Invertd.__init__), which means:

> nearest_interp – whether to use nearest interpolation mode when inverting the spatial transforms, default to True. If False, use the same interpolation mode as the original transform. It also can be a list of bool, each matches to the keys data.

The original transform, `transforms_test`, is a copy of:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/20be5e53d05d82b09b8027e59809356bda694b3b/spinalcordtoolbox/deepseg/monai.py#L165-L175

`Spacingd(mode=2)` refers to Spline interpolation of order 2, which is _exactly_ what @jcohenadad predicted.

**Comment by naga-karthik** [comment]
Wait, so are you suggesting that setting when `nearest_interp=False`, `Invertd` is using the same interpolation (i.e. `spline` which is `2`) even when I explicitly set the `Spacingd` transform is specifically applied to `keys=["image"]` when the _preprocessing_ is done on the inputs?

**Comment by naga-karthik** [comment]
But, commit https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4508/commits/160c0b76149bec381d2125ec080cfd2e719defbb changes the interpolation of the `image` to `bilinear` which we don't want right? 

We got the best results for interpolating the images with `spline` and the segmentations with `linear`. Is there a way to apply linear interpolation on the just the predictions (`"pred"`) and not touch the preprocessing transforms (which are applied only to the input images)?

**Comment by joshuacwnewton** [comment]
Yes exactly! My understanding is that 'Invert' uses the same interpolation as the preprocessing. 

I was unsure about using bilinear for the input, so thank you for confirming that it's not acceptable. I'll try to figure out a way to have different transforms for both the preprocessing and the inverse.
