### ISSUE TITLE
Update contrast-agnostic model to 2.4

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4509]
Would be useful for an urgent project: https://github.com/ivadomed/canproco/issues/98

(and less cumbersome to have it in SCT master rather than asking our collaborator to manually edit the `models.py` file)

**Comment by joshuacwnewton** [comment]
Note to self: 2.4 has [already been released](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.4) on the project repo, so updating should be very quick and easy. :) 

Will do ASAP.
