### ISSUE TITLE
Indicate deepseg model

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4518]
Thanks to a recent PR, the model version is now checked, and the user sees this at inference:

~~~
Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date
~~~

This is great, but what would be even greater, would be to display the model version, eg:
~~~
Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date (vX.Y)
~~~

**Comment by joshuacwnewton** [comment]
"Model version" is a bit tricky because we use URLs as versions (because multiple assets can be attached to a single GitHub release, and also because of OSF mirrors).

We can very easily do something like this, though:

```
Model 'model_seg_sc_contrast_agnostic_softseg_monai' is up to date (Source: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip
```

It's a bit verbose, but it is very explicit.
