### ISSUE TITLE
Cannot checkout a release

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4524]
### Description

I'm trying to checkout a release and I'm getting this error:
```bash
julien-macbook:~/code/spinalcordtoolbox $ git checkout 6.3
error: pathspec '6.3' did not match any file(s) known to git
```

And on the page of the release commit, it says this:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/21cc5b1f-a909-40bd-9a31-f2a0354cd632)

Is this normal? On the [documentation](https://spinalcordtoolbox.com/user_section/installation/mac.html#option-2-install-from-github-development), we instruct with the following syntax, so that's a problem:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/85647870-d2ca-4d44-855c-df94dae0e82a)

**Comment by jcohenadad** [comment]
Is this maybe related to the fact that we use 'squeeze' when merging PRs? But if that's the case, we need to find a solution to instruct people on how to git checkout a specific release.

**Comment by joshuacwnewton** [comment]
I received the same error in my local SCT installation. To checkout a (recently created) tag, I needed to first run:

```
git fetch --tags
```

Sample output:

```console
master|joshua@monarch:~/repos/spinalcordtoolbox$ git fetch --tags
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 102 (delta 76), reused 78 (delta 57), pack-reused 0
Receiving objects: 100% (102/102), 33.38 KiB | 11.13 MiB/s, done.
Resolving deltas: 100% (76/76), completed with 9 local objects.
 * [new tag]           6.1                                   -> 6.1
 * [new tag]           6.2                                   -> 6.2
 * [new tag]           6.3                                   -> 6.3
```

----

Interestingly, I did _not_ get this issue when freshly cloning SCT using `git clone {URL}`. However, I did get this issue when running the specific `git clone` command used in our installer:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/86d5f8d5a473e5e034d365726a548d96776da755/install_sct#L425

**Comment by mguaypaq** [comment]
Joshua is right that `git fetch --tags` is the right command to use to fix this. By default, the installer only downloads a single commit, to speed up the download.

As for warning message on github, it's not because of our use of 'squeeze' when merging PRs. It sounds scary but it's a harmless message. It's because our release is:

1. Start with the master branch.
2. Add 1-2 commits to set the `version.txt` file, and the `requirements-freeze.txt` file. (These commits are never added to the master branch.)
3. Tag the result as (for example) 6.3

Because of step 2, technically the tag is on a divergent history compared to the master branch (or any other branch). Our release process is slightly unusual, so github doesn't fully understand it, and it displays the warning message.

**Comment by joshuacwnewton** [comment]
Marking this as completed, I think? But if there is something actionable we should do, feel free to reopen.

**Comment by jcohenadad** [comment]
I see. Indeed, with a full clone done _before_ running `install_sct` the checkout works fine:

<details><summary>Terminal output</summary>

```console
julien-macbook:~/temp $ git clone https://github.com/spinalcordtoolbox/spinalcordtoolbox bla
Cloning into 'bla'...
remote: Enumerating objects: 61499, done.
remote: Counting objects: 100% (2717/2717), done.
remote: Compressing objects: 100% (1773/1773), done.
remote: Total 61499 (delta 1822), reused 1604 (delta 923), pack-reused 58782
Receiving objects: 100% (61499/61499), 119.56 MiB | 13.08 MiB/s, done.
Resolving deltas: 100% (35482/35482), done.
julien-macbook:~/temp $ git bla
git: 'bla' is not a git command. See 'git --help'.

The most similar command is
	blame
julien-macbook:~/temp $ cd bla
julien-macbook:~/temp/bla $ git checkout 6.3
Note: switching to '6.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6e75cd8a Update version.txt for 6.3
```

</details>

So as long as users follow the [dev install](https://spinalcordtoolbox.com/user_section/installation/mac.html#option-2-install-from-github-development) in the right order, it works fine. But if a user would like to check out a release _after_ running the installer, then it will break, right? And our decision is to leave it as is because adding to much info in the documentation will confuse people and this use case concerns <1% of our users. Fair enough.
