### ISSUE TITLE
Reuse of warping field should not happen if SCT version evolved

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4526]
### Description

While comparing the effect of https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4514 on data from https://github.com/sct-pipeline/spine-park, I ran the previous and the new method back-to-back, in the same folder, and did not observe any difference.

Digging a bit, I noticed that the straightening was _not_ redone, because it already found a warping field, even though the warping field would be different with the now-different straightening method (notice the `Reusing existing warping field which seems to be valid`):

<details><summary>Terminal output</summary>

```console
julien-macbook:~/temp/Lydia/results_20240611_093435/data_processed/sub-DEV169Sujet03/anat $ sct_register_to_template -i sub-DEV169Sujet03_T2.nii.gz -s sub-DEV169Sujet03_T2_seg.nii.gz -l sub-DEV169Sujet03_T2_label-vertebrae.nii.gz -c t2 -param step=1,type=seg,algo=centermassrot:step=2,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=0 -ofolder master -qc /Users/julien/temp/Lydia/results_20240611_093435/qc

--
Spinal Cord Toolbox (git-master-cf48c8950b39f2ed605c3962f26a45c1116fd4ed)

sct_register_to_template -i sub-DEV169Sujet03_T2.nii.gz -s sub-DEV169Sujet03_T2_seg.nii.gz -l sub-DEV169Sujet03_T2_label-vertebrae.nii.gz -c t2 -param step=1,type=seg,algo=centermassrot:step=2,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=0 -ofolder master -qc /Users/julien/temp/Lydia/results_20240611_093435/qc
--


Check template files...
  OK: /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_t2.nii.gz
  OK: /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_levels.nii.gz
  OK: /Users/julien/code/spinalcordtoolbox/data/PAM50/template/PAM50_cord.nii.gz

Check parameters:
  Data:                 sub-DEV169Sujet03_T2.nii.gz
  Landmarks:            sub-DEV169Sujet03_T2_label-vertebrae.nii.gz
  Segmentation:         sub-DEV169Sujet03_T2_seg.nii.gz
  Path template:        /Users/julien/code/spinalcordtoolbox/data/PAM50
  Remove temp files:    1

Check input labels...
Creating temporary folder (/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-11_11-24-01_register-to-template_folmdjps)

Copying input data to tmp folder and convert to nii...

Generate labels from template vertebral labeling

Check if provided labels are available in the template

Binarize segmentation

Change orientation of input images to RPI...

Resample data to 1mm isotropic...
load data...
Converting image from type 'int16' to type 'float64' for linear interpolation

Done! To view results, type:
fsleyes data_rpi_1mm.nii &

load data...
Converting image from type 'uint8' to type 'float64' for linear interpolation

Done! To view results, type:
fsleyes seg_bin_rpi_1mm.nii.gz &

To avoid intensity overflow due to convertion to +uint8+, intensity will be rescaled to the maximum quantization scale

Straighten the spinal cord using centerline/segmentation...
Reusing existing warping field which seems to be valid
cp /Users/julien/temp/Lydia/results_20240611_093435/data_processed/sub-DEV169Sujet03/anat/straightening.cache straightening.cache
cp /Users/julien/temp/Lydia/results_20240611_093435/data_processed/sub-DEV169Sujet03/anat/warp_curve2straight.nii.gz warp_curve2straight.nii.gz
cp /Users/julien/temp/Lydia/results_20240611_093435/data_processed/sub-DEV169Sujet03/anat/warp_straight2curve.nii.gz warp_straight2curve.nii.gz
cp /Users/julien/temp/Lydia/results_20240611_093435/data_processed/sub-DEV169Sujet03/anat/straight_ref.nii.gz straight_ref.nii.gz
/Users/julien/code/spinalcordtoolbox/bin/isct_antsApplyTransforms -d 3 -i /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-11_11-24-01_register-to-template_folmdjps/seg_bin_rpi_1mm_crop.nii.gz -o /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-11_11-24-01_register-to-template_folmdjps/seg_bin_rpi_1mm_crop_straight.nii.gz -t warp_curve2straight.nii.gz -r straight_ref.nii.gz -n 'BSpline[3]' # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-11_11-24-01_register-to-template_folmdjps
/Users/julien/code/spinalcordtoolbox/bin/isct_ComposeMultiTransform 3 warp_straight2curve.nii.gz -R /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-11_11-24-01_register-to-template_folmdjps/data_rpi_1mm.nii warp_straight2curve.nii.gz # in /private/var/folders/5f/6n99hhyj5_g5cv_1bbx1q7cr0000gn/T/sct_2024-06-11_11-24-01_register-to-template_folmdjps
```

</details>
<Description of the issue>

### Proposed solution

In addition to checking for the identical input data, we should also check for SCT's version. If not the same, we should re-run the straightening.

**Comment by mguaypaq** [comment]
I guess the easiest way would be to include the sct version (either tag or commit) in the filename of the cached result.

**Comment by mguaypaq** [comment]
Actually there's an even easier way. The caching mechanism in SCT already supports adding arbitrary parameters as "things that influence the output":
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/spinalcordtoolbox/utils/fs.py#L164-L170

So we can just add the `utils.sys.__version__` string as a parameter. There are 3 scripts which use caching:
- [ ] [`sct_label_vertebrae`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/spinalcordtoolbox/scripts/sct_label_vertebrae.py#L305-L330)
- [ ] [`sct_register_to_template`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/spinalcordtoolbox/scripts/sct_register_to_template.py#L518-L570)
- [ ] [`sct_smooth_spinalcord`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/spinalcordtoolbox/scripts/sct_smooth_spinalcord.py#L197-L229)

One benefit of doing it this way is that we don't even have to update the tutorial which mentions this ([link](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/documentation/source/user_section/tutorials/other-features/spinalcord-smoothing.rst?plain=1#L45)). But I should still add a test. I'll have a PR soon.
