### ISSUE TITLE
Label-based transformation during template registration is wrong

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4527]
### Description

Issue originally described here: https://github.com/sct-pipeline/spine-park/issues/33, but followed up here since it seems to be an SCT-specific issue.

Quick tl;dr:

- This issue is pre-existing, and was thankfully not caused by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4514.
- The first landmark-based rigid registration did not work, leading to a strong cropping of the straightened image:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/a0f662f4-9885-4aa8-a16c-228f74645fa7)

**Comment by joshuacwnewton** [comment]
Thanks for the report! I assume that this is pretty high priority, given that it involves @Kaonashi22's work? If so, I can look into this first thing tomorrow. :)

**Comment by jcohenadad** [comment]
Yes exactly, high priority

**Comment by mguaypaq** [comment]
The straightened space uses the same qform/sform as the original image (except for a translation shift, but that doesn't affect the orientation). So, if the original image has a tilted Z axis, then the straightened image will not be aligned with the PAM50 axis, which is purely vertical in physical coordinates.

**Comment by jcohenadad** [comment]
> The straightened space uses the same qform/sform as the original image (except for a translation shift, but that doesn't affect the orientation). So, if the original image has a tilted Z axis, then the straightened image will not be aligned with the PAM50 axis, which is purely vertical in physical coordinates.

so yes, that's it. But I'm wondering if this has _always_ been the case (and if so... well... I'm very surprised about it!)

**Comment by joshuacwnewton** [comment]
I'm able to reproduce the behavior from https://github.com/sct-pipeline/spine-park/issues/33. 

I worked with `sub-DEV203Sujet08_T2.nii.gz` (which was also used for debugging the bijective issue). The commands I used were:

```
sct_deepseg_sc -i sub-DEV203Sujet08_T2.nii.gz -c t2
sct_label_vertebrae -i sub-DEV203Sujet08_T2.nii.gz -s sub-DEV203Sujet08_T2_seg.nii.gz -c t2
sct_label_utils -i sub-DEV203Sujet08_T2_seg_labeled.nii.gz -vert-body 3,9 -o sub-DEV203Sujet08_T2_labels_vert.nii.gz
sct_register_to_template -i sub-DEV203Sujet08_T2.nii.gz -s sub-DEV203Sujet08_T2_seg.nii.gz -l sub-DEV203Sujet08_T2_labels_vert.nii.gz -c t2 -qc ~/qc_singleSubj
```

> [!CAUTION]
> I was then going to test with an older version of SCT, but ran into a pretty awful issue: Older versions of SCT will completely wipe the `$SCT_DIR/data/` directory upon reinstalling... which is where I had been storing _all_ of my issue-related data for the past few months, including the data for this subject. (Lesson learned... I'll store my issue data in a separate directory and just symlink from `data/` to there instead. The reason I even do this is for ease of creating debug configurations in PyCharm, aha.)

Anyway, after redownloading the data from Slack, then trying with SCT v5.0.0 (Nov 2020), I get (more or less) similar results.

6.3:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/3cf05035-88f9-4c99-8452-2151047cd626)

5.0.0:

![Screenshot from 2024-06-12 12-43-19](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/16181459/fd3d3b9a-cd7e-45b0-887b-ed24ca9e9d53)

**Comment by jcohenadad** [comment]
Thank you for checking @joshuacwnewton (and sorry to head about the data wiping out, that is frustrating). OK, so I guess the next step would be to consider generating q/sform that are aligned in the physical z axis. Any pros/cons that we can think of @mguaypaq @benjamindeleener @joshuacwnewton?

**Comment by mguaypaq** [comment]
The main potential issue I can think of with aligning the qform/sform with PAM50, is that this would potentially change how ANTs applies the warping fields. What I mean is that right now:

* Each voxel is translated using the vectors in the warping field, and some interpolation happens. This seems to me like a fairly minimal resampling step.

If we change the qform/sform:

* Each voxel would be translated, but also rotated implicitly because of the different qforms. This would possibly be a heavier resampling, with a bit less precision.

But this is just my intuition, and maybe the change will not be big. Just something to check, somehow, before we commit the change.

But I have a question, if we choose to align with PAM50: where do we put the origin of the coordinate system? For the X and Y directions it's clear: use the centerline. But for the Z direction, do we want the bottom, middle, top of the centerline? A specific landmark (may not always be present)?

**Comment by jcohenadad** [comment]
> Each voxel would be translated, but also rotated implicitly because of the different qforms. This would possibly be a heavier resampling, with a bit less precision.

I don't think that adding more rotation/translation would affect resampling errors, as long as there are rotations/translation/non-linear warp for registration to the template in the first place (and there usually is). What I mean is, interpolation error is equally problematic if the displacement is 1mm vs. 100mm (with some subtle exception, of course, eg. if we talk about a translation that exactly corresponds to a multiple of the pixdim, but it is almost never the case).

> But I have a question, if we choose to align with PAM50: where do we put the origin of the coordinate system? For the X and Y directions it's clear: use the centerline. But for the Z direction, do we want the bottom, middle, top of the centerline? A specific landmark (may not always be present)?

Good question. How about we choose the middle of the S-I extent, which corresponds to z=495:

![image](https://github.com/spinalcordtoolbox/spinalcordtoolbox/assets/2482071/a41029e2-4cec-416a-b23c-8d7a18f6bb05)

> [!NOTE]
> Weirdly, while the x-centerline is at `x[phys]=0`, the y-centerline is at about `y[phys]=-46`

**Comment by benjamindeleener** [comment]
I agree that it must be related to qform/sform of the centerline image. The straightening algorithm first creates the straight centerline in the pixel space and then converts the coordinates into physical space for straightening following [these lines](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/straightening.py#L347):

```python
coord_straight[:, 0] = int(np.round(nx_s / 2))
coord_straight[:, 1] = int(np.round(ny_s / 2))
coord_straight[:, 2] = np.linspace(0, end_point_coord[2] - start_point_coord[2], number_of_points)
coord_phys_straight = image_centerline_straight.transfo_pix2phys(coord_straight, mode='absolute')
```

The straight image is a cropped version of the original image but preserves orientation. It allows to straighten a spinal cord and keep it within the same image. If there are some errors in the qform/sform, it may have been the source of the error. One way to be sure would be to save the straight centerline to see if the referentiel spaces are correct. The code also provide [a verbose option](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/straightening.py#L361).

Regarding the note about the position of the origin of the template in the previous comment: the PAM50 template is registered with the ICBM152 (brain) template so the origin (0, 0, 0) of both templates should be the same. That is why the center of the spinal cord is centered around 0 (left-right symetry) and at -46 mm (posterior to the origin in the ICBM152 brain template). That is also why the template goes negatively in Z.

**Comment by jcohenadad** [comment]
> If there are some errors in the qform/sform, it may have been the source of the error

I don’t think this is the issue here. The fundamental problem is that we estimate a z-scaling transformation between pairs of labels that ore not colinear. Hence my suggestion to create the straight space aligned with the PAM50 centerline.

However, @benjamindeleener had a giid point about creating the straightened cord in the same voxel space (more or less) as the input image. If we decide to create the straight space within the PAM50 that won’t be possible anymore.

So, alternatively we could change the step=0 transform, and instead rely on 3 labels (instead of two) that would define two orthogonal planes.

**Comment by jcohenadad** [comment]
Answering my own comment https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4527#issuecomment-2163337044

> so yes, that's it. But I'm wondering if this has always been the case (and if so... well... I'm very surprised about it!)

I think this is because 99% of the time, the anatomical image (T1w, T2w) is acquired _without_ tilting the FOV, hence with the voxel's IS axis aligned with the physical's z axis. In the case of Lydia's data, the anatomical image is tilted, hence we discovered this issue.

**Comment by benjamindeleener** [comment]
Agreed. We could add a rotation+translation step to adjust for tilting, in addition to the z-scaling factor. We might need more than two points to do so, but we can use the centerline itself.

**Comment by jcohenadad** [comment]
> We could add a rotation+translation step to adjust for tilting, in addition to the z-scaling factor. We might need more than two points to do so, but we can use the centerline itself.

Yup, that's exactly what I'm currently working on.
