### ISSUE TITLE
Deduplicate "sct_apply_transfo + label dilation" code snippet in `sct_register_to_template` script

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4534]
### Description

While working on https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4533 I stumbled upon potential refactoring.

This code:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/spinalcordtoolbox/scripts/sct_register_to_template.py#L590-L605

Can re-use the `label` feature of `sct_apply_transfo`:
https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/65ffa7524dc145a23086127be6d9f03ccc6b0778/spinalcordtoolbox/scripts/sct_apply_transfo.py#L200-L206

Instead of re-implementing it.

> [!WARNING]
> Note that the label dilation uses a kernel of 4 (vs. 3 in `sct_register_to_template`). My suggestion would be to change the default 4 to 3 in `sct_apply_transfo` because 3 should be enough.

**Comment by joshuacwnewton** [comment]
Curiously, when testing this in #4546, I found a potential bug:

- `sct_apply_transfo -x label` converts the dilated labels back into point labels.
- However, the current `sct_register_to_template` dilation does _not_ convert the dilated labels back into point labels.

This means that when we de-duplicate the dilation by using `-x label`, `batch_processing.sh` changes a bit: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/9795761959/job/27048696469?pr=4546

If this is acceptable, then I can go ahead and update the batch_processing.sh results.

**Comment by joshuacwnewton** [comment]
(Note: There was no change in batch_processing.sh results when using `ball 4` vs. `ball 3`, which confirms your suspicions.)

**Comment by jcohenadad** [comment]
> If this is acceptable, then I can go ahead and update the batch_processing.sh results.

yes, definitely acceptable. Thank you for testing/reporting!
