### ISSUE TITLE
`keep_largest_object` function exists in two scripts

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4544]
The `keep_largest_object` function exists in two different scripts. Each has a different implementation.

---

1. 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9e1f65b86902cb237d5f79058a4623eed2d2c8eb/spinalcordtoolbox/math.py#L350

used by 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9e1f65b86902cb237d5f79058a4623eed2d2c8eb/spinalcordtoolbox/deepseg/inference.py#L23

---

2.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9e1f65b86902cb237d5f79058a4623eed2d2c8eb/spinalcordtoolbox/deepseg_/postprocessing.py#L151

used by

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/9e1f65b86902cb237d5f79058a4623eed2d2c8eb/spinalcordtoolbox/deepseg_/sc.py#L18

**Comment by joshuacwnewton** [comment]
Woof, good catch! That should be a quick refactor, then.
