### ISSUE TITLE
Suspicious application of a mask in moco

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4579]
While working on #4578, I noticed suspicious things about the use of the input mask. 

## Inconsistent input type

Here is the line that calls the application of the mask:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aa4aa7b038745e86b3058c5f8819de999d5c01ed/spinalcordtoolbox/moco.py#L605-L606

As can be seen, the second input argument to `apply_mask_if_soft()` is an Image Class `im_maskz_list[iz]`. Proof from the debugger:
```python
print(im_maskz_list[iz])
<spinalcordtoolbox.image.Image object at 0x7f8523e4fac0>
```

However, the function expects a file name:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aa4aa7b038745e86b3058c5f8819de999d5c01ed/spinalcordtoolbox/image.py#L1657

So this is the first weird thing I observed.

## Strange logic to multiply the mask with the image

~The second weird thing is that the function is supposed to multiply the mask with the image, and then output the masked image. In order to do so, the mask and the image should have the same shape in order to be multiplied. So I assume this is what this check is for:~

SCRAP THAT: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4579#issuecomment-2256715468

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aa4aa7b038745e86b3058c5f8819de999d5c01ed/spinalcordtoolbox/image.py#L1668

However, it performs the multiplication only if the shape of the mask and of the image are NOT the same. Shouldn't we expect something like this instead?
```python
    if np.array_equal(im_mask.data, im_mask.data.astype(bool)):
```

### Multiplying mask with image

Another issue, even more concerning, is about the rationale for multiplying the image with the mask. When doing so, the output image will have zero outside the mask, and image content inside. However, the registration algorithm will treat the boundary of the zeroed region as a strong contrast for aligning the source and target image, resulting in poor registration performance. I am wondering why we implemented this logic in the first place?

**Comment by joshuacwnewton** [comment]
> ## Inconsistent input type

> However, the function expects a file name:

Yes, this is not great. Luckily, it does not actually affect processing, because if an `Image` object is passed to the `Image` constructor, it will simply return a copy:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aa4aa7b038745e86b3058c5f8819de999d5c01ed/spinalcordtoolbox/image.py#L1666-L1667

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/48e2489dac81ba0c3d70c068d6f8df094c56da3b/spinalcordtoolbox/image.py#L286-L288

Still, we should probably fix this. :sweat_smile: 

----

> ## Strange logic to multiply the mask with the image

> However, it performs the multiplication only if the shape of the mask and of the image are NOT the same. Shouldn't we expect something like this instead?

I'm not sure that this is checking shape between _mask and image_; to me, it looks like it's comparing the mask with _itself_ as a boolean array (as a way of checking if the mask is soft). 

If the mask is not equal to itself as bool, then it's not a binary mask, i.e. it is soft.

----

> ## Multiplying mask with image

> Another issue, even more concerning, is about the rationale for multiplying the image with the mask. When doing so, the output image will have zero outside the mask, and image content inside.

Looking at the history of the changes, it can be traced back:

- Refactoring PR: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3446
- Original PR: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/2634

From your original PR description:

> When dealing with tricky motion correction problems, it would be good to have `isct_antsSliceRegularizedRegistration` focus on the spinal cord more than on the lateral tissue (muscle, noise, etc). Currently, `isct_antsSliceRegularizedRegistration` only accepts binary masks as input. When inputting weighted mask, the function crashes (see #2630). This PR modifies the `msct_moco` module such that soft masks can be used for better performance. One motivation for this PR is this recent [user feedback](http://forum.spinalcordmri.org/t/sct-dmri-moco-doesnt-seem-to-correct-motion/358/2).

**Comment by jcohenadad** [comment]
> I'm not sure that this is checking shape between mask and image; to me, it looks like it's comparing the mask with itself as a boolean array (as a way of checking if the mask is soft).

oops! you're absolutely right-- my tired eyes read `im_data.data, im_mask.data.astype(bool))` instead of `im_mask.data, im_mask.data.astype(bool))` 😅 . I'm crossing over the original issue post

**Comment by jcohenadad** [comment]
>> From your original PR description: When dealing with tricky motion correction problems, it would be good to have isct_antsSliceRegularizedRegistration focus on the spinal cord more than on the lateral tissue (muscle, noise, etc). Currently, isct_antsSliceRegularizedRegistration only accepts binary masks as input. When inputting weighted mask, the function crashes (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2630). This PR modifies the msct_moco module such that soft masks can be used for better performance. One motivation for this PR is this recent [user feedback](http://forum.spinalcordmri.org/t/sct-dmri-moco-doesnt-seem-to-correct-motion/358/2).

Still, I suspect this was a bad idea, because the output image will have a distinctive mask appearance (ie: 'gaussian' like disk in case of a gaussian disk mask), hence the registration algorithm will try to align the gaussian envelop for aligning the source and target image, instead of focusing on the image content, resulting in poor registration performance.

I think we should test this, using a binary mask (used _as is_ inside `isct_antsSliceRegularizedRegistration`) vs. a soft mask (used by the code to multiply the image by it) and compare moco performance.

**Comment by jcohenadad** [comment]
And another problem with that logic:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/aa4aa7b038745e86b3058c5f8819de999d5c01ed/spinalcordtoolbox/image.py#L1668

Is that a mask could be binary, but encoded as type=FLOAT, which is exactly what just happened with a binary FLOAT mask provided by @4rnaudB (details in https://github.com/4rnaudB/spinalcord-signal-recovery/issues/5-- repos is private until article submission-- will add @joshuacwnewton with read permission), where at least here, we can observe the poor quality of registration when the image is multiplied by the mask (confirming my suspicion)-- hence I think we should definitely do something about it (ie: remove the code that multiply the image by the mask)

**Comment by jcohenadad** [comment]
Just to clarify the suggested changes:
- if the input mask is soft (find an appropriate way to test this, eg: check if there are other values than 0 and 1), binarize it using 0.5 threshold. 
  - Or, if easier, just systematically binarize the input mask (even if it is already binary and UINT8, it won't hurt to binarize it because it takes about 1s, and it will make the code cleaner).
- the function 'apply_mask_if_soft' should probably be removed (if it is not used elsewhere)
