### ISSUE TITLE
Installer fails on macOS with write permission error for `$SCT_DIR`

### ISSUE THREAD

**Issue by tomDag25** [spinalcordtoolbox/spinalcordtoolbox#4623]
### Description

I have a macOS; with zsh Terminal; when installing using the procedure described [here](https://spinalcordtoolbox.com/user_section/installation/mac.html#option-1-install-from-package-recommended), I downloaded the file under my Download/ folder; and then after running the install script I got permission issue: 

```console
thomasdagonneau@MacBook-Pro-de-Thomas-3 Downloads % bash install_sct-6.4_macos.sh


*******************************
* Welcome to SCT installation *
*******************************



Checking OS type and version...

Darwin MacBook-Pro-de-Thomas-3.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64 x86_64
ProductVersion:		14.3.1

Checking requirements...


OK!

Source files not present. Downloading source files (@ 6.4) to /var/folders/ny/ww_nlk897_x59csrbfysz19w0000gn/T/tmp.FiWu7c9SGJ/spinalcordtoolbox.
Cloning into '/var/folders/ny/ww_nlk897_x59csrbfysz19w0000gn/T/tmp.FiWu7c9SGJ/spinalcordtoolbox'...
Note: switching to '1f12b63e930354e018d637b9717c00ff35c6d6e0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false


SCT version ......... 6.4
Installation type ... package
Operating system .... osx (	14.3.1)
Shell config ........ /Users/thomasdagonneau/.zshrc

SCT will be installed here: [/Users/thomasdagonneau/sct_6.4]



Do you agree? [y]es/[n]o: y

ERROR: /Users/thomasdagonneau/sct_6.4 exists but does not have write permission.


Installation failed!

Please find the file "/Users/thomasdagonneau/Downloads/install_sct_log.txt",
then upload it as a .txt attachment in a new topic on SCT's forum:
--> https://forum.spinalcordmri.org/c/sct
```

This is surprising, given that the installation folder is under my home folder.

So; to circumvent,vent the issue I used sudo:

However; SCT cannot be launched; which is likely because the SCT PATH was added to `.bashrc`, which is not called in my ZSH terminal.

**Comment by joshuacwnewton** [comment]
Hi @tomDag25! Thank you for reporting this issue.

We do not recommend using `sudo` to install SCT. So, let's focus on fixing the permissions issue. :)

I too am surprised to see that the installer is failing with a permission-related error message. The step that is a standard `bash` test for write permissions. 

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fad3464a5df9b072f2550dbdfb0e2c8b7d07d43d/install_sct#L519-L521

Could you please run the following commands and share the output?

```bash
# test permissions (before)
ls -lah ~ | grep sct
test -w ~/sct_v6.4 && echo is writeable || echo is not writeable
# update permissoins
chmod +w ~/sct_v6.4
# test permissions (after)
ls -lah ~ | grep sct
test -w ~/sct_v6.4 && echo is writeable || echo is not writeable
```

After updating permissions, you should see the `w` flag added in the output of `ls`, and you should see the `test` command return "is writeable". If so, you should be able to re-run `./install_sct-6.4_macos.sh` and install SCT to `~/sct_v6.4`.

**Comment by tomDag25** [comment]
So I did the command in my terminal but it's still not writeable : 


'''
thomasdagonneau@MacBook-Pro-de-Thomas-3 ~ % chmod +w ~/sct_6.4
thomasdagonneau@MacBook-Pro-de-Thomas-3 ~ % ls -lah ~ | grep sct
test -w ~/sct_6.4 && echo is writeable || echo is not writeable
drwxr-xr-x    24 root             staff   768B Sep  3 14:43 sct_6.4
drwxr-xr-x     8 thomasdagonneau  staff   256B Sep  3 15:11 sct_course_data
is not writeable
'''

**Comment by joshuacwnewton** [comment]
Ah! The `sct_v6.4` folder has permissions `rwxr-xr-x` (i.e. `u:rwx` `g:r-x` `o:r-x`).

Meaning, the owner of the folder has full permissions, but "group"/"other" do not have write permissions. And, because `root` is the owner of the folder, your user account (`thomasdagonneau`) does not have write permissions.

To fix this, you will need to make sure your user account owns the folder:

```
sudo chown -hR thomasdagonneau ~/sct_6.4
```

Once your user account owns the folder, then `chmod +w` should work as well. Finally, you should be able to proceed with the installation script without issue.

**Comment by tomDag25** [comment]
That was it thanks ! My sct is working thank you !

**Comment by jcohenadad** [comment]
reopening just to make sure if we should do something about it for our futur users (ie: if it happened to Thomas who is in the lab and can receive special help, it might happen to other folks outside the lab who might be shy asking for help)
