### ISSUE TITLE
Integrate TotalSpineSeg project into SCT

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4626]
This issue is meant to track the necessary steps required to integrate [`neuropoly/TotalSpineSeg`](https://github.com/neuropoly/totalspineseg) into SCT. 

> Context: https://github.com/neuropoly/totalspineseg/pull/46#issuecomment-2342387047
> 
>> [U]ltimately this method will be callable via SCT. [W]e should already think of an appropriate API to plug it inside SCT. Tagging @joshuacwnewton @mguaypaq so we can start thinking about it

TotalSpineSeg uses a two-stage approach, with both stages based on `nnUNetv2`. `sct_deepseg` already supports multi-model inference (see [`-task seg_tumor-edema-cavity_t1-t2`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/fd89b9e240720c19c8f1d368a1329b6e123d4c21/spinalcordtoolbox/deepseg/models.py#L241-L252)). But, I'm not sure if `sct_deepseg`'s infrastructure is built to handle the non-`nnUNet` steps that occur [between the Step 1 and Step 2 models](https://github.com/neuropoly/totalspineseg/blob/d3318be8c84bb10ce494d2fb3b1cf7e52c86b4b7/totalspineseg/inference.py#L240-L342).

----

I think some initial steps could be:

- [ ] Try installing [TotalSpineSeg's dependencies](https://github.com/neuropoly/totalspineseg/blob/d3318be8c84bb10ce494d2fb3b1cf7e52c86b4b7/pyproject.toml#L42-L54) into the SCT venv.
- [ ] Try running inference using each of TotalSpineSeg's models individually.

If those work OK, then we can begin brainstorming how to adopt the postprocessing steps used by TotalSpineSeg.

----

Alternatively, we could just `pip install` the entire TotalSpineSeg project, and simply call a designated entry point function for inference (a similar pattern to how we use ivadomed). This would take care of handling the implementation of the postprocessing steps.

My only concern is that doing this might lead to long-term maintenance issues (i.e. out of date/conflicting dependencies due to separate repos). ivadomed was a separate project with a separate repo, integrated into SCT using an API. This worked OK while ivadomed was actively maintained, but when maintenance stopped, the `pip`/API-based integration became a bit of a liability. There are still out of date packages that SCT is holding back due to ivadomed, and it's quite cumbersome to have to continuously patch ivadomed just to unlock SCT's dependencies.)

So, I think our approach should possibly depend on whether or not TotalSpineSeg will continue to be maintained as a standalone project: 

- Will users continue to install TotalSpineSeg separately outside of SCT, and will changes continue to be made to the project? 
- Or, should SCT absorb the project entirely, to preemptively account for the possibility of it going unmaintained in the future (and thus allowing us to smoothly take over maintenance of the project as part of SCT, with a shared set of dependencies).

**Comment by NathanMolinier** [comment]
During the last SCT meeting (2024-10-01) we mentioned that it would be nice to have a first implementation of TotalSpineSeg before the next SCT course (beginning of december). So I believe, the best strategy would be to:
- Add TotalSpineSeg as a dependency during few months
- Then implement TotalSpineSeg project more deeply into SCT to facilitate the maintenance

Also, I had an in-person discussion with @jcohenadad and we thought that we could implement TotalSpineSeg in both `sct_label_vertebrae` and `sct_deepseg`:
- `sct_label_vertebrae`: we could only call the first step of TotalSpineSeg (using the flag `--step1`) to label the discs as done by the current `sct_label_vertebrae`
- `sct_deepseg`: we could call TotalSpineSeg to perform the full spine segmentation using the 2 steps.

Regarding inference, we could easily have a different inference script than the [one](https://github.com/neuropoly/totalspineseg/blob/train-with-vert-landmarks-variants/totalspineseg/inference.py) used currently to remove some unnecessary steps. This could also help change the way we call nnUNet.

**Comment by joshuacwnewton** [comment]
Great summary! I guess the next steps would be:

- [ ] Try installing TotalSpineSeg's dependencies into `venv_sct` (just to catch any dependency conflicts early before proceeding with other steps)
- [ ] Reserve the `totalspineseg` package name on PyPI.
- [ ] Manually [build and upload](https://github.com/neuropoly/totalspineseg/issues/64#issuecomment-2379696810) a basic test wheel to https://test.pypi.org/. (We don't have to worry about automation and multiple releases right away.)
- [ ] Try installing this wheel into SCT using `pip install {LINK_TO_TEST_PYPI_WHEEL}`
- [ ] Try running inference via an API call to `totalspineseg`.

If all of this works, then we can go ahead and add additional features (e.g. different API calls for different outputs) as well as maybe figuring out automated builds + uploads to the non-test PyPI.

**Comment by NathanMolinier** [comment]
I have a few concerns:
- In the [package](https://pypi.org/project/totalspineseg/) requirements, we install a different nnunetv2 version but I believe it would work the same if we use the specified version in sct. 
- I created a bad function to install the weights inside the package: "totalspineseg_init" but how to integrate this inside sct

**Comment by joshuacwnewton** [comment]
> I created a bad function to install the weights inside the package: "totalspineseg_init" but how to integrate this inside sct

I notice that in the README, there are command line (CLI) scripts for this (`totalspineseg_init`/`totalspineseg`). But there doesn't seem to be an equivalent Python function that could be called inside of SCT? For example:

```python
# in sct_deepseg
from totalspineseg.init_inference import install_weights
from totalspineseg.inference import main

install_weights({insert args here})
main({insert args here})
```

Basically, it can be helpful to make a separation between A. argparse parsing B. core functionality (image processing, etc.). For the CLI scripts, you can keep the argparse parsing, but for SCT's calls to totalspineseg, we could go directly to B. and call the functions directly. (See [this dev Wiki page](https://github.com/spinalcordtoolbox/spinalcordtoolbox/wiki/Programming%3A-API-code-vs-CLI-code) for more info on how SCT tries to do this.)

**Comment by joshuacwnewton** [comment]
The reason we do that for ANTs is because we pretty much have to (since it's written in C++, unless we switch to AntsPy). 😝

But because TotalSpineSeg is written in Python, there are a lot of benefits to using `import` instead. (Namely, better error handling/debugging, and better performance with 1 process instead of 2.)

I am trying to find good resources on this topic. I found [this post](https://stackoverflow.com/questions/48862112/subprocess-or-import-to-invoke-a-script-in-python), but it is a little bare:

> in the absence of factors which force the other choice, `import` is generally vastly preferrable in terms of usability and performance

**Comment by NathanMolinier** [comment]
Ok let me update the package then. Then, where should I add the code ?
