### ISSUE TITLE
Planning for upcoming SCT Course (v6.5, December 2024)

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4641]
As per the [2024-09-06](https://docs.google.com/document/d/10txnIVrX3roF-VYP3yYUVLk7KmeL-43-ppKMKJ1BCpE/edit#heading=h.si61tbeip3y9) SCT dev meeting, we will be hosting an SCT Course tentatively scheduled for **December 9-10, 2024**. This course will correspond to the tentatively-scheduled [6.5 Milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestone/56), currently scheduled for **November 21st, 2024**. 

This issue acts as a meta-issue for planning both the course and its corresponding release:

----

## Administrative tasks

- [x] Create a landing page on https://spinalcordmri.org/workshops.html
  - PR: https://github.com/spinalcordmri/spinalcordmri.github.io/pull/90 
- [x] Create the sign-up Google Form and place it on the landing page.
  - Form: https://docs.google.com/forms/d/1kyOMiMlQOTmp0oDr16Rg5MtLBSMESI2s8Nng2ka2QIw/edit
- [x] Create an announcement post on the SCT forum (and potentially Neurostars).
- [x] Ask Naama to advertise on their mailing list
- [x] Announce the course to the mailing list at predefined dates.
- [x] Create a GitHub issue to track the feedback we receive during/after the course. See: #4743

## Zoom planning tasks

- [x] Make sure Zoom room limit can accommodate 100+ attendees. (It's confirmed 300)
- [ ] Fix Zoom permissions for creating breakout rooms to help people with issues ("xxx email is not included on the plan ...")
- [ ] Fix Zoom to only allow people to join once the meeting has started (to avoid automatically creating recordings when a random curious person joins early)
- [ ] Zoom: remove permission for ppl to draw on my shared screen
- [ ] Zoom: remove permission for ppl to ask for recording on local disk

## Course material tasks

Links: [`GDrive::NeuroPoly/Projects/SCT/Courses/2024-12-09_Online`](https://drive.google.com/drive/u/0/folders/1gsndMQDKyq9XWewC_uA_B1SQ48SNWgpN)`/`[`SCT_Course_2024.slides`](https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit#slide=id.p1)

- [x] Set up the exit poll for soliciting feedback (and add to [this slide](https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit#slide=id.g29c9dc34b67_0_7))
  - Form: https://forms.gle/tnZfcCxdGdREMYSM8
- [x] Re-use the `sct_deepseg` "Model Gallery" materials in a new slide.
- [x] Rework the "segmentation" section to prioritize the contrast agnostic segmentation model.
- [x] Port the recently-added tutorials to the SCT Course.
  - [x] Lesion analysis: [Slides](https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit#slide=id.g30f530482e0_0_16)
  - [x] Rootlets seg: [Slides](https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit#slide=id.g30f530482e0_0_41) 

## Codebase tasks

- [x] Revisit the previous "SCT Course Feedback" issues ([#3612](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3612), [#4303](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4303)) and double-check if anything needs to be implemented ahead of time.
   - [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4663
   - [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4664
   - [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4665
   - [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4666
   - [x] https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4667

**Comment by joshuacwnewton** [comment]
> This course will correspond to the tentatively-scheduled [6.5 Milestone](https://github.com/spinalcordtoolbox/spinalcordtoolbox/milestone/56), currently scheduled for **October 24th, 2024**.

Currently, our quarterly schedule is forecasting future releases in October, January, and April, with the April release tentatively chosen for the "7.0" moniker (where we will push for a big advertisement of `sct_deepseg`'s new and existing models).

However, this schedule was chosen under the assumption that we would have an early-November SCT course. Now that the course has been scheduled for December, there is an extra gap month of development after 6.5 but before the course.

Given this, I would like to propose nixing the January release, releasing 6.5 in November, and releasing 7.0 in April as planned. This would provide additional buffer for both releases, while also eliminating a potentially insubstantial release (due to late course + winter holidays).

**Comment by mguaypaq** [comment]
> Given this, I would like to propose nixing the January release, releasing 6.5 in late November, and releasing 7.0 in April as planned. This would provide an additional ~1 month of buffer for both releases, while also eliminating a potentially insubstantial release (due to late course + winter holidays).

Done!

**Comment by joshuacwnewton** [comment]
As the SCT Course has completed successfully, I am happy to close this issue! :tada: 

See you next year! :)
