### ISSUE TITLE
`arxiv` URLs throw error code 429 (Too Many Requests) for cron broken link checker

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4648]
[Over the last few days](https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/workflows/check-broken-links.yml), arxiv has begun throwing error code 429 from our broken link checker.

The number of URLs that get this error is variable:

- 3: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/11313417217/job/31462152015
- 1: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/11325268975/job/31502314988
- 2: https://github.com/spinalcordtoolbox/spinalcordtoolbox/actions/runs/11343775160/job/31547074774

I figure it would be pretty straightforward to just retest the links, but with a lengthy delay. This would hopefully bypass the 429 error, while also letting us retest links in general to ensure that we minimize the noise from broken links that fail due to some one-off network issue.

**Comment by mguaypaq** [comment]
To be good web citizens, ideally we would honor the [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) response header when we get a 429 response, if possible.

**Comment by joshuacwnewton** [comment]
Ah! Thank you so much for this. I hadn't realized that this existed. I'll revise my solution to incorporate this. :)
