### ISSUE TITLE
`sct_run_batch`: add support for multiple input datasets  

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4658]
Add support for multiple input datasets for `sct_run_batch`. Currently, the script requires all the subjects to be organized as folders within a single directory:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5d774187486e4c61773d3f082ec35a37981da5a/spinalcordtoolbox/scripts/sct_run_batch.py#L45-L46

A possible workaround: merge different datasets into a single directory. Disadvantages of this approach: there might be an overlap in `paritipant_id`s between the datasets. And the git-annex dataset version gets lost after the merge.

**Comment by valosekj** [comment]
Interesting idea! I will give it a try. Wondering whether this solution results in a single output directory (with `data_processed`, `results`,  `qc`, and `log` folders) across all datasets or one output directory per dataset.

**Comment by jcohenadad** [comment]
> Wondering whether this solution results in a single output directory (with data_processed, results, qc, and log folders) across all datasets or one output directory per dataset.

hum, I think that if you use the same `-path-output`, all subjects from all datasets will be placed as a flat directory-- hence, if you have subjects with the same name between two datasets, that will be problematic. In this case, we might need to add a feature, that will add a prefix on the output processed/results data, that corresponds to the dataset name

**Comment by joshuacwnewton** [comment]
Ah, right! In that case you can also specify the output path as well: 

```bash
# in datasets.txt
path/to/dataset1 path/to/output1
path/to/dataset2 path/to/output2
```

```
xargs -n2 sh -c 'sct_run_batch -path-data $1 -path-output $2' sh < datasets.txt
```

([Source](https://superuser.com/a/1745364))

Or even more simply, just make a "meta" shell script that runs `sct_run_batch` multiple times:

```bash
# in process_datasets.sh
sct_run_batch -config config_dataset1.yml
sct_run_batch -config config_dataset2.yml
```

I worry that by adding support for 1 (or many) datasets directly into `sct_run_batch`, the complexity of the script would increase quite a bit? But, if this "simple" solution isn't sufficient, we can definitely consider it.

**Comment by valosekj** [comment]
Thank you!

The following workflow works well for me!

```
xargs -n2 sh -c 'sct_run_batch -path-data $1 -path-output $2 -config config-02_process_data.json' sh < datasets.txt
```

`config-02_process_data.json`:

```json
{
  "script"      : "~/code/mri-metrics/scripts/02_process_data.sh", 
  "jobs"        : 8
}
```

`datasets.txt`:

```bash
path/to/dataset1 path/to/output1
path/to/dataset2 path/to/output1
```

By reusing `path/to/output1`, results across all datasets are stored in a single output directory. (which is fine and intended because subjects do NOT have the same names across datasets).

---

> I worry that by adding support for 1 (or many) datasets directly into sct_run_batch, the complexity of the script would increase quite a bit? But, if this "simple" solution isn't sufficient, we can definitely consider it.

Agree. Let's stick with the workflow described above for now.

**Comment by valosekj** [comment]
I believe that we can close the issue as not planned as the workaround above works fine.
