### ISSUE TITLE
Weird registration results when running tutorial data script `batch_single_subject.sh`

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4662]
I ran the `batch_single_subject.sh` script from `sct_tutorial_data` (to mess around with some of the course commands), and all of the automatic FSLeyes results windows popped up.

One of those FSLeyes windows showed me this:

![image](https://github.com/user-attachments/assets/64faebfb-9f03-430e-8bba-26d59cbec187)

I'll look into this more once I'm done the rest of my work on the slides.

**Comment by joshuacwnewton** [comment]
Ah! The issue is due to the newly inserted [rootlets segmentation command](https://github.com/spinalcordtoolbox/sct_tutorial_data/blob/8b91e72c6575cbf40c5a66898fe3a13d9c26790c/single_subject/batch_single_subject.sh#L138C1-L139C75):

```bash
# Segment the spinal nerve rootlets
sct_deepseg -i t2.nii.gz -task seg_spinal_rootlets_t2w -qc ~/qc_singleSubj
```

This overwrites the cord segmentation file (`t2_seg.nii.gz`) and thus the subsequent registration step uses the wrong segmentation.

The fix should be as simple as setting `-o` to be `t2_rootlets.nii.gz`. But, we should have perhaps configured the rootlets model to use `_rootlets` as a suffix rather than `_seg`. (I'm not sure why we did that in the first place? I'm surprised!)

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/e655bb096b32b7c63b7b7bd737d7a9660bccf4cc/spinalcordtoolbox/deepseg/inference.py#L290-L291

**Comment by valosekj** [comment]
> The fix should be as simple as setting `-o` to be `t2_rootlets.nii.gz`. But, we should have perhaps configured the rootlets model to use `_rootlets` as a suffix rather than `_seg`. (I'm not sure why we did that in the first place? I'm surprised!)

Agree! I usually use `_rootlets` in my analysis and keep `_seg` for spinal cord segmentation.

Or if we want to start spreading "[our suffix convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#examples-and-use-cases)", we could use `_label-rootlets_dseg` suffix.

**Comment by jcohenadad** [comment]
> Or if we want to start spreading "[our suffix convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#examples-and-use-cases)", we could use _label-rootlets_dseg suffix.

maybe for 7.0, and that would be an excellent question for out poll!
