### ISSUE TITLE
Investigate slow template warping after label dilation

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4663]
From https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4303:

> - [ ] for `sct_warp_template`, I noticed that after the modification to warp the label files appropriately (using the dilation step), the function is muuuuuuch slower. It disrupted the course quite a bit. Given that these registered label files are not really used, maybe we can re-consider warping them by default. Alternatively, we could find a way to dilate them much faster.

**Comment by joshuacwnewton** [comment]
I see the dilation + labeling that is mentioned above:

<details>
<summary> Console log </summary>

```console
master|joshua@mosaic:~/repos/sct_tutorial_data/single_subject/data/fmri$ time sct_warp_template -d fmri_moco_mean.nii.gz -w warp_template2fmri.nii.gz -a 0 -qc ~/qc_singleSubj
/home/joshua/.local/bin:/home/joshua/repos/spinalcordtoolbox/bin:/home/joshua/.local/bin:/home/joshua/repos/spinalcordtoolbox/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

--
Spinal Cord Toolbox (git-master-c9ded66db45f6cf518b0c283ff33fa756e4b5271*)

sct_warp_template -d fmri_moco_mean.nii.gz -w warp_template2fmri.nii.gz -a 0 -qc /home/joshua/qc_singleSubj
--


Check parameters:
  Working directory ........ /home/joshua/repos/sct_tutorial_data/single_subject/data/fmri
  Destination image ........ fmri_moco_mean.nii.gz
  Warping field ............ warp_template2fmri.nii.gz
  Path template ............ /home/joshua/repos/spinalcordtoolbox/data/PAM50
  Output folder ............ label


WARP TEMPLATE:

Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-10-29_11-57-34_apply-transfo-3d-label_pdd45kna)

Take the center of mass of each registered dilated labels...
File label/template/PAM50_label_body.nii.gz already exists. Will overwrite it.

Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-10-29_11-57-38_apply-transfo-3d-label_g5m4bst_)

Take the center of mass of each registered dilated labels...
File label/template/PAM50_label_disc.nii.gz already exists. Will overwrite it.

Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-10-29_11-57-43_apply-transfo-3d-label_iks3nxms)

Take the center of mass of each registered dilated labels...
File label/template/PAM50_label_discPosterior.nii.gz already exists. Will overwrite it.

Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-10-29_11-57-47_apply-transfo-3d-label_lyindlid)

Take the center of mass of each registered dilated labels...
File label/template/PAM50_spinal_midpoint.nii.gz already exists. Will overwrite it.
cp /home/joshua/repos/spinalcordtoolbox/data/PAM50/template/info_label.txt label/template
Resampling image "fmri_moco_mean.nii.gz" to 0.6x0.6 mm
Resampling image "PAM50_wm.nii.gz" to 0.6x0.6 mm
Compute center of mass at each slice
/home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/lib/python3.9/site-packages/scipy/ndimage/_measurements.py:1542: RuntimeWarning: invalid value encountered in scalar divide
  results = [sum(input * grids[dir].astype(float), labels, index) / normalizer

*** Generating Quality Control (QC) html report ***
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/home/joshua/qc_singleSubj/single_subject/data/fmri/sct_warp_template/2024_10_29_115753.099135/background_img.png
Successfully generated the QC results in /home/joshua/qc_singleSubj/_json/qc_2024_10_29_115753.099135.json

To see the results in a browser, type:
xdg-open /home/joshua/qc_singleSubj/index.html


Done! To view results, type:
fsleyes fmri_moco_mean.nii.gz -cm greyscale -a 100.0 label/template/PAM50_t2.nii.gz -cm greyscale -dr 0 4000 -a 100.0 label/template/PAM50_gm.nii.gz -cm YlOrRd -dr 0.4 1 -a 50.0 label/template/PAM50_wm.nii.gz -cm blue-lightblue -dr 0.4 1 -a 50.0 &


real	0m23.197s
user	0m22.570s
sys	0m1.802s
```
</details>

Those log messages come from `sct_apply_transfo -x label`. The label method is applied automatically based on file naming patterns:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/b083497faacb5ab74209c28b30a92cc85fc197b6/spinalcordtoolbox/scripts/sct_warp_template.py#L134-L135

The files that match this pattern are:

- `PAM50_label_body.nii.gz`
- `PAM50_label_disc.nii.gz`
- `PAM50_label_discPosterior.nii.gz`
- `PAM50_spinal_midpoint.nii.gz`

For comparison, I tried checking out the version of SCT we used for the 2021 course (5.4), and indeed it was much quicker, despite containing 3/4 files listed above (no midpoint file though):

```bash
#       Before     After
real	0m9.375s   0m23.197s
user	0m7.974s   0m22.570s
sys	0m10.830s  0m1.802s
```

At first, I thought the issue might be due to https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3271, since it explicitly mentions a slowdown with `sct_apply_transfo`. However, even in the "fast" SCT course, we still used `sct_apply_transfo`, just with `-x linear` instead of `-x label`. So, it seems the label method really is the source of the slowdown.

I will next try to debug why the label-based transform is so much slower, and see if I can optimize it at all.

**Comment by jcohenadad** [comment]
I suspect the dilation is what slows the process down (I could be wrong)

**Comment by joshuacwnewton** [comment]
The issue really does come directly from the dilation:

```python
Dilate labels before warping...
Creating temporary folder (/tmp/sct_2024-10-29_12-43-36_apply-transfo-3d-label_yuovh9pv)

Take the center of mass of each registered dilated labels...
File label/template/PAM50_label_disc.nii.gz already exists. Will overwrite it.
         22397 function calls (22110 primitive calls) in 7.470 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    7.470    7.470 {built-in method builtins.exec}
        1    0.000    0.000    7.470    7.470 <string>:1(<module>)
        1    0.003    0.003    7.470    7.470 sct_apply_transfo.py:127(apply)
      2/1    0.000    0.000    7.122    7.122 math.py:102(dilate)
        1    0.000    0.000    7.120    7.120 generic.py:631(maximum)
        1    7.069    7.069    7.120    7.120 generic.py:350(_apply_scalar_per_pixel_3D)
        1    0.000    0.000    0.149    0.149 sys.py:299(run_proc)
```

Specifically, the `rank.maximum()` function we use on `uint` arrays:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/975cf70f92fe9d9e04e92d613b06c81c43fc162d/spinalcordtoolbox/math.py#L120-L121

Confusingly, this is supposed to be **[more](https://github.com/scikit-image/scikit-image/blob/025b9d68da20aabbabf1c64bce544aeb1b80e2ea/skimage/filters/rank/generic.py#L26-L27) [efficient](https://github.com/scikit-image/scikit-image/blob/025b9d68da20aabbabf1c64bce544aeb1b80e2ea/skimage/filters/rank/generic.py#L658-L661)** for large arrays! Yet, the function still performs a "per voxel" operation (`apply_scalar_per_pixel_3D`), so maybe it's still inefficient.

I think the above function is meant for actual images where most/all voxels are non-zero. However, Since we already know that our label images are mostly empty (apart from a few point labels), then it feels like we shouldn't *need* a per-voxel dilation? Couldn't we filter for non-zero voxels first, and just apply dilation to those coordinates?

ANS: [Yes we can!](https://stackoverflow.com/a/52535205) 

```python
def _dilate_point_labels(data, footprint):
    """
    A more efficient dilation algorithm when we know the image is mostly nonzero (i.e. point label image)
    """
    ar_x, ar_y, ar_z = data.shape
    fp_x, fp_y, fp_z = footprint.shape
    for (x, y, z) in np.argwhere(data != 0):
        x_min, x_max = (max(0, x - fp_x)), (min(ar_x, x + fp_x))
        y_min, y_max = (max(0, y - fp_y)), (min(ar_y, y + fp_y))
        z_min, z_max = (max(0, z - fp_z)), (min(ar_z, z + fp_z))
        data[x_min:x_max, y_min:y_max, z_min:z_max] = dilation(
            data[x_min:x_max, y_min:y_max, z_min:z_max],
            footprint=footprint,
            out=None
        )
    return data
```

This approach makes dilation much faster, with the bottleneck now being `sct_apply_transfo` itself:

```
        1    0.006    0.006    0.154    0.154 math.py:129(_dilate_point_labels)
```
