### ISSUE TITLE
Cropping requirement of `seg_ms_lesion_mp2rage` task is not well documented

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4671]
From the most recent SCT meeting, Pierre-Louis noted that the cropping requirement was not clear, and so it was difficult to do a fair 1:1 comparison between MS lesion models.

**Comment by valosekj** [comment]
I documented the cropping in [this recent tutorial](https://spinalcordtoolbox.com/latest/user_section/tutorials/lesion-analysis/lesion-segmentation-ms.html#mp2rage-unit1). The commands in the tutorial are based on the `LONG_DESCRIPTION` of the `seg_ms_lesion_mp2rage` model:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a458fa37fd22179dd2a6c13d33b7d191552abee7/spinalcordtoolbox/deepseg/models.py#L346-L356
