### ISSUE TITLE
Unify FSLeyes commands for multiclass DeepSeg models

### ISSUE THREAD

**Issue by valosekj** [spinalcordtoolbox/spinalcordtoolbox#4693]
FSLeyes commands outputted by `sct_deepseg -i t2.nii.gz -task seg_sc_lesion_t2w_sci` differ from the FSLeyes command in [our tutorial](https://github.com/spinalcordtoolbox/sct_tutorial_data/blob/8b91e72c6575cbf40c5a66898fe3a13d9c26790c/single_subject/batch_single_subject.sh#L128):

<img width="1406" alt="Screenshot 2024-11-12 at 11 16 44 AM" src="https://github.com/user-attachments/assets/5204f40c-6d93-4147-adc1-252e99ff292b">

We could consider unifying the commands. I personally like the command from our tutorial, which opens both spinal cord and lesion segmentation in a single FSLeyes window:

```console
fsleyes t2.nii.gz -cm greyscale t2_sc_seg.nii.gz -cm red -a 70.0 t2_lesion_seg.nii.gz -cm blue-lightblue -a 70.0 &
```

**Comment by valosekj** [comment]
Hey @joshuacwnewton! I noticed this issue was resolved by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4690. Was it intentional?

**Comment by joshuacwnewton** [comment]
Yes! Because TotalSpineSeg outputs 5 files, the problem was even worse in that PR, so I added a small commit to only output 1 `fsleyes` command (and thus fix the issue for all `sct_deepseg` models).

**Comment by valosekj** [comment]
Okay! Great, thank you for the confirmation and fixing the issue! 👍🏻
