### ISSUE TITLE
Remove `sct_deepseg` models that were superseded by other models

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4700]
As of recently, we have been trending towards building "contrast agnostic" models, which aim to work consistently across a number of contrasts, and reduce e.g. CSA variability between contrasts.

This approach naturally causes contrast-specific models to become redundant. We probably want to avoid misleading our users, and encourage them to use the contrast agnostic models. So, ideally we would remove the older models to prevent any confusion.

This issue is to discuss which of our models ([**Model Gallery**](https://spinalcordtoolbox.com/latest/user_section/command-line/sct_deepseg.html)) we should remove before 6.5. 

Some initial suggestions:

- [ ] ~~`seg_ms_lesion_mp2rage` (Superseded by `seg_ms_lesion`)~~
  - See [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4700#issuecomment-2483909184)
- [ ] `seg_sc_ms_lesion_stir_psir` (Superseded by `seg_ms_lesion`)
- [ ] ~~`mice_gm` (Duplicate with `seg_mouse_gm_wm_t1w`)~~
  - See [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4700#issuecomment-2483930504)
- [ ] `ms_sc_mp2rage` (Superseded by `seg_sc_contrast_agnostic`)

Some questions:

- Should we have a deprecation period? (e.g. For 6.5, we remove from Model Gallery, mention deprecation in code... then remove the models for real in v7.0?)
- Are there any other models we should remove?

**Comment by plbenveniste** [comment]
I think that `seg_sc_ms_lesion_stir_psir` should be removed. The `seg_ms_lesion` model outperforms it. 

As for the `seg_ms_lesion_mp2rage` model, I don't know. I think @Nilser3 is considering adding a new version soon.

**Comment by jcohenadad** [comment]
all the mouse models are not properly tested across datasets, so i would keep them

**Comment by joshuacwnewton** [comment]
Thanks for the feedback! I've updated the issue accordingly. Only 2 models should be removed, then? :relaxed:
