### ISSUE TITLE
Rootlets QC outlining algorithm glitches out when re-used for TotalSpineSeg QC

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4704]
For the rootlets QC, we use an algorithm to draw an outline around the rootlets to improve contrast and make the regions easier to see ([`plot_outlines()`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/b2a6393c842ed0aae0a84083b3683d720a48b511/spinalcordtoolbox/reports/qc2.py#L740-L800)).

However, when I try to re-use this QC for TotalSpineSeg, the lines start glitching out:

![image](https://github.com/user-attachments/assets/4d16e8d3-e38b-4dd0-a54c-e9cb119b1473)

I am assuming that this is because the connected components touch, breaking the assumption of the algorithm? I will maybe try to turn this off for TotalSpineSeg's QC.

**Comment by mguaypaq** [comment]
The algorithm in `plot_outlines()` relies pretty strongly on the input being a binary segmentation (with only two values: 0 and _one_ arbitrary nonzero value, typically 1).

This could probably be fixed with a loop over unique values:
```py
for val in np.unique(data):
    plot_outlines(data == val, ax=ax, ...)
```

**Comment by mguaypaq** [comment]
Alternatively, I think I could modify `plot_outlines()` to efficiently draw the outlines for a multi-valued (but still discrete) segmentation, if you want.
