### ISSUE TITLE
Canal segmentation model has output suffix "_seg_seg.nii.gz"

### ISSUE THREAD

**Issue by joshuacwnewton** [spinalcordtoolbox/spinalcordtoolbox#4714]
The cause of this issue is due to the `labels` key in the `dataset.json` file:

```json
{
    "channel_names": {
        "0": "T2w"
    },
    "labels": {
        "background": 0,
        "canal_seg": 1
    },
    "numTraining": 86,
    "file_ending": ".nii.gz",
    "overwrite_image_reader_writer": "SimpleITKIO",
    "image_orientation": "LAS"
}
```

Because the label is `canal_seg`, SCT's code turns it into `_{canal_seg}_seg`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/89b1ffcbc649cb0f90573cb37aa378f1a3cd3b08/spinalcordtoolbox/deepseg/inference.py#L320

![image](https://github.com/user-attachments/assets/69ba84f5-59df-4e59-b2b2-c88eb484e229)

**Comment by abelsalm** [comment]
So basically I just have to modify the release name ?

**Comment by joshuacwnewton** [comment]
Sorry, I was unclear I think. 

In your model .zip, there is a file called `dataset.json`. You just have to modify this file so that it says `"canal"` instead of `"canal_seg"` (but keep the release name the same).

**Comment by abelsalm** [comment]
Done ! Should solve the problem.

**Comment by joshuacwnewton** [comment]
Thank you! The problem has been solved. :) 

![image](https://github.com/user-attachments/assets/2212d608-1e46-4f4e-8458-12ba6c56f61b)
