### ISSUE TITLE
Weird looking hyperlinks

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4717]
https://spinalcordtoolbox.com/stable/user_section/tutorials/multimodal-registration/contrast-agnostic-registration.html

<img width="888" alt="image" src="https://github.com/user-attachments/assets/6a9248b1-a66e-4bd9-88eb-b5bf221a07f0">

**Comment by joshuacwnewton** [comment]
Looks like the author of that page used Markdown syntax, when they should have used RST syntax. Easy fix!
