### ISSUE TITLE
Issue with T2s-based registration

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4724]
### Description

While running https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit#slide=id.p93 (version: 20241129_093539), I noticed an issue with the quality of the registration:

![ezgif-5-53fc10e9ea](https://github.com/user-attachments/assets/bd55ddbb-a230-401c-908f-5c19afca8c78)

**Comment by jcohenadad** [comment]
After cleaning the WM segmentation from its extreme values #4725, the registration is better, but still not "as good" as it used to be:

![ezgif-5-dcbc2cffaa](https://github.com/user-attachments/assets/f678ebc9-d177-4489-a8bc-cb89e1ade406)

digging further...

**Comment by jcohenadad** [comment]
Sanity check: I converted the WM segmentation to UINT8 (originally in FLOAT64), and registration results were the same (phew!).

**Comment by jcohenadad** [comment]
Issue is likely related to another problem with the WMseg: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4725#issuecomment-2508017958

**Comment by joshuacwnewton** [comment]
I think we can close this since we now know that #4725 is the issue.

**Comment by jcohenadad** [comment]
Reopening, because even after fixing #4725, the registration is still far from acceptable:

![ezgif-6-94206c4af9](https://github.com/user-attachments/assets/e009d75a-1721-4bae-a85f-5d24d88ba7f0)

Looking at the subtraction, I notice negative values (-1), which is expected, since some of the GM pixels are not included in the SC segmentation, as noted in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4725#issuecomment-2508076011:

![Screenshot 2024-12-02 at 12 12 21 PM](https://github.com/user-attachments/assets/316e4331-6574-4eea-a2c8-413c79d21ec3)

I'm investigating whether these negative values have a 'negative' impact (pun not intended) on the registration

**Comment by joshuacwnewton** [comment]
Given what you wrote in this comment earlier:

> Sanity check: I converted the WM segmentation to UINT8 (originally in FLOAT64), and registration results were the same (phew!).

I presume that removing the negative values does indeed fix the issue. So, I think we can just add `-type uint8` to the subtraction step to fix this, maybe?

**Comment by joshuacwnewton** [comment]
Sorry, I mean to suggest that we add `-type uint8` in the course command (where we explicitly want to subtract gm from sc but only have `[0, 1]` values)

**Comment by jcohenadad** [comment]
adding `-type uint8` brings all the zeros to 127 😅

![image](https://github.com/user-attachments/assets/ce1fe064-42e9-441c-aed8-e126881d3c89)

**Comment by jcohenadad** [comment]
So let's go with `sct_maths -i t2s_seg.nii.gz -sub t2s_gmseg.nii.gz -thr 0 -o t2s_wmseg.nii.gz` in the course material

**Comment by jcohenadad** [comment]
I think we can now close this

**Comment by mguaypaq** [comment]
Yes, I think `-thr 0` is clearer about the intent than a type conversion (if it even worked). And I'm glad that this two-step computation is now possible to do it with a single `sct_maths` command since #4485.
