### ISSUE TITLE
Suspicious extreme value when performing subtraction operation

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4725]
### Description

While testing the SCT course, during the subtraction of the T2\*w cord seg to the T2\*w GM seg, the output shows an abnormal intensity range:

![Screenshot 2024-11-29 at 9 43 20 AM](https://github.com/user-attachments/assets/99677d9a-da71-48db-9f35-6ce903fd3ebe)

Whereas the cord seg and GM seg don't show such extreme values:

![Screenshot 2024-11-29 at 9 43 15 AM](https://github.com/user-attachments/assets/d3d2d7a1-1f12-45d1-9e4a-b3934e7213b7)

![Screenshot 2024-11-29 at 9 43 12 AM](https://github.com/user-attachments/assets/0130cc0c-1731-467a-b69d-9106193afc78)

This might have caused the "apparent" black output mentioned by @tomDag25 in [his comment](https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit?disco=AAABZfjAT1c), whereas in fact, the viewer simply 'squeezed' the dynamic of the signal intensity to accommodate such extreme value, resulting in pixels having value=1 appearing as _almost_ black (hence invisible in contrast with the background).

I suspect this is a precision issue during type conversion, that was introduced in 'fairly' recent versions, given that this was not an issue during the last course.

Possibly related to #4724 (investigating further)

**Comment by jcohenadad** [comment]
Yup! Here's our problem:

![image](https://github.com/user-attachments/assets/c3f354b5-df01-467d-b065-7e36d5b61547)

**Comment by jcohenadad** [comment]
Oops! I did not properly inspect the resulting WM segmentation. Another obvious issue came up:

![image](https://github.com/user-attachments/assets/ae7a2a99-b939-4dfd-b266-f25fe2159e78)

**Comment by sandrinebedard** [comment]
I can reproduce the issue:
![Capture d’écran, le 2024-11-29 à 10 54 43](https://github.com/user-attachments/assets/6b4e9951-5f4a-4125-9252-6819cd51f121)
![Capture d’écran, le 2024-11-29 à 10 54 25](https://github.com/user-attachments/assets/37cdfb32-181e-473f-a435-93b8f3d0a3f7)

This seams to happen when the GM is not includes in the spinal cord segmentation, the subtraction should result in a negative value, but the values are super high!

**Comment by sandrinebedard** [comment]
I don't have that issue when using sct_deepseg_sc (only since the GM segmentation is all covered by the sc seg), the problem is definitly in the substraction

**Comment by joshuacwnewton** [comment]
Without looking too deeply into it, this seems like an overflow issue? e.g. negative value + unsigned int = wraps around to a very large positive value.

This [SO answer](https://stackoverflow.com/a/34931602) might provide a potential solution?

```python
data_to_sub = np.sum(list_data, axis=0)
newtype = np.result_type(data, data_to_sub, np.byte)
data = np.subtract(data, data_to_sub, dtype=newtype)
```

**Comment by mguaypaq** [comment]
Thanks @joshuacwnewton for pointing me towards `np.result_type`! I opened a PR.
