### ISSUE TITLE
SCT course: Testing fMRI segmentation using contrast-agnostic and episeg models

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4727]
Documenting results here:

contrast-agnostic: Great 👍 

![ezgif-6-be40caa4db](https://github.com/user-attachments/assets/563ebaee-232d-4964-badb-80c07804031e)

episeg: not good 👎 

![ezgif-6-329b8a56b4](https://github.com/user-attachments/assets/e94079a1-194a-41c5-b041-4fde1b2a4d46)

This is a surprising result, as EPIseg was designed to work specifically on GRE-EPI data. @rohanbanerjee can you please investigate.

As for the course, I think we can use the contrast-agnostic method for fMRI EPI seg. Please vote 👍 / 👎

**Comment by rohanbanerjee** [comment]
Surprising indeed, I'm looking into the data and why this might be the case
