### ISSUE TITLE
SCT course: `sct_deepseg` in lieu of `sct_deepseg_sc` should be used in the multi-subject `process_data.sh` script

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4729]
Comment: https://docs.google.com/presentation/d/1uUOpgshwnyC2p8r2GalXlUczQLpX6PfJbtzNELxbqdI/edit?disco=AAABZfV8T90

**Comment by jcohenadad** [comment]
Tried running with contrast-agnostic-- results are good, but the whole process is slow:

~~~
Started: 2024-11-29 12h19m24s | Ended: 12h31m05s | Duration: 00h11m41s
~~~

Let's compare with the previous implementation...

**Comment by joshuacwnewton** [comment]
Already added in https://github.com/spinalcordtoolbox/sct_tutorial_data/pull/25 (https://github.com/spinalcordtoolbox/sct_tutorial_data/pull/25/commits/bb812ed1c5c3f095a70dd8b8427bf9ea09ae5b3e) :)

**Comment by jcohenadad** [comment]
~~~
Started: 2024-11-29 12h35m20s | Ended: 12h44m06s | Duration: 00h08m46s
~~~

about 3min faster-- let's stick with the contrast-agnostic
