### ISSUE TITLE
Display cumulative count of citations on the "Citation list" doc page

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/spinalcordtoolbox#4731]
On our page, the following graph is shown:

![image](https://github.com/user-attachments/assets/d2f65112-652d-4e21-9584-b33a38e6cc1b)

It would be useful to show the total citation count across years (eg: I'm speaking at a conference tomorrow, and will be advertising SCT-- I'd like to report the total citation count and currently I have to manually add up all the years-- or find the link to the gsheet and do it-- but in any case this is a >5s job)

**Comment by joshuacwnewton** [comment]
![image](https://github.com/user-attachments/assets/1e45117f-fda4-4d52-b096-06818569e93f)

**Comment by jcohenadad** [comment]
Indeed it is-- I'd keep the issue open because I'd like to consider showing the cumulative count only-- this is common practice, and it 'impresses' more than count per year

**Comment by jcohenadad** [comment]
i dunno how to add the year to the new graph i've created...

**Comment by joshuacwnewton** [comment]
![image](https://github.com/user-attachments/assets/39e85e82-b0cf-42e6-baf0-8101d368f36d)

Here you go (added to gsheet besides yours)

The relevant label settings are in both "Setup", the data range should be extended to include the "Year" column (i.e. B), and the X-axis should be set to "Year" 

![image](https://github.com/user-attachments/assets/c7363df4-2790-4d9a-ae8f-56132f36ecbe)

**Comment by jcohenadad** [comment]
amazing, thank you! PS: I've also added it in the 'Graphs_bigger' sheet, to copy/paste in PPTX slides

**Comment by jcohenadad** [comment]
actually, let's reopen, and close once the cumulative count is displayed on the SCT website
