### ISSUE TITLE
Qc of sct_deepseg shows oversegmentation, but not the case

### ISSUE THREAD

**Issue by sandrinebedard** [spinalcordtoolbox/spinalcordtoolbox#4741]
### Description
I noticed that the segmentation looks oversegmented in the QC report using `sct_deepseg -qc` with contrast-agnostis, but when I recgenerate the qc with `sct_qc -p sct_deepseg_sc` and in FSLeyes, it is not oversegmented. I tested on the dMRI data from the course:

~~~
sct_deepseg -task seg_sc_contrast_agnostic -i dmri_dwi_mean.nii.gz -qc ~/qc_singleSubj
~~~
![image](https://github.com/user-attachments/assets/0c0e1a9b-38bd-4a73-a1a4-2a490a2327be)

~~~
sct_qc -i dmri_dwi_mean.nii.gz -s dmri_dwi_mean_seg.nii.gz -p sct_deepseg_sc -qc ~/qc_singleSubj
~~~

![image](https://github.com/user-attachments/assets/f3c45876-d881-4761-867d-0dbe5fdba99d)

Screenshot in FSLeyes:
![image](https://github.com/user-attachments/assets/e535079b-9332-4035-8501-8e9689fd1c18)

Here is the data:

[dmri_dwi_mean_seg.nii.gz](https://github.com/user-attachments/files/17982982/dmri_dwi_mean_seg.nii.gz)
[dmri_dwi_mean.nii.gz](https://github.com/user-attachments/files/17982983/dmri_dwi_mean.nii.gz)

**Comment by joshuacwnewton** [comment]
`sct_deepseg_sc` uses the following (old) QC process:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4220101576d7b18a5b1af18a8b211d8a849ec2ef/spinalcordtoolbox/reports/qc.py#L468-L472

It also calls `_resample_slicewise`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4220101576d7b18a5b1af18a8b211d8a849ec2ef/spinalcordtoolbox/reports/qc.py#L574-L576

`_resample_slicewise` includes a binarization step:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/4868a2cdd79a7109bce1de8747f52cbed9d18b0f/spinalcordtoolbox/reports/slice.py#L174-L183

But we do not use this binarization step in `qc2.py`:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/a03b08e95499bfffb79cf99f8743cfd57213360a/spinalcordtoolbox/reports/qc2.py#L316-L333

I think if we replace `resample_nib` with `_resample_slicewise.py`, the QC reports will be unified.

**Comment by sandrinebedard** [comment]
woww looks much better!
