### ISSUE TITLE
verbose flag doesn't work (same output for "-v 0" and "-v 1")

### ISSUE THREAD

**Issue by slevyrosetti** [spinalcordtoolbox/spinalcordtoolbox#485]
For example:
`sct_label_utils -i mt0crop.nii.gz -o mt0crop_seg_ok.nii.gz -t create -x ${mt0_seg_coord} -v 1`
and
`sct_label_utils -i mt0crop.nii.gz -o mt0crop_seg_ok.nii.gz -t create -x ${mt0_seg_coord} -v 0`
give the same output in the terminal command window.

**Comment by joshuacwnewton** [comment]
Closing this issue, as now `-verbose 0` has an effect (log levels, `display_viewer_syntax`, etc.)
