### ISSUE TITLE
Call sct tools within the code without system calls

### ISSUE THREAD

**Issue by poquirion** [spinalcordtoolbox/spinalcordtoolbox#732]
- [x] finalise debug the main()/get_parser() paradigm
- [ ] rewrite the the lines where you have system calls

**Comment by jcohenadad** [comment]
important to printout the "bash equivalent" command for easier debugging within bash terminal.

**Comment by poquirion** [comment]
I am thinking of adding a dev or verbose option to get those print for developer only
